// Generated by scripts/gen-messages-types.ts from messages/*.json. Do not
// edit: run `pnpm --filter @oxagen/app gen:messages`; CI fails when this
// file is stale (INV-12).
type Messages = {
  app: {
    name: string;
    description: string;
  };
  pages: {
    login: string;
    signup: string;
    verify: string;
    twoFactor: string;
    forgotPassword: string;
    resetPassword: string;
    invitation: string;
    invitationNotFound: string;
    newOrganization: string;
    cliAuthorize: string;
    fleet: string;
    run: string;
    agents: string;
    agent: string;
    agentSource: string;
    tools: string;
    skills: string;
    steering: string;
    spend: string;
    people: string;
    apiKeys: string;
    billing: string;
  };
  unrecorded: {
    tools: string;
    run: {
      frames_wrapped: string;
    };
  };
  notFound: {
    title: string;
    body: string;
    home: string;
  };
  globalError: {
    title: string;
    body: string;
    retry: string;
  };
  agents: {
    notRecorded: string;
    harness: {
      stella: string;
      "claude-code": string;
      "claude-agent-sdk": string;
      custom: string;
    };
    status: {
      unenrolled: string;
      enrolled: string;
      suspended: string;
      retired: string;
    };
    list: {
      tiles: {
        label: string;
        identities: {
          title: string;
          basis: string;
        };
        enrolled: {
          title: string;
          basis: string;
        };
        tamper: {
          title: string;
          basis: string;
        };
      };
      title: string;
      tableLabel: string;
      columns: {
        identity: string;
        harness: string;
        operator: string;
        status: string;
        runs: string;
        spend: string;
        incidents: string;
        actions: string;
      };
      basisNotRecorded: string;
      edit: string;
      pager: string;
      first: string;
      next: string;
      empty: {
        title: string;
        body: string;
        register: string;
        command: string;
      };
    };
    detail: {
      header: string;
      seeBelt: string;
      tabs: {
        label: string;
        identity: string;
        toolbelt: string;
        enrollment: string;
        incidents: string;
        definition: string;
      };
      identity: {
        title: string;
        lead: string;
        agentKey: string;
        principal: string;
        harness: string;
        operator: string;
        status: string;
        registered: string;
        firstFrame: string;
        noFrame: string;
      };
      roles: {
        title: string;
        lead: string;
        empty: string;
        columns: {
          role: string;
          scope: string;
          assigned: string;
          expires: string;
        };
        scope: {
          org: string;
          workspace: string;
        };
        standing: string;
      };
      credentials: {
        title: string;
        lead: string;
        empty: string;
        columns: {
          key: string;
          issued: string;
          lastUsed: string;
          expires: string;
          state: string;
        };
        never: string;
        noExpiry: string;
        active: string;
        revoked: string;
      };
      toolbelt: {
        title: string;
        computation: {
          title: string;
          computedAt: string;
          ceiling: string;
          ceilingValue: {
            caller: string;
            sentinel: string;
          };
          roleGrants: string;
          denyGeneration: string;
          denyGenerationValue: string;
          killSwitches: string;
        };
        presentation: {
          title: string;
          mode: {
            full: string;
            searchable: string;
          };
          sent: {
            definitions: string;
            meta_tools: string;
          };
          limit: string;
        };
        tools: {
          title: string;
          empty: string;
          columns: {
            tool: string;
            category: string;
            risk: string;
            decision: string;
            rule: string;
            access: string;
          };
          risk: {
            low: string;
            medium: string;
            high: string;
          };
          decision: {
            allow: string;
            require_approval: string;
          };
          readOnly: string;
          writes: string;
        };
        cannotSee: {
          title: string;
          empty: string;
          columns: {
            tool: string;
            rule: string;
          };
        };
      };
      enrollment: {
        title: string;
        lead: string;
        columns: {
          host: string;
          status: string;
          mode: string;
          collector: string;
          hooks: string;
          bundle: string;
          deviceKey: string;
          lastSeen: string;
        };
        hooks: {
          ok: string;
          missing: string;
          unreported: string;
        };
        bundleVersion: string;
        never: string;
        revoked: string;
        empty: {
          title: string;
          body: string;
          command: string;
        };
      };
      incidents: {
        title: string;
        empty: string;
        columns: {
          kind: string;
          severity: string;
          detected: string;
          session: string;
          state: string;
        };
        severity: {
          notice: string;
          warning: string;
          tamper: string;
        };
        detectedBy: {
          collector: string;
          control_plane: string;
          human: string;
        };
        open: string;
        resolved: string;
        pager: string;
        first: string;
        next: string;
      };
      definition: {
        openEditor: string;
        none: {
          title: string;
          body: string;
        };
        unparsed: string;
        fields: {
          title: string;
          schema: string;
          slug: string;
          name: string;
          description: string;
          modelTier: string;
          budget: string;
          tools: string;
          denyTools: string;
          sideEffects: string;
          harness: string;
          instructions: string;
          unset: string;
        };
        source: {
          title: string;
          lead: string;
          path: string;
          branch: string;
          commit: string;
          digest: string;
          pullRequest: string;
          committed: string;
        };
      };
    };
    actions: {
      rotate: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
        done: string;
        expires: string;
      };
      suspend: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      resume: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      retire: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        delegationCeiling: string;
        agentNotFound: string;
        agentRetired: string;
        agentPrincipalMissing: string;
        noRepository: string;
        repositoryAmbiguous: string;
        branchIsDefault: string;
        definitionSchema: string;
        definitionSlug: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
    source: {
      facts: string;
      loading: string;
      branchAt: string;
      uncommitted: string;
      truth: string;
      lead: string;
      back: string;
      discard: string;
      save: string;
      modified: string;
      unchanged: string;
      stat: string;
      parse: {
        error: string;
        reason: {
          unterminated_string: string;
          unterminated_array: string;
          array_separator: string;
          inline_table_key: string;
          inline_table_separator: string;
          missing_value: string;
          unreadable_value: string;
          expected_key_value: string;
          text_after_value: string;
        };
      };
      commit: {
        title: string;
        diff: string;
        branch: string;
        branchHint: string;
        message: string;
        messageHint: string;
        submit: string;
        pending: string;
        done: string;
        pullRequest: string;
        invalid: {
          branch: string;
          message: string;
          source: string;
        };
      };
    };
  };
  auth: {
    shell: {
      brand: string;
      tags: {
        free: string;
        markup: string;
        evidence: string;
      };
    };
    fields: {
      name: string;
      email: string;
      password: string;
      newPassword: string;
      confirmPassword: string;
      code: string;
      backupCode: string;
      rememberMe: string;
      showPassword: string;
      hidePassword: string;
      passwordHint: string;
    };
    errors: {
      emailRequired: string;
      emailInvalid: string;
      passwordRequired: string;
      passwordTooShort: string;
      passwordTooLong: string;
      passwordsDiffer: string;
      nameRequired: string;
      nameTooLong: string;
      codeInvalid: string;
      backupCodeInvalid: string;
      tokenMissing: string;
    };
    outcomes: {
      wrongCredentials: string;
      emailNotVerified: string;
      suspended: string;
      rateLimited: string;
      alreadyRegistered: string;
      codeWrong: string;
      linkExpired: string;
      unavailable: string;
      unknown: string;
    };
    sso: {
      google: string;
      github: string;
      or: string;
    };
    login: {
      eyebrow: string;
      title: string;
      lead: string;
      forgot: string;
      submit: string;
      pending: string;
      newHere: string;
      createAccount: string;
      haveInvite: string;
    };
    signup: {
      eyebrow: string;
      lead: string;
      submit: string;
      pending: string;
      terms: string;
      haveAccount: string;
      logIn: string;
    };
    verify: {
      eyebrow: string;
      lead: string;
      leadNoEmail: string;
      expired: string;
      resendTitle: string;
      resend: string;
      resendPending: string;
      resent: string;
      wrongAddress: string;
      startOver: string;
    };
    twoFactor: {
      eyebrow: string;
      title: string;
      lead: string;
      leadBackup: string;
      submit: string;
      pending: string;
      useBackup: string;
      useTotp: string;
      back: string;
    };
    forgot: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      sentTitle: string;
      sentBody: string;
      again: string;
      back: string;
    };
    reset: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      doneTitle: string;
      doneBody: string;
      logIn: string;
      expiredTitle: string;
      expiredBody: string;
      requestNew: string;
      back: string;
    };
    invite: {
      eyebrow: string;
      invited: string;
      invitedOn: string;
      organization: string;
      role: string;
      sentTo: string;
      expires: string;
      never: string;
      roles: {
        owner: string;
        admin: string;
        member: string;
        billing: string;
        compliance: string;
        viewer: string;
      };
      accept: string;
      accepting: string;
      decline: string;
      declining: string;
      declined: string;
      signInLead: string;
      logIn: string;
      signUp: string;
      signedInAs: string;
      notYou: string;
      wrongAccountTitle: string;
      wrongAccountBody: string;
      logInAsOther: string;
      notFoundTitle: string;
      notFoundBody: string;
      closed: {
        accepted: string;
        declined: string;
        revoked: string;
        expired: string;
      };
      closedTitle: string;
      failed: string;
      denied: string;
    };
    cli: {
      title: string;
      lead: string;
      organization: string;
      workspace: string;
      grantsTitle: string;
      grantKeys: string;
      grantActs: string;
      approve: string;
      approving: string;
      cancel: string;
      cancelling: string;
      invalidTitle: string;
      invalidBody: string;
      invalid: {
        redirectUri: string;
        codeChallenge: string;
        codeChallengeMethod: string;
        state: string;
      };
      errors: {
        notPermitted: string;
        notFound: string;
        failed: string;
      };
    };
  };
  billing: {
    units: {
      gau: string;
    };
    range: string;
    checkout: {
      success: string;
      cancel: string;
    };
    plan: {
      title: string;
      none: string;
      plan: string;
      status: string;
      interval: string;
      intervals: {
        month: string;
        year: string;
      };
      period: string;
    };
    mode: {
      title: string;
      prepaid: string;
      prepaidNoCard: string;
      invoice: string;
      uninvoiced: string;
      invoiced: string;
      pastDue: string;
    };
    bucket: {
      title: string;
      period: string;
      included: string;
      purchased: string;
      carried: string;
      used: string;
      remaining: string;
      overdrawn: string;
      exhaustedNoCard: string;
    };
    autoTopup: {
      title: string;
      enabled: string;
      blocks: string;
      perTopup: string;
      readOnly: string;
      save: string;
      saving: string;
      saved: string;
      invalidBlocks: string;
      failed: string;
      savedCard: string;
      savedCardUnlabelled: string;
      noCard: string;
      attempt: {
        none: string;
        paid: string;
        open: string;
        failed: string;
      };
    };
    rate: {
      title: string;
      perGau: string;
      perBlock: string;
      blockSize: string;
      currency: string;
      included: string;
      effective: string;
      openEnded: string;
      source: string;
      published: string;
      negotiated: string;
      negotiatedNoRef: string;
      tiers: {
        free: string;
        build: string;
        scale: string;
        enterprise: string;
      };
    };
    purchase: {
      title: string;
      quantity: string;
      step: string;
      total: string;
      wholeBlocks: string;
      savesCard: string;
      submit: string;
      submitting: string;
      denied: string;
      errors: {
        invalid: string;
        aboveMax: string;
        denied: string;
        conflict: string;
        unavailable: string;
      };
    };
    invoices: {
      title: string;
      empty: string;
      columns: {
        number: string;
        kind: string;
        status: string;
        period: string;
        amountDue: string;
        amountPaid: string;
        invoice: string;
      };
      unnumbered: string;
      view: string;
      unpublished: string;
      kinds: {
        subscription: string;
        gau_purchase: string;
        gau_auto_topup: string;
        gau_interim: string;
        gau_period_close: string;
      };
      statuses: {
        open: string;
        paid: string;
        uncollectible: string;
        void: string;
      };
      pager: string;
      older: string;
      newest: string;
    };
    failure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
  };
  fleet: {
    stats: {
      label: string;
      live: {
        title: string;
        basis: string;
      };
      waiting: {
        title: string;
        oldest: string;
        none: string;
      };
    };
    approvals: {
      title: string;
      parked: string;
      empty: string;
      emptyDetail: string;
      agent: string;
      requester: string;
      timesOut: string;
      notRecorded: string;
      openRun: string;
    };
    runs: {
      title: string;
      columns: {
        run: string;
        agent: string;
        operator: string;
        status: string;
        cost: string;
        frames: string;
        started: string;
      };
      notRecorded: string;
      basisNotRecorded: string;
      source: {
        ledger: string;
        tacho: string;
      };
      older: string;
      newest: string;
      pager: string;
      empty: {
        title: string;
        body: string;
        enroll: string;
        command: string;
      };
    };
  };
  onboarding: {
    errors: {
      orgNameRequired: string;
      orgNameTooLong: string;
      slugInvalid: string;
      slugReserved: string;
      workspaceNameRequired: string;
      workspaceNameTooLong: string;
      workspaceSlugInvalid: string;
      workspaceSlugReserved: string;
      slugTaken: string;
      failed: string;
      denied: string;
    };
    organization: {
      eyebrow: string;
      title: string;
      lead: string;
      name: string;
      slug: string;
      slugHint: string;
      workspaceTitle: string;
      workspaceName: string;
      workspaceSlug: string;
      workspaceHint: string;
      creates: string;
      submit: string;
      pending: string;
    };
  };
  organization: {
    tabs: {
      label: string;
      people: string;
      apiKeys: string;
    };
    roles: {
      owner: string;
      admin: string;
      member: string;
      billing: string;
      compliance: string;
      viewer: string;
    };
    people: {
      title: string;
      person: string;
      role: string;
      joined: string;
      actions: string;
      empty: string;
    };
    actions: {
      denied: string;
      role: {
        open: string;
        title: string;
        body: string;
        label: string;
        confirm: string;
        pending: string;
      };
      remove: {
        open: string;
        title: string;
        body: string;
        confirm: string;
        pending: string;
      };
      failure: {
        lastOwner: string;
        targetNotMember: string;
        roleNotFound: string;
        roleNotGrantable: string;
        insufficientRole: string;
        noPrincipal: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
    invitations: {
      title: string;
      email: string;
      role: string;
      sent: string;
      expires: string;
      never: string;
      empty: string;
    };
    apiKeys: {
      lead: string;
      tableLabel: string;
      columns: {
        name: string;
        prefix: string;
        created: string;
        lastUsed: string;
        expires: string;
        status: string;
      };
      status: {
        live: string;
        revoked: string;
      };
      never: string;
      neverUsed: string;
      empty: string;
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
      };
    };
    denied: {
      title: string;
      body: string;
    };
    pending: {
      title: string;
      body: string;
    };
    error: {
      title: string;
      body: string;
    };
  };
  shell: {
    skipToContent: string;
    loading: string;
    sidebar: {
      label: string;
      navLabel: string;
      sections: {
        workspace: string;
        organization: string;
      };
    };
    nav: {
      fleet: string;
      agents: string;
      tools: string;
      skills: string;
      steering: string;
      spend: string;
      organization: string;
      billing: string;
      apiKeys: string;
    };
    switcher: {
      org: string;
      ws: string;
      current: string;
      denied: string;
      unavailable: string;
    };
    topbar: {
      label: string;
      menu: string;
      breadcrumbs: string;
      search: string;
      searchShortcut: string;
      userMenu: string;
    };
    userMenu: {
      switchTheme: string;
      themeNow: string;
    };
    commands: {
      title: string;
      input: string;
      empty: string;
      footer: {
        move: string;
        open: string;
        escape: string;
        close: string;
      };
    };
    mobileNav: {
      label: string;
      slots: {
        fleet: string;
        agents: string;
        tools: string;
        spend: string;
      };
      more: string;
      waiting: string;
    };
    drawer: {
      title: string;
      close: string;
    };
  };
  skills: {
    eyebrow: string;
    lede: string;
    loading: string;
    inventory: {
      title: string;
      window: string;
      reported: string;
      noneReported: string;
      notReported: string;
      list: string;
      next: string;
    };
    row: {
      sessions: string;
      lastSeen: string;
      harnesses: string;
    };
    empty: {
      title: string;
      hint: string;
    };
    failure: {
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
      };
      retry: string;
      back: string;
    };
  };
  spend: {
    period: string;
    notRecorded: string;
    basisNotRecorded: string;
    basis: {
      gateway_observed: string;
      client_attested: string;
      mixed: string;
      estimated: string;
    };
    tabs: {
      label: string;
      operator: string;
      agent: string;
      tool: string;
      waste: string;
      budgets: string;
    };
    actions: {
      exportReport: string;
      setBudget: string;
    };
    strip: {
      spend: string;
      proven: string;
      provenNote: string;
      accepted: string;
      acceptedNote: string;
      productiveRatio: string;
      productiveRatioNote: string;
    };
    columns: {
      provider: string;
      runs: string;
      calls: string;
      spend: string;
      proven: string;
      productiveRatio: string;
    };
    groups: {
      operator: {
        title: string;
        key: string;
        empty: string;
      };
      agent: {
        title: string;
        key: string;
        empty: string;
      };
      model: {
        title: string;
        key: string;
        empty: string;
      };
      tool: {
        title: string;
        key: string;
        empty: string;
      };
    };
    waste: {
      wasted: string;
      share: string;
      runsWithWaste: string;
      largestCause: string;
      noCause: string;
      byCause: string;
      none: string;
      proof: string;
      cause: {
        cache_write_never_read: string;
      };
    };
    budgets: {
      title: string;
      empty: string;
      scopeColumn: string;
      periodColumn: string;
      limitColumn: string;
      spentColumn: string;
      positionColumn: string;
      scope: {
        org: string;
        workspace: string;
      };
      monthly: string;
      rolling: string;
      noLimit: string;
      disabled: string;
      position: string;
      state: {
        ok: string;
        threshold_50: string;
        threshold_80: string;
        threshold_95: string;
        exceeded: string;
      };
    };
    drill: {
      title: {
        operator: string;
        agent: string;
        tool: string;
      };
      back: string;
      perCall: string;
      perRun: string;
      share: string;
      byDay: string;
      day: string;
      tools: string;
      toolsEmpty: string;
    };
    failure: {
      denied: {
        title: string;
        body: string;
      };
      pending: {
        title: string;
        body: string;
      };
      error: {
        title: string;
        body: string;
        code: string;
      };
    };
    empty: {
      title: string;
      body: string;
      back: string;
    };
    budgetDialog: {
      title: string;
      scope: string;
      period: string;
      rolling: string;
      windowDays: string;
      limit: string;
      limitHint: string;
      enabled: string;
      submit: string;
      pending: string;
      errors: {
        limitInvalid: string;
        windowDaysInvalid: string;
      };
      alert: {
        denied: string;
        failed: string;
      };
    };
    exportDialog: {
      title: string;
      month: string;
      monthHint: string;
      submit: string;
      pending: string;
      errors: {
        monthInvalid: string;
      };
      alert: {
        denied: string;
        failed: string;
      };
    };
    fleet: {
      label: string;
      spendToday: string;
      spendTodayNote: string;
      cacheHitRate: string;
      cacheHitRateNote: string;
    };
  };
  steering: {
    tabs: {
      label: string;
      records: string;
      proposals: string;
      prs: string;
    };
    failure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
    pager: {
      label: string;
      range: string;
      previous: string;
      next: string;
    };
    status: {
      proposed: string;
      pr_open: string;
      checks_running: string;
      checks_passed: string;
      checks_failed: string;
      merged: string;
      rejected: string;
    };
    records: {
      title: string;
      lead: string;
      filter: string;
      all: string;
      emptyTitle: string;
      empty: string;
      emptyKind: string;
      authority: string;
      facts: {
        version: string;
        commit: string;
        path: string;
        published: string;
      };
    };
    proposals: {
      title: string;
      lead: string;
      emptyTitle: string;
      empty: string;
      checks: string;
      source: string;
      support: string;
      runs: string;
      agents: string;
      records: string;
      evidence: string;
      none: string;
      viewPr: string;
    };
    prs: {
      title: string;
      lead: string;
      empty: string;
      number: string;
      columns: {
        pr: string;
        branch: string;
        kind: string;
        state: string;
      };
    };
    pr: {
      heading: string;
      title: string;
      machine: string;
      goToPr: string;
      rejected: string;
      notOpened: string;
      modeUnread: string;
      modes: {
        solo: string;
        team: string;
        regulated: string;
      };
      facts: {
        repository: string;
        branch: string;
        branchInto: string;
        head: string;
        headUnknown: string;
        path: string;
        governance: string;
      };
      checks: {
        title: string;
        names: {
          schema: string;
          lineage_uniqueness: string;
          record_hash: string;
          secret_pii_scan: string;
          conflict_against_active: string;
          constraint_effect: string;
        };
        statuses: {
          pending: string;
          running: string;
          passed: string;
          failed: string;
        };
      };
      body: string;
      onMerge: {
        title: string;
        publishes: string;
        version: string;
        promotion: string;
        review: string;
      };
      merged: {
        title: string;
        commit: string;
        at: string;
        promotion: string;
        record: string;
      };
    };
    actions: {
      open: {
        open: string;
        title: string;
        rerun: string;
        body: string;
        confirm: string;
        rerunConfirm: string;
        pending: string;
      };
      dismiss: {
        open: string;
        title: string;
        body: string;
        reason: string;
        confirm: string;
        pending: string;
      };
      merge: {
        confirm: string;
        pending: string;
        blocked: string;
      };
      failure: {
        orgRoleRequired: string;
        noPrincipal: string;
        separationOfDuties: string;
        proposalNotFound: string;
        proposalMoved: string;
        lineagePrOpen: string;
        governanceUnreadable: string;
        repositoryMissing: string;
        checksNotPassed: string;
        headMoved: string;
        baseMoved: string;
        githubRefused: string;
        refused: string;
        invalid: string;
        pendingApproval: string;
        unavailable: string;
      };
    };
  };
  ui: {
    brand: {
      name: string;
      home: string;
    };
    dialog: {
      close: string;
    };
    record: {
      kinds: {
        rule: string;
        constraint: string;
        procedure: string;
        fact: string;
        memory: string;
        preference: string;
      };
      unclassified: string;
      force: string;
      effects: {
        require: string;
        forbid: string;
      };
      scope: string;
      scopes: {
        repository: string;
        workspace: string;
      };
      lineage: string;
    };
    runStatus: {
      live: string;
      sealed: string;
      halted: string;
    };
    readFailure: {
      denied: string;
      pendingApproval: string;
      error: string;
    };
  };
};

declare module "next-intl" {
  interface AppConfig {
    Messages: Messages;
  }
}

export {};
