// Generated by scripts/gen-messages-types.ts from messages/*.json. Do not
// edit: run `pnpm --filter @oxagen/app gen:messages`; CI fails when this
// file is stale (INV-12).
type Messages = {
  app: {
    name: string;
    description: string;
    skipToContent: string;
  };
  routes: {
    home: {
      title: string;
    };
    login: {
      title: string;
    };
    signup: {
      title: string;
    };
    verify: {
      title: string;
    };
    twoFactor: {
      title: string;
    };
    forgotPassword: {
      title: string;
    };
    resetPassword: {
      title: string;
    };
    invite: {
      title: string;
    };
    newOrganization: {
      title: string;
    };
    cliAuthorize: {
      title: string;
    };
    githubSetup: {
      title: string;
    };
    organization: {
      title: string;
    };
    apiKeys: {
      title: string;
    };
    billing: {
      title: string;
    };
    audit: {
      title: string;
    };
    fleet: {
      title: string;
    };
    run: {
      title: string;
    };
    agents: {
      title: string;
    };
    tools: {
      title: string;
    };
    ontology: {
      title: string;
    };
    steering: {
      title: string;
    };
    spend: {
      title: string;
    };
  };
  unrecorded: {
    agents: string;
    tools: string;
    steering: string;
    spend: string;
    run: {
      frames_wrapped: string;
    };
  };
  states: {
    denied: {
      title: string;
      body: string;
    };
    error: {
      title: string;
      body: string;
    };
    empty: {
      title: string;
    };
  };
  notFound: {
    title: string;
    body: string;
    home: string;
  };
  globalError: {
    title: string;
    body: string;
    retry: string;
  };
  auth: {
    shell: {
      brand: string;
      home: string;
      tags: {
        free: string;
        markup: string;
        evidence: string;
      };
    };
    fields: {
      name: string;
      email: string;
      password: string;
      newPassword: string;
      confirmPassword: string;
      code: string;
      backupCode: string;
      rememberMe: string;
      showPassword: string;
      hidePassword: string;
      passwordHint: string;
    };
    errors: {
      emailRequired: string;
      emailInvalid: string;
      passwordRequired: string;
      passwordTooShort: string;
      passwordTooLong: string;
      passwordsDiffer: string;
      nameRequired: string;
      nameTooLong: string;
      codeInvalid: string;
      backupCodeInvalid: string;
      tokenMissing: string;
    };
    outcomes: {
      wrongCredentials: string;
      emailNotVerified: string;
      suspended: string;
      rateLimited: string;
      alreadyRegistered: string;
      codeWrong: string;
      linkExpired: string;
      unavailable: string;
      unknown: string;
    };
    sso: {
      google: string;
      github: string;
      or: string;
    };
    login: {
      eyebrow: string;
      title: string;
      lead: string;
      forgot: string;
      submit: string;
      pending: string;
      newHere: string;
      createAccount: string;
      haveInvite: string;
    };
    signup: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      terms: string;
      haveAccount: string;
      logIn: string;
    };
    verify: {
      eyebrow: string;
      title: string;
      lead: string;
      leadNoEmail: string;
      expired: string;
      resendTitle: string;
      resend: string;
      resendPending: string;
      resent: string;
      wrongAddress: string;
      startOver: string;
    };
    twoFactor: {
      eyebrow: string;
      title: string;
      lead: string;
      leadBackup: string;
      submit: string;
      pending: string;
      useBackup: string;
      useTotp: string;
      back: string;
    };
    forgot: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      sentTitle: string;
      sentBody: string;
      again: string;
      back: string;
    };
    reset: {
      eyebrow: string;
      title: string;
      lead: string;
      submit: string;
      pending: string;
      doneTitle: string;
      doneBody: string;
      logIn: string;
      expiredTitle: string;
      expiredBody: string;
      requestNew: string;
      back: string;
    };
    invite: {
      eyebrow: string;
      title: string;
      invited: string;
      invitedOn: string;
      organization: string;
      role: string;
      sentTo: string;
      expires: string;
      never: string;
      roles: {
        owner: string;
        admin: string;
        member: string;
        billing: string;
        compliance: string;
        viewer: string;
      };
      accept: string;
      accepting: string;
      decline: string;
      declining: string;
      declined: string;
      signInLead: string;
      logIn: string;
      signUp: string;
      signedInAs: string;
      notYou: string;
      wrongAccountTitle: string;
      wrongAccountBody: string;
      logInAsOther: string;
      notFoundTitle: string;
      notFoundBody: string;
      closed: {
        accepted: string;
        declined: string;
        revoked: string;
        expired: string;
      };
      closedTitle: string;
      failed: string;
    };
    cli: {
      title: string;
      lead: string;
      organization: string;
      workspace: string;
      grantsTitle: string;
      grantKeys: string;
      grantActs: string;
      approve: string;
      approving: string;
      cancel: string;
      cancelling: string;
      invalidTitle: string;
      invalidBody: string;
      invalid: {
        redirectUri: string;
        codeChallenge: string;
        codeChallengeMethod: string;
        state: string;
      };
      errors: {
        notPermitted: string;
        notFound: string;
        failed: string;
      };
    };
  };
  onboarding: {
    errors: {
      orgNameRequired: string;
      orgNameTooLong: string;
      slugInvalid: string;
      slugReserved: string;
      namespaceInvalid: string;
      workspaceNameRequired: string;
      workspaceNameTooLong: string;
      workspaceSlugInvalid: string;
      workspaceSlugReserved: string;
      slugTaken: string;
      namespaceTaken: string;
      failed: string;
    };
    organization: {
      eyebrow: string;
      title: string;
      lead: string;
      name: string;
      slug: string;
      slugHint: string;
      namespace: string;
      namespaceHint: string;
      workspaceTitle: string;
      workspaceName: string;
      workspaceSlug: string;
      workspaceHint: string;
      creates: string;
      submit: string;
      pending: string;
    };
  };
  shell: {
    skipToContent: string;
    loading: string;
    sidebar: {
      label: string;
      navLabel: string;
      sections: {
        workspace: string;
        organization: string;
      };
    };
    nav: {
      fleet: string;
      agents: string;
      tools: string;
      ontology: string;
      steering: string;
      spend: string;
      organization: string;
      billing: string;
      audit: string;
      apiKeys: string;
    };
    switcher: {
      org: string;
      ws: string;
    };
    topbar: {
      label: string;
      menu: string;
      breadcrumbs: string;
      search: string;
      searchShortcut: string;
      userMenu: string;
    };
    userMenu: {
      switchTheme: string;
      themeNow: string;
    };
    commands: {
      title: string;
      input: string;
      empty: string;
      footer: {
        move: string;
        open: string;
        escape: string;
        close: string;
      };
    };
    mobileNav: {
      label: string;
      more: string;
    };
    drawer: {
      title: string;
      close: string;
    };
  };
  ui: {
    brand: {
      name: string;
      home: string;
    };
  };
};

declare module "next-intl" {
  interface AppConfig {
    Messages: Messages;
  }
}

export {};
