/**
 * `oxagen.ai` — the retired brand domain.
 *
 * The site it used to serve is gone; every route now redirects to the
 * `oxagen.sh` homepage (see `oxagen_ai_redirect` below). The domain itself is
 * emphatically not gone, and that is what makes this file mostly about
 * records that have nothing to do with the redirect:
 *
 *   - Mail. Inbound routes through improvMX; outbound is signed by Amazon SES,
 *     SendGrid, Stripe, Resend and Linear, each with its own DKIM keys, and
 *     policed by SPF and DMARC records at three different names.
 *   - Live services. `api`, `mcp` and `admin` are served from a Google Cloud
 *     load balancer that this migration does not touch, alongside `redis`,
 *     `clickhouse` and `pgadmin` on the same address. They answer today.
 *   - Ownership proofs. GitHub, Google, Discord, Anthropic, Mistral and Stripe
 *     each verify control of this domain through a TXT record.
 *
 * None of that survives a nameserver change on its own. The failure mode is
 * the reason this file is careful: a zone that is missing an MX record does
 * not return an error, it silently bounces mail, and a missing DKIM key does
 * not bounce anything — it just starts landing in spam folders, days later,
 * with nothing pointing back at the change that caused it.
 *
 * `imported-dns-oxagen-ai.json` is generated by `tools/import-dns.py` from the
 * previous provider's export and checked in deliberately, for the same reason
 * its `oxagen.sh` counterpart is: a 400-character DKIM public key retyped by
 * hand is a silent mail-delivery failure, and reviewing a generated file
 * against the export is a thing a human can actually do.
 */

locals {
  imported_dns_oxagen_ai = jsondecode(file("${path.module}/imported-dns-oxagen-ai.json"))
}

# The zone is created empty and the domain's nameservers are repointed at it by
# hand at the registrar — `oxagen.ai` is registered with Vercel, which
# Terraform has no provider credentials for here. `tofu output
# nameservers_oxagen_ai` is what gets typed into that form.
#
# Apply this file *before* repointing, never after. Between the two moments the
# world still resolves this domain through the old provider, so a zone that is
# incomplete when the nameservers move takes mail and three live services down
# with it, and the TTLs mean putting them back is not instant.
resource "aws_route53_zone" "oxagen_ai" {
  name    = "oxagen.ai"
  comment = "Oxagen — retired domain: redirects to oxagen.sh, still carries mail and the GCP-hosted services"
}

resource "aws_route53_record" "imported_oxagen_ai" {
  for_each = local.imported_dns_oxagen_ai

  zone_id = aws_route53_zone.oxagen_ai.zone_id
  name    = each.value.name == "" ? "oxagen.ai" : "${each.value.name}.oxagen.ai"
  type    = each.value.type
  ttl     = each.value.ttl
  records = each.value.records
}

# ---------------------------------------------------------------------------
# Subdomains still hosted elsewhere
# ---------------------------------------------------------------------------

# `tools/import-dns.py` drops every A record it finds, because for `oxagen.sh`
# an A record was always the old host and always the migration's subject. Here
# it is not: these six names point at a Google Cloud load balancer that is not
# part of this migration and is still serving. `api` answers, `mcp` answers,
# and carrying them across by hand is the difference between retiring a
# website and taking an API down.
#
# Explicit entries rather than a wildcard, and this is not a style preference.
# A wildcard record in this zone makes ACM's CAA check follow it to another
# domain and fail certificate issuance outright — the certificate goes to
# FAILED and has to be reissued, and the error names CAA rather than the
# wildcard that caused it. See `dns.tf` for the full account; it cost three
# reissues to find the first time.
#
# Each entry disappears when that service moves or is switched off.
resource "aws_route53_record" "oxagen_ai_elsewhere" {
  for_each = var.oxagen_ai_elsewhere

  zone_id = aws_route53_zone.oxagen_ai.zone_id
  name    = "${each.key}.oxagen.ai"
  type    = "A"
  ttl     = 300
  records = [each.value]
}

# ---------------------------------------------------------------------------
# Certificate authority authorisation
# ---------------------------------------------------------------------------

# Rewritten rather than carried over, on the same reasoning as `oxagen.sh`'s —
# though this zone starts from a better place: it already authorises
# `amazon.com`, so ACM can issue for the redirect's certificate. The set below
# reproduces exactly the four issuers live today.
#
# `pki.goog` is the load-bearing one here beyond Amazon. The `api`, `admin` and
# `mcp` names hold Google-issued certificates, renewed through the
# `_acme-challenge` records carried in the imported set; dropping that issuer
# would not break anything on the day and would fail their next renewal.
resource "aws_route53_record" "caa_oxagen_ai" {
  zone_id = aws_route53_zone.oxagen_ai.zone_id
  name    = "oxagen.ai"
  type    = "CAA"
  ttl     = 300

  records = [for issuer in var.caa_issuers : "0 issue \"${issuer}\""]
}

# ---------------------------------------------------------------------------
# The redirect
# ---------------------------------------------------------------------------

# Apex and `www` only. The other names in this zone are services and mail, not
# routes of a website, and sending `api.oxagen.ai` to a marketing homepage
# would turn a working API into a 301.
module "oxagen_ai_redirect" {
  source = "../../modules/redirect-site"

  providers = {
    aws           = aws
    aws.us_east_1 = aws.us_east_1
  }

  name                   = "oxagen-ai-redirect"
  domain_name            = "oxagen.ai"
  alternate_domain_names = ["www.oxagen.ai"]
  hosted_zone_id         = aws_route53_zone.oxagen_ai.zone_id
  redirect_to            = var.oxagen_ai_redirect_to

  tags = { Brand = local.brand }
}
