#!/usr/bin/env node
/**
 * check_manifest.mjs — regenerate the capability manifest and report any
 * declared layer that has no file on disk.
 *
 * Output modes:
 *   (default)   warn-only — gaps print as GitHub `::warning::` annotations and
 *               the process exits 0. Incomplete, in-progress capabilities (a
 *               normal mid-phase state) therefore do NOT fail CI. The gaps are
 *               instead tracked in Linear by tools/scripts/ensure-manifest-tickets.ts.
 *   --strict    restore the old behaviour — exit 1 if any gap exists (use when
 *               you want a hard completeness gate, e.g. a release cut).
 *   --json      emit the gaps as JSON to stdout ({ gaps: [{ capability, missing[] }] })
 *               and suppress the human logs. Consumed by the ticketer. Exit 0.
 *
 * A structural error (no contracts dir) always hard-fails (exit 2) regardless
 * of mode — that's a broken repo, not an incomplete feature.
 *
 * Layer→path map matches this monorepo's layout (not the skill template's
 * placeholder Next.js single-app layout).
 */
import { readdirSync, existsSync, writeFileSync, readFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ARGS = new Set(process.argv.slice(2));
const JSON_MODE = ARGS.has("--json");
const STRICT = ARGS.has("--strict");

// In --json mode stdout must be pure JSON for the ticketer, so silence the
// human-readable progress logs.
const info = JSON_MODE ? () => {} : (...a) => console.log(...a);

const ROOT = resolve(process.cwd());
const CAP_DIR = join(ROOT, "packages/oxagen/src/contracts");
const MANIFEST = join(ROOT, "packages/oxagen/capabilities.manifest.json");
const BARREL = join(ROOT, "packages/oxagen/src/contracts.generated.ts");

function slugify(name) {
  return name.replace(/\./g, "-");
}

// Regenerate the contract barrel from the contents of ./contracts. This is the
// auto-discovery that replaces the old hand-maintained import list in
// index.ts: adding a contract file is enough to register it, and a stale
// barrel is impossible because the gate rewrites it on every run.
function writeContractBarrel(files) {
  const imports = files
    .map((f) => f.replace(/\.ts$/, ""))
    .sort()
    .map((base) => `import "./contracts/${base}.js";`)
    .join("\n");
  const body = [
    "// AUTO-GENERATED by tools/scripts/check_manifest.mjs — do not edit by hand.",
    "// Every contract file under ./contracts auto-registers on import; this barrel",
    "// is the single import that pulls them all in. Run `pnpm check:manifest`",
    "// (or the gate) to regenerate after adding or removing a contract.",
    "",
    imports,
    "",
  ].join("\n");
  writeFileSync(BARREL, body);
}

/**
 * Returns true when the given layer is satisfied for a capability.
 *
 * The "mcp" layer is special: the MCP server dispatches ALL mcp-surface
 * capabilities dynamically via `capabilitiesForSurface("mcp") + invoke()`.
 * There are no per-tool files under apps/mcp/src/tools/ — they were deleted
 * in commit d401d73 because they were zombie stubs using the now-dead
 * placeholderContext(). The correct gate for the "mcp" layer is therefore:
 * does the capability's surfaces[] include "mcp"? If yes, the dynamic server
 * will dispatch it — that IS the mcp layer artifact.
 *
 * @param {string} layer - the layer name from the contract's layers[]
 * @param {string} capName - the capability name (e.g. "org.create")
 * @param {string[]} capSurfaces - the capability's surfaces[] array
 */
function layerSatisfied(layer, capName, capSurfaces) {
  const slug = slugify(capName);
  // The mcp layer is satisfied by dynamic dispatch: if the capability
  // declares "mcp" in its surfaces[], the server will serve it.
  if (layer === "mcp") {
    return capSurfaces.includes("mcp");
  }
  const candidates = {
    schema: [join(ROOT, "packages/database/src/schema")],
    api: [join(ROOT, `apps/api/src/routes/v1/${capName}.ts`)],
    unit: [join(CAP_DIR, `${capName}.test.ts`)],
    e2e: [join(ROOT, `apps/app/e2e/${slug}.spec.ts`)],
    docs: [join(ROOT, `docs/capabilities/${capName}.md`)],
    marketing: [join(ROOT, "apps/website")],
  };
  const paths = candidates[layer] ?? [];
  return paths.some((p) => existsSync(p));
}

function readCapabilities() {
  if (!existsSync(CAP_DIR)) {
    console.error(`No capabilities dir at ${CAP_DIR}.`);
    process.exit(2);
  }
  return readdirSync(CAP_DIR)
    .filter(
      (f) =>
        f.endsWith(".ts") &&
        f !== "index.ts" && // the contracts barrel/array, not a capability
        !f.endsWith(".test.ts") &&
        !f.endsWith(".handler.ts"),
    )
    .map((file) => {
      const src = readFileSync(join(CAP_DIR, file), "utf8");
      const nameMatch = src.match(/name:\s*["'`]([^"'`]+)["'`]/);
      const domainMatch = src.match(/domain:\s*["'`]([^"'`]+)["'`]/);
      const modeMatch = src.match(/mode:\s*["'`]([^"'`]+)["'`]/);
      const layersMatch = src.match(/layers:\s*\[([^\]]*)\]/);
      const surfacesMatch = src.match(/surfaces:\s*\[([^\]]*)\]/);
      const name = nameMatch ? nameMatch[1] : file.replace(/\.ts$/, "");
      const domain = domainMatch ? domainMatch[1] : "unknown";
      const mode = modeMatch ? modeMatch[1] : "sync";
      const layers = layersMatch
        ? layersMatch[1]
            .split(",")
            .map((s) => s.trim().replace(/["'`]/g, ""))
            .filter(Boolean)
        : [];
      const surfaces = surfacesMatch
        ? surfacesMatch[1]
            .split(",")
            .map((s) => s.trim().replace(/["'`]/g, ""))
            .filter(Boolean)
        : ["api", "mcp"];
      return { file, name, domain, mode, surfaces, layers };
    });
}

function main() {
  const caps = readCapabilities();

  // Auto-discovery: rewrite the contract barrel so adding a contract file is
  // the only step needed to register it.
  writeContractBarrel(caps.map((c) => c.file));
  info(`Wrote ${BARREL} with ${caps.length} contract imports.`);

  // No timestamp: this file is committed, so a `generatedAt` would make it
  // nondeterministic and churn git on every regeneration. The content is a
  // pure function of the contract files, which is what we want to track.
  const manifest = { capabilities: [] };
  // gapsByCap: { "<capability>": ["<missing layer>", ...] } — grouped so the
  // ticketer can open one item per capability rather than one per layer.
  const gapsByCap = {};

  for (const cap of caps) {
    const layerStatus = {};
    for (const layer of cap.layers) {
      const ok = layerSatisfied(layer, cap.name, cap.surfaces);
      layerStatus[layer] = ok;
      if (!ok) (gapsByCap[cap.name] ??= []).push(layer);
    }
    manifest.capabilities.push({
      name: cap.name,
      file: cap.file,
      domain: cap.domain,
      mode: cap.mode,
      surfaces: cap.surfaces,
      layers: layerStatus,
    });
  }

  writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + "\n");
  info(`Wrote ${MANIFEST} with ${manifest.capabilities.length} capabilities.`);

  const gaps = Object.entries(gapsByCap).map(([capability, missing]) => ({
    capability,
    missing,
  }));

  // --json: emit the structured gap list for ensure-manifest-tickets.ts.
  if (JSON_MODE) {
    process.stdout.write(JSON.stringify({ gaps }, null, 2) + "\n");
    return;
  }

  if (gaps.length) {
    // GitHub Actions surfaces `::warning::` lines as annotations on the run.
    for (const { capability, missing } of gaps) {
      console.log(
        `::warning title=Manifest gap::${capability} missing layer(s): ${missing.join(", ")}`,
      );
    }
    console.error("\nMANIFEST GAPS — feature incomplete (tracked in Linear, not blocking):");
    for (const { capability, missing } of gaps) {
      for (const layer of missing) console.error(`  - ${capability}: missing "${layer}"`);
    }
    // --strict restores the hard gate; default is warn-only (exit 0).
    if (STRICT) {
      console.error("\n--strict: failing because gaps exist.");
      process.exit(1);
    }
    console.error(
      "\n(warn-only — pass --strict to fail; gaps are filed to Linear by ensure-manifest-tickets.)",
    );
    return;
  }
  info("All declared layers satisfied.");
}

main();
