#!/usr/bin/env tsx
/**
 * cli-dev — install the `oxagen` binary onto the developer's PATH so it runs the
 * `@oxagen/cli` source directly through the repo's own `tsx`.
 *
 * Why a launcher script instead of a symlink to `dist/index.js`:
 * the CLI imports workspace packages (e.g. `@oxagen/engram`) that are published
 * as raw TypeScript (`exports` → `./src/index.ts`), so the built `dist/index.js`
 * cannot run under plain `node`, and its `#!/usr/bin/env tsx` shebang fails
 * unless `tsx` happens to be on the global PATH (it isn't — it's a workspace
 * dev-dependency). Instead we install a tiny shell launcher that execs the
 * repo-local `tsx` against `src/index.tsx`. Benefits:
 *   - works for every command, including ones that load TS-only workspace deps;
 *   - always reflects the working tree (no build, no watch, no stale dist);
 *   - preserves the caller's cwd, so `oxagen` operates on the directory you run
 *     it from.
 *
 * Usage:
 *   pnpm cli:dev          # install `oxagen` onto PATH (runs live from source)
 *   pnpm cli:dev --once   # same; kept for backwards compatibility
 */
import kleur from "kleur";
import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { delimiter, join, resolve } from "node:path";
import { homedir } from "node:os";

const ROOT = resolve(process.cwd());
const CLI_DIR = resolve(ROOT, "apps/cli");
const SRC_ENTRY = resolve(CLI_DIR, "src/index.tsx");
const TSX_BIN = resolve(ROOT, "node_modules/.bin/tsx");
const BIN_NAME = "oxagen";

/** Directories on $PATH, in priority order, that we're willing to install into. */
function pathEntries(): string[] {
  return (process.env.PATH ?? "")
    .split(delimiter)
    .filter(Boolean)
    .map((p) => resolve(p));
}

function isSymlink(p: string): boolean {
  try {
    return lstatSync(p).isSymbolicLink();
  } catch {
    return false;
  }
}

/**
 * Pick a writable bin directory that is already on the developer's PATH.
 * Preference: ~/.local/bin, then any other writable PATH entry. We never fall
 * back to a dir that isn't on PATH — a binary you can't invoke is worse than a
 * clear error telling you how to fix your PATH.
 */
function resolveInstallDir(): { dir: string; onPath: boolean } {
  const onPath = new Set(pathEntries());
  const localBin = resolve(homedir(), ".local/bin");
  const preferred = [localBin, ...[...onPath]];

  for (const dir of preferred) {
    if (!onPath.has(dir)) continue;
    try {
      mkdirSync(dir, { recursive: true });
      const probe = join(dir, `.oxagen-cli-dev-probe-${process.pid}`);
      symlinkSync(SRC_ENTRY, probe);
      rmSync(probe);
      return { dir, onPath: true };
    } catch {
      // not writable / not creatable — try the next candidate
    }
  }

  mkdirSync(localBin, { recursive: true });
  return { dir: localBin, onPath: false };
}

/** Write the `oxagen` launcher into the install dir and make it executable. */
function installLauncher(installDir: string): string {
  const linkPath = join(installDir, BIN_NAME);
  const launcher = `#!/bin/sh
# Auto-generated by \`pnpm cli:dev\`. Runs the @oxagen/cli source through the
# repo's own tsx so every invocation reflects the working tree. Do not edit.
exec "${TSX_BIN}" "${SRC_ENTRY}" "$@"
`;

  // Replace whatever is there (old symlink from a previous install, or stale launcher).
  if (existsSync(linkPath) || isSymlink(linkPath)) {
    rmSync(linkPath, { force: true });
  }
  writeFileSync(linkPath, launcher, "utf8");
  chmodSync(linkPath, 0o755);
  return linkPath;
}

function main(): void {
  if (!existsSync(TSX_BIN)) {
    console.error(
      kleur.red(
        `[cli:dev] repo tsx not found at ${TSX_BIN} — run \`pnpm install\` first.`,
      ),
    );
    process.exit(1);
  }

  const { dir, onPath } = resolveInstallDir();
  const linkPath = installLauncher(dir);

  console.log(
    kleur.green(`[cli:dev] installed ${kleur.bold(BIN_NAME)} → ${linkPath}`),
  );
  console.log(kleur.dim(`[cli:dev]   ↳ runs ${SRC_ENTRY} via tsx (live source)`));

  if (!onPath) {
    console.log("");
    console.log(
      kleur.yellow(
        `[cli:dev] ⚠ ${dir} is not on your PATH — \`${BIN_NAME}\` won't resolve yet.`,
      ),
    );
    console.log(kleur.yellow(`[cli:dev]   Add it to your shell profile:`));
    console.log(kleur.yellow(`[cli:dev]     export PATH="${dir}:$PATH"`));
    console.log("");
  }

  console.log(kleur.dim(`[cli:dev] verify with:  ${BIN_NAME} --help`));
}

main();
