#!/usr/bin/env tsx
/**
 * gen-rls-migration.ts — generate bypass-aware Postgres RLS policies from
 * the POLICY_MANIFEST into the Atlas migration directory.
 *
 * Usage:
 *   pnpm tsx tools/scripts/gen-rls-migration.ts [out-file-name.sql]
 *   cd packages/database && pnpm exec atlas migrate hash   # re-stamp atlas.sum
 *
 * Default output: packages/database/atlas/migrations/<existing or new>
 * restore_rls_policies file. Pass an explicit file name (e.g.
 * `20260701120000_rls_new_tables.sql`) to emit a fresh follow-up migration
 * after adding tables to the manifest.
 *
 * WHY THIS LIVES IN ATLAS (OXA-1700): the Atlas baseline is generated from
 * `drizzle-kit export`, which emits ONLY what Drizzle models — the 2026-06-11
 * re-baseline silently dropped every ENABLE/FORCE ROW LEVEL SECURITY and
 * tenant_isolation policy (the same failure mode that dropped the oxagen_app
 * GRANTs, see 20260612052000_regrant_oxagen_app.sql). Keeping the policy DDL
 * as a versioned Atlas migration means `atlas migrate apply` replays it on
 * every fresh environment, and integration/manifest-coverage.test.ts fails CI
 * if a future rebuild loses it again.
 *
 * The generated SQL is idempotent (DROP POLICY IF EXISTS + CREATE) so the
 * file can be regenerated in place BEFORE it has shipped. Once applied to a
 * persistent environment it is immutable like any other migration — additions
 * go in a NEW file (pass a file name argument).
 *
 * NOTE: ESM-safe path resolution via fileURLToPath(import.meta.url) — the
 * repo is ESM ("type":"module"). Do NOT use __dirname here.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  POLICY_MANIFEST,
  type PolicyClass,
} from "../../packages/database/src/tenant-policy.manifest.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ORG = `nullif(current_setting('app.current_org_id', true), '')::uuid`;
const WS = `nullif(current_setting('app.current_workspace_id', true), '')::uuid`;
const BYPASS = `current_setting('app.rls_bypass', true) = 'on'`;

interface Predicates {
  /** Read filter (SELECT/UPDATE/DELETE visibility). */
  readonly using: string;
  /** Write filter (INSERT/UPDATE row acceptance). */
  readonly check: string;
}

function predicates(cls: PolicyClass): Predicates {
  if (cls === "org_only") {
    const p = `${BYPASS} OR (org_id = ${ORG})`;
    return { using: p, check: p };
  }
  if (cls === "workspace_nullable") {
    const p = `${BYPASS} OR (org_id = ${ORG} AND (workspace_id IS NULL OR workspace_id = ${WS}))`;
    return { using: p, check: p };
  }
  if (cls === "workspace_only") {
    // Membership/join tables that carry workspace_id but no org_id.
    const p = `${BYPASS} OR (workspace_id = ${WS})`;
    return { using: p, check: p };
  }
  if (cls === "org_or_global") {
    // Nullable org_id: NULL rows are a shared/global catalog. This is the ONE
    // class where USING ≠ WITH CHECK:
    //   • READS  (USING): own-org rows + the global (NULL) catalog.
    //   • WRITES (CHECK): own-org rows ONLY. Creating/altering a global (NULL)
    //     row is reserved for the seeding/system path (app.rls_bypass='on').
    // A symmetric predicate would let any tenant INSERT org_id=NULL and publish
    // a platform-wide registry entry visible to everyone (SSRF / supply-chain).
    return {
      using: `${BYPASS} OR (org_id IS NULL OR org_id = ${ORG})`,
      check: `${BYPASS} OR (org_id = ${ORG})`,
    };
  }
  if (cls === "standard_or_builtin") {
    // Nil-UUID sentinel rows (packages/skills BUILTIN_ORG_ID/WORKSPACE_ID) are
    // a platform-global catalog: readable by every tenant, writable only via
    // the bypass/seeding path. Same read/write asymmetry rationale as
    // org_or_global — a symmetric predicate would let any tenant publish a
    // platform-wide builtin row.
    const NIL = `'00000000-0000-0000-0000-000000000000'::uuid`;
    return {
      using: `${BYPASS} OR (org_id = ${ORG} AND workspace_id = ${WS}) OR (org_id = ${NIL} AND workspace_id = ${NIL})`,
      check: `${BYPASS} OR (org_id = ${ORG} AND workspace_id = ${WS})`,
    };
  }
  // standard: org_id + workspace_id both required
  const p = `${BYPASS} OR (org_id = ${ORG} AND workspace_id = ${WS})`;
  return { using: p, check: p };
}

const blocks = POLICY_MANIFEST.map(({ table, policyClass }) => {
  const { using, check } = predicates(policyClass);
  return `ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${table} FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ${table};
CREATE POLICY tenant_isolation ON ${table}
  USING (${using})
  WITH CHECK (${check});`;
});

const sqlContent = `-- GENERATED by tools/scripts/gen-rls-migration.ts — do not edit by hand.
-- Re-generate with: pnpm tsx tools/scripts/gen-rls-migration.ts
-- then: cd packages/database && pnpm exec atlas migrate hash
--
-- Restore tenant + workspace RLS lost in the 2026-06-11 Atlas re-baseline
-- (OXA-1700; original design OXA-1515). \`drizzle-kit export\` emits only the
-- Drizzle-modeled schema, so policy DDL must live as a versioned migration in
-- this directory to survive rebuilds — exactly like the oxagen_app regrant.
--
-- Bypass-aware: app.rls_bypass='on' (set by withSystemDb / the seeding window
-- when TENANT_RLS_ENFORCEMENT_ENABLED=false) disables filtering; tenant
-- sessions get app.current_org_id / app.current_workspace_id via withTenantDb.
-- FORCE applies policies to the table owner too; only superusers and
-- BYPASSRLS roles are exempt — oxagen_app is neither.
-- ${POLICY_MANIFEST.length} tables.

${blocks.join("\n\n")}
`;

const outName = process.argv[2] ?? "20260612140000_restore_rls_policies.sql";
if (!/^\d{14}_[a-z0-9_]+\.sql$/.test(outName)) {
  console.error(
    `refusing to write "${outName}" — Atlas migration names must match <14-digit-timestamp>_<slug>.sql`,
  );
  process.exit(1);
}
const outPath = resolve(
  __dirname,
  "../../packages/database/atlas/migrations",
  outName,
);
writeFileSync(outPath, sqlContent, "utf8");
console.log(
  `wrote ${outPath} (${POLICY_MANIFEST.length} tables) — now run: cd packages/database && pnpm exec atlas migrate hash`,
);
