#!/usr/bin/env tsx
/**
 * gen-rls-migration.ts — generate bypass-aware Postgres RLS policies from
 * the POLICY_MANIFEST and write them to packages/database/drizzle/0001_rls_policies.sql.
 *
 * Usage: pnpm tsx tools/scripts/gen-rls-migration.ts
 *
 * The migration is applied by `pnpm db:migrate` (tools/scripts/db-migrate.ts),
 * which reads every *.sql file in packages/database/drizzle/ sorted by name
 * and applies unapplied files via the public._migrations tracking table.
 *
 * NOTE: This file uses ESM-safe path resolution via fileURLToPath(import.meta.url)
 * because the repo is ESM ("type":"module"). Do NOT use __dirname here.
 */
import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { POLICY_MANIFEST, type PolicyClass } from "../../packages/database/src/tenant-policy.manifest.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ORG = `nullif(current_setting('app.current_org_id', true), '')::uuid`;
const WS = `nullif(current_setting('app.current_workspace_id', true), '')::uuid`;
const BYPASS = `current_setting('app.rls_bypass', true) = 'on'`;

interface Predicates {
  /** Read filter (SELECT/UPDATE/DELETE visibility). */
  readonly using: string;
  /** Write filter (INSERT/UPDATE row acceptance). */
  readonly check: string;
}

function predicates(cls: PolicyClass): Predicates {
  if (cls === "org_only") {
    const p = `${BYPASS} OR (org_id = ${ORG})`;
    return { using: p, check: p };
  }
  if (cls === "workspace_nullable") {
    const p = `${BYPASS} OR (org_id = ${ORG} AND (workspace_id IS NULL OR workspace_id = ${WS}))`;
    return { using: p, check: p };
  }
  if (cls === "workspace_only") {
    // Membership/join tables that carry workspace_id but no org_id.
    const p = `${BYPASS} OR (workspace_id = ${WS})`;
    return { using: p, check: p };
  }
  if (cls === "org_or_global") {
    // Nullable org_id: NULL rows are a shared/global catalog. This is the ONE
    // class where USING ≠ WITH CHECK:
    //   • READS  (USING): own-org rows + the global (NULL) catalog.
    //   • WRITES (CHECK): own-org rows ONLY. Creating/altering a global (NULL)
    //     row is reserved for the seeding/system path (app.rls_bypass='on').
    // A symmetric predicate would let any tenant INSERT org_id=NULL and publish
    // a platform-wide registry entry visible to everyone (SSRF / supply-chain).
    return {
      using: `${BYPASS} OR (org_id IS NULL OR org_id = ${ORG})`,
      check: `${BYPASS} OR (org_id = ${ORG})`,
    };
  }
  if (cls === "org_or_global") {
    // Nullable org_id: NULL rows are a shared/global catalog. This is the ONE
    // class where USING ≠ WITH CHECK:
    //   • READS  (USING): own-org rows + the global (NULL) catalog.
    //   • WRITES (CHECK): own-org rows ONLY. Creating/altering a global (NULL)
    //     row is reserved for the seeding/system path (app.rls_bypass='on').
    // A symmetric predicate would let any tenant INSERT org_id=NULL and publish
    // a platform-wide registry entry visible to everyone (SSRF / supply-chain).
    return {
      using: `${BYPASS} OR (org_id IS NULL OR org_id = ${ORG})`,
      check: `${BYPASS} OR (org_id = ${ORG})`,
    };
  }
  // standard: org_id + workspace_id both required
  const p = `${BYPASS} OR (org_id = ${ORG} AND workspace_id = ${WS})`;
  return { using: p, check: p };
}

const blocks = POLICY_MANIFEST.map(({ table, policyClass }) => {
  const { using, check } = predicates(policyClass);
  return `ALTER TABLE ${table} ENABLE ROW LEVEL SECURITY;
ALTER TABLE ${table} FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON ${table};
CREATE POLICY tenant_isolation ON ${table}
  USING (${using})
  WITH CHECK (${check});`;
});

const sqlContent = `-- GENERATED by tools/scripts/gen-rls-migration.ts — do not edit by hand.
-- Re-generate with: pnpm tsx tools/scripts/gen-rls-migration.ts
-- Tenant + workspace RLS (OXA-1515). Bypass-aware: app.rls_bypass='on' disables
-- filtering during the seeding window (TENANT_RLS_ENFORCEMENT_ENABLED=false).
-- Applied by: pnpm db:migrate (tools/scripts/db-migrate.ts) via public._migrations.
BEGIN;

${blocks.join("\n\n")}

COMMIT;
`;

const outPath = resolve(__dirname, "../../packages/database/drizzle/0001_rls_policies.sql");
writeFileSync(outPath, sqlContent, "utf8");
console.log(`wrote 0001_rls_policies.sql (${POLICY_MANIFEST.length} tables)`);
