import { execFileSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  discoverManifests,
  readManifestVersion,
  setAllVersions,
  versionDrift,
} from "./lib/versions";

// A scratch repository with one manifest of each kind, tracked by git the
// way the real tree is, since discovery goes through `git ls-files`.
let root: string;

function write(rel: string, text: string): void {
  const path = join(root, rel);
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, text);
}

const CARGO_TOML = `[package]
name = "oxagen-desktop"
version = "2.1.1"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
`;

const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "derive_more"
version = "2.1.1"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "oxagen-desktop"
version = "2.1.1"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.219"
`;

const PYPROJECT = `[build-system]
requires = ["hatchling"]

[project]
name = "oxagen-py"
version = "2.1.1"
description = "example"
`;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), "oxagen-versions-"));
  write(
    "package.json",
    '{\n  "name": "root",\n  "version": "2.1.1",\n  "private": true\n}\n',
  );
  write(
    "pnpm-workspace.yaml",
    'packages:\n  - "apps/*"\n  - "packages/*"\n\noverrides:\n  zod: 3.0.0\n',
  );
  write(
    "apps/cli/package.json",
    '{\n  "name": "@oxagen/cli",\n  "version": "2.1.1"\n}\n',
  );
  write(
    "packages/rules/package.json",
    '{\n  "name": "@oxagen/rules",\n  "version": "0.1.0"\n}\n',
  );
  write(
    "packages/noversion/package.json",
    '{\n  "name": "@oxagen/noversion",\n  "private": true\n}\n',
  );
  write("apps/desktop/src-tauri/Cargo.toml", CARGO_TOML);
  write("apps/desktop/src-tauri/Cargo.lock", CARGO_LOCK);
  write("tools/py/pyproject.toml", PYPROJECT);
  // Untracked and nested-elsewhere manifests must not count.
  write("node_modules/dep/package.json", '{"name":"dep","version":"9.9.9"}');
  write(
    "scratch/Cargo.toml",
    '[package]\nname = "scratch"\nversion = "0.0.1"\n',
  );
  const git = (args: string[]) =>
    execFileSync("git", args, { cwd: root, encoding: "utf8", stdio: "pipe" });
  git(["init", "-q"]);
  git([
    "add",
    "package.json",
    "pnpm-workspace.yaml",
    "apps",
    "packages",
    "tools",
  ]);
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe("discoverManifests", () => {
  it("finds every tracked manifest kind and nothing untracked", () => {
    const found = discoverManifests(root).map(
      (m) => `${m.kind}:${m.file}:${m.name}`,
    );
    expect(found).toEqual([
      "package.json:package.json:root",
      "package.json:apps/cli/package.json:@oxagen/cli",
      "package.json:packages/noversion/package.json:@oxagen/noversion",
      "package.json:packages/rules/package.json:@oxagen/rules",
      "Cargo.toml:apps/desktop/src-tauri/Cargo.toml:oxagen-desktop",
      "Cargo.lock:apps/desktop/src-tauri/Cargo.lock:oxagen-desktop",
      "pyproject.toml:tools/py/pyproject.toml:oxagen-py",
    ]);
  });
});

describe("versionDrift", () => {
  it("names each manifest that disagrees with the root", () => {
    const { version, drift } = versionDrift(root);
    expect(version).toBe("2.1.1");
    expect(drift.map((d) => [d.file, d.version])).toEqual([
      ["packages/noversion/package.json", null],
      ["packages/rules/package.json", "0.1.0"],
    ]);
  });
});

describe("setAllVersions", () => {
  it("writes one version into every kind and touches only the version line", () => {
    const written = setAllVersions(root, "2.2.0");
    expect(written.map((w) => w.from)).toEqual([
      "2.1.1",
      "2.1.1",
      null,
      "0.1.0",
      "2.1.1",
      "2.1.1",
      "2.1.1",
    ]);
    expect(versionDrift(root).drift).toEqual([]);

    const lock = readFileSync(
      join(root, "apps/desktop/src-tauri/Cargo.lock"),
      "utf8",
    );
    // The crate's own entry moved; the dependency that happened to share the
    // number did not.
    expect(lock).toContain('name = "oxagen-desktop"\nversion = "2.2.0"');
    expect(lock).toContain('name = "derive_more"\nversion = "2.1.1"');
    expect(lock).toContain('name = "serde"\nversion = "1.0.219"');

    const cargo = readFileSync(
      join(root, "apps/desktop/src-tauri/Cargo.toml"),
      "utf8",
    );
    expect(cargo).toContain('version = "2.2.0"\nedition = "2021"');
    expect(cargo).toContain('serde = { version = "1", features = ["derive"] }');

    const py = readFileSync(join(root, "tools/py/pyproject.toml"), "utf8");
    expect(py).toContain('[project]\nname = "oxagen-py"\nversion = "2.2.0"');

    const injected = readFileSync(
      join(root, "packages/noversion/package.json"),
      "utf8",
    );
    expect(injected).toBe(
      '{\n  "name": "@oxagen/noversion",\n  "version": "2.2.0",\n  "private": true\n}\n',
    );
  });

  it("refuses a version that is not X.Y.Z", () => {
    expect(() => setAllVersions(root, "2.2")).toThrow(/not a release version/);
    expect(
      readManifestVersion(root, {
        file: "package.json",
        kind: "package.json",
        name: "root",
      }),
    ).toBe("2.1.1");
  });
});
