/**
 * Pipeline (runTurn) — graph-sync port tests.
 *
 * Proves that:
 *  1. runTurn fires the injected GraphSyncProvider after a turn that touches files.
 *  2. A GraphSyncProvider that throws does NOT propagate the error and does NOT
 *     cause the turn to fail.
 *  3. graphSync is NOT called when filesTouched is empty (no file mutations).
 */
import { describe, it, expect, vi } from "vitest";
import { MemoryWorkspace } from "../workspaces/memory";
import { runTurn } from "./index";
import { DEFAULT_AGENT_MODEL } from "../engine";
import { classifyTier, modelForTier } from "../router/model-router";
import type { AgentAi, GraphSyncProvider, ModelRunArgs } from "../ports";

// ── Minimal AgentAi that optionally edits a file, then returns. ──────────────

function makeAi(editFile?: string): AgentAi {
  return {
    stream(args: ModelRunArgs) {
      return {
        fullStream: (async function* () {
          if (editFile) {
            const editTool = args.tools.edit_file as {
              execute: (i: unknown, o: unknown) => Promise<unknown>;
            };
            await editTool.execute(
              { path: editFile, old_string: "before", new_string: "after" },
              {},
            );
          }
          yield { type: "text-delta", text: "done" };
        })(),
        steps: Promise.resolve([{}]),
        usage: Promise.resolve({ inputTokens: 1, outputTokens: 1, totalTokens: 2 }),
        response: Promise.resolve({ messages: [] }),
      } as unknown as ReturnType<AgentAi["stream"]>;
    },
    generateObject: async () => ({ object: {} as never, usage: { totalTokens: 0 } }),
  };
}

describe("runTurn — GraphSyncProvider", () => {
  it("fires ensureGraph and recordLineage with the touched file after a turn", async () => {
    const ws = new MemoryWorkspace({ "src/a.ts": "before" });

    const ensureGraph = vi.fn().mockResolvedValue(undefined);
    const recordLineage = vi.fn().mockResolvedValue(undefined);
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    await runTurn({
      prompt: "rename before to after in src/a.ts",
      workspace: ws,
      ai: makeAi("src/a.ts"),
      bare: true,
      graphSync,
    });

    // Give fire-and-forget promises a tick to settle.
    await new Promise((r) => setImmediate(r));

    expect(ensureGraph).toHaveBeenCalledOnce();
    expect(ensureGraph).toHaveBeenCalledWith(expect.arrayContaining(["src/a.ts"]));

    expect(recordLineage).toHaveBeenCalledOnce();
    const [[lineageArgs]] = recordLineage.mock.calls as [[{ executionId: string; touchedFiles: string[] }]];
    expect(lineageArgs.touchedFiles).toContain("src/a.ts");
    // executionId is a turn_ prefixed id generated by the pipeline.
    expect(lineageArgs.executionId).toMatch(/^turn_/);
  });

  it("does NOT propagate a throwing ensureGraph — the turn still succeeds", async () => {
    const ws = new MemoryWorkspace({ "src/b.ts": "before" });

    const ensureGraph = vi.fn().mockRejectedValue(new Error("Neo4j down"));
    const recordLineage = vi.fn().mockResolvedValue(undefined);
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    const result = await runTurn({
      prompt: "rename before to after in src/b.ts",
      workspace: ws,
      ai: makeAi("src/b.ts"),
      bare: true,
      graphSync,
    });

    // Give fire-and-forget promises a tick to settle.
    await new Promise((r) => setImmediate(r));

    // Turn must succeed despite the throwing hook.
    expect(result.text).toBe("done");
    expect(ensureGraph).toHaveBeenCalledOnce();
  });

  it("does NOT propagate a throwing recordLineage — the turn still succeeds", async () => {
    const ws = new MemoryWorkspace({ "src/c.ts": "before" });

    const ensureGraph = vi.fn().mockResolvedValue(undefined);
    const recordLineage = vi.fn().mockRejectedValue(new Error("write error"));
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    const result = await runTurn({
      prompt: "rename before to after in src/c.ts",
      workspace: ws,
      ai: makeAi("src/c.ts"),
      bare: true,
      graphSync,
    });

    await new Promise((r) => setImmediate(r));

    expect(result.text).toBe("done");
    expect(recordLineage).toHaveBeenCalledOnce();
  });

  it("forwards the git diff + changed files to onFileChange after an edit", async () => {
    const ws = new MemoryWorkspace({ "src/e.ts": "before" });
    const changes: Array<{ diff: string; changedFiles: string[] }> = [];

    await runTurn({
      prompt: "rename before to after in src/e.ts",
      workspace: ws,
      ai: makeAi("src/e.ts"),
      bare: true,
      onFileChange: (diff, changedFiles) => changes.push({ diff, changedFiles }),
    });

    expect(changes.length).toBeGreaterThan(0);
    const last = changes[changes.length - 1]!;
    expect(last.changedFiles).toContain("src/e.ts");
    expect(last.diff).toContain("src/e.ts");
  });

  it("does NOT call graphSync when no files are touched", async () => {
    // AI emits text but edits no files.
    const ws = new MemoryWorkspace({ "src/d.ts": "untouched" });

    const ensureGraph = vi.fn();
    const recordLineage = vi.fn();
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    await runTurn({
      prompt: "describe the file",
      workspace: ws,
      ai: makeAi(), // no file edit
      bare: true,
      graphSync,
    });

    await new Promise((r) => setImmediate(r));

    expect(ensureGraph).not.toHaveBeenCalled();
    expect(recordLineage).not.toHaveBeenCalled();
  });
});

describe("runTurn — bare mode model accounting", () => {
  it("labels/accounts an unpinned, high-stakes bare run with DEFAULT_AGENT_MODEL, matching what actually executes", async () => {
    // Regression test: runBare's accounting used to compute the label via
    // modelForTier("balanced") (Sonnet) while the actual execution call below
    // it passed `opts.model` through as-is — undefined when unpinned, which
    // fell through to runCodingAgent's OWN internal default
    // (DEFAULT_AGENT_MODEL, Fable 5). The label silently diverged from what
    // ran. Assert BOTH sides agree: the model the stream() call actually
    // received, and the label recorded on the trace. A prompt that matches
    // PRECISE_DOMAINS (auth) still floors to the frontier tier — same slug as
    // DEFAULT_AGENT_MODEL — so this also covers the classifyTier escalation
    // path (Perf #8), not just the old hard-default.
    const ws = new MemoryWorkspace({ "a.ts": "x" });
    let modelUsed: string | undefined;
    const ai: AgentAi = {
      stream(args: ModelRunArgs) {
        modelUsed = args.model;
        return {
          fullStream: (async function* () {
            yield { type: "text-delta", text: "done" };
          })(),
          steps: Promise.resolve([{}]),
          usage: Promise.resolve({ inputTokens: 1, outputTokens: 1, totalTokens: 2 }),
          response: Promise.resolve({ messages: [] }),
        } as unknown as ReturnType<AgentAi["stream"]>;
      },
      generateObject: async () => ({ object: {} as never, usage: { totalTokens: 0 } }),
    };

    const prompt = "do something";
    const result = await runTurn({
      prompt: "fix the authentication bug in the login flow",
      workspace: ws,
      ai,
      bare: true,
      // No `model` passed — the label AND the actual execution must both
      // resolve to the router's tier for this prompt (never diverge).
    });

    const expected = modelForTier(classifyTier({ text: prompt }).tier);
    expect(modelUsed).toBe(expected);
    expect(result.trace.selectedModel).toBe(expected);
    // The whole point: label == execution.
    expect(result.trace.selectedModel).toBe(modelUsed);
  });

  it("routes an unpinned, trivial bare run through the classifyTier floor (Perf #8), matching what actually executes", async () => {
    // Perf #8: an unpinned bare turn no longer hard-defaults to the frontier
    // tier — a trivial, short, single-file-scoped ask routes through the same
    // deterministic classifyTier floor the full pipeline uses, so it runs on
    // the cheap tier. Assert the label and the actual execution still agree
    // (no divergence), and that it is NOT the frontier default.
    const ws = new MemoryWorkspace({ "a.ts": "x" });
    let modelUsed: string | undefined;
    const ai: AgentAi = {
      stream(args: ModelRunArgs) {
        modelUsed = args.model;
        return {
          fullStream: (async function* () {
            yield { type: "text-delta", text: "done" };
          })(),
          steps: Promise.resolve([{}]),
          usage: Promise.resolve({ inputTokens: 1, outputTokens: 1, totalTokens: 2 }),
          response: Promise.resolve({ messages: [] }),
        } as unknown as ReturnType<AgentAi["stream"]>;
      },
      generateObject: async () => ({ object: {} as never, usage: { totalTokens: 0 } }),
    };

    const result = await runTurn({
      prompt: "do something",
      workspace: ws,
      ai,
      bare: true,
      // No `model` passed — both the label and the actual execution must
      // resolve to the SAME classifyTier-derived default.
    });

    expect(modelUsed).not.toBe(DEFAULT_AGENT_MODEL);
    expect(result.trace.selectedModel).toBe(modelUsed);
  });

  it("still labels/accounts a pinned bare run with the pinned model", async () => {
    const ws = new MemoryWorkspace({ "a.ts": "x" });
    const result = await runTurn({
      prompt: "do something",
      workspace: ws,
      ai: makeAi(),
      bare: true,
      model: "openai/gpt-5",
    });
    expect(result.trace.selectedModel).toBe("openai/gpt-5");
  });
});

describe("runTurn — thinking-log persistence", () => {
  function aiWithReasoning(reasoning: string): AgentAi {
    return {
      stream(_args: ModelRunArgs) {
        return {
          fullStream: (async function* () {
            yield { type: "reasoning-delta", text: reasoning };
            yield { type: "text-delta", text: "done" };
          })(),
          steps: Promise.resolve([{}]),
          usage: Promise.resolve({ inputTokens: 1, outputTokens: 1, totalTokens: 2 }),
          response: Promise.resolve({ messages: [] }),
          finishReason: Promise.resolve("stop"),
        } as unknown as ReturnType<AgentAi["stream"]>;
      },
      generateObject: async () => ({ object: {} as never, usage: { totalTokens: 0 } }),
    };
  }

  it("persists the model's reasoning onto the trace (bare path)", async () => {
    const ws = new MemoryWorkspace({ "a.ts": "x" });
    const result = await runTurn({
      prompt: "think about it",
      workspace: ws,
      ai: aiWithReasoning("I should check the imports before editing."),
      bare: true,
    });
    expect(result.trace.thinkingLog).toBeDefined();
    expect(result.trace.thinkingLog?.[0]?.text).toContain("check the imports");
    expect(result.trace.thinkingLog?.[0]?.round).toBe(0);
  });

  it("omits the thinking log when the model emits no reasoning", async () => {
    const ws = new MemoryWorkspace({ "a.ts": "x" });
    const result = await runTurn({
      prompt: "no reasoning here",
      workspace: ws,
      ai: makeAi(),
      bare: true,
    });
    expect(result.trace.thinkingLog).toBeUndefined();
  });
});
