/**
 * Pipeline (runTurn) — graph-sync port tests.
 *
 * Proves that:
 *  1. runTurn fires the injected GraphSyncProvider after a turn that touches files.
 *  2. A GraphSyncProvider that throws does NOT propagate the error and does NOT
 *     cause the turn to fail.
 *  3. graphSync is NOT called when filesTouched is empty (no file mutations).
 */
import { describe, it, expect, vi } from "vitest";
import { MemoryWorkspace } from "../workspaces/memory";
import { runTurn } from "./index";
import type { AgentAi, GraphSyncProvider, ModelRunArgs } from "../ports";

// ── Minimal AgentAi that optionally edits a file, then returns. ──────────────

function makeAi(editFile?: string): AgentAi {
  return {
    stream(args: ModelRunArgs) {
      return {
        fullStream: (async function* () {
          if (editFile) {
            const editTool = args.tools.edit_file as {
              execute: (i: unknown, o: unknown) => Promise<unknown>;
            };
            await editTool.execute(
              { path: editFile, old_string: "before", new_string: "after" },
              {},
            );
          }
          yield { type: "text-delta", text: "done" };
        })(),
        steps: Promise.resolve([{}]),
        usage: Promise.resolve({ inputTokens: 1, outputTokens: 1, totalTokens: 2 }),
        response: Promise.resolve({ messages: [] }),
      } as unknown as ReturnType<AgentAi["stream"]>;
    },
    generateObject: async () => ({ object: {} as never, usage: { totalTokens: 0 } }),
  };
}

describe("runTurn — GraphSyncProvider", () => {
  it("fires ensureGraph and recordLineage with the touched file after a turn", async () => {
    const ws = new MemoryWorkspace({ "src/a.ts": "before" });

    const ensureGraph = vi.fn().mockResolvedValue(undefined);
    const recordLineage = vi.fn().mockResolvedValue(undefined);
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    await runTurn({
      prompt: "rename before to after in src/a.ts",
      workspace: ws,
      ai: makeAi("src/a.ts"),
      bare: true,
      graphSync,
    });

    // Give fire-and-forget promises a tick to settle.
    await new Promise((r) => setImmediate(r));

    expect(ensureGraph).toHaveBeenCalledOnce();
    expect(ensureGraph).toHaveBeenCalledWith(expect.arrayContaining(["src/a.ts"]));

    expect(recordLineage).toHaveBeenCalledOnce();
    const [[lineageArgs]] = recordLineage.mock.calls as [[{ executionId: string; touchedFiles: string[] }]];
    expect(lineageArgs.touchedFiles).toContain("src/a.ts");
    // executionId is a turn_ prefixed id generated by the pipeline.
    expect(lineageArgs.executionId).toMatch(/^turn_/);
  });

  it("does NOT propagate a throwing ensureGraph — the turn still succeeds", async () => {
    const ws = new MemoryWorkspace({ "src/b.ts": "before" });

    const ensureGraph = vi.fn().mockRejectedValue(new Error("Neo4j down"));
    const recordLineage = vi.fn().mockResolvedValue(undefined);
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    const result = await runTurn({
      prompt: "rename before to after in src/b.ts",
      workspace: ws,
      ai: makeAi("src/b.ts"),
      bare: true,
      graphSync,
    });

    // Give fire-and-forget promises a tick to settle.
    await new Promise((r) => setImmediate(r));

    // Turn must succeed despite the throwing hook.
    expect(result.text).toBe("done");
    expect(ensureGraph).toHaveBeenCalledOnce();
  });

  it("does NOT propagate a throwing recordLineage — the turn still succeeds", async () => {
    const ws = new MemoryWorkspace({ "src/c.ts": "before" });

    const ensureGraph = vi.fn().mockResolvedValue(undefined);
    const recordLineage = vi.fn().mockRejectedValue(new Error("write error"));
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    const result = await runTurn({
      prompt: "rename before to after in src/c.ts",
      workspace: ws,
      ai: makeAi("src/c.ts"),
      bare: true,
      graphSync,
    });

    await new Promise((r) => setImmediate(r));

    expect(result.text).toBe("done");
    expect(recordLineage).toHaveBeenCalledOnce();
  });

  it("does NOT call graphSync when no files are touched", async () => {
    // AI emits text but edits no files.
    const ws = new MemoryWorkspace({ "src/d.ts": "untouched" });

    const ensureGraph = vi.fn();
    const recordLineage = vi.fn();
    const graphSync: GraphSyncProvider = { ensureGraph, recordLineage };

    await runTurn({
      prompt: "describe the file",
      workspace: ws,
      ai: makeAi(), // no file edit
      bare: true,
      graphSync,
    });

    await new Promise((r) => setImmediate(r));

    expect(ensureGraph).not.toHaveBeenCalled();
    expect(recordLineage).not.toHaveBeenCalled();
  });
});
