/**
 * @oxagen/run-ledger — the durable evidence ledger for governed agent runs.
 *
 * Run identity, immutable attempts, the append-only event log, seals,
 * authorization snapshots and finalization grants live here. Nothing in this
 * package executes an agent: the runner that used to sit behind it left with
 * ADR-043, and execution evidence now arrives through evidence ingress
 * (`docs/specs/run-evidence-ingress/spec.md`, `docs/specs/tacho/`).
 *
 * This package is the ONLY writer of the `agent.agent_runs*` tables.
 */
export {
  lockRunForControl,
  cancelRunInTransaction,
  setRunIngressPaused,
} from "./run-control";
// The control plane's close of an attempt whose producer went silent (#3988).
export {
  LEDGER_IDLE_CLOSE_AFTER_MS,
  LEDGER_IDLE_CLOSE_REASON,
  buildListIdleAttemptsSql,
  ledgerIdleCutoff,
  listIdleLedgerAttempts,
  mapIdleLedgerAttemptRow,
  type IdleLedgerAttempt,
  type IdleLedgerAttemptRow,
} from "./idle-attempts";
export { type PlatformSurface } from "./surface";

// Reassembly (spec §14): a recorded model stream folded ONCE, where the frame
// is written, into the message it was — and the pure step summary over the
// result. Nothing downstream reassembles.
export {
  assembleModelStream,
  decodeAssembly,
  encodeAssembly,
  looksLikeModelStream,
  MESSAGE_ASSEMBLY_CONTENT_TYPE,
  MESSAGE_ASSEMBLY_VERSION,
  type AssemblyTiming,
  type AssemblyUsage,
  type BlockJson,
  type ContentBlock,
  type MessageAssembly,
  type TextBlock,
  type ThinkingBlock,
  type ToolResultBlock,
  type ToolUseBlock,
  type ToolVerdict,
  type WireShape,
} from "./content-blocks";
export {
  writeAssembly,
  type AssemblyWrite,
  type AssemblyWriteInput,
} from "./assembly-write";
export {
  clauseOf,
  nameList,
  pastTense,
  precisOf,
  summarizeStep,
  PRECIS_MAX,
  type BlockFigure,
  type StepSummary,
  type StepTiming,
} from "./step-summary";

// Frame bodies and the seal's replay evidence (ADR-058): the body and archive
// store seams the recorder writes through, and the pure grading helpers.
export {
  prepareFrameBody,
  bodyRetainedByPolicy,
  deriveCompletenessGaps,
  deriveSealRollup,
  gradeSealedAttempt,
  ledgerEnforcementTier,
  archiveFrameOf,
  readArchiveFrame,
  NO_BODY,
  type AttemptEventBodyInput,
  type PreparedFrameBody,
  type FrameBodyColumns,
  type FrameFidelity,
  type RetentionPolicyBinding,
  type RunBodyStore,
  type RunArchiveStore,
  type SealedFrameRow,
  type SealRollup,
} from "./frame-body";

// One frame shape for a run from either store, and the pure reads over it:
// the bisect alignment and what each frame is to a transcript (ADR-058).
export {
  ledgerFrame,
  ledgerFrameSummary,
  tachoFrame,
  tachoTimestamp,
  bisectKey,
  bisectFrames,
  stepKind,
  ledgerPhase,
  frameKinds,
  isTranscriptKind,
  TRANSCRIPT_KINDS,
  turnOrdinals,
  spliceSubagentChains,
  frameKey,
  withoutDuplicateModelCalls,
  type RunFrame,
  type FrameChain,
  type FrameSpawn,
  type FrameLlmCall,
  type FramePhase,
  type FrameIdentity,
  type TranscriptKind,
  type TachoFrameRowLike,
  type BisectResult,
} from "./run-frames";
// The frames a run's transcript folds, composed once for every reader of a
// run's steps: the Run page and the summary job (ADR-182).
export {
  TRANSCRIPT_FRAME_CAP,
  listSubagentSessions,
  readRunChains,
  readTranscriptFrames,
  subagentChainRead,
  subagentSessionsQuery,
  withoutLateReports,
  type FrameRead,
  type RunChainReads,
  type SubagentChainPosition,
  type SubagentRowRead,
} from "./run-read";
// The one transcript fold: steps, turns as steps grouped by turn, and every
// fact a reader would otherwise derive from the frames (ADR-182).
export {
  foldTranscript,
  stepFolds,
  frameFolds,
  turnFolds,
  filterFoldsByKind,
  transcriptCounts,
  countsAsError,
  frameCounts,
  toolUseClaimer,
  markWords,
  wordsDigest,
  wordsHalf,
  type RecallBody,
  recallOf,
  RECALL_ITEM_MAX,
  TRANSCRIPT_NODES,
  TRANSCRIPT_OUTCOMES,
  UNKEYED_TOOL_PAIRING,
  type TranscriptCounts,
  type FrameCounts,
  type TranscriptDecision,
  type TranscriptEntryKind,
  type TranscriptFold,
  type TranscriptNode,
  type TranscriptOutcome,
  type TranscriptRecall,
  type TranscriptRecallBody,
  type TranscriptRecallItem,
  type TranscriptWords,
  type TranscriptZoom,
  type ToolUseRef,
} from "./transcript-steps";
// The Run page's figures, counted over the same fold (ADR-182).
export {
  transcriptFigures,
  type BatchFigures,
  type FamilyFigure,
  type TranscriptFigures,
} from "./transcript-figures";
export {
  bareToolName,
  TOOL_FAMILIES,
  toolFamilyOf,
  type ToolFamily,
} from "./tool-family";
export { tachoFrameSummary, tachoPhase, tachoStage } from "./tacho-kinds";

// The ledger itself: admission, immutable attempts, fenced appends, seals,
// terminal outcome, and the read side.
export {
  createPostgresRunStore,
  DEFAULT_READ_EVENTS_LIMIT,
  EVENT_SEQUENCE_CONFLICT_EVENT,
  ATTEMPT_TERMINAL_STATUSES,
  generateRunPublicId,
  generateAttemptPublicId,
  buildRunRowIdentityFromSpec,
  mapRunV2IdentityRow,
  mapRunSummaryRow,
  mapAttemptRow,
  mapAttemptEventReadRow,
  prepareAttemptEvent,
  planAttemptBatch,
  reconcileReplayedEvents,
  foldAttemptStreamDigest,
  foldAttemptEventState,
  attemptRejectionReason,
  assertAttemptWritable,
  runStatusForTerminal,
  buildCreateRunSql,
  buildLockRunForAttemptSql,
  buildInsertAttemptSql,
  buildMarkRunAttemptedSql,
  buildLockAttemptForWriteSql,
  buildLockRunOfAttemptSql,
  buildSelectAttemptEventStateSql,
  buildAllocateRunSeqSql,
  buildInsertAttemptEventsSql,
  buildInsertAttemptSealSql,
  buildFinishRunSql,
  buildAbandonRunSql,
  buildGetRunByPublicIdSql,
  buildListRunAttemptsSql,
  buildListAttemptIdentitySql,
  buildReadAttemptEventsSinceSql,
  buildListCompactedSealsSql,
  buildReadToolCallsForRunsSql,
  buildListCompactedSealsForRunsSql,
  buildCompactSealedAttemptsSql,
  buildSetRunSummarySql,
  framesFromSegment,
  type GeneratedRunSummary,
  type CompactedSealRow,
  type RunCompactedSealRow,
  type RunToolCallRecord,
  type ToolCallFrameRow,
  type RunStore,
  type RunStoreOptions,
  type RunSecurityEventSink,
  type CreateRunInput,
  type CreateAttemptInput,
  type CreatedAttempt,
  type ResolvedEngineIdentity,
  type AttemptProvenance,
  type AttemptEventInput,
  type AppendAttemptBatchInput,
  type AppendAttemptBatchResult,
  type AppendedAttemptEvent,
  type AttemptEventReadRecord,
  type AttemptEventState,
  type AttemptTerminalStatus,
  type SealAttemptInput,
  type AbandonRunInput,
  type AbandonedRun,
  type RunSummary,
  type AttemptRecord,
  type AttemptSealRecord,
  type PreparedAttemptEvent,
  type AttemptBatchPlan,
  type AttemptEventInsertRow,
  type InsertAttemptInput,
  type InsertSealInput,
  type LockedAttemptRow,
  type ExistingAttemptEventRow,
  type AttemptEventStateRow,
  type RunV2IdentityRow,
  type RunSummaryRow,
  type AttemptRow,
  type AttemptEventReadRow,
} from "./run-store";

// The closed event vocabulary plus the digest contract the finalizer must
// reproduce byte for byte.
export {
  EVENT_SCHEMA_VERSION,
  MAX_INLINE_PAYLOAD_BYTES,
  EVIDENCE_STAGES,
  RETENTION_CONTENT_CLASSES,
  EVENT_TYPE_REGISTRY,
  RUN_EVENT_TYPES,
  TERMINAL_EVENT_TYPE,
  FORBIDDEN_INLINE_PAYLOAD_ROOTS,
  EMPTY_EVENT_STREAM_DIGEST,
  encryptedBlobRefSchema,
  observedAtSchema,
  isRunEventType,
  requireEventTypeDefinition,
  stageOfEventType,
  retentionContentClassOf,
  isContentClassRetained,
  isTerminalEventType,
  stepKindOfEventType,
  MODEL_CALL_EVENT_TYPES,
  TOOL_CALL_EVENT_TYPES,
  TOOL_ENGINE_CALL_OUTCOMES,
  contextWindowPayloadSchema,
  type ContextWindowPayload,
  isForbiddenPayloadKey,
  assertNoForbiddenPayloadFields,
  validateInlineEventPayload,
  validateEncryptedEventReference,
  computeEventDigest,
  advanceEventStreamDigest,
  computeEventStreamDigest,
  type EvidenceStage,
  type RetentionContentClass,
  type EventTypeDefinition,
  type RunEventType,
  type RunStepKind,
  type ToolEngineCallOutcome,
  type ValidatedInlinePayload,
  type EventDigestInput,
  type EventStreamEntry,
} from "./event-payload-registry";

// The context windows a run recorded on its model-call frames, and the
// assembler's manifests beside them (ADR-193).
export {
  assemblyOf,
  isContextWindowEvent,
  isLaterLlmCallSighting,
  ledgerContextWindows,
  tachoContextWindow,
  type RecordedAssembly,
  type RecordedWindow,
  type RecordedWindowBlock,
  type TachoModelCallRow,
} from "./context-windows";

// The one-shot, non-expiring finalization grant minted atomically with every
// seal, and the durable obligation that guarantees its evidence is submitted.
export {
  FINALIZATION_GRANT_CAPABILITY,
  generateFinalizationGrantPublicId,
  buildInsertFinalizationGrantSql,
  buildInsertFinalizationObligationSql,
  buildSelectFinalizationHandleSql,
  mapFinalizationHandleRow,
  type SealDigests,
  type FinalizationGrantInput,
  type FinalizationHandleRow,
  type SealedAttemptHandle,
} from "./finalization-grant";

// RunSpecV2 is the trusted admission contract — built ONLY by server code,
// never from a request body. Surfaces parse caller input with
// `parseCallerRunInfluence` and hand the result to `buildTrustedRunSpecV2`
// alongside separately-resolved trusted sections.
export {
  // primitives
  canonicalJson,
  digestOfCanonicalJson,
  assertSha256Digest,
  assertDecimalGeneration,
  RESERVED_PUBLIC_ID_PREFIXES,
  RUN_ENGINES,
  REPOSITORY_PROVIDERS,
  TOOL_RISK_LEVELS,
  MAX_RUN_ATTEMPTS_CEILING,
  MAX_RUN_STEPS_CEILING,
  TRUSTED_RUN_SPEC_SECTIONS,
  // schemas
  runSpecV2Schema,
  generalRunSpecV2Schema,
  repoEditRunSpecV2Schema,
  enginePolicySchema,
  actorBindingSchema,
  authorizationSnapshotRefSchema,
  denyGenerationVectorSchema,
  repositoryBindingSchema,
  workspacePolicySchema,
  contextPolicySchema,
  toolPolicySchema,
  outputPolicySchema,
  callerRunInfluenceSchema,
  callerRunPreferencesSchema,
  sha256DigestSchema,
  decimalGenerationSchema,
  repositoryBindingPublicIdSchema,
  retentionPolicyPublicIdSchema,
  // parsers / builders / comparators
  parseRunSpecV2,
  parseCallerRunInfluence,
  buildTrustedRunSpecV2,
  runSpecV2Digest,
  assertRunSpecV2Digest,
  compareRunRowIdentity,
  assertRunRowMatchesSpec,
  isExternalToolIdentity,
  isAdmissibleToolIdentity,
  EXTERNAL_TOOL_PREFIXES,
  EXTERNAL_TOOL_SEGMENT_MAX,
  EXTERNAL_TOOL_IDENTITY_MAX,
  type RunSpecV2,
  type RunSpecV2Input,
  type GeneralRunSpecV2,
  type RepoEditRunSpecV2,
  type TrustedRunSpecV2Input,
  type TrustedRunSpecSection,
  type CallerRunInfluence,
  type ParsedCallerRunInfluence,
  type RunRowIdentity,
  type RunIdentityMismatch,
  type RepositoryBinding,
  type AuthorizationSnapshotRef,
  type RepositoryBindingPublicId,
  type RetentionPolicyPublicId,
  type ReservedPublicIdKind,
  type Sha256Digest,
  type DecimalGeneration,
} from "./run-spec-v2";

// Typed, dependency-free errors — `instanceof`-matchable from any surface, with
// structural `code` guards for bundling edge cases.
export {
  CanonicalJsonError,
  RunSpecValidationError,
  RunSpecDigestMismatchError,
  RunSpecIdentityMismatchError,
  UntrustedRunSpecFieldError,
  UnknownRunEventTypeError,
  ForbiddenEventPayloadFieldError,
  RunEventPayloadTooLargeError,
  RunEventIntegrityError,
  RunEventSequenceGapError,
  AttemptNotWritableError,
  AttemptAdvancedError,
  RunEventShapeError,
  RunNotWritableError,
  RunStoreStateError,
  isAttemptAdvancedError,
  isRunEventInputError,
  isRunEventShapeError,
  isRunNotWritableError,
  isRunSpecValidationError,
  isRunSpecDigestMismatchError,
  isRunSpecIdentityMismatchError,
  isUntrustedRunSpecFieldError,
  isUnknownRunEventTypeError,
  isForbiddenEventPayloadFieldError,
  isRunEventPayloadTooLargeError,
  isRunEventIntegrityError,
  isRunEventSequenceGapError,
  isAttemptNotWritableError,
  isRunStoreStateError,
  type RunSpecIssue,
  type AttemptRejectionReason,
  type RunNotWritableReason,
} from "./run-errors";

// The run attestation a seal signs and stores (#4000, ADR-195).
export {
  ATTESTER_KEY_ENV,
  deferredAttester,
  sealAttestationPayload,
  signSealAttestation,
  type SealAttestationColumns,
  type SealAttestationFigures,
} from "./attester";
