/**
 * @oxagen/run-ledger — the durable evidence ledger for governed agent runs.
 *
 * Run identity, immutable attempts, the append-only event log, seals,
 * authorization snapshots and finalization grants live here. Nothing in this
 * package executes an agent: the runner that used to sit behind it left with
 * ADR-043, and execution evidence now arrives through evidence ingress
 * (`docs/specs/run-evidence-ingress/spec.md`, `docs/specs/tacho/`).
 *
 * This package is the ONLY writer of the `agent.agent_runs*` tables.
 */
export { type PlatformSurface } from "./surface";

// The ledger itself: admission, immutable attempts, fenced appends, seals,
// terminal outcome, and the read side.
export {
  createPostgresRunStore,
  DEFAULT_READ_EVENTS_LIMIT,
  EVENT_SEQUENCE_CONFLICT_EVENT,
  ATTEMPT_TERMINAL_STATUSES,
  generateRunPublicId,
  generateAttemptPublicId,
  buildRunRowIdentityFromSpec,
  mapRunV2IdentityRow,
  mapRunSummaryRow,
  mapAttemptRow,
  mapAttemptEventReadRow,
  prepareAttemptEvent,
  planAttemptBatch,
  reconcileReplayedEvents,
  foldAttemptStreamDigest,
  foldAttemptEventState,
  attemptRejectionReason,
  assertAttemptWritable,
  runStatusForTerminal,
  buildCreateRunSql,
  buildLockRunForAttemptSql,
  buildInsertAttemptSql,
  buildMarkRunAttemptedSql,
  buildLockAttemptForWriteSql,
  buildSelectAttemptEventStateSql,
  buildAllocateRunSeqSql,
  buildInsertAttemptEventsSql,
  buildInsertAttemptSealSql,
  buildFinishRunSql,
  buildGetRunByPublicIdSql,
  buildListRunAttemptsSql,
  buildListAttemptIdentitySql,
  buildReadAttemptEventsSinceSql,
  type RunStore,
  type RunStoreOptions,
  type RunSecurityEventSink,
  type CreateRunInput,
  type CreateAttemptInput,
  type CreatedAttempt,
  type ResolvedEngineIdentity,
  type AttemptProvenance,
  type AttemptEventInput,
  type AppendAttemptBatchInput,
  type AppendAttemptBatchResult,
  type AppendedAttemptEvent,
  type AttemptEventReadRecord,
  type AttemptEventState,
  type AttemptTerminalStatus,
  type SealAttemptInput,
  type RunSummary,
  type AttemptRecord,
  type AttemptSealRecord,
  type PreparedAttemptEvent,
  type AttemptBatchPlan,
  type AttemptEventInsertRow,
  type InsertAttemptInput,
  type InsertSealInput,
  type LockedAttemptRow,
  type ExistingAttemptEventRow,
  type AttemptEventStateRow,
  type RunV2IdentityRow,
  type RunSummaryRow,
  type AttemptRow,
  type AttemptEventReadRow,
} from "./run-store";

// The closed event vocabulary plus the digest contract the finalizer must
// reproduce byte for byte.
export {
  EVENT_SCHEMA_VERSION,
  MAX_INLINE_PAYLOAD_BYTES,
  EVIDENCE_STAGES,
  RETENTION_CONTENT_CLASSES,
  EVENT_TYPE_REGISTRY,
  RUN_EVENT_TYPES,
  TERMINAL_EVENT_TYPE,
  FORBIDDEN_INLINE_PAYLOAD_ROOTS,
  EMPTY_EVENT_STREAM_DIGEST,
  encryptedBlobRefSchema,
  observedAtSchema,
  isRunEventType,
  requireEventTypeDefinition,
  stageOfEventType,
  retentionContentClassOf,
  isContentClassRetained,
  isTerminalEventType,
  isForbiddenPayloadKey,
  assertNoForbiddenPayloadFields,
  validateInlineEventPayload,
  validateEncryptedEventReference,
  computeEventDigest,
  advanceEventStreamDigest,
  computeEventStreamDigest,
  type EvidenceStage,
  type RetentionContentClass,
  type EventTypeDefinition,
  type RunEventType,
  type ValidatedInlinePayload,
  type EventDigestInput,
  type EventStreamEntry,
} from "./event-payload-registry";

// The one-shot, non-expiring finalization grant minted atomically with every
// seal, and the durable obligation that guarantees its evidence is submitted.
export {
  FINALIZATION_GRANT_CAPABILITY,
  generateFinalizationGrantPublicId,
  buildInsertFinalizationGrantSql,
  buildInsertFinalizationObligationSql,
  buildSelectFinalizationHandleSql,
  mapFinalizationHandleRow,
  type SealDigests,
  type FinalizationGrantInput,
  type FinalizationHandleRow,
  type SealedAttemptHandle,
} from "./finalization-grant";

// RunSpecV2 is the trusted admission contract — built ONLY by server code,
// never from a request body. Surfaces parse caller input with
// `parseCallerRunInfluence` and hand the result to `buildTrustedRunSpecV2`
// alongside separately-resolved trusted sections.
export {
  // primitives
  canonicalJson,
  digestOfCanonicalJson,
  assertSha256Digest,
  assertDecimalGeneration,
  RESERVED_PUBLIC_ID_PREFIXES,
  RUN_ENGINES,
  REPOSITORY_PROVIDERS,
  TOOL_RISK_LEVELS,
  MAX_RUN_ATTEMPTS_CEILING,
  MAX_RUN_STEPS_CEILING,
  TRUSTED_RUN_SPEC_SECTIONS,
  // schemas
  runSpecV2Schema,
  generalRunSpecV2Schema,
  repoEditRunSpecV2Schema,
  enginePolicySchema,
  actorBindingSchema,
  authorizationSnapshotRefSchema,
  denyGenerationVectorSchema,
  repositoryBindingSchema,
  workspacePolicySchema,
  contextPolicySchema,
  toolPolicySchema,
  outputPolicySchema,
  callerRunInfluenceSchema,
  callerRunPreferencesSchema,
  sha256DigestSchema,
  decimalGenerationSchema,
  repositoryBindingPublicIdSchema,
  retentionPolicyPublicIdSchema,
  // parsers / builders / comparators
  parseRunSpecV2,
  parseCallerRunInfluence,
  buildTrustedRunSpecV2,
  runSpecV2Digest,
  assertRunSpecV2Digest,
  compareRunRowIdentity,
  assertRunRowMatchesSpec,
  type RunSpecV2,
  type RunSpecV2Input,
  type GeneralRunSpecV2,
  type RepoEditRunSpecV2,
  type TrustedRunSpecV2Input,
  type TrustedRunSpecSection,
  type CallerRunInfluence,
  type ParsedCallerRunInfluence,
  type RunRowIdentity,
  type RunIdentityMismatch,
  type RepositoryBinding,
  type AuthorizationSnapshotRef,
  type RepositoryBindingPublicId,
  type RetentionPolicyPublicId,
  type ReservedPublicIdKind,
  type Sha256Digest,
  type DecimalGeneration,
} from "./run-spec-v2";

// Typed, dependency-free errors — `instanceof`-matchable from any surface, with
// structural `code` guards for bundling edge cases.
export {
  CanonicalJsonError,
  RunSpecValidationError,
  RunSpecDigestMismatchError,
  RunSpecIdentityMismatchError,
  UntrustedRunSpecFieldError,
  UnknownRunEventTypeError,
  ForbiddenEventPayloadFieldError,
  RunEventPayloadTooLargeError,
  RunEventIntegrityError,
  RunEventSequenceGapError,
  AttemptNotWritableError,
  RunStoreStateError,
  isRunSpecValidationError,
  isRunSpecDigestMismatchError,
  isRunSpecIdentityMismatchError,
  isUntrustedRunSpecFieldError,
  isUnknownRunEventTypeError,
  isForbiddenEventPayloadFieldError,
  isRunEventPayloadTooLargeError,
  isRunEventIntegrityError,
  isRunEventSequenceGapError,
  isAttemptNotWritableError,
  isRunStoreStateError,
  type RunSpecIssue,
  type AttemptRejectionReason,
} from "./run-errors";
