import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  numeric,
  bigint,
  smallint,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { COST_CENTER_LABEL_PATTERN } from "./cost";
import { agentSchema } from "./_schemas";
import {
  appendOnlyAuditMixin,
  auditMixin,
  citext,
  idMixin,
  softDeleteMixin,
  orgScopeMixin,
  versionMixin,
  uuidv7Default,
} from "./_mixins";

// Agent identity + versioning (spec §6, agent-runtime epic).
export const agents = agentSchema.table(
  "agents",
  {
    ...idMixin("agt"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    slug: citext("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    agentType: text("agent_type").notNull(),
    activeVersionId: uuid("active_version_id"),
    // status: text + check per spec §6
    status: text("status").notNull().default("draft"),
    // deploymentStatus is the deploy on/off toggle, distinct from the
    // draft/active/archived authoring lifecycle in `status`.
    deploymentStatus: text("deployment_status").notNull().default("inactive"),
    // Retirement closes configuration validity without changing identity or history.
    validUntil: timestamp("valid_until", { withTimezone: true, mode: "date" }),
    // Nullable avatar. Either an https:// URL or the platform designed-avatar
    // spec string "avatar:v1:<json>" ({emoji,bg,mode}); capped at 512 chars at
    // the contract layer. Same column name as users/organizations for
    // consistency, even though it may carry the spec string, not a plain URL.
    avatarUrl: text("avatar_url"),
    // LLM-inferred, plain-text (<=256 char) description of what this agent does,
    // derived from its config (name/instructions/tools/triggers). Regenerated by
    // agent.definition.summarize when stale.
    summary: text("summary"),
    // SHA-256 of the canonical version config `summary` was derived from (same
    // canonicalization as agent_versions.checksum). When it no longer matches the
    // current config, the summary is stale and gets regenerated.
    summaryChecksum: text("summary_checksum"),
    // Agent RBAC Phase 1 (docs/specs/agent-rbac/spec.md §3.1): the delegated
    // IAM principal (iam.principals, kind='agent') for this agent IDENTITY —
    // one per agent, never per version/run. App-enforced reference (no
    // cross-schema FK per CLAUDE.md storage rules); provisioned by
    // agent.definition.create and soft-deleted together with the agent.
    principalId: uuid("principal_id"),
    // The harness the agent runs under (MC spec §6.2): the identity half
    // records it so the identities table can print it without a host row.
    // CHECK: harness IN ('stella', 'claude-code', 'codex', 'cursor',
    // 'claude-agent-sdk', 'custom') (migration 20260918210100).
    harness: text("harness").notNull().default("custom"),
    // How the identity came to exist (#2967, ADR-065): `ui` (the default),
    // `cli` (for register_agent to write on the CLI surface), or
    // `onboarding` — the agent whose first frame opened the organization's
    // onboarding gate, stamped by ingest_tacho_events at the unlock. CHECK
    // enforced below.
    registeredVia: text("registered_via").notNull().default("ui"),
    // The cost center this agent's spend is charged back to: a label from the
    // organization's `cost.cost_centers`, checked by the write handler (no
    // cross-schema FK). Wins over the workspace's label in the rollup.
    costCenter: text("cost_center"),
  },
  (t) => ({
    // NON-partial on purpose: covers soft-deleted rows too, so a slug a
    // workspace has ever used is PERMANENTLY reserved (never recycled), like an
    // npm package name. Immutability of the live slug is enforced by the
    // agents_slug_immutable trigger; this index reserves it past deletion.
    // (ADR-024, migration 20260709130000_agent_slug_no_recycle.)
    workspaceSlugUniq: uniqueIndex("agents_workspace_slug_uniq").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("agents_org_idx").on(t.orgId, t.workspaceId),
    principalIdx: index("agents_principal_idx").on(t.principalId),
    deploymentStatusIdx: index("agents_deployment_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.deploymentStatus,
    ),
    statusCheck: check(
      "agents_status_check",
      sql`${t.status} IN ('draft', 'active', 'archived')`,
    ),
    deploymentStatusCheck: check(
      "agents_deployment_status_check",
      sql`${t.deploymentStatus} IN ('inactive', 'active')`,
    ),
    slugCheck: check(
      "agents_slug_check",
      sql`${t.slug} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`,
    ),
    harnessCheck: check(
      "agents_harness_check",
      sql`${t.harness} IN ('stella', 'claude-code', 'codex', 'cursor', 'claude-agent-sdk', 'custom')`,
    ),
    registeredViaCheck: check(
      "agents_registered_via_check",
      sql`${t.registeredVia} IN ('ui', 'cli', 'onboarding')`,
    ),
    costCenterCheck: check(
      "agents_cost_center_check",
      sql`${t.costCenter} IS NULL OR ${t.costCenter} ~ '${sql.raw(COST_CENTER_LABEL_PATTERN)}'`,
    ),
  }),
);

// Immutable version snapshots. INSERT-only once published; no updatedAt by design.
export const agentVersions = agentSchema.table(
  "agent_versions",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    agentId: uuid("agent_id")
      .notNull()
      .references(() => agents.id),
    version: integer("version").notNull(),
    isPublished: boolean("is_published").notNull().default(false),
    // checksum: SHA-256 over canonical config — immutability contract.
    checksum: text("checksum"),
    config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
    createdById: uuid("created_by_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    // The definition of record is the file `.oxagen/agents/<slug>.toml` in the
    // workspace's repository (ADR-057 decision 1). A version written by
    // `commit_agent_definition` caches where that file went: its path, the
    // digest of the file at the commit, the commit, the branch it was pushed
    // to and the pull request that carries it, plus the file's text so the
    // definition tab reads the record without a GitHub round trip. Null on
    // every version the legacy `create/update_agent_def` path inserted.
    definitionPath: text("definition_path"),
    definitionDigest: text("definition_digest"),
    definitionSource: text("definition_source"),
    commitSha: text("commit_sha"),
    branch: text("branch"),
    pullRequestUrl: text("pull_request_url"),
    // No updatedAt by design — INSERT-only once published.
  },
  (t) => ({
    agentVersionUniq: uniqueIndex("agent_versions_agent_version_uniq").on(
      t.agentId,
      t.version,
    ),
    agentIdx: index("agent_versions_agent_idx").on(t.agentId),
  }),
);

// Approval requests: cross-domain references (execution_step_id, message_id,
// tool_call_id) are app-enforced; FKs stay within the agent schema per
// CLAUDE.md storage rules.
export const approvalRequests = agentSchema.table(
  "approval_requests",
  {
    ...idMixin("apr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    executionStepId: uuid("execution_step_id"),
    toolCallId: uuid("tool_call_id"),
    // The chat turn that parked the call; null on a row the mandate gate
    // writes, where the call arrived through the kernel with no message.
    messageId: uuid("message_id"),
    // The run the parked call belongs to, as a public id (#3286). Both kinds
    // of run this product tracks have to be representable — the ledger's
    // `agent_runs` (`arun_…`) and the wrapped `tacho.sessions` (`tse_…`) — and
    // no one table holds both, so this is a public id rather than a foreign
    // key. Null when no run was in scope when the call was parked; a null
    // means "not recorded", never "some other run".
    runPublicId: text("run_public_id"),
    resumePayload: jsonb("resume_payload"),
    resumeKey: text("resume_key"),
    resumeStatus: text("resume_status"),
    resumeStartedAt: timestamp("resume_started_at", {
      withTimezone: true,
      mode: "date",
    }),
    resumeFinishedAt: timestamp("resume_finished_at", {
      withTimezone: true,
      mode: "date",
    }),
    resumeRunPublicId: text("resume_run_public_id"),
    resumeError: text("resume_error"),
    capabilityName: text("capability_name").notNull(),
    inputPreview: jsonb("input_preview").notNull(),
    riskLevel: text("risk_level").notNull(),
    // The four-hop chain (MC spec App. A.6, ADR-059 decision 4): the mandate
    // the parked call drew on, the rule ids that required a person, and the
    // sha256 of the call's canonical input so an approved call can be retried
    // once. Null / empty on rows the chat approval gate writes.
    mandateId: uuid("mandate_id"),
    ruleIds: text("rule_ids").array().notNull().default(sql`'{}'::text[]`),
    inputDigest: text("input_digest"),
    // Set when the approved call was retried and proceeded on this approval;
    // an approval is single-use.
    tokenUsedAt: timestamp("token_used_at", {
      withTimezone: true,
      mode: "date",
    }),
    // The auto-approval clause of the workspace's rule set, evaluated when the
    // call was parked (MC spec §6.9 part 2, ADR-070): the rule that was read,
    // and every reason the call did not qualify (empty when it did). Null /
    // empty when no rule covered the call.
    autoRuleId: text("auto_rule_id"),
    resolvedReasons: text("resolved_reasons")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    // resolution null until resolved.
    resolution: text("resolution"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "date" }),
    resolvedByUserId: uuid("resolved_by_user_id"),
    // `policy:<rule id>` when an auto-approval rule resolved the request and
    // no person looked. Exclusive with resolved_by_user_id, so a receipt can
    // never read a policy decision as somebody's.
    resolvedByPolicy: text("resolved_by_policy"),
    note: text("note"),
    expiresAt: timestamp("expires_at", {
      withTimezone: true,
      mode: "date",
    }).notNull(),
  },
  (t) => ({
    resumeQueueIdx: index("approval_requests_resume_queue_idx")
      .on(t.resumeStatus, t.createdAt)
      .where(sql`resume_payload IS NOT NULL`),
    resumeKeyIdx: index("approval_requests_resume_key_idx").on(
      t.workspaceId,
      t.resumeKey,
    ),
    resumeStatusCheck: check(
      "approval_requests_resume_status_check",
      sql`${t.resumeStatus} IS NULL OR ${t.resumeStatus} IN ('waiting', 'queued', 'running', 'succeeded', 'dispatched', 'failed', 'indeterminate', 'denied', 'expired')`,
    ),
    orgResolutionIdx: index("approval_requests_org_resolution_idx").on(
      t.orgId,
      t.workspaceId,
      t.resolution,
    ),
    orgIdx: index("approval_requests_org_idx").on(t.orgId, t.workspaceId),
    messageIdx: index("approval_requests_message_idx").on(t.messageId),
    // The Run page's Policy tab: one run's parked calls inside one workspace.
    runIdx: index("approval_requests_run_idx")
      .on(t.workspaceId, t.runPublicId)
      .where(sql`run_public_id IS NOT NULL`),
    // The retry lookup: an approved, unused row for this call's digest.
    mandateDigestIdx: index("approval_requests_mandate_digest_idx")
      .on(t.workspaceId, t.mandateId, t.inputDigest)
      .where(sql`mandate_id IS NOT NULL`),
    resolutionCheck: check(
      "approval_requests_resolution_check",
      sql`${t.resolution} IN ('approved', 'denied', 'expired') OR ${t.resolution} IS NULL`,
    ),
    runPublicIdCheck: check(
      "approval_requests_run_public_id_check",
      sql`${t.runPublicId} IS NULL OR ${t.runPublicId} ~ '^(arun|tse)_[0-9a-z]+$'`,
    ),
    riskLevelCheck: check(
      "approval_requests_risk_level_check",
      sql`${t.riskLevel} IN ('low', 'medium', 'high', 'critical')`,
    ),
    // The rule-hit counters list_approval_rules reports over a 30-day window.
    autoRuleIdx: index("approval_requests_auto_rule_idx")
      .on(t.workspaceId, t.autoRuleId, t.createdAt)
      .where(sql`auto_rule_id IS NOT NULL`),
    // The standing-approval lookup an auto-approval rule's window reads
    // (ADR-070, lastHumanApprovalOf): the newest approval of this exact call
    // that a PERSON resolved. mandate_digest_idx above cannot serve it — that
    // one is partial on mandate_id IS NOT NULL and keys on mandate_id, and
    // this lookup has no mandate and keys on capability_name. Partial on the
    // same predicate as the query, so it stays small: only resolved rows a
    // person approved.
    humanApprovalDigestIdx: index("approval_requests_human_digest_idx")
      .on(
        t.workspaceId,
        t.capabilityName,
        t.inputDigest,
        sql`${t.resolvedAt} DESC`,
      )
      .where(
        sql`resolution = 'approved' AND resolved_by_user_id IS NOT NULL AND resolved_at IS NOT NULL`,
      ),
    resolvedByPolicyFormCheck: check(
      "approval_requests_resolved_by_policy_form_check",
      sql`${t.resolvedByPolicy} IS NULL OR ${t.resolvedByPolicy} ~ '^policy:[a-z0-9][a-z0-9._-]*$'`,
    ),
    // One approver, never two: an auto-approval is not somebody's decision.
    oneApproverCheck: check(
      "approval_requests_one_approver_check",
      sql`NOT (${t.resolvedByPolicy} IS NOT NULL AND ${t.resolvedByUserId} IS NOT NULL)`,
    ),
  }),
);

// Agent execution tracking: lineage, steps, tool calls (migration 0019)
export const agentExecutions = agentSchema.table(
  "agent_executions",
  {
    ...idMixin("aex"),
    ...auditMixin(),
    ...orgScopeMixin(),
    // Nullable: dynamic supervisor runs don't have a pre-registered agent definition.
    agentId: uuid("agent_id").references(() => agents.id),
    agentVersionId: uuid("agent_version_id").references(() => agentVersions.id),
    originType: text("origin_type").notNull(),
    originId: uuid("origin_id").notNull(),
    status: text("status").notNull().default("planning"),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    estimatedCostUsd: numeric("estimated_cost_usd", {
      precision: 10,
      scale: 6,
    }),
    // AgentInstance shape (agent-schema.ts §4): self-reference for subagent/A2A
    // lineage (app-enforced, no FK).
    parentExecutionId: uuid("parent_execution_id"),
    // Live: schema.reconcile.dispatch writes reconcile progress counters here
    // and schema.reconcile.status reads them back. (The sibling `debug` column
    // was dropped in 20260802140000 — genuinely unreferenced.)
    state: jsonb("state").notNull().default(sql`'{}'::jsonb`),
  },
  (t) => ({
    orgStatusIdx: index("agent_executions_org_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    originIdx: index("agent_executions_origin_idx").on(
      t.originType,
      t.originId,
    ),
    agentIdx: index("agent_executions_agent_idx").on(t.agentId),
    // FK → agent.agent_versions. Index the FK so agent_versions mutations don't
    // seq-scan the high-write executions table (only agent_id was indexed).
    agentVersionIdx: index("agent_executions_agent_version_idx").on(
      t.agentVersionId,
    ),
    parentExecutionIdx: index("agent_executions_parent_execution_idx").on(
      t.parentExecutionId,
    ),
    createdAtIdx: index("agent_executions_created_at_idx").on(t.createdAt),
    // Activity feed / execution list (agent.execution.list.ts,
    // command.menu.search.ts — 2026-07-11 audit §4.1 item 1). Distinct from
    // orgStatusIdx above, which leads with (org_id, workspace_id, status) —
    // this composite serves the feed's created_at DESC sort directly.
    orgWsCreatedIdx: index("agent_executions_org_ws_created_idx").on(
      t.orgId,
      t.workspaceId,
      t.createdAt,
    ),
    statusCheck: check(
      "agent_executions_status_check",
      sql`${t.status} IN ('planning', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    // Mirror of the CHECK constraint that already lives in the baseline/0007
    // migrations. Declared here so the Drizzle schema can never drift from the
    // DB again — the omission let workflow.run insert "workflow.run" (dot) and
    // get rejected at runtime while typecheck/Drizzle-mock tests passed.
    // Keep in sync with AGENT_EXECUTION_ORIGIN_TYPES in
    // packages/oxagen/src/contracts/agent.execution.record.ts.
    originTypeCheck: check(
      "agent_executions_origin_type_check",
      sql`${t.originType} IN ('chat', 'event_trigger', 'scheduled_job', 'mcp_request', 'workflow_run', 'fanout', 'a2a')`,
    ),
  }),
);

export const agentExecutionSteps = agentSchema.table(
  "agent_execution_steps",
  {
    ...idMixin("aes"),
    ...auditMixin(),
    executionId: uuid("execution_id")
      .notNull()
      .references(() => agentExecutions.id),
    ...orgScopeMixin(),
    stepNumber: integer("step_number").notNull(),
    stepType: text("step_type").notNull(),
    status: text("status").notNull(),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Durable claim/lease (spec §1): a lost
    // worker's step becomes resweepable instead of stranding the execution.
    claimedBy: text("claimed_by"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    attempts: integer("attempts").notNull().default(0),
  },
  (t) => ({
    executionIdx: index("agent_execution_steps_execution_idx").on(
      t.executionId,
    ),
    orgIdx: index("agent_execution_steps_org_idx").on(t.orgId, t.workspaceId),
    claimIdx: index("agent_execution_steps_claim_idx")
      .on(t.orgId, t.status)
      .where(sql`${t.status} IN ('pending', 'running')`),
    statusCheck: check(
      "agent_execution_steps_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
  }),
);

export const agentToolCalls = agentSchema.table(
  "agent_tool_calls",
  {
    ...idMixin("atc"),
    ...auditMixin(),
    executionStepId: uuid("execution_step_id")
      .notNull()
      .references(() => agentExecutionSteps.id),
    ...orgScopeMixin(),
    toolName: text("tool_name").notNull(),
    toolType: text("tool_type").notNull(),
    requestPayload: jsonb("request_payload").notNull(),
    responsePayload: jsonb("response_payload"),
    status: text("status").notNull(),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
  },
  (t) => ({
    stepIdx: index("agent_tool_calls_step_idx").on(t.executionStepId),
    toolIdx: index("agent_tool_calls_tool_idx").on(t.toolName),
    orgIdx: index("agent_tool_calls_org_idx").on(t.orgId, t.workspaceId),
    statusCheck: check(
      "agent_tool_calls_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed')`,
    ),
  }),
);

// ── Durable agent runs — the evidence ledger's run identity ─────────────────
//
// One row per governed run, across every surface, written exclusively by
// @oxagen/run-ledger. `surface` mirrors that package's PlatformSurface union
// so the row and the seam can never drift into two vocabularies for the same
// thing; ADR-043 added `external` to both for a `client_attested` submission
// that no Oxagen surface admitted interactively.
//
// ADR-043 (runtime excision) removed the durable worker, and with it the
// claim/lease trio (`claimed_by` / `lease_expires_at` / `attempts`) and the
// engine-state checkpoint pair (`checkpoint` / `checkpoint_seq`). Oxagen
// claims nothing, leases nothing and restores no engine state: an external
// engine executes and submits, and this row records WHO was authorized to do
// so. Attempt bookkeeping that survives is evidence, not scheduling —
// `attempt_count` against the pinned `max_attempts` ceiling, and
// `active_attempt_id`.
//
// `spec` is the serialized RunSpecV2 (trusted identity, bindings, engine
// policy) — data only, never live engine ports or callbacks. The full
// per-attempt history is agent_run_events, which is append-only and
// digest-chained; there is no mutable pointer summarizing it.
export const agentRuns = agentSchema.table(
  "agent_runs",
  {
    ...idMixin("arun"),
    ...orgScopeMixin(),
    ...auditMixin(),
    surface: text("surface").notNull(),
    status: text("status").notNull().default("pending"),
    spec: jsonb("spec").notNull(),
    result: jsonb("result"),
    error: text("error"),
    // Cancel fences ledger appends and new attempts under the run lock.
    // It does not stop the external process (ADR-056).
    cancelRequested: boolean("cancel_requested").notNull().default(false),
    ingressPaused: boolean("ingress_paused").notNull().default(false),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    // ── Generated summary (Mission Control mockup 2821-2835; G14; ADR-058) ──
    // Written by `summarize_run`: a light-tier model reads the frames and
    // writes what changed. Labelled generated wherever it renders and never
    // standing in for the record; the three summary columns are set together
    // so a summary always names the model and the instant that produced it.
    name: text("name"),
    summary: text("summary"),
    summaryGeneratedAt: timestamp("summary_generated_at", {
      withTimezone: true,
      mode: "date",
    }),
    summaryModel: text("summary_model"),

    // ── RunSpecV2 typed identity (docs/specs/run-evidence-ingress) ───────────
    //
    // The V1/V2 discriminant. Existing rows backfill to 1 via the column
    // default; a governed V2 admission writes 2 and must then supply the
    // COMPLETE typed set below (agent_runs_v2_identity_check). Every column
    // here is nullable at the column level on purpose: `agent_runs` already
    // holds V1 history that has no trusted principal, repository, or retention
    // binding, and fabricating one for a historical row is exactly what the
    // expand-only rule forbids. Completeness is a conditional CHECK, not a
    // column-level NOT NULL.
    //
    // These are duplicated OUT of `spec` deliberately: security queries and the
    // worker's row/spec identity comparison must not depend on untyped JSON
    // extraction (spec.md §"Trusted run and attempt identity").
    specVersion: integer("spec_version").notNull().default(1),
    runKind: text("run_kind"),
    // RFC 8785 canonical digest of the serialized RunSpecV2.
    specDigest: text("spec_digest"),
    // Actor binding: the authenticated human who delegated the run and the
    // deployed-agent principal acting for them. NOT agents.parentUserId.
    initiatingPrincipalId: uuid("initiating_principal_id"),
    agentPrincipalId: uuid("agent_principal_id"),
    agentId: uuid("agent_id"),
    agentVersionId: uuid("agent_version_id"),
    agentVersionChecksum: text("agent_version_checksum"),
    // Digest-addressed pinned grant ceiling (iam.authorization_snapshots).
    authorizationSnapshotId: uuid("authorization_snapshot_id"),
    // Child runs narrow their parent's ceiling; a root run is null.
    parentRunId: uuid("parent_run_id"),
    // Immutable repository binding plus the copies admission resolved from it.
    // The copies are not redundancy for its own sake: the binding row is
    // versioned, and the run must prove which version it saw.
    repositoryBindingId: uuid("repository_binding_id"),
    repositoryProvider: text("repository_provider"),
    providerRepositoryId: text("provider_repository_id"),
    repositoryConnectionId: uuid("repository_connection_id"),
    configuredDefaultRef: text("configured_default_ref"),
    baseCommitSha: text("base_commit_sha"),
    baseTreeSha: text("base_tree_sha"),
    // Immutable retention-policy version pinned at admission — both the public
    // identity and its canonical digest, so a swapped row is detectable.
    retentionPolicyId: uuid("retention_policy_id"),
    retentionPolicyDigest: text("retention_policy_digest"),
    // Trusted engine policy: the pinned ceiling `attempt_count` is bounded
    // against. The V1 `attempts` counter it used to coexist with went with the
    // worker in ADR-043.
    maxAttempts: integer("max_attempts"),

    // ── Operational V2 pointers (mutable; see the immutability trigger) ──────
    // The attempt currently open (created, not yet sealed); null otherwise.
    // Not a lease — the seal is the only fence (ADR-043).
    activeAttemptId: uuid("active_attempt_id"),
    // Number of attempts ever created for this run, bounded by max_attempts.
    attemptCount: integer("attempt_count").notNull().default(0),
    // Next run-global event sequence to allocate. PostgreSQL-assigned inside
    // the append transaction (not a SEQUENCE object — the allocation must roll
    // back with the append). Monotonic ACROSS attempts, unlike attempt_seq.
    nextRunSeq: bigint("next_run_seq", { mode: "number" }).notNull().default(1),
  },
  (t) => ({
    orgIdx: index("agent_runs_org_idx").on(t.orgId, t.workspaceId),
    // Both partial indexes were cut for the worker's cross-org claim UPDATE
    // and lease sweeper (hence no org_id prefix). Those queries left with the
    // runtime; the indexes stay because "which runs are still open, oldest
    // first" is now an OPERATOR question — the stuck-run and unsealed-attempt
    // views the governance surfaces read.
    claimIdx: index("agent_runs_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`${t.status} IN ('pending', 'running')`),
    v2ClaimIdx: index("agent_runs_v2_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`spec_version = 2 AND status IN ('pending', 'running')`),
    // Security lookups by trusted identity (who ran what, under which snapshot).
    v2ActorIdx: index("agent_runs_v2_actor_idx")
      .on(t.orgId, t.workspaceId, t.initiatingPrincipalId, t.agentPrincipalId)
      .where(sql`spec_version = 2`),
    parentRunIdx: index("agent_runs_parent_run_idx")
      .on(t.parentRunId)
      .where(sql`parent_run_id IS NOT NULL`),
    // `external` is the post-ADR-043 addition: a `client_attested` submission
    // from an engine Oxagen did not host has no interactive surface of origin.
    // The other four are kept because historical rows carry them.
    surfaceCheck: check(
      "agent_runs_surface_check",
      sql`${t.surface} IN ('chat', 'api-chat', 'a2a', 'repo-edit', 'external')`,
    ),
    statusCheck: check(
      "agent_runs_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    specVersionCheck: check(
      "agent_runs_spec_version_check",
      sql`${t.specVersion} IN (1, 2)`,
    ),
    // The V1/V2 discriminant. A preserved V1 row carries NONE of the typed V2
    // identity; a V2 row carries all of it. The seven repository columns follow
    // run_kind: a `general` run binds no repository and carries NULL in each,
    // a `repo_edit` run carries every one (migration 20260914190000; the
    // earlier form required them on every V2 row, so a general run could not
    // be admitted). There is no partially-bound run.
    v2IdentityCheck: check(
      "agent_runs_v2_identity_check",
      sql`(
        ${t.specVersion} = 1
        AND ${t.runKind} IS NULL
        AND ${t.specDigest} IS NULL
        AND ${t.initiatingPrincipalId} IS NULL
        AND ${t.agentPrincipalId} IS NULL
        AND ${t.agentId} IS NULL
        AND ${t.agentVersionId} IS NULL
        AND ${t.agentVersionChecksum} IS NULL
        AND ${t.authorizationSnapshotId} IS NULL
        AND ${t.repositoryBindingId} IS NULL
        AND ${t.repositoryProvider} IS NULL
        AND ${t.providerRepositoryId} IS NULL
        AND ${t.repositoryConnectionId} IS NULL
        AND ${t.configuredDefaultRef} IS NULL
        AND ${t.baseCommitSha} IS NULL
        AND ${t.baseTreeSha} IS NULL
        AND ${t.retentionPolicyId} IS NULL
        AND ${t.retentionPolicyDigest} IS NULL
        AND ${t.maxAttempts} IS NULL
      ) OR (
        ${t.specVersion} = 2
        AND ${t.runKind} IS NOT NULL
        AND ${t.specDigest} IS NOT NULL
        AND ${t.initiatingPrincipalId} IS NOT NULL
        AND ${t.agentPrincipalId} IS NOT NULL
        AND ${t.agentId} IS NOT NULL
        AND ${t.agentVersionId} IS NOT NULL
        AND ${t.agentVersionChecksum} IS NOT NULL
        AND ${t.authorizationSnapshotId} IS NOT NULL
        AND ${t.retentionPolicyId} IS NOT NULL
        AND ${t.retentionPolicyDigest} IS NOT NULL
        AND ${t.maxAttempts} IS NOT NULL
        AND (
          (
            ${t.runKind} = 'general'
            AND ${t.repositoryBindingId} IS NULL
            AND ${t.repositoryProvider} IS NULL
            AND ${t.providerRepositoryId} IS NULL
            AND ${t.repositoryConnectionId} IS NULL
            AND ${t.configuredDefaultRef} IS NULL
            AND ${t.baseCommitSha} IS NULL
            AND ${t.baseTreeSha} IS NULL
          ) OR (
            ${t.runKind} = 'repo_edit'
            AND ${t.repositoryBindingId} IS NOT NULL
            AND ${t.repositoryProvider} IS NOT NULL
            AND ${t.providerRepositoryId} IS NOT NULL
            AND ${t.repositoryConnectionId} IS NOT NULL
            AND ${t.configuredDefaultRef} IS NOT NULL
            AND ${t.baseCommitSha} IS NOT NULL
            AND ${t.baseTreeSha} IS NOT NULL
          )
        )
      )`,
    ),
    runKindCheck: check(
      "agent_runs_run_kind_check",
      sql`${t.runKind} IS NULL OR ${t.runKind} IN ('general', 'repo_edit')`,
    ),
    specDigestCheck: check(
      "agent_runs_spec_digest_check",
      sql`${t.specDigest} IS NULL OR ${t.specDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    retentionDigestCheck: check(
      "agent_runs_retention_digest_check",
      sql`${t.retentionPolicyDigest} IS NULL OR ${t.retentionPolicyDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    maxAttemptsCheck: check(
      "agent_runs_max_attempts_check",
      sql`${t.maxAttempts} IS NULL OR ${t.maxAttempts} > 0`,
    ),
    attemptCountCheck: check(
      "agent_runs_attempt_count_check",
      sql`${t.attemptCount} >= 0 AND (${t.maxAttempts} IS NULL OR ${t.attemptCount} <= ${t.maxAttempts})`,
    ),
    nextRunSeqCheck: check(
      "agent_runs_next_run_seq_check",
      sql`${t.nextRunSeq} >= 1`,
    ),
    summaryCheck: check(
      "agent_runs_summary_check",
      sql`(${t.summary} IS NULL) = (${t.summaryGeneratedAt} IS NULL) AND (${t.summary} IS NULL) = (${t.summaryModel} IS NULL)`,
    ),
    // A run may not be its own parent — the cheapest half of cycle prevention
    // (deeper cycles are prevented by the snapshot-narrowing rule in IAM).
    parentRunCheck: check(
      "agent_runs_parent_run_check",
      sql`${t.parentRunId} IS NULL OR ${t.parentRunId} <> ${t.id}`,
    ),
  }),
);

// Append-only event log for agent_runs — the canonical source for resumable
// SSE subscriptions and ClickHouse ingestion (spec.md §4.2:
// "the event log is canonical"). Immutable child: bare uuid pk
// (no idMixin/public_id — nothing
// external addresses one event row directly) and no updatedAt. `seq` is
// app-assigned and monotonic per run starting at 1 — deliberately NOT a
// serial/identity column, so the worker can assert the exact next value in
// the same transaction as the checkpoint write (`UNIQUE(run_id, seq)` below
// turns a racing double-append into a constraint violation, not silent
// duplication).
// V2 (docs/specs/run-evidence-ingress) adds a second record shape to this same
// table rather than a second log: `event_record_version` is the discriminant, 1
// for every preserved legacy row and 2 for a fenced-attempt event. The legacy
// `seq/type/payload` columns became nullable so a V2 row can leave them empty,
// and the old full `UNIQUE(run_id, seq)` was replaced by three PARTIAL unique
// indexes — V1 `(run_id, seq)`, V2 `(run_id, run_seq)`, V2 `(attempt_id,
// attempt_seq)` — so a V2 row can never be read as legacy and vice versa. A
// leftover full unique on `(run_id, seq)` would defeat the discriminant, which
// is why the migration drops it explicitly.
export const agentRunEvents = agentSchema.table(
  "agent_run_events",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    // No cross-schema FK to agent_runs — app-enforced per CLAUDE.md storage
    // rules (same convention as the other cross-table ids in this schema).
    runId: uuid("run_id").notNull(),
    // 1 = legacy run-global record, 2 = fenced attempt record. Existing rows
    // backfill to 1 through the column default.
    eventRecordVersion: smallint("event_record_version").notNull().default(1),
    // ── V1 legacy columns (required for V1, NULL for V2) ─────────────────────
    seq: integer("seq"),
    type: text("type"),
    payload: jsonb("payload"),
    // `created_at` is the RECORDED time for both record versions — the instant
    // Postgres accepted the append. V2 additionally carries the producer's
    // `observed_at`; the two differ by transport and buffering latency and the
    // event digest commits to the observed one.
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),

    // ── V2 fenced-attempt columns (required for V2, NULL for V1) ─────────────
    // The immutable attempt this event belongs to. Without it a reclaimed run's
    // events interleave across executions with no stable identity.
    attemptId: uuid("attempt_id"),
    // Monotonic across attempts, allocated from agent_runs.next_run_seq inside
    // the append transaction. Drives resumable SSE subscriptions.
    runSeq: bigint("run_seq", { mode: "number" }),
    // Producer-assigned, contiguous, and reset to 1 for each new attempt.
    // Drives unambiguous replay.
    attemptSeq: integer("attempt_seq"),
    eventSchemaVersion: text("event_schema_version"),
    eventType: text("event_type"),
    // One of the nine evidence stages (EVIDENCE_STAGES in
    // schema/run-evidence-foundation.ts).
    stage: text("stage"),
    // Digest of the canonical payload bytes, whether inline or encrypted.
    payloadDigest: text("payload_digest"),
    // Digest over (attempt_seq, schema, type, stage, payload_digest,
    // observed_at). Identical sequence + identical digest is idempotent;
    // identical sequence + different digest is a security event.
    eventDigest: text("event_digest"),
    // EXACTLY ONE of these two carries the body. Inline is allow-listed receipt
    // metadata only; anything large or sensitive is an encrypted blob reference
    // (an `evb_` public id — app-enforced text; the blob index is planned in
    // docs/specs/run-evidence-ingress/03-evidence-ledger-plan.md).
    payloadInline: jsonb("payload_inline"),
    encryptedPayloadRef: text("encrypted_payload_ref"),
    observedAt: timestamp("observed_at", { withTimezone: true, mode: "date" }),

    // ── Frame body (Mission Control spec §8.2 `content`, §13.1) ──────────────
    // The payload above is the frame's receipt metadata; the body is the
    // content the frame is about (the prompt, the model response, the tool
    // input and output). Bodies are content-addressed, redacted before write
    // and encrypted in the organisation's object store; the row holds the
    // reference, the sha256 of the redacted bytes, their length, the
    // redactions applied, and `fidelity`: `full` when the bytes were retained,
    // `digest_only` when the run's pinned retention policy kept the digest
    // alone (a completeness gap the seal grades `inspect`) or the frame
    // carried no content. ADR-058.
    bodyRef: text("body_ref"),
    bodyDigest: text("body_digest"),
    bodyBytes: integer("body_bytes"),
    redactions: jsonb("redactions"),
    fidelity: text("fidelity").notNull().default("digest_only"),
  },
  (t) => ({
    // Partial: legacy rows only. Replaces the former full
    // UNIQUE(run_id, seq) constraint, which would otherwise collide every V2
    // row on (run_id, NULL) semantics and blur the discriminant.
    v1RunSeqUniq: uniqueIndex("agent_run_events_v1_run_seq_uq")
      .on(t.runId, t.seq)
      .where(sql`event_record_version = 1`),
    v2RunSeqUniq: uniqueIndex("agent_run_events_v2_run_seq_uq")
      .on(t.runId, t.runSeq)
      .where(sql`event_record_version = 2`),
    v2AttemptSeqUniq: uniqueIndex("agent_run_events_v2_attempt_seq_uq")
      .on(t.attemptId, t.attemptSeq)
      .where(sql`event_record_version = 2`),
    orgIdx: index("agent_run_events_org_idx").on(t.orgId, t.workspaceId),
    recordVersionCheck: check(
      "agent_run_events_record_version_check",
      sql`${t.eventRecordVersion} IN (1, 2)`,
    ),
    // The discriminant, spelled out. A V1 row is exactly the legacy shape with
    // every V2 field null; a V2 row is exactly the attempt shape with every
    // legacy field null. Nothing in between is representable.
    recordShapeCheck: check(
      "agent_run_events_record_shape_check",
      sql`(
        ${t.eventRecordVersion} = 1
        AND ${t.seq} IS NOT NULL
        AND ${t.type} IS NOT NULL
        AND ${t.payload} IS NOT NULL
        AND ${t.attemptId} IS NULL
        AND ${t.runSeq} IS NULL
        AND ${t.attemptSeq} IS NULL
        AND ${t.eventSchemaVersion} IS NULL
        AND ${t.eventType} IS NULL
        AND ${t.stage} IS NULL
        AND ${t.payloadDigest} IS NULL
        AND ${t.eventDigest} IS NULL
        AND ${t.payloadInline} IS NULL
        AND ${t.encryptedPayloadRef} IS NULL
        AND ${t.observedAt} IS NULL
      ) OR (
        ${t.eventRecordVersion} = 2
        AND ${t.seq} IS NULL
        AND ${t.type} IS NULL
        AND ${t.payload} IS NULL
        AND ${t.attemptId} IS NOT NULL
        AND ${t.runSeq} IS NOT NULL
        AND ${t.attemptSeq} IS NOT NULL
        AND ${t.eventSchemaVersion} IS NOT NULL
        AND ${t.eventType} IS NOT NULL
        AND ${t.stage} IS NOT NULL
        AND ${t.payloadDigest} IS NOT NULL
        AND ${t.eventDigest} IS NOT NULL
        AND ${t.observedAt} IS NOT NULL
        AND (${t.payloadInline} IS NULL) <> (${t.encryptedPayloadRef} IS NULL)
      )`,
    ),
    stageCheck: check(
      "agent_run_events_stage_check",
      sql`${t.stage} IS NULL OR ${t.stage} IN ('admission', 'checkout', 'context', 'model', 'tool', 'change', 'verification', 'provider_publish', 'terminal')`,
    ),
    seqBoundsCheck: check(
      "agent_run_events_seq_bounds_check",
      sql`(${t.runSeq} IS NULL OR ${t.runSeq} >= 1) AND (${t.attemptSeq} IS NULL OR ${t.attemptSeq} >= 1) AND (${t.seq} IS NULL OR ${t.seq} >= 1)`,
    ),
    digestCheck: check(
      "agent_run_events_digest_check",
      sql`(${t.payloadDigest} IS NULL OR ${t.payloadDigest} ~ '^sha256:[0-9a-f]{64}$') AND (${t.eventDigest} IS NULL OR ${t.eventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
    fidelityCheck: check(
      "agent_run_events_fidelity_check",
      sql`${t.fidelity} IN ('full', 'digest_only')`,
    ),
    // A retained body carries its reference, digest and length together and
    // is the only `full` frame; a digest-only frame has no reference; a frame
    // with no content has none of the three and no redactions.
    bodyShapeCheck: check(
      "agent_run_events_body_shape_check",
      sql`(
        (${t.fidelity} = 'full') = (${t.bodyRef} IS NOT NULL)
      ) AND (
        ${t.bodyRef} IS NULL OR (${t.bodyDigest} IS NOT NULL AND ${t.bodyBytes} IS NOT NULL)
      ) AND (
        ${t.bodyDigest} IS NOT NULL OR (${t.bodyBytes} IS NULL AND ${t.redactions} IS NULL)
      ) AND (
        ${t.bodyDigest} IS NULL OR ${t.bodyDigest} ~ '^sha256:[0-9a-f]{64}$'
      ) AND (
        ${t.bodyBytes} IS NULL OR ${t.bodyBytes} >= 0
      )`,
    ),
  }),
);

// ── Immutable attempt identity (docs/specs/run-evidence-ingress) ─────────────
//
// One row per successful V2 worker claim, created BEFORE any model or tool
// work. `arat_` is the public identity every API boundary and evidence receipt
// uses. The resolved engine name/version/build digest is pinned here rather
// than read back from a live worker, so evidence names the exact binary that
// executed. A successor that resumes an earlier attempt records the restore
// tuple and keeps its OWN attempt identity — attempt IDs are never reused
// (spec.md §"Attempt identity").
//
// Immutable: append-only audit columns and the migration revokes UPDATE/DELETE.
export const agentRunAttempts = agentSchema.table(
  "agent_run_attempts",
  {
    ...idMixin("arat"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    // 1-based, dense, and unique per run — the retry counter the pinned
    // max_attempts ceiling bounds.
    attemptNumber: integer("attempt_number").notNull(),
    // Identity of the external engine process that produced this attempt.
    workerId: text("worker_id").notNull(),
    claimedAt: timestamp("claimed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    engineName: text("engine_name").notNull(),
    engineVersion: text("engine_version").notNull(),
    // Build or container-image digest of the engine that actually ran.
    engineBuildDigest: text("engine_build_digest").notNull(),
    // ── Restore tuple: both present, or both absent ─────────────────────────
    // The checkpoint half (`restored_checkpoint_id` / `restored_checkpoint_digest`)
    // went with agent.agent_run_checkpoints in ADR-043: Oxagen no longer runs
    // agents, so there is no engine state to restore — only the attempt
    // provenance chain remains as evidence.
    resumedFromAttemptId: uuid("resumed_from_attempt_id"),
    resumedFromAttemptPublicId: citext("resumed_from_attempt_public_id"),
    // A fork replay (Mission Control spec §8.4 `fork`, `fork_run`): the
    // run-global sequence the successor branches from. Frames up to it replay
    // from the recording; the next model call runs live. Always paired with
    // the restore tuple, since a fork resumes the attempt that recorded the
    // frame. ADR-058.
    forkedFromRunSeq: bigint("forked_from_run_seq", { mode: "number" }),
  },
  (t) => ({
    runAttemptUniq: uniqueIndex("agent_run_attempts_run_attempt_uq").on(
      t.runId,
      t.attemptNumber,
    ),
    orgIdx: index("agent_run_attempts_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempts_run_idx").on(t.runId),
    attemptNumberCheck: check(
      "agent_run_attempts_attempt_number_check",
      sql`${t.attemptNumber} >= 1`,
    ),
    // A partial restore reference cannot prove provenance, so the tuple is
    // all-or-nothing.
    restoreTupleCheck: check(
      "agent_run_attempts_restore_tuple_check",
      sql`(
        ${t.resumedFromAttemptId} IS NULL
        AND ${t.resumedFromAttemptPublicId} IS NULL
      ) OR (
        ${t.resumedFromAttemptId} IS NOT NULL
        AND ${t.resumedFromAttemptPublicId} IS NOT NULL
      )`,
    ),
    // A successor may never restore from itself.
    restoreSelfCheck: check(
      "agent_run_attempts_restore_self_check",
      sql`${t.resumedFromAttemptId} IS NULL OR ${t.resumedFromAttemptId} <> ${t.id}`,
    ),
    digestCheck: check(
      "agent_run_attempts_digest_check",
      sql`${t.engineBuildDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    forkCheck: check(
      "agent_run_attempts_fork_check",
      sql`${t.forkedFromRunSeq} IS NULL OR (${t.forkedFromRunSeq} >= 1 AND ${t.resumedFromAttemptId} IS NOT NULL)`,
    ),
  }),
);

// ── Immutable attempt seals ──────────────────────────────────────────────────
//
// One row per terminated attempt, for EVERY terminal outcome including normal
// completion — that is what closes the crash window between "finished" and
// "finalized". A truly zero-event abandoned attempt seals with event_count = 0,
// a NULL final-event digest, and the canonical empty stream digest; it never
// invents a terminal event to satisfy the shape.
export const agentRunAttemptSeals = agentSchema.table(
  "agent_run_attempt_seals",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    terminalStatus: text("terminal_status").notNull(),
    reasonCode: text("reason_code"),
    eventCount: integer("event_count").notNull(),
    finalRunSeq: bigint("final_run_seq", { mode: "number" }),
    finalAttemptSeq: integer("final_attempt_seq"),
    finalEventDigest: text("final_event_digest"),
    // Always present: the canonical empty-stream digest when event_count = 0.
    eventStreamDigest: text("event_stream_digest").notNull(),
    sealerKind: text("sealer_kind").notNull(),
    sealerWorkerId: text("sealer_worker_id").notNull(),
    sealedAt: timestamp("sealed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    // ── Replay (Mission Control spec §8.3, §8.4, §13.3; ADR-058) ─────────────
    // The grade computed at seal from the completeness gaps: the strongest
    // verb a reader can apply to the recording. Never raised afterwards; the
    // row is immutable. Null only on a seal written before the recorder
    // graded (a row this migration backfilled), never on a new seal.
    replayGrade: text("replay_grade"),
    // The gaps the grade was computed from (closed vocabulary in
    // @oxagen/tacho COMPLETENESS_GAP_KINDS), as a JSON array of strings.
    completenessGaps: jsonb("completeness_gaps")
      .notNull()
      .default(sql`'[]'::jsonb`),
    // The RFC 6962 root over the attempt's event digests in run_seq order, and
    // the archive segment (frame envelopes as zstd NDJSON) written once at
    // seal. Both present on a graded seal; the segment reference is the
    // storage key a compacted run reads from.
    merkleRoot: text("merkle_root"),
    archiveSegmentRef: text("archive_segment_ref"),
    // The seal's rollup (spec §13.3): model calls, tool calls and distinct
    // turns folded from the rows at seal, so a run keeps its counts once
    // compaction (agent.compact_sealed_attempt_events) has removed its hot
    // frames. `turns` is null when a model call's payload was encrypted,
    // because the turn index travels inside it.
    modelCalls: integer("model_calls"),
    toolCalls: integer("tool_calls"),
    turns: integer("turns"),
    // Where the attempt's model calls were observed from (spec §8.4), derived
    // at seal from the rows (`ledgerEnforcementTier`) exactly like the grade
    // above it. `fork` is only reachable on `gateway`, so pinning every
    // ledger attempt to `harness` capped every recording at `view`. Null on a
    // seal written before this column existed; a reader treats that as
    // `harness`, which is what the seal was graded under.
    enforcementTier: text("enforcement_tier"),
  },
  (t) => ({
    rollupCheck: check(
      "agent_run_attempt_seals_rollup_check",
      sql`(${t.modelCalls} IS NULL OR ${t.modelCalls} >= 0) AND (${t.toolCalls} IS NULL OR ${t.toolCalls} >= 0) AND (${t.turns} IS NULL OR ${t.turns} >= 0) AND (${t.replayGrade} IS NULL) = (${t.modelCalls} IS NULL) AND (${t.replayGrade} IS NULL) = (${t.toolCalls} IS NULL)`,
    ),
    // An attempt seals exactly once — this uniqueness is what makes the
    // seal/grant/obligation transaction idempotent under duplicate sweeps.
    attemptUniq: uniqueIndex("agent_run_attempt_seals_attempt_uq").on(
      t.attemptId,
    ),
    orgIdx: index("agent_run_attempt_seals_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempt_seals_run_idx").on(t.runId),
    enforcementTierCheck: check(
      "agent_run_attempt_seals_enforcement_tier_check",
      sql`${t.enforcementTier} IS NULL OR ${t.enforcementTier} IN ('gateway', 'harness', 'observe')`,
    ),
    terminalStatusCheck: check(
      "agent_run_attempt_seals_terminal_status_check",
      sql`${t.terminalStatus} IN ('completed', 'failed', 'cancelled', 'denied', 'abandoned')`,
    ),
    // `ingress` is the only kind a seal is written under today — evidence
    // ingress stamps it. `worker` and `reclaimer` are the retired runtime's
    // vocabulary, kept solely so historical rows stay valid (ADR-043).
    sealerKindCheck: check(
      "agent_run_attempt_seals_sealer_kind_check",
      sql`${t.sealerKind} IN ('ingress', 'worker', 'reclaimer')`,
    ),
    // Zero-event seals carry no final-event evidence; non-zero seals carry all
    // of it. Anything else is an unprovable claim about the stream.
    eventEvidenceCheck: check(
      "agent_run_attempt_seals_event_evidence_check",
      sql`(
        ${t.eventCount} = 0
        AND ${t.finalRunSeq} IS NULL
        AND ${t.finalAttemptSeq} IS NULL
        AND ${t.finalEventDigest} IS NULL
      ) OR (
        ${t.eventCount} > 0
        AND ${t.finalRunSeq} IS NOT NULL
        AND ${t.finalAttemptSeq} IS NOT NULL
        AND ${t.finalEventDigest} IS NOT NULL
      )`,
    ),
    digestCheck: check(
      "agent_run_attempt_seals_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
    replayGradeCheck: check(
      "agent_run_attempt_seals_replay_grade_check",
      sql`${t.replayGrade} IS NULL OR ${t.replayGrade} IN ('inspect', 'view', 'fork', 'retry')`,
    ),
    // A graded seal carries its Merkle root and its archive segment; an
    // ungraded (pre-recorder) seal carries neither.
    replayEvidenceCheck: check(
      "agent_run_attempt_seals_replay_evidence_check",
      sql`(${t.replayGrade} IS NULL) = (${t.merkleRoot} IS NULL) AND (${t.replayGrade} IS NULL) = (${t.archiveSegmentRef} IS NULL) AND (${t.merkleRoot} IS NULL OR ${t.merkleRoot} ~ '^sha256:[0-9a-f]{64}$') AND jsonb_typeof(${t.completenessGaps}) = 'array'`,
    ),
  }),
);

// ── Immutable one-shot finalization grants ───────────────────────────────────
//
// Minted in the SAME transaction as the seal, for every seal. The `afg_` public
// id is ALSO the evidence envelope's stable `submission_id`, so every retry of
// the obligation reuses one submission identity instead of forking a new one.
//
// It deliberately has NO expiry column: the attempt/seal/digest binding plus
// one successful consumption are the limiting authority, so a KMS or storage
// outage can never strand an obligation behind an expired grant (spec.md
// §"Security and retention rules"). Consumption is recorded by the evidence
// ledger's grant-use row in the next PR; this table is never updated.
export const agentRunFinalizationGrants = agentSchema.table(
  "agent_run_finalization_grants",
  {
    ...idMixin("afg"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    // Copied so the finalizer can build the envelope without a second read.
    attemptPublicId: citext("attempt_public_id").notNull(),
    // Constrained to exactly one capability — a grant can never execute tools.
    capabilityId: text("capability_id")
      .notNull()
      .default("ingest_run_evidence"),
    eventCount: integer("event_count").notNull(),
    finalEventDigest: text("final_event_digest"),
    eventStreamDigest: text("event_stream_digest").notNull(),
    issuedAt: timestamp("issued_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    attemptUniq: uniqueIndex("agent_run_finalization_grants_attempt_uq").on(
      t.attemptId,
    ),
    sealUniq: uniqueIndex("agent_run_finalization_grants_seal_uq").on(t.sealId),
    orgIdx: index("agent_run_finalization_grants_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
    capabilityCheck: check(
      "agent_run_finalization_grants_capability_check",
      sql`${t.capabilityId} = 'ingest_run_evidence'`,
    ),
    eventCountCheck: check(
      "agent_run_finalization_grants_event_count_check",
      sql`${t.eventCount} >= 0 AND (${t.eventCount} = 0) = (${t.finalEventDigest} IS NULL)`,
    ),
    digestCheck: check(
      "agent_run_finalization_grants_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable finalization obligations (the durable outbox) ──────────────────
//
// Created in the seal transaction next to the grant. There is deliberately NO
// `processed_at` column: pending state is DERIVED by anti-joining the evidence
// ledger's grant-use row, so a crash between "wrote evidence" and "marked done"
// cannot lose or duplicate an obligation. Mutable retry/claim coordination is a
// separate table in the evidence-ledger PR — never a mutation of this row.
export const agentRunFinalizationObligations = agentSchema.table(
  "agent_run_finalization_obligations",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    grantId: uuid("grant_id").notNull(),
    // The grant's `afg_` public id, copied verbatim. Stable across every retry.
    submissionId: citext("submission_id").notNull(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    grantUniq: uniqueIndex("agent_run_finalization_obligations_grant_uq").on(
      t.grantId,
    ),
    // `(org_id, submission_id)` is the finalization idempotency key the
    // evidence ledger keys on; enforce it here too so a duplicate obligation
    // cannot exist to be double-processed.
    submissionUniq: uniqueIndex(
      "agent_run_finalization_obligations_submission_uq",
    ).on(t.orgId, t.submissionId),
    attemptUniq: uniqueIndex(
      "agent_run_finalization_obligations_attempt_uq",
    ).on(t.attemptId),
    orgIdx: index("agent_run_finalization_obligations_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
  }),
);

// ── Workspace agent-asset registry (stella-cutover Wave 4) ───────────────────
//
// Tool declarations + context records: a logical identity row keyed
// (workspace_id, slug) plus immutable version snapshots, an explicitly pinned
// active_version_id, and soft delete on the identity row only. Migration
// 20260831120000_agent_asset_registry.sql.

// Declared tool contracts (Stella ToolContract vocabulary): the JSON schema,
// read_only flag, risk grade and policy group live on the version row; the
// identity row carries the source discriminator and the enable toggle.
export const tools = agentSchema.table(
  "tools",
  {
    ...idMixin("tol"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    name: text("name").notNull(),
    slug: citext("slug").notNull(),
    description: text("description"),
    // builtin = shipped built-in; custom = workspace-authored script tool;
    // mcp = an MCP server's advertised tool; foundry = tool-foundry authored.
    source: citext("source").notNull(),
    enabled: boolean("enabled").notNull().default(true),
    // Explicitly pinned active version, decoupled from tool_versions.is_latest.
    activeVersionId: uuid("active_version_id").references(
      (): AnyPgColumn => toolVersions.id,
    ),
    // The mcp.mcp_servers row an imported tool was pulled from (source =
    // 'mcp'); null for declared tools. Not a foreign key: a server soft-deletes
    // and its tools keep their rows for replay (#2958).
    mcpServerId: uuid("mcp_server_id"),
    activatedByUserId: uuid("activated_by_user_id"),
    activatedAt: timestamp("activated_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => ({
    workspaceSlugIdx: uniqueIndex("tools_workspace_slug_idx").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("tools_org_idx").on(t.orgId, t.workspaceId),
    activeVersionIdx: index("tools_active_version_idx").on(t.activeVersionId),
    mcpServerIdx: index("tools_mcp_server_idx")
      .on(t.mcpServerId)
      .where(sql`mcp_server_id IS NOT NULL`),
    sourceCheck: check(
      "tools_source_check",
      sql`${t.source} IN ('builtin', 'custom', 'mcp', 'foundry')`,
    ),
  }),
);

export const toolVersions = agentSchema.table(
  "tool_versions",
  {
    ...idMixin("tlv"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...versionMixin(),
    toolId: uuid("tool_id").notNull(),
    // The tool's JSON Schema for its input parameters.
    inputSchema: jsonb("input_schema").notNull(),
    readOnly: boolean("read_only").notNull().default(false),
    riskGrade: text("risk_grade").notNull(),
    policyGroup: text("policy_group"),
    // The full declared manifest body, verbatim.
    manifest: jsonb("manifest").notNull(),
    // SHA-256 hex over the canonical (sorted-key) manifest JSON — immutability
    // contract (see skill_versions.checksum).
    checksum: text("checksum").notNull(),
    // Where the schema came from (MC spec App. A.5): 'declared' for a
    // hand-authored manifest (publish_tool_declaration), 'imported' for a
    // server's tools/list (import_tools). The observed origins arrive with the
    // recorder that captures tool outputs (ADR-072).
    schemaOrigin: text("schema_origin").notNull().default("declared"),
    // Safety classification (spec §6.9 part 1), the shape of
    // toolClassificationSchema in @oxagen/oxagen/contracts/tool.classification:
    // side-effect class, egress class, consequence tags, measures, data
    // classes. Null until an admin classifies the version. Describes the tool
    // and decides nothing by itself; a class kill switch matches a version by
    // its tags at call time. A new version of the tool starts with the
    // classification of the version it replaces (publishTool), and a changed
    // classification bumps the deny generation in the writer's transaction
    // (trigger tool_versions_classification_deny_generation), so the gateway's
    // gate reloads the tags.
    classification: jsonb("classification"),
    // The risk grade the classifier set. risk_grade is the declared grade and
    // part of the checksum; this one is not, so reclassifying never makes an
    // unchanged manifest look changed.
    classifiedRiskGrade: text("classified_risk_grade"),
    classifiedByUserId: uuid("classified_by_user_id"),
    classifiedAt: timestamp("classified_at", {
      withTimezone: true,
      mode: "date",
    }),
    classificationReason: text("classification_reason"),
    // The mandate gate's half of the same classification (MC spec §6.9 part 1,
    // ADR-059 decision 6, 20260915202300_mandates_and_ledger.sql): the
    // consequences invoking this version can cause, the measures it exposes
    // as paths into its input ({ path, type, unit, scale? } per measure name),
    // and the path into its output that carries the external effect id a
    // settlement records. These are columns rather than keys inside
    // `classification` because a mandate reads them on every gated call and
    // the kill-switch gate reads the jsonb; both describe the tool and decide
    // nothing by themselves.
    consequenceTags: text("consequence_tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    measures: jsonb("measures").notNull().default(sql`'{}'::jsonb`),
    effectIdPath: text("effect_id_path"),
  },
  (t) => ({
    toolIdx: index("tool_versions_tool_idx").on(t.toolId),
    toolLatestIdx: uniqueIndex("tool_versions_tool_latest_idx")
      .on(t.toolId)
      .where(sql`is_latest = true`),
    toolVersionIdx: uniqueIndex("tool_versions_tool_version_idx").on(
      t.toolId,
      t.versionNumber,
    ),
    orgIdx: index("tool_versions_org_idx").on(t.orgId, t.workspaceId),
    riskGradeCheck: check(
      "tool_versions_risk_grade_check",
      sql`${t.riskGrade} IN ('low', 'medium', 'high', 'critical')`,
    ),
    checksumCheck: check(
      "tool_versions_checksum_check",
      sql`${t.checksum} ~ '^[0-9a-f]{64}$'`,
    ),
    schemaOriginCheck: check(
      "tool_versions_schema_origin_check",
      sql`${t.schemaOrigin} IN ('declared', 'imported')`,
    ),
    classifiedRiskGradeCheck: check(
      "tool_versions_classified_risk_grade_check",
      sql`${t.classifiedRiskGrade} IS NULL OR ${t.classifiedRiskGrade} IN ('low', 'medium', 'high', 'critical')`,
    ),
    // A classification names its risk grade and when it was set, or is absent altogether.
    classificationCheck: check(
      "tool_versions_classification_check",
      sql`(${t.classification} IS NULL AND ${t.classifiedAt} IS NULL AND ${t.classifiedRiskGrade} IS NULL) OR (${t.classification} IS NOT NULL AND ${t.classifiedAt} IS NOT NULL AND ${t.classifiedRiskGrade} IS NOT NULL)`,
    ),
  }),
);

// Steering/context records — the published registry. Stella keeps these as
// .oxagen/rules/<lineage>.toml, one record per file; the slug is the file stem
// and the lineage id (MC spec §10.2). Lifecycle (status) is driven by the
// append-only contextPromotions ledger below, never edited directly.
//
// The classification columns (kind, force, constraint_effect, statement) are
// required on every write, by merge_context_pr (ADR-061) and by
// publish_context_record alike (#3302; migration `20260920130000`). Before
// #3302, publish_context_record wrote only the body, so a record it published
// carried NULL in all four and sat active in the registry without ever
// reaching an agent — readWorkspaceSteering only ever delivers a record whose
// force is must or should, and nothing told the publisher their record never
// steered. The publication columns (commit_sha, path, published_at) stay
// NULL on a record published through publish_context_record: that path
// writes no commit, because merge — not this call — is the publication event
// for a Context PR (ADR-061 §10).
export const contextRecords = agentSchema.table(
  "context_records",
  {
    ...idMixin("ctr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    slug: citext("slug").notNull(),
    title: text("title").notNull(),
    label: text("label"),
    // promote → active, retire → retired, supersede → superseded.
    status: text("status").notNull().default("active"),
    validUntil: timestamp("valid_until", { withTimezone: true, mode: "date" }),
    activeVersionId: uuid("active_version_id").references(
      (): AnyPgColumn => contextRecordVersions.id,
    ),
    activatedByUserId: uuid("activated_by_user_id"),
    activatedAt: timestamp("activated_at", {
      withTimezone: true,
      mode: "date",
    }),
    // The six kinds of context-record/v0.1 (Stella's file surface). Every
    // write path has required one since #3302, enforced today at the
    // application layer (contracts/context.record.publish.ts,
    // context.steering.store.ts). The DB-level NOT NULL is a deliberate
    // follow-up migration (see migration `20260920150000`'s comment,
    // Codex round 3 on #3486): db-migrate.yml runs on no ordering guarantee
    // against the deploy that ships this requirement, so a hard constraint
    // here today could reject a write from an old container still in a
    // rolling deploy.
    kind: text("kind"),
    // How hard the record steers: must | should | may | info. Every write
    // path has required one since #3302; a record with no force can never
    // reach an agent. See `kind`'s comment for why this stays nullable at
    // the DB layer for now.
    force: text("force"),
    // require | forbid on a constraint; NULL on every other kind. `allow` is
    // unrepresentable: a record never grants authority (spec §10.3).
    constraintEffect: text("constraint_effect"),
    // repository | workspace (spec §9 Scope, §10.2).
    sharingScope: text("sharing_scope").notNull().default("workspace"),
    // The single-sentence claim, as it appears in the file.
    statement: text("statement"),
    // The merge commit on the production branch that published this record,
    // and the file's path in that repository.
    commitSha: text("commit_sha"),
    path: text("path"),
    publishedAt: timestamp("published_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => ({
    workspaceSlugIdx: uniqueIndex("context_records_workspace_slug_idx").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("context_records_org_idx").on(t.orgId, t.workspaceId),
    activeVersionIdx: index("context_records_active_version_idx").on(
      t.activeVersionId,
    ),
    labelCheck: check(
      "context_records_label_check",
      sql`${t.label} IS NULL OR (length(btrim(${t.label})) BETWEEN 1 AND 200)`,
    ),
    statusCheck: check(
      "context_records_status_check",
      sql`${t.status} IN ('active', 'retired', 'superseded')`,
    ),
    kindCheck: check(
      "context_records_kind_check",
      sql`${t.kind} IN ('rule', 'constraint', 'procedure', 'fact', 'memory', 'preference')`,
    ),
    forceCheck: check(
      "context_records_force_check",
      sql`${t.force} IN ('must', 'should', 'may', 'info')`,
    ),
    constraintEffectCheck: check(
      "context_records_constraint_effect_check",
      sql`(${t.constraintEffect} IS NULL AND ${t.kind} IS DISTINCT FROM 'constraint') OR (${t.constraintEffect} IN ('require', 'forbid') AND ${t.kind} = 'constraint')`,
    ),
    sharingScopeCheck: check(
      "context_records_sharing_scope_check",
      sql`${t.sharingScope} IN ('repository', 'workspace')`,
    ),
    commitShaCheck: check(
      "context_records_commit_sha_check",
      sql`${t.commitSha} IS NULL OR ${t.commitSha} ~ '^[0-9a-f]{7,40}$'`,
    ),
  }),
);

export const contextRecordVersions = agentSchema.table(
  "context_record_versions",
  {
    ...idMixin("crv"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...versionMixin(),
    recordId: uuid("record_id").notNull(),
    // The canonical record body (one TOML record per file in Stella).
    body: text("body").notNull(),
    // SHA-256 hex over body — immutability contract (see skill_versions).
    checksum: text("checksum").notNull(),
    // ContextProvenanceV1 vocabulary (packages/run-evidence contextgraph.ts):
    // [{ type, uri?, range?, digest?, method?, by? }].
    provenance: jsonb("provenance").notNull().default(sql`'[]'::jsonb`),
    // The classification this version's body carries, written by
    // merge_context_pr alongside the record row's copy. It belongs here
    // because it describes the body: promoting an older version back into
    // service must compile what that version says, not what the record row
    // was last told (#3312). NULL in all four on a version the legacy
    // publish_context_record path wrote; the record row is the fallback then.
    kind: text("kind"),
    force: text("force"),
    constraintEffect: text("constraint_effect"),
    statement: text("statement"),
  },
  (t) => ({
    recordIdx: index("context_record_versions_record_idx").on(t.recordId),
    recordLatestIdx: uniqueIndex("context_record_versions_record_latest_idx")
      .on(t.recordId)
      .where(sql`is_latest = true`),
    recordVersionIdx: uniqueIndex(
      "context_record_versions_record_version_idx",
    ).on(t.recordId, t.versionNumber),
    orgIdx: index("context_record_versions_org_idx").on(t.orgId, t.workspaceId),
    checksumCheck: check(
      "context_record_versions_checksum_check",
      sql`${t.checksum} ~ '^[0-9a-f]{64}$'`,
    ),
    kindCheck: check(
      "context_record_versions_kind_check",
      sql`${t.kind} IS NULL OR ${t.kind} IN ('rule', 'constraint', 'procedure', 'fact', 'memory', 'preference')`,
    ),
    forceCheck: check(
      "context_record_versions_force_check",
      sql`${t.force} IS NULL OR ${t.force} IN ('must', 'should', 'may', 'info')`,
    ),
    constraintEffectCheck: check(
      "context_record_versions_constraint_effect_check",
      sql`(${t.constraintEffect} IS NULL AND ${t.kind} IS DISTINCT FROM 'constraint') OR (${t.constraintEffect} IN ('require', 'forbid') AND ${t.kind} = 'constraint')`,
    ),
  }),
);

/**
 * A classification column of {@link contextRecordVersions}, for the
 * deploy-before-migrate probe.
 *
 * Migration `20260918160000` adds `kind`, `force`, `constraint_effect` and
 * `statement` to the version table. Production applies migrations by hand from
 * the app node while `deploy-node` ships on merge without waiting, so between
 * the two there is a window in which the code that reads and writes these four
 * is live and the columns are not. Naming one then raises 42703 and aborts the
 * transaction, which would take out every bundle fetch, control poll, event
 * ingest and enrollment in the workspace -- none of which are about a version's
 * classification at all.
 *
 * One ref answers for all four: they are added by a single `ALTER TABLE`, so
 * either all four are there or none is.
 */
export const CONTEXT_VERSION_CLASSIFICATION_COLUMN = {
  schema: "agent",
  table: "context_record_versions",
  column: "kind",
} as const;

// Append-only hash-chained ledger of context-record lifecycle actions,
// mirroring Stella's promotions.jsonl: chain_digest = sha256(prev_digest +
// canonical row), seq monotonic per record starting at 1. INSERT-only at the
// grant level (no UPDATE/DELETE for oxagen_app) — a promotion is evidence.
export const contextPromotions = agentSchema.table(
  "context_promotions",
  {
    ...idMixin("ctp"),
    ...appendOnlyAuditMixin(),
    ...orgScopeMixin(),
    recordId: uuid("record_id").notNull(),
    // The version being promoted/superseded-by; NULL for a retire.
    versionId: uuid("version_id"),
    seq: integer("seq").notNull(),
    action: text("action").notNull(),
    approverUserId: uuid("approver_user_id"),
    policyVersion: text("policy_version").notNull(),
    // The previous entry's chain_digest; NULL only for seq = 1.
    prevChainDigest: text("prev_chain_digest"),
    chainDigest: text("chain_digest").notNull(),
  },
  (t) => ({
    recordSeqIdx: uniqueIndex("context_promotions_record_seq_idx").on(
      t.recordId,
      t.seq,
    ),
    orgIdx: index("context_promotions_org_idx").on(t.orgId, t.workspaceId),
    actionCheck: check(
      "context_promotions_action_check",
      sql`${t.action} IN ('promote', 'retire', 'supersede')`,
    ),
    seqCheck: check("context_promotions_seq_check", sql`${t.seq} > 0`),
    chainCheck: check(
      "context_promotions_chain_check",
      sql`${t.chainDigest} ~ '^[0-9a-f]{64}$' AND (${t.prevChainDigest} IS NULL OR ${t.prevChainDigest} ~ '^[0-9a-f]{64}$') AND ((${t.seq} = 1) = (${t.prevChainDigest} IS NULL))`,
    ),
  }),
);

// A record proposal and the Context PR that publishes it (ADR-061, MC spec
// §9.2, §10.3). One row is one concern: it carries the record it proposes,
// the support it cites, and the state machine
//   proposed → pr_open → checks_running → checks_passed | checks_failed → merged
// with rejected reachable from proposed and from any open-PR state through
// dismiss_proposal. The promotion event a merge writes is a contextPromotions
// row (promotion_event_id), never a field here: the ledger is append-only and
// this row is not.
export const contextProposals = agentSchema.table(
  "context_proposals",
  {
    ...idMixin("prp"),
    ...auditMixin(),
    ...orgScopeMixin(),
    lineageId: citext("lineage_id").notNull(),
    kind: text("kind").notNull(),
    force: text("force").notNull(),
    constraintEffect: text("constraint_effect"),
    sharingScope: text("sharing_scope").notNull(),
    title: text("title"),
    label: text("label"),
    statement: text("statement").notNull(),
    rationale: text("rationale").notNull(),
    // Who raised it, as a label the page prints: `user:<uuid>`,
    // `api_key:<uuid>`, or the caller's own attribution (a job, a run).
    source: text("source").notNull(),
    supportRuns: text("support_runs").array().notNull().default(sql`'{}'`),
    supportAgents: text("support_agents").array().notNull().default(sql`'{}'`),
    supportingRecordIds: text("supporting_record_ids")
      .array()
      .notNull()
      .default(sql`'{}'`),
    evidenceLinks: text("evidence_links").array().notNull().default(sql`'{}'`),
    status: text("status").notNull().default("proposed"),
    // ── The Context PR, set by open_context_pr ──────────────────────────────
    // The governance mode read from .oxagen/rules/governance.toml when the PR
    // was opened; merge_context_pr reads the file again.
    governanceMode: text("governance_mode"),
    repository: text("repository"),
    baseRef: text("base_ref"),
    branch: text("branch"),
    path: text("path"),
    prNumber: integer("pr_number"),
    prUrl: text("pr_url"),
    headSha: text("head_sha"),
    // The record's stamped identity in the committed file.
    stampedRecordId: text("stamped_record_id"),
    recordHash: text("record_hash"),
    // [{ name, status, summary, detailsUrl, startedAt, completedAt }], one
    // entry per §10.3 check, in the order they run.
    checks: jsonb("checks").notNull().default(sql`'[]'::jsonb`),
    // ── The merge, set by merge_context_pr ──────────────────────────────────
    mergedCommit: text("merged_commit"),
    mergedAt: timestamp("merged_at", { withTimezone: true, mode: "date" }),
    mergedByUserId: uuid("merged_by_user_id"),
    publishedRecordId: uuid("published_record_id"),
    promotionEventId: uuid("promotion_event_id"),
    // ── The dismissal, set by dismiss_proposal ──────────────────────────────
    dismissedAt: timestamp("dismissed_at", {
      withTimezone: true,
      mode: "date",
    }),
    dismissedReason: text("dismissed_reason"),
  },
  (t) => ({
    orgIdx: index("context_proposals_org_idx").on(t.orgId, t.workspaceId),
    lineageIdx: index("context_proposals_lineage_idx").on(
      t.workspaceId,
      t.lineageId,
    ),
    // One concern, one pull request: at most one open PR per lineage.
    openPrIdx: uniqueIndex("context_proposals_open_pr_idx")
      .on(t.workspaceId, t.lineageId)
      .where(
        sql`status IN ('pr_open', 'checks_running', 'checks_passed', 'checks_failed')`,
      ),
    labelCheck: check(
      "context_proposals_label_check",
      sql`${t.label} IS NULL OR (length(btrim(${t.label})) BETWEEN 1 AND 200)`,
    ),
    kindCheck: check(
      "context_proposals_kind_check",
      sql`${t.kind} IN ('rule', 'constraint', 'procedure', 'fact', 'memory', 'preference')`,
    ),
    forceCheck: check(
      "context_proposals_force_check",
      sql`${t.force} IN ('must', 'should', 'may', 'info')`,
    ),
    constraintEffectCheck: check(
      "context_proposals_constraint_effect_check",
      sql`(${t.constraintEffect} IS NULL AND ${t.kind} <> 'constraint') OR (${t.constraintEffect} IN ('require', 'forbid') AND ${t.kind} = 'constraint')`,
    ),
    sharingScopeCheck: check(
      "context_proposals_sharing_scope_check",
      sql`${t.sharingScope} IN ('repository', 'workspace')`,
    ),
    statusCheck: check(
      "context_proposals_status_check",
      sql`${t.status} IN ('proposed', 'pr_open', 'checks_running', 'checks_passed', 'checks_failed', 'merged', 'rejected')`,
    ),
    governanceModeCheck: check(
      "context_proposals_governance_mode_check",
      sql`${t.governanceMode} IS NULL OR ${t.governanceMode} IN ('solo', 'team', 'regulated')`,
    ),
    mergedCheck: check(
      "context_proposals_merged_check",
      sql`(${t.status} = 'merged') = (${t.mergedCommit} IS NOT NULL AND ${t.promotionEventId} IS NOT NULL AND ${t.publishedRecordId} IS NOT NULL)`,
    ),
  }),
);

// Records agents append through append_record — the protocol's
// `context/append` (MC spec §9): observations, memories, knowledge, evidence,
// context-use records and record proposals, content-addressed by
// record_hash. Append-only: a correction is a new record on the same lineage
// and superseded is derived, never stored. A `directive` never lands here;
// it reaches the workspace only through a Context PR.
export const contextAppends = agentSchema.table(
  "context_appends",
  {
    ...idMixin("cta"),
    ...appendOnlyAuditMixin(),
    ...orgScopeMixin(),
    kind: text("kind").notNull(),
    lineageId: citext("lineage_id").notNull(),
    statement: text("statement").notNull(),
    sharingScope: text("sharing_scope").notNull(),
    // `sha256:<64 hex>` over the record's canonical preimage
    // (packages/run-evidence record-hash.ts).
    recordHash: text("record_hash").notNull(),
    // ContextProvenanceV1-style source refs: frames (`frame:<run>/<seq>`) and
    // records the appended record derives from.
    sourceRefs: text("source_refs").array().notNull().default(sql`'{}'`),
    evidenceLinks: text("evidence_links").array().notNull().default(sql`'{}'`),
    // The proposal a `record_proposal` append opened; NULL on every other kind.
    proposalId: uuid("proposal_id"),
  },
  (t) => ({
    orgIdx: index("context_appends_org_idx").on(t.orgId, t.workspaceId),
    lineageIdx: index("context_appends_lineage_idx").on(
      t.workspaceId,
      t.lineageId,
    ),
    // Re-appending identical content is idempotent.
    hashIdx: uniqueIndex("context_appends_workspace_hash_idx").on(
      t.workspaceId,
      t.recordHash,
    ),
    kindCheck: check(
      "context_appends_kind_check",
      sql`${t.kind} IN ('observation', 'memory', 'knowledge', 'evidence', 'record_proposal', 'context_use', 'context_use_feedback')`,
    ),
    sharingScopeCheck: check(
      "context_appends_sharing_scope_check",
      sql`${t.sharingScope} IN ('repository', 'workspace')`,
    ),
    hashCheck: check(
      "context_appends_record_hash_check",
      sql`${t.recordHash} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    proposalCheck: check(
      "context_appends_proposal_check",
      sql`(${t.proposalId} IS NOT NULL) = (${t.kind} = 'record_proposal')`,
    ),
  }),
);
