import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  numeric,
  bigint,
  smallint,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { agentSchema } from "./_schemas";
import {
  appendOnlyAuditMixin,
  auditMixin,
  citext,
  idMixin,
  softDeleteMixin,
  orgScopeMixin,
  versionMixin,
  uuidv7Default,
} from "./_mixins";

// Agent identity + versioning (spec §6, agent-runtime epic).
export const agents = agentSchema.table(
  "agents",
  {
    ...idMixin("agt"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    slug: citext("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    agentType: text("agent_type").notNull(),
    activeVersionId: uuid("active_version_id"),
    // status: text + check per spec §6
    status: text("status").notNull().default("draft"),
    // deploymentStatus is the deploy on/off toggle, distinct from the
    // draft/active/archived authoring lifecycle in `status`.
    deploymentStatus: text("deployment_status").notNull().default("inactive"),
    // Nullable avatar. Either an https:// URL or the platform designed-avatar
    // spec string "avatar:v1:<json>" ({emoji,bg,mode}); capped at 512 chars at
    // the contract layer. Same column name as users/organizations for
    // consistency, even though it may carry the spec string, not a plain URL.
    avatarUrl: text("avatar_url"),
    // LLM-inferred, plain-text (<=256 char) description of what this agent does,
    // derived from its config (name/instructions/tools/triggers). Regenerated by
    // agent.definition.summarize when stale.
    summary: text("summary"),
    // SHA-256 of the canonical version config `summary` was derived from (same
    // canonicalization as agent_versions.checksum). When it no longer matches the
    // current config, the summary is stale and gets regenerated.
    summaryChecksum: text("summary_checksum"),
    // Agent RBAC Phase 1 (docs/specs/agent-rbac/spec.md §3.1): the delegated
    // IAM principal (org.principals, kind='agent') for this agent IDENTITY —
    // one per agent, never per version/run. App-enforced reference (no
    // cross-schema FK per CLAUDE.md storage rules); provisioned by
    // agent.definition.create and soft-deleted together with the agent.
    principalId: uuid("principal_id"),
  },
  (t) => ({
    // NON-partial on purpose: covers soft-deleted rows too, so a slug a
    // workspace has ever used is PERMANENTLY reserved (never recycled), like an
    // npm package name. Immutability of the live slug is enforced by the
    // agents_slug_immutable trigger; this index reserves it past deletion.
    // (ADR-024, migration 20260709130000_agent_slug_no_recycle.)
    workspaceSlugUniq: uniqueIndex("agents_workspace_slug_uniq").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("agents_org_idx").on(t.orgId, t.workspaceId),
    principalIdx: index("agents_principal_idx").on(t.principalId),
    deploymentStatusIdx: index("agents_deployment_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.deploymentStatus,
    ),
    statusCheck: check(
      "agents_status_check",
      sql`${t.status} IN ('draft', 'active', 'archived')`,
    ),
    deploymentStatusCheck: check(
      "agents_deployment_status_check",
      sql`${t.deploymentStatus} IN ('inactive', 'active')`,
    ),
    slugCheck: check(
      "agents_slug_check",
      sql`${t.slug} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`,
    ),
  }),
);

// Agent triggers: how a deployed agent is invoked — manual, scheduled (cron),
// or by an external event. connectionId references a connected source
// (app-enforced; no cross-schema FK per CLAUDE.md storage rules).
export const agentTriggers = agentSchema.table(
  "agent_triggers",
  {
    ...idMixin("atr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    agentId: uuid("agent_id")
      .notNull()
      .references(() => agents.id),
    triggerType: text("trigger_type").notNull(),
    // eventSource/eventType are null for manual/schedule triggers.
    eventSource: text("event_source"),
    eventType: text("event_type"),
    connectionId: uuid("connection_id"),
    // filter scopes event triggers, e.g. { branches: [...], pathGlobs: [...] }.
    filter: jsonb("filter").notNull().default(sql`'{}'::jsonb`),
    // schedule is a cron expression; null unless triggerType = 'schedule'.
    schedule: text("schedule"),
    enabled: boolean("enabled").notNull().default(false),
  },
  (t) => ({
    agentIdx: index("agent_triggers_agent_idx").on(t.agentId),
    orgIdx: index("agent_triggers_org_idx").on(t.orgId, t.workspaceId),
    typeEnabledIdx: index("agent_triggers_type_enabled_idx").on(
      t.triggerType,
      t.enabled,
    ),
    triggerTypeCheck: check(
      "agent_triggers_trigger_type_check",
      sql`${t.triggerType} IN ('manual', 'schedule', 'event')`,
    ),
  }),
);

// Immutable version snapshots. INSERT-only once published; no updatedAt by design.
export const agentVersions = agentSchema.table(
  "agent_versions",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    agentId: uuid("agent_id")
      .notNull()
      .references(() => agents.id),
    version: integer("version").notNull(),
    isPublished: boolean("is_published").notNull().default(false),
    // checksum: SHA-256 over canonical config — immutability contract.
    checksum: text("checksum"),
    config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
    createdByUserId: uuid("created_by_user_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    // No updatedAt by design — INSERT-only once published.
  },
  (t) => ({
    agentVersionUniq: uniqueIndex("agent_versions_agent_version_uniq").on(
      t.agentId,
      t.version,
    ),
    agentIdx: index("agent_versions_agent_idx").on(t.agentId),
  }),
);

// Skills (spec §6, agent-runtime epic). Logical identity + immutable
// versions, mirroring the agents/tools/playbooks versioning pattern.
export const skills = agentSchema.table(
  "skills",
  {
    ...idMixin("skl"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    name: text("name").notNull(),
    slug: citext("slug").notNull(),
    description: text("description"),
    // builtin = shipped in packages/skills; tenant = workspace-authored.
    source: citext("source").notNull(),
    // Per-workspace enable toggle (distinct from soft-delete). Disabled skills
    // are excluded from agent tool materialization but remain authorable.
    enabled: boolean("enabled").notNull().default(true),
    // Explicitly pinned active version, decoupled from skill_versions.is_latest.
    // Same-schema FK to skill_versions.id (forward ref — Drizzle resolves lazily).
    activeVersionId: uuid("active_version_id").references(
      (): AnyPgColumn => skillVersions.id,
    ),
    // Audit of who/when last changed the active version. user-id is a
    // cross-schema reference (auth.users) — app-enforced, no FK per storage rules.
    activatedByUserId: uuid("activated_by_user_id"),
    activatedAt: timestamp("activated_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Fast-path list display (OXA-1750): last invocation + total usage count.
    lastUsedAt: timestamp("last_used_at", { withTimezone: true, mode: "date" }),
    usageCount: integer("usage_count").notNull().default(0),
    // Provenance for workspace-owned copies installed from a template (OXA-1748).
    installedFromSlug: citext("installed_from_slug"),
  },
  (t) => ({
    workspaceSlugIdx: uniqueIndex("skills_workspace_slug_idx").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("skills_org_idx").on(t.orgId, t.workspaceId),
    // FK → agent.skill_versions (skills_active_version_id_skill_versions_id_fk).
    // Index the FK so skill_versions mutations don't seq-scan skills.
    activeVersionIdx: index("skills_active_version_idx").on(t.activeVersionId),
  }),
);

export const skillVersions = agentSchema.table(
  "skill_versions",
  {
    ...idMixin("slv"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...versionMixin(),
    skillId: uuid("skill_id").notNull(),
    body: text("body").notNull(),
    // References from the .skill.md frontmatter (graph nodes, files, etc).
    referencesPayload: jsonb("references_payload")
      .notNull()
      .default(sql`'[]'::jsonb`),
    // Author-supplied summary of what changed in this version (commit message).
    changeSummary: text("change_summary"),
    // checksum: SHA-256 hex over body — immutability contract (see agent_versions).
    checksum: text("checksum"),
  },
  (t) => ({
    skillIdx: index("skill_versions_skill_idx").on(t.skillId),
    skillLatestIdx: uniqueIndex("skill_versions_skill_latest_idx")
      .on(t.skillId)
      .where(sql`is_latest = true`),
    skillVersionIdx: uniqueIndex("skill_versions_skill_version_idx").on(
      t.skillId,
      t.versionNumber,
    ),
    orgIdx: index("skill_versions_org_idx").on(t.orgId, t.workspaceId),
  }),
);

// Background tasks tracking agent.task.background.* Inngest runs.
export const backgroundTasks = agentSchema.table(
  "background_tasks",
  {
    ...idMixin("bgt"),
    ...auditMixin(),
    ...orgScopeMixin(),
    kind: text("kind").notNull(),
    label: text("label"),
    inngestRunId: text("inngest_run_id").notNull().unique(),
    status: text("status").notNull(),
    inputPayload: jsonb("input_payload").notNull(),
    resultPayload: jsonb("result_payload"),
    failureReason: text("failure_reason"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    createdByUserId: uuid("created_by_user_id"),
  },
  (t) => ({
    orgStatusIdx: index("background_tasks_org_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    orgIdx: index("background_tasks_org_idx").on(t.orgId, t.workspaceId),
    statusCheck: check(
      "background_tasks_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
  }),
);

// Approval requests: cross-domain references (execution_step_id, message_id,
// tool_call_id) are app-enforced; FKs stay within the agent schema per
// CLAUDE.md storage rules.
export const approvalRequests = agentSchema.table(
  "approval_requests",
  {
    ...idMixin("apr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    executionStepId: uuid("execution_step_id"),
    toolCallId: uuid("tool_call_id"),
    messageId: uuid("message_id").notNull(),
    capabilityName: text("capability_name").notNull(),
    inputPreview: jsonb("input_preview").notNull(),
    riskLevel: text("risk_level").notNull(),
    // resolution null until resolved.
    resolution: text("resolution"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "date" }),
    resolvedByUserId: uuid("resolved_by_user_id"),
    note: text("note"),
    expiresAt: timestamp("expires_at", {
      withTimezone: true,
      mode: "date",
    }).notNull(),
  },
  (t) => ({
    orgResolutionIdx: index("approval_requests_org_resolution_idx").on(
      t.orgId,
      t.workspaceId,
      t.resolution,
    ),
    orgIdx: index("approval_requests_org_idx").on(t.orgId, t.workspaceId),
    messageIdx: index("approval_requests_message_idx").on(t.messageId),
    resolutionCheck: check(
      "approval_requests_resolution_check",
      sql`${t.resolution} IN ('approved', 'denied', 'expired') OR ${t.resolution} IS NULL`,
    ),
    riskLevelCheck: check(
      "approval_requests_risk_level_check",
      sql`${t.riskLevel} IN ('low', 'medium', 'high', 'critical')`,
    ),
  }),
);

// Subagent fanout aggregate; child runs join via subagent_runs.fanout_id.
export const subagentFanouts = agentSchema.table(
  "subagent_fanouts",
  {
    ...idMixin("fan"),
    ...auditMixin(),
    ...orgScopeMixin(),
    parentMessageId: uuid("parent_message_id").notNull(),
    inngestEventId: text("inngest_event_id"),
    status: text("status").notNull(),
    totalChildren: integer("total_children").notNull(),
    completedChildren: integer("completed_children").notNull().default(0),
  },
  (t) => ({
    orgIdx: index("subagent_fanouts_org_idx").on(t.orgId, t.workspaceId),
    parentMessageIdx: index("subagent_fanouts_parent_message_idx").on(
      t.parentMessageId,
    ),
    statusCheck: check(
      "subagent_fanouts_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'partial', 'timed_out')`,
    ),
  }),
);

export const subagentRuns = agentSchema.table(
  "subagent_runs",
  {
    ...idMixin("sar"),
    ...auditMixin(),
    ...orgScopeMixin(),
    fanoutId: uuid("fanout_id").notNull(),
    childMessageId: uuid("child_message_id").notNull(),
    capabilityName: text("capability_name").notNull(),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    // Structural ≤280-char digest of the output, written by the executor at
    // completion so agent.subagent.aggregate can return summaries instead of
    // relaying full payloads into the parent LLM context
    // (docs/specs/graph-mediated-fanout).
    summary: text("summary"),
    status: text("status").notNull(),
    errorReason: text("error_reason"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Durable claim/lease (docs/specs/graph-mediated-fanout-phase2 §1).
    // claimedBy = Inngest run id of the owning worker; leaseExpiresAt null means
    // unclaimed or terminal. The lease sweeper requeues expired-lease rows until
    // the attempt cap, so a dead worker's task is reclaimed without a coordinator.
    claimedBy: text("claimed_by"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    attempts: integer("attempts").notNull().default(0),
  },
  (t) => ({
    fanoutIdx: index("subagent_runs_fanout_idx").on(t.fanoutId),
    statusIdx: index("subagent_runs_status_idx").on(t.status),
    orgIdx: index("subagent_runs_org_idx").on(t.orgId, t.workspaceId),
    // Partial index for the claim UPDATE and the lease sweeper — only
    // non-terminal rows are ever scanned by either.
    claimIdx: index("subagent_runs_claim_idx")
      .on(t.orgId, t.status)
      .where(sql`${t.status} IN ('pending', 'running')`),
    statusCheck: check(
      "subagent_runs_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed')`,
    ),
  }),
);

// Agent execution tracking: lineage, steps, tool calls (migration 0019)
export const agentExecutions = agentSchema.table(
  "agent_executions",
  {
    ...idMixin("aex"),
    ...auditMixin(),
    ...orgScopeMixin(),
    // Nullable: dynamic supervisor runs don't have a pre-registered agent definition.
    agentId: uuid("agent_id").references(() => agents.id),
    agentVersionId: uuid("agent_version_id").references(() => agentVersions.id),
    originType: text("origin_type").notNull(),
    originId: uuid("origin_id").notNull(),
    status: text("status").notNull().default("planning"),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    estimatedCostUsd: numeric("estimated_cost_usd", {
      precision: 10,
      scale: 6,
    }),
    // AgentInstance shape (agent-schema.ts §4): self-reference for subagent/A2A
    // lineage (app-enforced, no FK).
    parentExecutionId: uuid("parent_execution_id"),
    // Live: schema.reconcile.dispatch writes reconcile progress counters here
    // and schema.reconcile.status reads them back. (The sibling `debug` column
    // was dropped in 20260802140000 — genuinely unreferenced.)
    state: jsonb("state").notNull().default(sql`'{}'::jsonb`),
  },
  (t) => ({
    orgStatusIdx: index("agent_executions_org_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    originIdx: index("agent_executions_origin_idx").on(
      t.originType,
      t.originId,
    ),
    agentIdx: index("agent_executions_agent_idx").on(t.agentId),
    // FK → agent.agent_versions. Index the FK so agent_versions mutations don't
    // seq-scan the high-write executions table (only agent_id was indexed).
    agentVersionIdx: index("agent_executions_agent_version_idx").on(
      t.agentVersionId,
    ),
    parentExecutionIdx: index("agent_executions_parent_execution_idx").on(
      t.parentExecutionId,
    ),
    createdAtIdx: index("agent_executions_created_at_idx").on(t.createdAt),
    // Activity feed / execution list (agent.execution.list.ts,
    // command.menu.search.ts — 2026-07-11 audit §4.1 item 1). Distinct from
    // orgStatusIdx above, which leads with (org_id, workspace_id, status) —
    // this composite serves the feed's created_at DESC sort directly.
    orgWsCreatedIdx: index("agent_executions_org_ws_created_idx").on(
      t.orgId,
      t.workspaceId,
      t.createdAt,
    ),
    statusCheck: check(
      "agent_executions_status_check",
      sql`${t.status} IN ('planning', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    // Mirror of the CHECK constraint that already lives in the baseline/0007
    // migrations. Declared here so the Drizzle schema can never drift from the
    // DB again — the omission let workflow.run insert "workflow.run" (dot) and
    // get rejected at runtime while typecheck/Drizzle-mock tests passed.
    // Keep in sync with AGENT_EXECUTION_ORIGIN_TYPES in
    // packages/oxagen/src/contracts/agent.execution.record.ts.
    originTypeCheck: check(
      "agent_executions_origin_type_check",
      sql`${t.originType} IN ('chat', 'event_trigger', 'scheduled_job', 'mcp_request', 'workflow_run', 'fanout', 'a2a')`,
    ),
  }),
);

export const agentExecutionSteps = agentSchema.table(
  "agent_execution_steps",
  {
    ...idMixin("aes"),
    ...auditMixin(),
    executionId: uuid("execution_id")
      .notNull()
      .references(() => agentExecutions.id),
    ...orgScopeMixin(),
    stepNumber: integer("step_number").notNull(),
    stepType: text("step_type").notNull(),
    status: text("status").notNull(),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Durable claim/lease — same semantics as subagent_runs (spec §1): a lost
    // worker's step becomes resweepable instead of stranding the execution.
    claimedBy: text("claimed_by"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    attempts: integer("attempts").notNull().default(0),
  },
  (t) => ({
    executionIdx: index("agent_execution_steps_execution_idx").on(
      t.executionId,
    ),
    orgIdx: index("agent_execution_steps_org_idx").on(t.orgId, t.workspaceId),
    claimIdx: index("agent_execution_steps_claim_idx")
      .on(t.orgId, t.status)
      .where(sql`${t.status} IN ('pending', 'running')`),
    statusCheck: check(
      "agent_execution_steps_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
  }),
);

export const agentToolCalls = agentSchema.table(
  "agent_tool_calls",
  {
    ...idMixin("atc"),
    ...auditMixin(),
    executionStepId: uuid("execution_step_id")
      .notNull()
      .references(() => agentExecutionSteps.id),
    ...orgScopeMixin(),
    toolName: text("tool_name").notNull(),
    toolType: text("tool_type").notNull(),
    requestPayload: jsonb("request_payload").notNull(),
    responsePayload: jsonb("response_payload"),
    status: text("status").notNull(),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
  },
  (t) => ({
    stepIdx: index("agent_tool_calls_step_idx").on(t.executionStepId),
    toolIdx: index("agent_tool_calls_tool_idx").on(t.toolName),
    orgIdx: index("agent_tool_calls_org_idx").on(t.orgId, t.workspaceId),
    statusCheck: check(
      "agent_tool_calls_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed')`,
    ),
  }),
);

// Durable code-agent sandbox sessions (spec §5.2 sandbox runtime).
// One row per long-lived Modal (or future driver) sandbox; sessions are
// reused across agent turns via session_key. snapshotId enables fast
// restore after idle eviction. Status lifecycle: running → idle → stopped → gone.
export const sandboxSessions = agentSchema.table(
  "sandbox_sessions",
  {
    ...idMixin("sbx"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    // Caller-supplied stable key (e.g. conversation id or agent-run id) used to
    // reuse one durable sandbox across multiple agent turns. Nullable: ephemeral
    // sandboxes (no reuse intent) carry no key.
    sessionKey: text("session_key"),
    // Sandbox driver identifier, e.g. "modal".
    driver: text("driver").notNull(),
    // Runtime image/language: node | python | shell | agent.
    image: text("image").notNull(),
    // Driver-issued live sandbox id (Modal `sb-...`). Mutable on restore.
    sandboxId: text("sandbox_id").notNull(),
    // Last filesystem snapshot id for warm restore; null before first snapshot.
    snapshotId: text("snapshot_id"),
    // Lifecycle status. DEFAULT 'running' — a row is created when the sandbox
    // starts. Transitions: running → idle (TTL timer) → stopped (explicit) → gone
    // (evicted/GC'd). CHECK constraint mirrors the IN list.
    status: text("status").notNull().default("running"),
    // Wall-clock of the most recent agent interaction (used by TTL logic).
    lastUsedAt: timestamp("last_used_at", { withTimezone: true, mode: "date" }),
    // Soft expiry: created_at + configured TTL. Null = no expiry.
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }),
    // Arbitrary driver/caller metadata (image labels, resource class, etc.).
    metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
    // ── Session lifecycle & work-recovery (spec: sandbox-session-lifecycle) ──
    // Reap-eligible instant = last_used_at + grace; written when a turn releases
    // the session to 'idle'. NULL while a turn is active ('running'), so the
    // idle-grace reaper only ever considers genuinely released sessions.
    graceDeadlineAt: timestamp("grace_deadline_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Work-safety state, orthogonal to `status`. The reaper MUST capture
    // uncommitted work to a recovery branch before it may flush a dirty sandbox;
    // this column is the audit trail of that guarantee.
    // none → pending → recovering → recovered | failed.
    recoveryStatus: text("recovery_status").notNull().default("none"),
    // Branch/commit the reaper pushed uncommitted work to (file recovery).
    recoveryBranch: text("recovery_branch"),
    recoveryCommit: text("recovery_commit"),
    // Failure reason when recovery_status='failed' — the sandbox is RETAINED
    // (never flushed) so the work can still be recovered manually or next tick.
    recoveryError: text("recovery_error"),
    recoveredAt: timestamp("recovered_at", {
      withTimezone: true,
      mode: "date",
    }),
    // When the reaper terminated the sandbox (distinct from an explicit stop).
    flushedAt: timestamp("flushed_at", { withTimezone: true, mode: "date" }),
    // Last-observed uncommitted-changes state (NULL = never checked). Powers the
    // inspector's dirty indicator; the reaper always re-checks live before flush.
    dirty: boolean("dirty"),
    dirtyCheckedAt: timestamp("dirty_checked_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => ({
    orgIdx: index("sandbox_sessions_org_idx").on(t.orgId, t.workspaceId),
    statusIdx: index("sandbox_sessions_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    // At most one live durable sandbox per (workspace, sessionKey).
    sessionKeyUniq: uniqueIndex("sandbox_sessions_session_key_uniq")
      .on(t.workspaceId, t.sessionKey)
      .where(
        sql`session_key IS NOT NULL AND status IN ('running','idle') AND deleted_at IS NULL`,
      ),
    // Reaper candidate scan: idle sessions past their grace deadline that the
    // reaper has not yet flushed. Partial to stay tiny (only live-but-idle rows).
    reapIdx: index("sandbox_sessions_reap_idx")
      .on(t.graceDeadlineAt)
      .where(sql`flushed_at IS NULL AND grace_deadline_at IS NOT NULL`),
    statusCheck: check(
      "sandbox_sessions_status_check",
      sql`${t.status} IN ('running','idle','stopped','gone')`,
    ),
    recoveryStatusCheck: check(
      "sandbox_sessions_recovery_status_check",
      sql`${t.recoveryStatus} IN ('none','pending','recovering','recovered','failed')`,
    ),
    imageCheck: check(
      "sandbox_sessions_image_check",
      sql`${t.image} IN ('node','python','shell','agent')`,
    ),
  }),
);

// Agent plans: structured execution plans with approval gates.
// Status flow: draft → awaiting_approval → approved | denied | amended → executing → completed.
// Plans are immutable after approval.
export const agentPlans = agentSchema.table(
  "agent_plans",
  {
    ...idMixin("apl"),
    ...auditMixin(),
    ...orgScopeMixin(),
    status: text("status").notNull().default("draft"),
    goals: jsonb("goals").notNull().default(sql`'[]'::jsonb`),
    constraints: jsonb("constraints").notNull().default(sql`'[]'::jsonb`),
    tasks: jsonb("tasks").notNull().default(sql`'[]'::jsonb`),
    approvalRequired: boolean("approval_required").notNull().default(true),
    messageId: uuid("message_id"),
    approvedAt: timestamp("approved_at", { withTimezone: true, mode: "date" }),
    approvedByUserId: uuid("approved_by_user_id"),
    taskCount: integer("task_count").notNull().default(0),
  },
  (t) => ({
    orgStatusIdx: index("agent_plans_org_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    orgIdx: index("agent_plans_org_idx").on(t.orgId, t.workspaceId),
    messageIdx: index("agent_plans_message_idx").on(t.messageId),
    statusCheck: check(
      "agent_plans_status_check",
      sql`${t.status} IN ('draft', 'awaiting_approval', 'approved', 'denied', 'amended', 'executing', 'completed')`,
    ),
  }),
);

// A2A (Agent2Agent) protocol tasks — durable state for the A2A transport
// surface (POST /a2a JSON-RPC, alongside /mcp). One row per A2A task. The
// external `public_id` (a2a_...) is the opaque `taskId` A2A clients see; the
// caller-supplied A2A `contextId` groups tasks in one multi-turn conversation.
// State uses the A2A lowercase wire strings (submitted/working/…); the CHECK
// mirrors the A2A_TASK_STATES list. message_history and artifacts are stored as
// the exact A2A wire JSON so tasks/get can round-trip them without translation.
export const a2aTasks = agentSchema.table(
  "a2a_tasks",
  {
    ...idMixin("a2a"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    // A2A conversation-grouping id (opaque; caller-supplied or server-minted).
    contextId: text("context_id").notNull(),
    // A2A task lifecycle state (lowercase wire string). DEFAULT 'submitted'.
    state: text("state").notNull().default("submitted"),
    // The A2A Message[] history (user turn + agent reply) as wire JSON.
    messageHistory: jsonb("message_history")
      .notNull()
      .default(sql`'[]'::jsonb`),
    // The A2A Artifact[] produced by the agent as wire JSON.
    artifacts: jsonb("artifacts").notNull().default(sql`'[]'::jsonb`),
    // The current TaskStatus.message (agent-facing status text), if any.
    statusMessage: jsonb("status_message"),
    // Terminal error detail for failed/rejected tasks (null otherwise).
    errorMessage: text("error_message"),
    // Arbitrary caller/agent metadata carried on the task.
    metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
    // Which agent this task is/was addressed to (routing input — the
    // resolved skillId target). App-enforced ref to agent.agents.id; null
    // when the task ran the generic chat baseline (no skillId, or an
    // unknown/inactive one, which falls back rather than 500ing).
    agentId: uuid("agent_id"),
  },
  (t) => ({
    orgIdx: index("a2a_tasks_org_idx").on(t.orgId, t.workspaceId),
    contextIdx: index("a2a_tasks_context_idx").on(t.workspaceId, t.contextId),
    stateIdx: index("a2a_tasks_state_idx").on(t.orgId, t.workspaceId, t.state),
    // "List this agent's A2A tasks" — paginated per performance conventions.
    agentIdx: index("a2a_tasks_agent_idx").on(
      t.orgId,
      t.workspaceId,
      t.agentId,
    ),
    stateCheck: check(
      "a2a_tasks_state_check",
      sql`${t.state} IN ('submitted','working','input-required','auth-required','completed','canceled','failed','rejected','unknown')`,
    ),
  }),
);

// ── File locks — the transactional lock authority (ADR-021 §5) ──────────────
//
// File locks are mutual-exclusion state, so Postgres is the source of truth,
// NOT Neo4j: eventual graph projection cannot provide mutual exclusion. These
// transactional rows are the sole file-lock authority.
//
// This extends the Inngest claim/lease mechanism (subagent_runs / execution
// steps above) to file-path granularity rather than inventing a second lock
// system: atomic acquire (advisory-lock + conditional upsert), TTL expiry, and
// a monotonic fencing token per resource so a stale lease-holder's late write
// is rejected at write time (verifyFileLease). One live lock per
// (workspace, resource_key) is enforced by the partial unique index.
export const fileLocks = agentSchema.table(
  "file_locks",
  {
    ...idMixin("flk"),
    ...auditMixin(),
    ...orgScopeMixin(),
    // Normalized resource identity — a repo-relative path (local CLI) or a
    // repository-scoped github:{owner}/{repo}:{path} key (platform).
    resourceKey: text("resource_key").notNull(),
    // Identity of the lock holder — an agent/session/mission/fleet-task id. Two
    // concurrent holders MUST pass different values to see each other as
    // conflicting; re-acquiring under the SAME holder renews instead of racing.
    holder: text("holder").notNull(),
    // Correlates every lock a turn/execution holds, for batch release-by-execution.
    executionId: text("execution_id").notNull(),
    // Monotonic per (workspace_id, resource_key), sourced from file_lock_fences
    // (below). A takeover after expiry always issues a strictly higher token, so
    // the previous holder's late write fails verifyFileLease.
    fencingToken: bigint("fencing_token", { mode: "number" }).notNull(),
    action: text("action").notNull().default("write"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }).notNull(),
    // Soft-release marker (NOT a soft delete): the partial unique index below
    // keys off it, so releasing frees the resource while keeping the row for a
    // final projection. Expired-but-unreleased rows are treated as free by
    // acquire (takeover) and reaped by sweepExpiredFileLeases.
    releasedAt: timestamp("released_at", { withTimezone: true, mode: "date" }),
  },
  (t) => ({
    // At most ONE live lock per resource per workspace — the core invariant.
    activeUniq: uniqueIndex("file_locks_active_uniq")
      .on(t.workspaceId, t.resourceKey)
      .where(sql`released_at IS NULL`),
    orgIdx: index("file_locks_org_idx").on(t.orgId, t.workspaceId),
    // Batch release-by-execution (turn-end backstop) scans by execution_id.
    executionIdx: index("file_locks_execution_idx")
      .on(t.orgId, t.executionId)
      .where(sql`released_at IS NULL`),
    actionCheck: check(
      "file_locks_action_check",
      sql`${t.action} IN ('read', 'write')`,
    ),
  }),
);

// Durable, monotonic fencing-token counter per resource. Lives in its own table
// (not derived from file_locks) precisely so the counter SURVIVES release: a
// lock row can be released/reaped, but the next acquirer of the same resource
// must still receive a strictly higher token than any prior holder ever held.
// Bumped only on a SUCCESSFUL acquire (INSERT ... ON CONFLICT DO UPDATE
// current_token + 1); a denied acquire never advances it.
export const fileLockFences = agentSchema.table(
  "file_lock_fences",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    resourceKey: text("resource_key").notNull(),
    currentToken: bigint("current_token", { mode: "number" })
      .notNull()
      .default(0),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    resourceUniq: uniqueIndex("file_lock_fences_resource_uniq").on(
      t.workspaceId,
      t.resourceKey,
    ),
    orgIdx: index("file_lock_fences_org_idx").on(t.orgId, t.workspaceId),
  }),
);

// ── Durable agent runs (agent-engine v2 Phase 2a; docs/specs/agent-engine-v2)
//
// The run row that packages/agent-runner's executeTurn persists to starting
// in Phase 2 (plan.md): one row per turn, across every surface. `surface`
// mirrors agent-runner's PlatformSurface union (execute-turn.ts) so the row
// and the seam can never drift into two vocabularies for the same thing.
//
// Durable claim/lease trio (claimedBy/leaseExpiresAt/attempts) is the same
// discipline as subagentRuns above: claimedBy is the owning worker's identity,
// a null lease means unclaimed-or-terminal, and the lease sweeper requeues
// expired-lease rows until the attempt cap so a killed worker's run is
// reclaimed without a coordinator. One deliberate difference from
// subagentRuns: the claim query here is cross-org — a small dedicated worker
// pool claims ANY pending run via withSystemDb + FOR UPDATE SKIP LOCKED, not
// one org's queue — so agent_runs_claim_idx (below) carries no org_id prefix.
//
// `spec` is the serialized RunSpec (instruction, model, option snapshot) —
// data only, never the live engine ports/callbacks a worker constructs
// in-process from it. `checkpoint`/`checkpointSeq` hold the LATEST checkpoint
// only (messages digest + budget/oracle/loop state, one transaction with the
// event append per plan.md Phase 2); the full history is agent_run_events.
export const agentRuns = agentSchema.table(
  "agent_runs",
  {
    ...idMixin("arun"),
    ...orgScopeMixin(),
    ...auditMixin(),
    surface: text("surface").notNull(),
    status: text("status").notNull().default("pending"),
    spec: jsonb("spec").notNull(),
    // Durable claim/lease — see module comment above.
    claimedBy: text("claimed_by"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    attempts: integer("attempts").notNull().default(0),
    // Latest checkpoint only; append-only history lives in agent_run_events.
    checkpoint: jsonb("checkpoint"),
    checkpointSeq: integer("checkpoint_seq").notNull().default(0),
    result: jsonb("result"),
    error: text("error"),
    // Set by the cancel path; the worker observes this and drops the run
    // future (Stella-style structured cancellation, spec.md §4.2) instead of
    // being torn down out-of-band.
    cancelRequested: boolean("cancel_requested").notNull().default(false),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),

    // ── RunSpecV2 typed identity (docs/specs/run-evidence-ingress) ───────────
    //
    // The V1/V2 discriminant. Existing rows backfill to 1 via the column
    // default; a governed V2 admission writes 2 and must then supply the
    // COMPLETE typed set below (agent_runs_v2_identity_check). Every column
    // here is nullable at the column level on purpose: `agent_runs` already
    // holds V1 history that has no trusted principal, repository, or retention
    // binding, and fabricating one for a historical row is exactly what the
    // expand-only rule forbids. Completeness is a conditional CHECK, not a
    // column-level NOT NULL.
    //
    // These are duplicated OUT of `spec` deliberately: security queries and the
    // worker's row/spec identity comparison must not depend on untyped JSON
    // extraction (spec.md §"Trusted run and attempt identity").
    specVersion: integer("spec_version").notNull().default(1),
    runKind: text("run_kind"),
    // RFC 8785 canonical digest of the serialized RunSpecV2.
    specDigest: text("spec_digest"),
    // Actor binding: the authenticated human who delegated the run and the
    // deployed-agent principal acting for them. NOT agents.parentUserId.
    initiatingPrincipalId: uuid("initiating_principal_id"),
    agentPrincipalId: uuid("agent_principal_id"),
    agentId: uuid("agent_id"),
    agentVersionId: uuid("agent_version_id"),
    agentVersionChecksum: text("agent_version_checksum"),
    // Digest-addressed pinned grant ceiling (iam.authorization_snapshots).
    authorizationSnapshotId: uuid("authorization_snapshot_id"),
    // Child runs narrow their parent's ceiling; a root run is null.
    parentRunId: uuid("parent_run_id"),
    // Immutable repository binding plus the copies admission resolved from it.
    // The copies are not redundancy for its own sake: the binding row is
    // versioned, and the run must prove which version it saw.
    repositoryBindingId: uuid("repository_binding_id"),
    repositoryProvider: text("repository_provider"),
    providerRepositoryId: text("provider_repository_id"),
    repositoryConnectionId: uuid("repository_connection_id"),
    configuredDefaultRef: text("configured_default_ref"),
    baseCommitSha: text("base_commit_sha"),
    baseTreeSha: text("base_tree_sha"),
    // Immutable retention-policy version pinned at admission — both the public
    // identity and its canonical digest, so a swapped row is detectable.
    retentionPolicyId: uuid("retention_policy_id"),
    retentionPolicyDigest: text("retention_policy_digest"),
    // Trusted engine policy. `attempts` above stays the V1 counter; V2 bounds
    // retries against this pinned ceiling.
    maxAttempts: integer("max_attempts"),

    // ── Operational V2 pointers (mutable; see the immutability trigger) ──────
    // The attempt currently holding a live lease, null between attempts.
    activeAttemptId: uuid("active_attempt_id"),
    // Newest committed checkpoint, for successor restore.
    latestCheckpointId: uuid("latest_checkpoint_id"),
    // Number of attempts ever created for this run, bounded by max_attempts.
    attemptCount: integer("attempt_count").notNull().default(0),
    // Next run-global event sequence to allocate. PostgreSQL-assigned inside
    // the append transaction (not a SEQUENCE object — the allocation must roll
    // back with the append). Monotonic ACROSS attempts, unlike attempt_seq.
    nextRunSeq: bigint("next_run_seq", { mode: "number" }).notNull().default(1),
  },
  (t) => ({
    orgIdx: index("agent_runs_org_idx").on(t.orgId, t.workspaceId),
    // Cross-org on purpose (see module comment): the claim UPDATE and the
    // lease sweeper scan across every tenant, so org_id would only shrink this
    // index without ever appearing in their WHERE clause.
    claimIdx: index("agent_runs_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`${t.status} IN ('pending', 'running')`),
    // V2 claim dispatch: the V2 worker path claims only spec_version = 2 rows,
    // and the V1 compatibility path only spec_version = 1, so neither scans
    // the other's queue while both drain.
    v2ClaimIdx: index("agent_runs_v2_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`spec_version = 2 AND status IN ('pending', 'running')`),
    // Security lookups by trusted identity (who ran what, under which snapshot).
    v2ActorIdx: index("agent_runs_v2_actor_idx")
      .on(t.orgId, t.workspaceId, t.initiatingPrincipalId, t.agentPrincipalId)
      .where(sql`spec_version = 2`),
    parentRunIdx: index("agent_runs_parent_run_idx")
      .on(t.parentRunId)
      .where(sql`parent_run_id IS NOT NULL`),
    surfaceCheck: check(
      "agent_runs_surface_check",
      sql`${t.surface} IN ('chat', 'api-chat', 'a2a', 'repo-edit')`,
    ),
    statusCheck: check(
      "agent_runs_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    specVersionCheck: check(
      "agent_runs_spec_version_check",
      sql`${t.specVersion} IN (1, 2)`,
    ),
    // The V1/V2 discriminant. A preserved V1 row carries NONE of the typed V2
    // identity; a V2 row carries ALL of it. There is no partially-bound run.
    v2IdentityCheck: check(
      "agent_runs_v2_identity_check",
      sql`(
        ${t.specVersion} = 1
        AND ${t.runKind} IS NULL
        AND ${t.specDigest} IS NULL
        AND ${t.initiatingPrincipalId} IS NULL
        AND ${t.agentPrincipalId} IS NULL
        AND ${t.agentId} IS NULL
        AND ${t.agentVersionId} IS NULL
        AND ${t.agentVersionChecksum} IS NULL
        AND ${t.authorizationSnapshotId} IS NULL
        AND ${t.repositoryBindingId} IS NULL
        AND ${t.repositoryProvider} IS NULL
        AND ${t.providerRepositoryId} IS NULL
        AND ${t.repositoryConnectionId} IS NULL
        AND ${t.configuredDefaultRef} IS NULL
        AND ${t.baseCommitSha} IS NULL
        AND ${t.baseTreeSha} IS NULL
        AND ${t.retentionPolicyId} IS NULL
        AND ${t.retentionPolicyDigest} IS NULL
        AND ${t.maxAttempts} IS NULL
      ) OR (
        ${t.specVersion} = 2
        AND ${t.runKind} IS NOT NULL
        AND ${t.specDigest} IS NOT NULL
        AND ${t.initiatingPrincipalId} IS NOT NULL
        AND ${t.agentPrincipalId} IS NOT NULL
        AND ${t.agentId} IS NOT NULL
        AND ${t.agentVersionId} IS NOT NULL
        AND ${t.agentVersionChecksum} IS NOT NULL
        AND ${t.authorizationSnapshotId} IS NOT NULL
        AND ${t.repositoryBindingId} IS NOT NULL
        AND ${t.repositoryProvider} IS NOT NULL
        AND ${t.providerRepositoryId} IS NOT NULL
        AND ${t.repositoryConnectionId} IS NOT NULL
        AND ${t.configuredDefaultRef} IS NOT NULL
        AND ${t.baseCommitSha} IS NOT NULL
        AND ${t.baseTreeSha} IS NOT NULL
        AND ${t.retentionPolicyId} IS NOT NULL
        AND ${t.retentionPolicyDigest} IS NOT NULL
        AND ${t.maxAttempts} IS NOT NULL
      )`,
    ),
    runKindCheck: check(
      "agent_runs_run_kind_check",
      sql`${t.runKind} IS NULL OR ${t.runKind} IN ('general', 'repo_edit')`,
    ),
    specDigestCheck: check(
      "agent_runs_spec_digest_check",
      sql`${t.specDigest} IS NULL OR ${t.specDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    retentionDigestCheck: check(
      "agent_runs_retention_digest_check",
      sql`${t.retentionPolicyDigest} IS NULL OR ${t.retentionPolicyDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    maxAttemptsCheck: check(
      "agent_runs_max_attempts_check",
      sql`${t.maxAttempts} IS NULL OR ${t.maxAttempts} > 0`,
    ),
    attemptCountCheck: check(
      "agent_runs_attempt_count_check",
      sql`${t.attemptCount} >= 0 AND (${t.maxAttempts} IS NULL OR ${t.attemptCount} <= ${t.maxAttempts})`,
    ),
    nextRunSeqCheck: check(
      "agent_runs_next_run_seq_check",
      sql`${t.nextRunSeq} >= 1`,
    ),
    // A run may not be its own parent — the cheapest half of cycle prevention
    // (deeper cycles are prevented by the snapshot-narrowing rule in IAM).
    parentRunCheck: check(
      "agent_runs_parent_run_check",
      sql`${t.parentRunId} IS NULL OR ${t.parentRunId} <> ${t.id}`,
    ),
  }),
);

// Append-only event log for agent_runs — the canonical source for resumable
// SSE subscriptions, ClickHouse ingestion, and ADR-028 replay (spec.md §4.2:
// "the event log is canonical"). Immutable child, same shape discipline as
// file_lock_fences above: bare uuid pk (no idMixin/public_id — nothing
// external addresses one event row directly) and no updatedAt. `seq` is
// app-assigned and monotonic per run starting at 1 — deliberately NOT a
// serial/identity column, so the worker can assert the exact next value in
// the same transaction as the checkpoint write (`UNIQUE(run_id, seq)` below
// turns a racing double-append into a constraint violation, not silent
// duplication).
// V2 (docs/specs/run-evidence-ingress) adds a second record shape to this same
// table rather than a second log: `event_record_version` is the discriminant, 1
// for every preserved legacy row and 2 for a fenced-attempt event. The legacy
// `seq/type/payload` columns became nullable so a V2 row can leave them empty,
// and the old full `UNIQUE(run_id, seq)` was replaced by three PARTIAL unique
// indexes — V1 `(run_id, seq)`, V2 `(run_id, run_seq)`, V2 `(attempt_id,
// attempt_seq)` — so a V2 row can never be read as legacy and vice versa. A
// leftover full unique on `(run_id, seq)` would defeat the discriminant, which
// is why the migration drops it explicitly.
export const agentRunEvents = agentSchema.table(
  "agent_run_events",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    // No cross-schema FK to agent_runs — app-enforced per CLAUDE.md storage
    // rules (same convention as fileLocks.executionId etc. above).
    runId: uuid("run_id").notNull(),
    // 1 = legacy run-global record, 2 = fenced attempt record. Existing rows
    // backfill to 1 through the column default.
    eventRecordVersion: smallint("event_record_version").notNull().default(1),
    // ── V1 legacy columns (required for V1, NULL for V2) ─────────────────────
    seq: integer("seq"),
    type: text("type"),
    payload: jsonb("payload"),
    // `created_at` is the RECORDED time for both record versions — the instant
    // Postgres accepted the append. V2 additionally carries the producer's
    // `observed_at`; the two differ by transport and buffering latency and the
    // event digest commits to the observed one.
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),

    // ── V2 fenced-attempt columns (required for V2, NULL for V1) ─────────────
    // The immutable attempt this event belongs to. Without it a reclaimed run's
    // events interleave across executions with no stable identity.
    attemptId: uuid("attempt_id"),
    // Monotonic across attempts, allocated from agent_runs.next_run_seq inside
    // the append transaction. Drives resumable SSE subscriptions.
    runSeq: bigint("run_seq", { mode: "number" }),
    // Producer-assigned, contiguous, and reset to 1 for each new attempt.
    // Drives unambiguous replay.
    attemptSeq: integer("attempt_seq"),
    eventSchemaVersion: text("event_schema_version"),
    eventType: text("event_type"),
    // One of the nine evidence stages (EVIDENCE_STAGES in
    // schema/run-evidence-foundation.ts).
    stage: text("stage"),
    // Digest of the canonical payload bytes, whether inline or encrypted.
    payloadDigest: text("payload_digest"),
    // Digest over (attempt_seq, schema, type, stage, payload_digest,
    // observed_at). Identical sequence + identical digest is idempotent;
    // identical sequence + different digest is a security event.
    eventDigest: text("event_digest"),
    // EXACTLY ONE of these two carries the body. Inline is allow-listed receipt
    // metadata only; anything large or sensitive is an encrypted blob reference
    // (an `evb_` public id — app-enforced text, the blob index lands in the
    // evidence-ledger PR).
    payloadInline: jsonb("payload_inline"),
    encryptedPayloadRef: text("encrypted_payload_ref"),
    observedAt: timestamp("observed_at", { withTimezone: true, mode: "date" }),
  },
  (t) => ({
    // Partial: legacy rows only. Replaces the former full
    // UNIQUE(run_id, seq) constraint, which would otherwise collide every V2
    // row on (run_id, NULL) semantics and blur the discriminant.
    v1RunSeqUniq: uniqueIndex("agent_run_events_v1_run_seq_uq")
      .on(t.runId, t.seq)
      .where(sql`event_record_version = 1`),
    v2RunSeqUniq: uniqueIndex("agent_run_events_v2_run_seq_uq")
      .on(t.runId, t.runSeq)
      .where(sql`event_record_version = 2`),
    v2AttemptSeqUniq: uniqueIndex("agent_run_events_v2_attempt_seq_uq")
      .on(t.attemptId, t.attemptSeq)
      .where(sql`event_record_version = 2`),
    orgIdx: index("agent_run_events_org_idx").on(t.orgId, t.workspaceId),
    recordVersionCheck: check(
      "agent_run_events_record_version_check",
      sql`${t.eventRecordVersion} IN (1, 2)`,
    ),
    // The discriminant, spelled out. A V1 row is exactly the legacy shape with
    // every V2 field null; a V2 row is exactly the attempt shape with every
    // legacy field null. Nothing in between is representable.
    recordShapeCheck: check(
      "agent_run_events_record_shape_check",
      sql`(
        ${t.eventRecordVersion} = 1
        AND ${t.seq} IS NOT NULL
        AND ${t.type} IS NOT NULL
        AND ${t.payload} IS NOT NULL
        AND ${t.attemptId} IS NULL
        AND ${t.runSeq} IS NULL
        AND ${t.attemptSeq} IS NULL
        AND ${t.eventSchemaVersion} IS NULL
        AND ${t.eventType} IS NULL
        AND ${t.stage} IS NULL
        AND ${t.payloadDigest} IS NULL
        AND ${t.eventDigest} IS NULL
        AND ${t.payloadInline} IS NULL
        AND ${t.encryptedPayloadRef} IS NULL
        AND ${t.observedAt} IS NULL
      ) OR (
        ${t.eventRecordVersion} = 2
        AND ${t.seq} IS NULL
        AND ${t.type} IS NULL
        AND ${t.payload} IS NULL
        AND ${t.attemptId} IS NOT NULL
        AND ${t.runSeq} IS NOT NULL
        AND ${t.attemptSeq} IS NOT NULL
        AND ${t.eventSchemaVersion} IS NOT NULL
        AND ${t.eventType} IS NOT NULL
        AND ${t.stage} IS NOT NULL
        AND ${t.payloadDigest} IS NOT NULL
        AND ${t.eventDigest} IS NOT NULL
        AND ${t.observedAt} IS NOT NULL
        AND (${t.payloadInline} IS NULL) <> (${t.encryptedPayloadRef} IS NULL)
      )`,
    ),
    stageCheck: check(
      "agent_run_events_stage_check",
      sql`${t.stage} IS NULL OR ${t.stage} IN ('admission', 'checkout', 'context', 'model', 'tool', 'change', 'verification', 'provider_publish', 'terminal')`,
    ),
    seqBoundsCheck: check(
      "agent_run_events_seq_bounds_check",
      sql`(${t.runSeq} IS NULL OR ${t.runSeq} >= 1) AND (${t.attemptSeq} IS NULL OR ${t.attemptSeq} >= 1) AND (${t.seq} IS NULL OR ${t.seq} >= 1)`,
    ),
    digestCheck: check(
      "agent_run_events_digest_check",
      sql`(${t.payloadDigest} IS NULL OR ${t.payloadDigest} ~ '^sha256:[0-9a-f]{64}$') AND (${t.eventDigest} IS NULL OR ${t.eventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable attempt identity (docs/specs/run-evidence-ingress) ─────────────
//
// One row per successful V2 worker claim, created BEFORE any model or tool
// work. `arat_` is the public identity every API boundary and evidence receipt
// uses. The resolved engine name/version/build digest is pinned here rather
// than read back from a live worker, so evidence names the exact binary that
// executed. A successor that restores an earlier attempt's checkpoint records
// the complete restore tuple and keeps its OWN attempt identity — attempt IDs
// are never reused (spec.md §"Attempt identity").
//
// Immutable: append-only audit columns and the migration revokes UPDATE/DELETE.
export const agentRunAttempts = agentSchema.table(
  "agent_run_attempts",
  {
    ...idMixin("arat"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    // 1-based, dense, and unique per run — the retry counter the pinned
    // max_attempts ceiling bounds.
    attemptNumber: integer("attempt_number").notNull(),
    // Identity of the claiming worker process (same vocabulary as
    // agent_runs.claimed_by).
    workerId: text("worker_id").notNull(),
    claimedAt: timestamp("claimed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    engineName: text("engine_name").notNull(),
    engineVersion: text("engine_version").notNull(),
    // Build or container-image digest of the engine that actually ran.
    engineBuildDigest: text("engine_build_digest").notNull(),
    // ── Restore tuple: all four present, or all four absent ──────────────────
    resumedFromAttemptId: uuid("resumed_from_attempt_id"),
    resumedFromAttemptPublicId: citext("resumed_from_attempt_public_id"),
    restoredCheckpointId: uuid("restored_checkpoint_id"),
    restoredCheckpointDigest: text("restored_checkpoint_digest"),
  },
  (t) => ({
    runAttemptUniq: uniqueIndex("agent_run_attempts_run_attempt_uq").on(
      t.runId,
      t.attemptNumber,
    ),
    orgIdx: index("agent_run_attempts_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempts_run_idx").on(t.runId),
    attemptNumberCheck: check(
      "agent_run_attempts_attempt_number_check",
      sql`${t.attemptNumber} >= 1`,
    ),
    // A partial restore reference cannot prove provenance, so the tuple is
    // all-or-nothing.
    restoreTupleCheck: check(
      "agent_run_attempts_restore_tuple_check",
      sql`(
        ${t.resumedFromAttemptId} IS NULL
        AND ${t.resumedFromAttemptPublicId} IS NULL
        AND ${t.restoredCheckpointId} IS NULL
        AND ${t.restoredCheckpointDigest} IS NULL
      ) OR (
        ${t.resumedFromAttemptId} IS NOT NULL
        AND ${t.resumedFromAttemptPublicId} IS NOT NULL
        AND ${t.restoredCheckpointId} IS NOT NULL
        AND ${t.restoredCheckpointDigest} IS NOT NULL
      )`,
    ),
    // A successor may never restore from itself.
    restoreSelfCheck: check(
      "agent_run_attempts_restore_self_check",
      sql`${t.resumedFromAttemptId} IS NULL OR ${t.resumedFromAttemptId} <> ${t.id}`,
    ),
    digestCheck: check(
      "agent_run_attempts_digest_check",
      sql`${t.engineBuildDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.restoredCheckpointDigest} IS NULL OR ${t.restoredCheckpointDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Mutable fenced lease (one per attempt) ───────────────────────────────────
//
// The ONLY mutable row in the attempt foundation, and the reason the plan calls
// operational lease state "the exception": renew, append, and seal all update
// it. It still denies DELETE — a fenced lease is evidence that an attempt lost
// its claim, not garbage to collect.
//
// `lease_epoch` is the fencing token: unique per (run, epoch) and strictly
// increasing, so a stale worker's late append is rejected at write time exactly
// like agent.file_lock_fences does for file locks. `fenced_at` is the tombstone
// the old attempt observes before it may perform any further mutation.
export const agentRunAttemptLeases = agentSchema.table(
  "agent_run_attempt_leases",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    attemptId: uuid("attempt_id").notNull(),
    runId: uuid("run_id").notNull(),
    // Opaque bearer token the worker echoes on every fenced operation. Never
    // derived from the attempt id — a leaked attempt id must not grant writes.
    leaseToken: text("lease_token").notNull(),
    leaseEpoch: bigint("lease_epoch", { mode: "number" }).notNull(),
    workerId: text("worker_id").notNull(),
    expiresAt: timestamp("expires_at", {
      withTimezone: true,
      mode: "date",
    }).notNull(),
    renewedAt: timestamp("renewed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    fencedAt: timestamp("fenced_at", { withTimezone: true, mode: "date" }),
    fencedReason: text("fenced_reason"),
    // Advanced in the same transaction as the append, so the lease is the live
    // pointer a successor and the finalizer both read.
    lastRunSeq: bigint("last_run_seq", { mode: "number" }),
    lastAttemptSeq: integer("last_attempt_seq"),
    eventCount: integer("event_count").notNull().default(0),
    finalEventDigest: text("final_event_digest"),
    // Running digest over the ordered (attempt_seq, schema, type,
    // payload_digest) tuples — the value the seal commits to.
    eventStreamDigest: text("event_stream_digest"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // Exactly one lease per attempt — a second claim must create a new attempt.
    attemptUniq: uniqueIndex("agent_run_attempt_leases_attempt_uq").on(
      t.attemptId,
    ),
    // The fencing invariant: an epoch is consumed once per run.
    runEpochUniq: uniqueIndex("agent_run_attempt_leases_run_epoch_uq").on(
      t.runId,
      t.leaseEpoch,
    ),
    orgIdx: index("agent_run_attempt_leases_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
    // Lease-sweeper scan: live (unfenced) leases ordered by expiry. Partial so
    // it stays proportional to running work, not to history.
    sweepIdx: index("agent_run_attempt_leases_sweep_idx")
      .on(t.expiresAt)
      .where(sql`fenced_at IS NULL`),
    epochCheck: check(
      "agent_run_attempt_leases_epoch_check",
      sql`${t.leaseEpoch} >= 1`,
    ),
    fenceCheck: check(
      "agent_run_attempt_leases_fence_check",
      sql`(${t.fencedAt} IS NULL AND ${t.fencedReason} IS NULL) OR (${t.fencedAt} IS NOT NULL AND ${t.fencedReason} IS NOT NULL)`,
    ),
    eventCountCheck: check(
      "agent_run_attempt_leases_event_count_check",
      sql`${t.eventCount} >= 0 AND (${t.eventCount} = 0) = (${t.finalEventDigest} IS NULL)`,
    ),
    digestCheck: check(
      "agent_run_attempt_leases_digest_check",
      sql`(${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$') AND (${t.eventStreamDigest} IS NULL OR ${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable checkpoints ────────────────────────────────────────────────────
//
// Written in the SAME transaction as the append it terminates, bound to that
// final event. Engine state itself is never stored here — it is a tenant-
// encrypted blob referenced by public id, so a checkpoint row carries identity
// and digests only.
//
// No public id by design: nothing external addresses one checkpoint. What
// travels is `checkpoint_digest`, which the restoring successor records.
export const agentRunCheckpoints = agentSchema.table(
  "agent_run_checkpoints",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    // The final event of the append this checkpoint terminates.
    eventId: uuid("event_id").notNull(),
    attemptSeq: integer("attempt_seq").notNull(),
    runSeq: bigint("run_seq", { mode: "number" }).notNull(),
    // Version of the engine-state serialization, so a restore can refuse an
    // incompatible checkpoint rather than mis-parse it.
    engineStateSchema: text("engine_state_schema").notNull(),
    checkpointDigest: text("checkpoint_digest").notNull(),
    // The attempt's stream digest as of this checkpoint — restoring a
    // checkpoint restores a provable position in the event stream.
    streamDigest: text("stream_digest").notNull(),
    // `evb_` public id of the tenant-encrypted engine-state blob.
    encryptedStateRef: text("encrypted_state_ref").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    attemptSeqUniq: uniqueIndex("agent_run_checkpoints_attempt_seq_uq").on(
      t.attemptId,
      t.attemptSeq,
    ),
    // One checkpoint per event at most — the append transaction inserts either
    // zero or one.
    eventUniq: uniqueIndex("agent_run_checkpoints_event_uq").on(t.eventId),
    orgIdx: index("agent_run_checkpoints_org_idx").on(t.orgId, t.workspaceId),
    runSeqIdx: index("agent_run_checkpoints_run_seq_idx").on(t.runId, t.runSeq),
    seqCheck: check(
      "agent_run_checkpoints_seq_check",
      sql`${t.attemptSeq} >= 1 AND ${t.runSeq} >= 1`,
    ),
    digestCheck: check(
      "agent_run_checkpoints_digest_check",
      sql`${t.checkpointDigest} ~ '^sha256:[0-9a-f]{64}$' AND ${t.streamDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
  }),
);

// ── Immutable attempt seals ──────────────────────────────────────────────────
//
// One row per terminated attempt, for EVERY terminal outcome including normal
// completion — that is what closes the crash window between "finished" and
// "finalized". A truly zero-event abandoned attempt seals with event_count = 0,
// a NULL final-event digest, and the canonical empty stream digest; it never
// invents a terminal event to satisfy the shape.
export const agentRunAttemptSeals = agentSchema.table(
  "agent_run_attempt_seals",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    terminalStatus: text("terminal_status").notNull(),
    reasonCode: text("reason_code"),
    eventCount: integer("event_count").notNull(),
    finalRunSeq: bigint("final_run_seq", { mode: "number" }),
    finalAttemptSeq: integer("final_attempt_seq"),
    finalEventDigest: text("final_event_digest"),
    // Always present: the canonical empty-stream digest when event_count = 0.
    eventStreamDigest: text("event_stream_digest").notNull(),
    sealerKind: text("sealer_kind").notNull(),
    sealerWorkerId: text("sealer_worker_id").notNull(),
    sealedAt: timestamp("sealed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // An attempt seals exactly once — this uniqueness is what makes the
    // seal/grant/obligation transaction idempotent under duplicate sweeps.
    attemptUniq: uniqueIndex("agent_run_attempt_seals_attempt_uq").on(
      t.attemptId,
    ),
    orgIdx: index("agent_run_attempt_seals_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempt_seals_run_idx").on(t.runId),
    terminalStatusCheck: check(
      "agent_run_attempt_seals_terminal_status_check",
      sql`${t.terminalStatus} IN ('completed', 'failed', 'cancelled', 'denied', 'abandoned')`,
    ),
    sealerKindCheck: check(
      "agent_run_attempt_seals_sealer_kind_check",
      sql`${t.sealerKind} IN ('worker', 'reclaimer')`,
    ),
    // Zero-event seals carry no final-event evidence; non-zero seals carry all
    // of it. Anything else is an unprovable claim about the stream.
    eventEvidenceCheck: check(
      "agent_run_attempt_seals_event_evidence_check",
      sql`(
        ${t.eventCount} = 0
        AND ${t.finalRunSeq} IS NULL
        AND ${t.finalAttemptSeq} IS NULL
        AND ${t.finalEventDigest} IS NULL
      ) OR (
        ${t.eventCount} > 0
        AND ${t.finalRunSeq} IS NOT NULL
        AND ${t.finalAttemptSeq} IS NOT NULL
        AND ${t.finalEventDigest} IS NOT NULL
      )`,
    ),
    digestCheck: check(
      "agent_run_attempt_seals_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable one-shot finalization grants ───────────────────────────────────
//
// Minted in the SAME transaction as the seal, for every seal. The `afg_` public
// id is ALSO the evidence envelope's stable `submission_id`, so every retry of
// the obligation reuses one submission identity instead of forking a new one.
//
// It deliberately has NO expiry column: the attempt/seal/digest binding plus
// one successful consumption are the limiting authority, so a KMS or storage
// outage can never strand an obligation behind an expired grant (spec.md
// §"Security and retention rules"). Consumption is recorded by the evidence
// ledger's grant-use row in the next PR; this table is never updated.
export const agentRunFinalizationGrants = agentSchema.table(
  "agent_run_finalization_grants",
  {
    ...idMixin("afg"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    // Copied so the finalizer can build the envelope without a second read.
    attemptPublicId: citext("attempt_public_id").notNull(),
    // Constrained to exactly one capability — a grant can never execute tools.
    capabilityId: text("capability_id")
      .notNull()
      .default("ingest_run_evidence"),
    eventCount: integer("event_count").notNull(),
    finalEventDigest: text("final_event_digest"),
    eventStreamDigest: text("event_stream_digest").notNull(),
    issuedAt: timestamp("issued_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    attemptUniq: uniqueIndex("agent_run_finalization_grants_attempt_uq").on(
      t.attemptId,
    ),
    sealUniq: uniqueIndex("agent_run_finalization_grants_seal_uq").on(t.sealId),
    orgIdx: index("agent_run_finalization_grants_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
    capabilityCheck: check(
      "agent_run_finalization_grants_capability_check",
      sql`${t.capabilityId} = 'ingest_run_evidence'`,
    ),
    eventCountCheck: check(
      "agent_run_finalization_grants_event_count_check",
      sql`${t.eventCount} >= 0 AND (${t.eventCount} = 0) = (${t.finalEventDigest} IS NULL)`,
    ),
    digestCheck: check(
      "agent_run_finalization_grants_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable finalization obligations (the durable outbox) ──────────────────
//
// Created in the seal transaction next to the grant. There is deliberately NO
// `processed_at` column: pending state is DERIVED by anti-joining the evidence
// ledger's grant-use row, so a crash between "wrote evidence" and "marked done"
// cannot lose or duplicate an obligation. Mutable retry/claim coordination is a
// separate table in the evidence-ledger PR — never a mutation of this row.
export const agentRunFinalizationObligations = agentSchema.table(
  "agent_run_finalization_obligations",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    grantId: uuid("grant_id").notNull(),
    // The grant's `afg_` public id, copied verbatim. Stable across every retry.
    submissionId: citext("submission_id").notNull(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    grantUniq: uniqueIndex("agent_run_finalization_obligations_grant_uq").on(
      t.grantId,
    ),
    // `(org_id, submission_id)` is the finalization idempotency key the
    // evidence ledger keys on; enforce it here too so a duplicate obligation
    // cannot exist to be double-processed.
    submissionUniq: uniqueIndex(
      "agent_run_finalization_obligations_submission_uq",
    ).on(t.orgId, t.submissionId),
    attemptUniq: uniqueIndex(
      "agent_run_finalization_obligations_attempt_uq",
    ).on(t.attemptId),
    orgIdx: index("agent_run_finalization_obligations_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
  }),
);
