import {
  boolean,
  check,
  index,
  integer,
  jsonb,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  numeric,
  bigint,
  smallint,
} from "drizzle-orm/pg-core";
import type { AnyPgColumn } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { agentSchema } from "./_schemas";
import {
  appendOnlyAuditMixin,
  auditMixin,
  citext,
  idMixin,
  softDeleteMixin,
  orgScopeMixin,
  versionMixin,
  uuidv7Default,
} from "./_mixins";

// Agent identity + versioning (spec §6, agent-runtime epic).
export const agents = agentSchema.table(
  "agents",
  {
    ...idMixin("agt"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    slug: citext("slug").notNull(),
    name: text("name").notNull(),
    description: text("description"),
    agentType: text("agent_type").notNull(),
    activeVersionId: uuid("active_version_id"),
    // status: text + check per spec §6
    status: text("status").notNull().default("draft"),
    // deploymentStatus is the deploy on/off toggle, distinct from the
    // draft/active/archived authoring lifecycle in `status`.
    deploymentStatus: text("deployment_status").notNull().default("inactive"),
    // Nullable avatar. Either an https:// URL or the platform designed-avatar
    // spec string "avatar:v1:<json>" ({emoji,bg,mode}); capped at 512 chars at
    // the contract layer. Same column name as users/organizations for
    // consistency, even though it may carry the spec string, not a plain URL.
    avatarUrl: text("avatar_url"),
    // LLM-inferred, plain-text (<=256 char) description of what this agent does,
    // derived from its config (name/instructions/tools/triggers). Regenerated by
    // agent.definition.summarize when stale.
    summary: text("summary"),
    // SHA-256 of the canonical version config `summary` was derived from (same
    // canonicalization as agent_versions.checksum). When it no longer matches the
    // current config, the summary is stale and gets regenerated.
    summaryChecksum: text("summary_checksum"),
    // Agent RBAC Phase 1 (docs/specs/agent-rbac/spec.md §3.1): the delegated
    // IAM principal (iam.principals, kind='agent') for this agent IDENTITY —
    // one per agent, never per version/run. App-enforced reference (no
    // cross-schema FK per CLAUDE.md storage rules); provisioned by
    // agent.definition.create and soft-deleted together with the agent.
    principalId: uuid("principal_id"),
  },
  (t) => ({
    // NON-partial on purpose: covers soft-deleted rows too, so a slug a
    // workspace has ever used is PERMANENTLY reserved (never recycled), like an
    // npm package name. Immutability of the live slug is enforced by the
    // agents_slug_immutable trigger; this index reserves it past deletion.
    // (ADR-024, migration 20260709130000_agent_slug_no_recycle.)
    workspaceSlugUniq: uniqueIndex("agents_workspace_slug_uniq").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("agents_org_idx").on(t.orgId, t.workspaceId),
    principalIdx: index("agents_principal_idx").on(t.principalId),
    deploymentStatusIdx: index("agents_deployment_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.deploymentStatus,
    ),
    statusCheck: check(
      "agents_status_check",
      sql`${t.status} IN ('draft', 'active', 'archived')`,
    ),
    deploymentStatusCheck: check(
      "agents_deployment_status_check",
      sql`${t.deploymentStatus} IN ('inactive', 'active')`,
    ),
    slugCheck: check(
      "agents_slug_check",
      sql`${t.slug} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`,
    ),
  }),
);

// Immutable version snapshots. INSERT-only once published; no updatedAt by design.
export const agentVersions = agentSchema.table(
  "agent_versions",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    agentId: uuid("agent_id")
      .notNull()
      .references(() => agents.id),
    version: integer("version").notNull(),
    isPublished: boolean("is_published").notNull().default(false),
    // checksum: SHA-256 over canonical config — immutability contract.
    checksum: text("checksum"),
    config: jsonb("config").notNull().default(sql`'{}'::jsonb`),
    createdByUserId: uuid("created_by_user_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    // No updatedAt by design — INSERT-only once published.
  },
  (t) => ({
    agentVersionUniq: uniqueIndex("agent_versions_agent_version_uniq").on(
      t.agentId,
      t.version,
    ),
    agentIdx: index("agent_versions_agent_idx").on(t.agentId),
  }),
);

// Approval requests: cross-domain references (execution_step_id, message_id,
// tool_call_id) are app-enforced; FKs stay within the agent schema per
// CLAUDE.md storage rules.
export const approvalRequests = agentSchema.table(
  "approval_requests",
  {
    ...idMixin("apr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    executionStepId: uuid("execution_step_id"),
    toolCallId: uuid("tool_call_id"),
    messageId: uuid("message_id").notNull(),
    capabilityName: text("capability_name").notNull(),
    inputPreview: jsonb("input_preview").notNull(),
    riskLevel: text("risk_level").notNull(),
    // resolution null until resolved.
    resolution: text("resolution"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "date" }),
    resolvedByUserId: uuid("resolved_by_user_id"),
    note: text("note"),
    expiresAt: timestamp("expires_at", {
      withTimezone: true,
      mode: "date",
    }).notNull(),
  },
  (t) => ({
    orgResolutionIdx: index("approval_requests_org_resolution_idx").on(
      t.orgId,
      t.workspaceId,
      t.resolution,
    ),
    orgIdx: index("approval_requests_org_idx").on(t.orgId, t.workspaceId),
    messageIdx: index("approval_requests_message_idx").on(t.messageId),
    resolutionCheck: check(
      "approval_requests_resolution_check",
      sql`${t.resolution} IN ('approved', 'denied', 'expired') OR ${t.resolution} IS NULL`,
    ),
    riskLevelCheck: check(
      "approval_requests_risk_level_check",
      sql`${t.riskLevel} IN ('low', 'medium', 'high', 'critical')`,
    ),
  }),
);

// Agent execution tracking: lineage, steps, tool calls (migration 0019)
export const agentExecutions = agentSchema.table(
  "agent_executions",
  {
    ...idMixin("aex"),
    ...auditMixin(),
    ...orgScopeMixin(),
    // Nullable: dynamic supervisor runs don't have a pre-registered agent definition.
    agentId: uuid("agent_id").references(() => agents.id),
    agentVersionId: uuid("agent_version_id").references(() => agentVersions.id),
    originType: text("origin_type").notNull(),
    originId: uuid("origin_id").notNull(),
    status: text("status").notNull().default("planning"),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    estimatedCostUsd: numeric("estimated_cost_usd", {
      precision: 10,
      scale: 6,
    }),
    // AgentInstance shape (agent-schema.ts §4): self-reference for subagent/A2A
    // lineage (app-enforced, no FK).
    parentExecutionId: uuid("parent_execution_id"),
    // Live: schema.reconcile.dispatch writes reconcile progress counters here
    // and schema.reconcile.status reads them back. (The sibling `debug` column
    // was dropped in 20260802140000 — genuinely unreferenced.)
    state: jsonb("state").notNull().default(sql`'{}'::jsonb`),
  },
  (t) => ({
    orgStatusIdx: index("agent_executions_org_status_idx").on(
      t.orgId,
      t.workspaceId,
      t.status,
    ),
    originIdx: index("agent_executions_origin_idx").on(
      t.originType,
      t.originId,
    ),
    agentIdx: index("agent_executions_agent_idx").on(t.agentId),
    // FK → agent.agent_versions. Index the FK so agent_versions mutations don't
    // seq-scan the high-write executions table (only agent_id was indexed).
    agentVersionIdx: index("agent_executions_agent_version_idx").on(
      t.agentVersionId,
    ),
    parentExecutionIdx: index("agent_executions_parent_execution_idx").on(
      t.parentExecutionId,
    ),
    createdAtIdx: index("agent_executions_created_at_idx").on(t.createdAt),
    // Activity feed / execution list (agent.execution.list.ts,
    // command.menu.search.ts — 2026-07-11 audit §4.1 item 1). Distinct from
    // orgStatusIdx above, which leads with (org_id, workspace_id, status) —
    // this composite serves the feed's created_at DESC sort directly.
    orgWsCreatedIdx: index("agent_executions_org_ws_created_idx").on(
      t.orgId,
      t.workspaceId,
      t.createdAt,
    ),
    statusCheck: check(
      "agent_executions_status_check",
      sql`${t.status} IN ('planning', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    // Mirror of the CHECK constraint that already lives in the baseline/0007
    // migrations. Declared here so the Drizzle schema can never drift from the
    // DB again — the omission let workflow.run insert "workflow.run" (dot) and
    // get rejected at runtime while typecheck/Drizzle-mock tests passed.
    // Keep in sync with AGENT_EXECUTION_ORIGIN_TYPES in
    // packages/oxagen/src/contracts/agent.execution.record.ts.
    originTypeCheck: check(
      "agent_executions_origin_type_check",
      sql`${t.originType} IN ('chat', 'event_trigger', 'scheduled_job', 'mcp_request', 'workflow_run', 'fanout', 'a2a')`,
    ),
  }),
);

export const agentExecutionSteps = agentSchema.table(
  "agent_execution_steps",
  {
    ...idMixin("aes"),
    ...auditMixin(),
    executionId: uuid("execution_id")
      .notNull()
      .references(() => agentExecutions.id),
    ...orgScopeMixin(),
    stepNumber: integer("step_number").notNull(),
    stepType: text("step_type").notNull(),
    status: text("status").notNull(),
    inputPayload: jsonb("input_payload").notNull(),
    outputPayload: jsonb("output_payload"),
    failureReason: text("failure_reason"),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),
    // Durable claim/lease (spec §1): a lost
    // worker's step becomes resweepable instead of stranding the execution.
    claimedBy: text("claimed_by"),
    leaseExpiresAt: timestamp("lease_expires_at", {
      withTimezone: true,
      mode: "date",
    }),
    attempts: integer("attempts").notNull().default(0),
  },
  (t) => ({
    executionIdx: index("agent_execution_steps_execution_idx").on(
      t.executionId,
    ),
    orgIdx: index("agent_execution_steps_org_idx").on(t.orgId, t.workspaceId),
    claimIdx: index("agent_execution_steps_claim_idx")
      .on(t.orgId, t.status)
      .where(sql`${t.status} IN ('pending', 'running')`),
    statusCheck: check(
      "agent_execution_steps_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
  }),
);

export const agentToolCalls = agentSchema.table(
  "agent_tool_calls",
  {
    ...idMixin("atc"),
    ...auditMixin(),
    executionStepId: uuid("execution_step_id")
      .notNull()
      .references(() => agentExecutionSteps.id),
    ...orgScopeMixin(),
    toolName: text("tool_name").notNull(),
    toolType: text("tool_type").notNull(),
    requestPayload: jsonb("request_payload").notNull(),
    responsePayload: jsonb("response_payload"),
    status: text("status").notNull(),
    latencyMs: bigint("latency_ms", { mode: "number" }),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
  },
  (t) => ({
    stepIdx: index("agent_tool_calls_step_idx").on(t.executionStepId),
    toolIdx: index("agent_tool_calls_tool_idx").on(t.toolName),
    orgIdx: index("agent_tool_calls_org_idx").on(t.orgId, t.workspaceId),
    statusCheck: check(
      "agent_tool_calls_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed')`,
    ),
  }),
);

// ── Durable agent runs — the evidence ledger's run identity ─────────────────
//
// One row per governed run, across every surface, written exclusively by
// @oxagen/run-ledger. `surface` mirrors that package's PlatformSurface union
// so the row and the seam can never drift into two vocabularies for the same
// thing; ADR-041 added `external` to both for a `client_attested` submission
// that no Oxagen surface admitted interactively.
//
// ADR-041 (runtime excision) removed the durable worker, and with it the
// claim/lease trio (`claimed_by` / `lease_expires_at` / `attempts`) and the
// engine-state checkpoint pair (`checkpoint` / `checkpoint_seq`). Oxagen
// claims nothing, leases nothing and restores no engine state: an external
// engine executes and submits, and this row records WHO was authorized to do
// so. Attempt bookkeeping that survives is evidence, not scheduling —
// `attempt_count` against the pinned `max_attempts` ceiling, and
// `active_attempt_id`.
//
// `spec` is the serialized RunSpecV2 (trusted identity, bindings, engine
// policy) — data only, never live engine ports or callbacks. The full
// per-attempt history is agent_run_events, which is append-only and
// digest-chained; there is no mutable pointer summarizing it.
export const agentRuns = agentSchema.table(
  "agent_runs",
  {
    ...idMixin("arun"),
    ...orgScopeMixin(),
    ...auditMixin(),
    surface: text("surface").notNull(),
    status: text("status").notNull().default("pending"),
    spec: jsonb("spec").notNull(),
    result: jsonb("result"),
    error: text("error"),
    // Set by the cancel path. Cooperative, not enforcement: the worker that
    // used to observe it left with ADR-041, so this is now a governance
    // signal an external engine's drain may honour, and the record that
    // cancellation was requested either way.
    cancelRequested: boolean("cancel_requested").notNull().default(false),
    startedAt: timestamp("started_at", { withTimezone: true, mode: "date" }),
    completedAt: timestamp("completed_at", {
      withTimezone: true,
      mode: "date",
    }),

    // ── RunSpecV2 typed identity (docs/specs/run-evidence-ingress) ───────────
    //
    // The V1/V2 discriminant. Existing rows backfill to 1 via the column
    // default; a governed V2 admission writes 2 and must then supply the
    // COMPLETE typed set below (agent_runs_v2_identity_check). Every column
    // here is nullable at the column level on purpose: `agent_runs` already
    // holds V1 history that has no trusted principal, repository, or retention
    // binding, and fabricating one for a historical row is exactly what the
    // expand-only rule forbids. Completeness is a conditional CHECK, not a
    // column-level NOT NULL.
    //
    // These are duplicated OUT of `spec` deliberately: security queries and the
    // worker's row/spec identity comparison must not depend on untyped JSON
    // extraction (spec.md §"Trusted run and attempt identity").
    specVersion: integer("spec_version").notNull().default(1),
    runKind: text("run_kind"),
    // RFC 8785 canonical digest of the serialized RunSpecV2.
    specDigest: text("spec_digest"),
    // Actor binding: the authenticated human who delegated the run and the
    // deployed-agent principal acting for them. NOT agents.parentUserId.
    initiatingPrincipalId: uuid("initiating_principal_id"),
    agentPrincipalId: uuid("agent_principal_id"),
    agentId: uuid("agent_id"),
    agentVersionId: uuid("agent_version_id"),
    agentVersionChecksum: text("agent_version_checksum"),
    // Digest-addressed pinned grant ceiling (iam.authorization_snapshots).
    authorizationSnapshotId: uuid("authorization_snapshot_id"),
    // Child runs narrow their parent's ceiling; a root run is null.
    parentRunId: uuid("parent_run_id"),
    // Immutable repository binding plus the copies admission resolved from it.
    // The copies are not redundancy for its own sake: the binding row is
    // versioned, and the run must prove which version it saw.
    repositoryBindingId: uuid("repository_binding_id"),
    repositoryProvider: text("repository_provider"),
    providerRepositoryId: text("provider_repository_id"),
    repositoryConnectionId: uuid("repository_connection_id"),
    configuredDefaultRef: text("configured_default_ref"),
    baseCommitSha: text("base_commit_sha"),
    baseTreeSha: text("base_tree_sha"),
    // Immutable retention-policy version pinned at admission — both the public
    // identity and its canonical digest, so a swapped row is detectable.
    retentionPolicyId: uuid("retention_policy_id"),
    retentionPolicyDigest: text("retention_policy_digest"),
    // Trusted engine policy: the pinned ceiling `attempt_count` is bounded
    // against. The V1 `attempts` counter it used to coexist with went with the
    // worker in ADR-041.
    maxAttempts: integer("max_attempts"),

    // ── Operational V2 pointers (mutable; see the immutability trigger) ──────
    // The attempt currently open (created, not yet sealed); null otherwise.
    // Not a lease — the seal is the only fence (ADR-041).
    activeAttemptId: uuid("active_attempt_id"),
    // Number of attempts ever created for this run, bounded by max_attempts.
    attemptCount: integer("attempt_count").notNull().default(0),
    // Next run-global event sequence to allocate. PostgreSQL-assigned inside
    // the append transaction (not a SEQUENCE object — the allocation must roll
    // back with the append). Monotonic ACROSS attempts, unlike attempt_seq.
    nextRunSeq: bigint("next_run_seq", { mode: "number" }).notNull().default(1),
  },
  (t) => ({
    orgIdx: index("agent_runs_org_idx").on(t.orgId, t.workspaceId),
    // Both partial indexes were cut for the worker's cross-org claim UPDATE
    // and lease sweeper (hence no org_id prefix). Those queries left with the
    // runtime; the indexes stay because "which runs are still open, oldest
    // first" is now an OPERATOR question — the stuck-run and unsealed-attempt
    // views the governance surfaces read.
    claimIdx: index("agent_runs_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`${t.status} IN ('pending', 'running')`),
    v2ClaimIdx: index("agent_runs_v2_claim_idx")
      .on(t.status, t.createdAt)
      .where(sql`spec_version = 2 AND status IN ('pending', 'running')`),
    // Security lookups by trusted identity (who ran what, under which snapshot).
    v2ActorIdx: index("agent_runs_v2_actor_idx")
      .on(t.orgId, t.workspaceId, t.initiatingPrincipalId, t.agentPrincipalId)
      .where(sql`spec_version = 2`),
    parentRunIdx: index("agent_runs_parent_run_idx")
      .on(t.parentRunId)
      .where(sql`parent_run_id IS NOT NULL`),
    // `external` is the post-ADR-041 addition: a `client_attested` submission
    // from an engine Oxagen did not host has no interactive surface of origin.
    // The other four are kept because historical rows carry them.
    surfaceCheck: check(
      "agent_runs_surface_check",
      sql`${t.surface} IN ('chat', 'api-chat', 'a2a', 'repo-edit', 'external')`,
    ),
    statusCheck: check(
      "agent_runs_status_check",
      sql`${t.status} IN ('pending', 'running', 'completed', 'failed', 'cancelled')`,
    ),
    specVersionCheck: check(
      "agent_runs_spec_version_check",
      sql`${t.specVersion} IN (1, 2)`,
    ),
    // The V1/V2 discriminant. A preserved V1 row carries NONE of the typed V2
    // identity; a V2 row carries ALL of it. There is no partially-bound run.
    v2IdentityCheck: check(
      "agent_runs_v2_identity_check",
      sql`(
        ${t.specVersion} = 1
        AND ${t.runKind} IS NULL
        AND ${t.specDigest} IS NULL
        AND ${t.initiatingPrincipalId} IS NULL
        AND ${t.agentPrincipalId} IS NULL
        AND ${t.agentId} IS NULL
        AND ${t.agentVersionId} IS NULL
        AND ${t.agentVersionChecksum} IS NULL
        AND ${t.authorizationSnapshotId} IS NULL
        AND ${t.repositoryBindingId} IS NULL
        AND ${t.repositoryProvider} IS NULL
        AND ${t.providerRepositoryId} IS NULL
        AND ${t.repositoryConnectionId} IS NULL
        AND ${t.configuredDefaultRef} IS NULL
        AND ${t.baseCommitSha} IS NULL
        AND ${t.baseTreeSha} IS NULL
        AND ${t.retentionPolicyId} IS NULL
        AND ${t.retentionPolicyDigest} IS NULL
        AND ${t.maxAttempts} IS NULL
      ) OR (
        ${t.specVersion} = 2
        AND ${t.runKind} IS NOT NULL
        AND ${t.specDigest} IS NOT NULL
        AND ${t.initiatingPrincipalId} IS NOT NULL
        AND ${t.agentPrincipalId} IS NOT NULL
        AND ${t.agentId} IS NOT NULL
        AND ${t.agentVersionId} IS NOT NULL
        AND ${t.agentVersionChecksum} IS NOT NULL
        AND ${t.authorizationSnapshotId} IS NOT NULL
        AND ${t.repositoryBindingId} IS NOT NULL
        AND ${t.repositoryProvider} IS NOT NULL
        AND ${t.providerRepositoryId} IS NOT NULL
        AND ${t.repositoryConnectionId} IS NOT NULL
        AND ${t.configuredDefaultRef} IS NOT NULL
        AND ${t.baseCommitSha} IS NOT NULL
        AND ${t.baseTreeSha} IS NOT NULL
        AND ${t.retentionPolicyId} IS NOT NULL
        AND ${t.retentionPolicyDigest} IS NOT NULL
        AND ${t.maxAttempts} IS NOT NULL
      )`,
    ),
    runKindCheck: check(
      "agent_runs_run_kind_check",
      sql`${t.runKind} IS NULL OR ${t.runKind} IN ('general', 'repo_edit')`,
    ),
    specDigestCheck: check(
      "agent_runs_spec_digest_check",
      sql`${t.specDigest} IS NULL OR ${t.specDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    retentionDigestCheck: check(
      "agent_runs_retention_digest_check",
      sql`${t.retentionPolicyDigest} IS NULL OR ${t.retentionPolicyDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
    maxAttemptsCheck: check(
      "agent_runs_max_attempts_check",
      sql`${t.maxAttempts} IS NULL OR ${t.maxAttempts} > 0`,
    ),
    attemptCountCheck: check(
      "agent_runs_attempt_count_check",
      sql`${t.attemptCount} >= 0 AND (${t.maxAttempts} IS NULL OR ${t.attemptCount} <= ${t.maxAttempts})`,
    ),
    nextRunSeqCheck: check(
      "agent_runs_next_run_seq_check",
      sql`${t.nextRunSeq} >= 1`,
    ),
    // A run may not be its own parent — the cheapest half of cycle prevention
    // (deeper cycles are prevented by the snapshot-narrowing rule in IAM).
    parentRunCheck: check(
      "agent_runs_parent_run_check",
      sql`${t.parentRunId} IS NULL OR ${t.parentRunId} <> ${t.id}`,
    ),
  }),
);

// Append-only event log for agent_runs — the canonical source for resumable
// SSE subscriptions and ClickHouse ingestion (spec.md §4.2:
// "the event log is canonical"). Immutable child: bare uuid pk
// (no idMixin/public_id — nothing
// external addresses one event row directly) and no updatedAt. `seq` is
// app-assigned and monotonic per run starting at 1 — deliberately NOT a
// serial/identity column, so the worker can assert the exact next value in
// the same transaction as the checkpoint write (`UNIQUE(run_id, seq)` below
// turns a racing double-append into a constraint violation, not silent
// duplication).
// V2 (docs/specs/run-evidence-ingress) adds a second record shape to this same
// table rather than a second log: `event_record_version` is the discriminant, 1
// for every preserved legacy row and 2 for a fenced-attempt event. The legacy
// `seq/type/payload` columns became nullable so a V2 row can leave them empty,
// and the old full `UNIQUE(run_id, seq)` was replaced by three PARTIAL unique
// indexes — V1 `(run_id, seq)`, V2 `(run_id, run_seq)`, V2 `(attempt_id,
// attempt_seq)` — so a V2 row can never be read as legacy and vice versa. A
// leftover full unique on `(run_id, seq)` would defeat the discriminant, which
// is why the migration drops it explicitly.
export const agentRunEvents = agentSchema.table(
  "agent_run_events",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    // No cross-schema FK to agent_runs — app-enforced per CLAUDE.md storage
    // rules (same convention as the other cross-table ids in this schema).
    runId: uuid("run_id").notNull(),
    // 1 = legacy run-global record, 2 = fenced attempt record. Existing rows
    // backfill to 1 through the column default.
    eventRecordVersion: smallint("event_record_version").notNull().default(1),
    // ── V1 legacy columns (required for V1, NULL for V2) ─────────────────────
    seq: integer("seq"),
    type: text("type"),
    payload: jsonb("payload"),
    // `created_at` is the RECORDED time for both record versions — the instant
    // Postgres accepted the append. V2 additionally carries the producer's
    // `observed_at`; the two differ by transport and buffering latency and the
    // event digest commits to the observed one.
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),

    // ── V2 fenced-attempt columns (required for V2, NULL for V1) ─────────────
    // The immutable attempt this event belongs to. Without it a reclaimed run's
    // events interleave across executions with no stable identity.
    attemptId: uuid("attempt_id"),
    // Monotonic across attempts, allocated from agent_runs.next_run_seq inside
    // the append transaction. Drives resumable SSE subscriptions.
    runSeq: bigint("run_seq", { mode: "number" }),
    // Producer-assigned, contiguous, and reset to 1 for each new attempt.
    // Drives unambiguous replay.
    attemptSeq: integer("attempt_seq"),
    eventSchemaVersion: text("event_schema_version"),
    eventType: text("event_type"),
    // One of the nine evidence stages (EVIDENCE_STAGES in
    // schema/run-evidence-foundation.ts).
    stage: text("stage"),
    // Digest of the canonical payload bytes, whether inline or encrypted.
    payloadDigest: text("payload_digest"),
    // Digest over (attempt_seq, schema, type, stage, payload_digest,
    // observed_at). Identical sequence + identical digest is idempotent;
    // identical sequence + different digest is a security event.
    eventDigest: text("event_digest"),
    // EXACTLY ONE of these two carries the body. Inline is allow-listed receipt
    // metadata only; anything large or sensitive is an encrypted blob reference
    // (an `evb_` public id — app-enforced text; the blob index is planned in
    // docs/specs/run-evidence-ingress/03-evidence-ledger-plan.md).
    payloadInline: jsonb("payload_inline"),
    encryptedPayloadRef: text("encrypted_payload_ref"),
    observedAt: timestamp("observed_at", { withTimezone: true, mode: "date" }),
  },
  (t) => ({
    // Partial: legacy rows only. Replaces the former full
    // UNIQUE(run_id, seq) constraint, which would otherwise collide every V2
    // row on (run_id, NULL) semantics and blur the discriminant.
    v1RunSeqUniq: uniqueIndex("agent_run_events_v1_run_seq_uq")
      .on(t.runId, t.seq)
      .where(sql`event_record_version = 1`),
    v2RunSeqUniq: uniqueIndex("agent_run_events_v2_run_seq_uq")
      .on(t.runId, t.runSeq)
      .where(sql`event_record_version = 2`),
    v2AttemptSeqUniq: uniqueIndex("agent_run_events_v2_attempt_seq_uq")
      .on(t.attemptId, t.attemptSeq)
      .where(sql`event_record_version = 2`),
    orgIdx: index("agent_run_events_org_idx").on(t.orgId, t.workspaceId),
    recordVersionCheck: check(
      "agent_run_events_record_version_check",
      sql`${t.eventRecordVersion} IN (1, 2)`,
    ),
    // The discriminant, spelled out. A V1 row is exactly the legacy shape with
    // every V2 field null; a V2 row is exactly the attempt shape with every
    // legacy field null. Nothing in between is representable.
    recordShapeCheck: check(
      "agent_run_events_record_shape_check",
      sql`(
        ${t.eventRecordVersion} = 1
        AND ${t.seq} IS NOT NULL
        AND ${t.type} IS NOT NULL
        AND ${t.payload} IS NOT NULL
        AND ${t.attemptId} IS NULL
        AND ${t.runSeq} IS NULL
        AND ${t.attemptSeq} IS NULL
        AND ${t.eventSchemaVersion} IS NULL
        AND ${t.eventType} IS NULL
        AND ${t.stage} IS NULL
        AND ${t.payloadDigest} IS NULL
        AND ${t.eventDigest} IS NULL
        AND ${t.payloadInline} IS NULL
        AND ${t.encryptedPayloadRef} IS NULL
        AND ${t.observedAt} IS NULL
      ) OR (
        ${t.eventRecordVersion} = 2
        AND ${t.seq} IS NULL
        AND ${t.type} IS NULL
        AND ${t.payload} IS NULL
        AND ${t.attemptId} IS NOT NULL
        AND ${t.runSeq} IS NOT NULL
        AND ${t.attemptSeq} IS NOT NULL
        AND ${t.eventSchemaVersion} IS NOT NULL
        AND ${t.eventType} IS NOT NULL
        AND ${t.stage} IS NOT NULL
        AND ${t.payloadDigest} IS NOT NULL
        AND ${t.eventDigest} IS NOT NULL
        AND ${t.observedAt} IS NOT NULL
        AND (${t.payloadInline} IS NULL) <> (${t.encryptedPayloadRef} IS NULL)
      )`,
    ),
    stageCheck: check(
      "agent_run_events_stage_check",
      sql`${t.stage} IS NULL OR ${t.stage} IN ('admission', 'checkout', 'context', 'model', 'tool', 'change', 'verification', 'provider_publish', 'terminal')`,
    ),
    seqBoundsCheck: check(
      "agent_run_events_seq_bounds_check",
      sql`(${t.runSeq} IS NULL OR ${t.runSeq} >= 1) AND (${t.attemptSeq} IS NULL OR ${t.attemptSeq} >= 1) AND (${t.seq} IS NULL OR ${t.seq} >= 1)`,
    ),
    digestCheck: check(
      "agent_run_events_digest_check",
      sql`(${t.payloadDigest} IS NULL OR ${t.payloadDigest} ~ '^sha256:[0-9a-f]{64}$') AND (${t.eventDigest} IS NULL OR ${t.eventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable attempt identity (docs/specs/run-evidence-ingress) ─────────────
//
// One row per successful V2 worker claim, created BEFORE any model or tool
// work. `arat_` is the public identity every API boundary and evidence receipt
// uses. The resolved engine name/version/build digest is pinned here rather
// than read back from a live worker, so evidence names the exact binary that
// executed. A successor that resumes an earlier attempt records the restore
// tuple and keeps its OWN attempt identity — attempt IDs are never reused
// (spec.md §"Attempt identity").
//
// Immutable: append-only audit columns and the migration revokes UPDATE/DELETE.
export const agentRunAttempts = agentSchema.table(
  "agent_run_attempts",
  {
    ...idMixin("arat"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    // 1-based, dense, and unique per run — the retry counter the pinned
    // max_attempts ceiling bounds.
    attemptNumber: integer("attempt_number").notNull(),
    // Identity of the external engine process that produced this attempt.
    workerId: text("worker_id").notNull(),
    claimedAt: timestamp("claimed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    engineName: text("engine_name").notNull(),
    engineVersion: text("engine_version").notNull(),
    // Build or container-image digest of the engine that actually ran.
    engineBuildDigest: text("engine_build_digest").notNull(),
    // ── Restore tuple: both present, or both absent ─────────────────────────
    // The checkpoint half (`restored_checkpoint_id` / `restored_checkpoint_digest`)
    // went with agent.agent_run_checkpoints in ADR-041: Oxagen no longer runs
    // agents, so there is no engine state to restore — only the attempt
    // provenance chain remains as evidence.
    resumedFromAttemptId: uuid("resumed_from_attempt_id"),
    resumedFromAttemptPublicId: citext("resumed_from_attempt_public_id"),
  },
  (t) => ({
    runAttemptUniq: uniqueIndex("agent_run_attempts_run_attempt_uq").on(
      t.runId,
      t.attemptNumber,
    ),
    orgIdx: index("agent_run_attempts_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempts_run_idx").on(t.runId),
    attemptNumberCheck: check(
      "agent_run_attempts_attempt_number_check",
      sql`${t.attemptNumber} >= 1`,
    ),
    // A partial restore reference cannot prove provenance, so the tuple is
    // all-or-nothing.
    restoreTupleCheck: check(
      "agent_run_attempts_restore_tuple_check",
      sql`(
        ${t.resumedFromAttemptId} IS NULL
        AND ${t.resumedFromAttemptPublicId} IS NULL
      ) OR (
        ${t.resumedFromAttemptId} IS NOT NULL
        AND ${t.resumedFromAttemptPublicId} IS NOT NULL
      )`,
    ),
    // A successor may never restore from itself.
    restoreSelfCheck: check(
      "agent_run_attempts_restore_self_check",
      sql`${t.resumedFromAttemptId} IS NULL OR ${t.resumedFromAttemptId} <> ${t.id}`,
    ),
    digestCheck: check(
      "agent_run_attempts_digest_check",
      sql`${t.engineBuildDigest} ~ '^sha256:[0-9a-f]{64}$'`,
    ),
  }),
);

// ── Immutable attempt seals ──────────────────────────────────────────────────
//
// One row per terminated attempt, for EVERY terminal outcome including normal
// completion — that is what closes the crash window between "finished" and
// "finalized". A truly zero-event abandoned attempt seals with event_count = 0,
// a NULL final-event digest, and the canonical empty stream digest; it never
// invents a terminal event to satisfy the shape.
export const agentRunAttemptSeals = agentSchema.table(
  "agent_run_attempt_seals",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    terminalStatus: text("terminal_status").notNull(),
    reasonCode: text("reason_code"),
    eventCount: integer("event_count").notNull(),
    finalRunSeq: bigint("final_run_seq", { mode: "number" }),
    finalAttemptSeq: integer("final_attempt_seq"),
    finalEventDigest: text("final_event_digest"),
    // Always present: the canonical empty-stream digest when event_count = 0.
    eventStreamDigest: text("event_stream_digest").notNull(),
    sealerKind: text("sealer_kind").notNull(),
    sealerWorkerId: text("sealer_worker_id").notNull(),
    sealedAt: timestamp("sealed_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    // An attempt seals exactly once — this uniqueness is what makes the
    // seal/grant/obligation transaction idempotent under duplicate sweeps.
    attemptUniq: uniqueIndex("agent_run_attempt_seals_attempt_uq").on(
      t.attemptId,
    ),
    orgIdx: index("agent_run_attempt_seals_org_idx").on(t.orgId, t.workspaceId),
    runIdx: index("agent_run_attempt_seals_run_idx").on(t.runId),
    terminalStatusCheck: check(
      "agent_run_attempt_seals_terminal_status_check",
      sql`${t.terminalStatus} IN ('completed', 'failed', 'cancelled', 'denied', 'abandoned')`,
    ),
    // `ingress` is the only kind a seal is written under today — evidence
    // ingress stamps it. `worker` and `reclaimer` are the retired runtime's
    // vocabulary, kept solely so historical rows stay valid (ADR-041).
    sealerKindCheck: check(
      "agent_run_attempt_seals_sealer_kind_check",
      sql`${t.sealerKind} IN ('ingress', 'worker', 'reclaimer')`,
    ),
    // Zero-event seals carry no final-event evidence; non-zero seals carry all
    // of it. Anything else is an unprovable claim about the stream.
    eventEvidenceCheck: check(
      "agent_run_attempt_seals_event_evidence_check",
      sql`(
        ${t.eventCount} = 0
        AND ${t.finalRunSeq} IS NULL
        AND ${t.finalAttemptSeq} IS NULL
        AND ${t.finalEventDigest} IS NULL
      ) OR (
        ${t.eventCount} > 0
        AND ${t.finalRunSeq} IS NOT NULL
        AND ${t.finalAttemptSeq} IS NOT NULL
        AND ${t.finalEventDigest} IS NOT NULL
      )`,
    ),
    digestCheck: check(
      "agent_run_attempt_seals_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable one-shot finalization grants ───────────────────────────────────
//
// Minted in the SAME transaction as the seal, for every seal. The `afg_` public
// id is ALSO the evidence envelope's stable `submission_id`, so every retry of
// the obligation reuses one submission identity instead of forking a new one.
//
// It deliberately has NO expiry column: the attempt/seal/digest binding plus
// one successful consumption are the limiting authority, so a KMS or storage
// outage can never strand an obligation behind an expired grant (spec.md
// §"Security and retention rules"). Consumption is recorded by the evidence
// ledger's grant-use row in the next PR; this table is never updated.
export const agentRunFinalizationGrants = agentSchema.table(
  "agent_run_finalization_grants",
  {
    ...idMixin("afg"),
    ...orgScopeMixin(),
    ...appendOnlyAuditMixin(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    // Copied so the finalizer can build the envelope without a second read.
    attemptPublicId: citext("attempt_public_id").notNull(),
    // Constrained to exactly one capability — a grant can never execute tools.
    capabilityId: text("capability_id")
      .notNull()
      .default("ingest_run_evidence"),
    eventCount: integer("event_count").notNull(),
    finalEventDigest: text("final_event_digest"),
    eventStreamDigest: text("event_stream_digest").notNull(),
    issuedAt: timestamp("issued_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    attemptUniq: uniqueIndex("agent_run_finalization_grants_attempt_uq").on(
      t.attemptId,
    ),
    sealUniq: uniqueIndex("agent_run_finalization_grants_seal_uq").on(t.sealId),
    orgIdx: index("agent_run_finalization_grants_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
    capabilityCheck: check(
      "agent_run_finalization_grants_capability_check",
      sql`${t.capabilityId} = 'ingest_run_evidence'`,
    ),
    eventCountCheck: check(
      "agent_run_finalization_grants_event_count_check",
      sql`${t.eventCount} >= 0 AND (${t.eventCount} = 0) = (${t.finalEventDigest} IS NULL)`,
    ),
    digestCheck: check(
      "agent_run_finalization_grants_digest_check",
      sql`${t.eventStreamDigest} ~ '^sha256:[0-9a-f]{64}$' AND (${t.finalEventDigest} IS NULL OR ${t.finalEventDigest} ~ '^sha256:[0-9a-f]{64}$')`,
    ),
  }),
);

// ── Immutable finalization obligations (the durable outbox) ──────────────────
//
// Created in the seal transaction next to the grant. There is deliberately NO
// `processed_at` column: pending state is DERIVED by anti-joining the evidence
// ledger's grant-use row, so a crash between "wrote evidence" and "marked done"
// cannot lose or duplicate an obligation. Mutable retry/claim coordination is a
// separate table in the evidence-ledger PR — never a mutation of this row.
export const agentRunFinalizationObligations = agentSchema.table(
  "agent_run_finalization_obligations",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    ...orgScopeMixin(),
    grantId: uuid("grant_id").notNull(),
    // The grant's `afg_` public id, copied verbatim. Stable across every retry.
    submissionId: citext("submission_id").notNull(),
    runId: uuid("run_id").notNull(),
    attemptId: uuid("attempt_id").notNull(),
    sealId: uuid("seal_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    grantUniq: uniqueIndex("agent_run_finalization_obligations_grant_uq").on(
      t.grantId,
    ),
    // `(org_id, submission_id)` is the finalization idempotency key the
    // evidence ledger keys on; enforce it here too so a duplicate obligation
    // cannot exist to be double-processed.
    submissionUniq: uniqueIndex(
      "agent_run_finalization_obligations_submission_uq",
    ).on(t.orgId, t.submissionId),
    attemptUniq: uniqueIndex(
      "agent_run_finalization_obligations_attempt_uq",
    ).on(t.attemptId),
    orgIdx: index("agent_run_finalization_obligations_org_idx").on(
      t.orgId,
      t.workspaceId,
    ),
  }),
);

// ── Workspace agent-asset registry (stella-cutover Wave 4) ───────────────────
//
// Tool declarations + context records: a logical identity row keyed
// (workspace_id, slug) plus immutable version snapshots, an explicitly pinned
// active_version_id, and soft delete on the identity row only. Migration
// 20260831120000_agent_asset_registry.sql.

// Declared tool contracts (Stella ToolContract vocabulary): the JSON schema,
// read_only flag, risk grade and policy group live on the version row; the
// identity row carries the source discriminator and the enable toggle.
export const tools = agentSchema.table(
  "tools",
  {
    ...idMixin("tol"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    name: text("name").notNull(),
    slug: citext("slug").notNull(),
    description: text("description"),
    // builtin = shipped built-in; custom = workspace-authored script tool;
    // mcp = an MCP server's advertised tool; foundry = tool-foundry authored.
    source: citext("source").notNull(),
    enabled: boolean("enabled").notNull().default(true),
    // Explicitly pinned active version, decoupled from tool_versions.is_latest.
    activeVersionId: uuid("active_version_id").references(
      (): AnyPgColumn => toolVersions.id,
    ),
    activatedByUserId: uuid("activated_by_user_id"),
    activatedAt: timestamp("activated_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => ({
    workspaceSlugIdx: uniqueIndex("tools_workspace_slug_idx").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("tools_org_idx").on(t.orgId, t.workspaceId),
    activeVersionIdx: index("tools_active_version_idx").on(t.activeVersionId),
    sourceCheck: check(
      "tools_source_check",
      sql`${t.source} IN ('builtin', 'custom', 'mcp', 'foundry')`,
    ),
  }),
);

export const toolVersions = agentSchema.table(
  "tool_versions",
  {
    ...idMixin("tlv"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...versionMixin(),
    toolId: uuid("tool_id").notNull(),
    // The tool's JSON Schema for its input parameters.
    inputSchema: jsonb("input_schema").notNull(),
    readOnly: boolean("read_only").notNull().default(false),
    riskGrade: text("risk_grade").notNull(),
    policyGroup: text("policy_group"),
    // The full declared manifest body, verbatim.
    manifest: jsonb("manifest").notNull(),
    // SHA-256 hex over the canonical (sorted-key) manifest JSON — immutability
    // contract (see skill_versions.checksum).
    checksum: text("checksum").notNull(),
  },
  (t) => ({
    toolIdx: index("tool_versions_tool_idx").on(t.toolId),
    toolLatestIdx: uniqueIndex("tool_versions_tool_latest_idx")
      .on(t.toolId)
      .where(sql`is_latest = true`),
    toolVersionIdx: uniqueIndex("tool_versions_tool_version_idx").on(
      t.toolId,
      t.versionNumber,
    ),
    orgIdx: index("tool_versions_org_idx").on(t.orgId, t.workspaceId),
    riskGradeCheck: check(
      "tool_versions_risk_grade_check",
      sql`${t.riskGrade} IN ('low', 'medium', 'high', 'critical')`,
    ),
    checksumCheck: check(
      "tool_versions_checksum_check",
      sql`${t.checksum} ~ '^[0-9a-f]{64}$'`,
    ),
  }),
);

// Steering/context records — Stella keeps these as .stella/rules/*.toml, one
// record per file; the slug is the file stem. Lifecycle (status) is driven by
// the append-only contextPromotions ledger below, never edited directly.
export const contextRecords = agentSchema.table(
  "context_records",
  {
    ...idMixin("ctr"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...softDeleteMixin(),
    slug: citext("slug").notNull(),
    title: text("title").notNull(),
    // promote → active, retire → retired, supersede → superseded.
    status: text("status").notNull().default("active"),
    activeVersionId: uuid("active_version_id").references(
      (): AnyPgColumn => contextRecordVersions.id,
    ),
    activatedByUserId: uuid("activated_by_user_id"),
    activatedAt: timestamp("activated_at", {
      withTimezone: true,
      mode: "date",
    }),
  },
  (t) => ({
    workspaceSlugIdx: uniqueIndex("context_records_workspace_slug_idx").on(
      t.workspaceId,
      t.slug,
    ),
    orgIdx: index("context_records_org_idx").on(t.orgId, t.workspaceId),
    activeVersionIdx: index("context_records_active_version_idx").on(
      t.activeVersionId,
    ),
    statusCheck: check(
      "context_records_status_check",
      sql`${t.status} IN ('active', 'retired', 'superseded')`,
    ),
  }),
);

export const contextRecordVersions = agentSchema.table(
  "context_record_versions",
  {
    ...idMixin("crv"),
    ...auditMixin(),
    ...orgScopeMixin(),
    ...versionMixin(),
    recordId: uuid("record_id").notNull(),
    // The canonical record body (one TOML record per file in Stella).
    body: text("body").notNull(),
    // SHA-256 hex over body — immutability contract (see skill_versions).
    checksum: text("checksum").notNull(),
    // ContextProvenanceV1 vocabulary (packages/run-evidence contextgraph.ts):
    // [{ type, uri?, range?, digest?, method?, by? }].
    provenance: jsonb("provenance").notNull().default(sql`'[]'::jsonb`),
  },
  (t) => ({
    recordIdx: index("context_record_versions_record_idx").on(t.recordId),
    recordLatestIdx: uniqueIndex("context_record_versions_record_latest_idx")
      .on(t.recordId)
      .where(sql`is_latest = true`),
    recordVersionIdx: uniqueIndex(
      "context_record_versions_record_version_idx",
    ).on(t.recordId, t.versionNumber),
    orgIdx: index("context_record_versions_org_idx").on(t.orgId, t.workspaceId),
    checksumCheck: check(
      "context_record_versions_checksum_check",
      sql`${t.checksum} ~ '^[0-9a-f]{64}$'`,
    ),
  }),
);

// Append-only hash-chained ledger of context-record lifecycle actions,
// mirroring Stella's promotions.jsonl: chain_digest = sha256(prev_digest +
// canonical row), seq monotonic per record starting at 1. INSERT-only at the
// grant level (no UPDATE/DELETE for oxagen_app) — a promotion is evidence.
export const contextPromotions = agentSchema.table(
  "context_promotions",
  {
    ...idMixin("ctp"),
    ...appendOnlyAuditMixin(),
    ...orgScopeMixin(),
    recordId: uuid("record_id").notNull(),
    // The version being promoted/superseded-by; NULL for a retire.
    versionId: uuid("version_id"),
    seq: integer("seq").notNull(),
    action: text("action").notNull(),
    approverUserId: uuid("approver_user_id"),
    policyVersion: text("policy_version").notNull(),
    // The previous entry's chain_digest; NULL only for seq = 1.
    prevChainDigest: text("prev_chain_digest"),
    chainDigest: text("chain_digest").notNull(),
  },
  (t) => ({
    recordSeqIdx: uniqueIndex("context_promotions_record_seq_idx").on(
      t.recordId,
      t.seq,
    ),
    orgIdx: index("context_promotions_org_idx").on(t.orgId, t.workspaceId),
    actionCheck: check(
      "context_promotions_action_check",
      sql`${t.action} IN ('promote', 'retire', 'supersede')`,
    ),
    seqCheck: check("context_promotions_seq_check", sql`${t.seq} > 0`),
    chainCheck: check(
      "context_promotions_chain_check",
      sql`${t.chainDigest} ~ '^[0-9a-f]{64}$' AND (${t.prevChainDigest} IS NULL OR ${t.prevChainDigest} ~ '^[0-9a-f]{64}$') AND ((${t.seq} = 1) = (${t.prevChainDigest} IS NULL))`,
    ),
  }),
);
