/**
 * emoji-data.ts — the curated, dependency-free emoji set behind the avatar
 * maker's Design tab emoji picker. No emoji package dependency: a small
 * static table is plenty for "pick an icon for your avatar" and keeps the
 * bundle light (see oxagen-engineering-policy §1 — prefer no dependency over
 * a heavy one for a small, stable need).
 *
 * Each entry carries a couple of search keywords so the picker's text filter
 * can match on synonyms, not just the category name.
 */

export interface EmojiEntry {
  emoji: string;
  keywords: readonly string[];
}

export interface EmojiCategory {
  id: string;
  label: string;
  entries: readonly EmojiEntry[];
}

export const EMOJI_CATEGORIES: readonly EmojiCategory[] = [
  {
    id: "smileys",
    label: "Smileys",
    entries: [
      { emoji: "😀", keywords: ["grin", "happy", "smile"] },
      { emoji: "😃", keywords: ["smile", "happy", "joy"] },
      { emoji: "😄", keywords: ["smile", "happy", "laugh"] },
      { emoji: "😁", keywords: ["grin", "smile", "teeth"] },
      { emoji: "😆", keywords: ["laugh", "happy", "haha"] },
      { emoji: "😅", keywords: ["sweat", "laugh", "relief"] },
      { emoji: "🤣", keywords: ["rofl", "laugh", "funny"] },
      { emoji: "😂", keywords: ["tears", "laugh", "joy"] },
      { emoji: "🙂", keywords: ["smile", "slight", "calm"] },
      { emoji: "🙃", keywords: ["upside", "down", "silly"] },
      { emoji: "😉", keywords: ["wink", "flirt"] },
      { emoji: "😊", keywords: ["blush", "smile", "happy"] },
      { emoji: "😇", keywords: ["halo", "angel", "innocent"] },
      { emoji: "🥰", keywords: ["hearts", "love", "adore"] },
      { emoji: "😍", keywords: ["heart", "eyes", "love"] },
      { emoji: "🤩", keywords: ["star", "eyes", "excited"] },
      { emoji: "😘", keywords: ["kiss", "love", "blow"] },
      { emoji: "😎", keywords: ["cool", "sunglasses", "chill"] },
      { emoji: "🤓", keywords: ["nerd", "glasses", "smart"] },
      { emoji: "🤔", keywords: ["thinking", "hmm", "ponder"] },
      { emoji: "😴", keywords: ["sleep", "zzz", "tired"] },
      { emoji: "🤯", keywords: ["mind", "blown", "shock"] },
      { emoji: "🥳", keywords: ["party", "celebrate", "confetti"] },
    ],
  },
  {
    id: "people",
    label: "People",
    entries: [
      { emoji: "👶", keywords: ["baby", "infant"] },
      { emoji: "🧒", keywords: ["child", "kid"] },
      { emoji: "🧑", keywords: ["person", "adult"] },
      { emoji: "👨", keywords: ["man"] },
      { emoji: "👩", keywords: ["woman"] },
      { emoji: "🧓", keywords: ["elder", "older", "person"] },
      { emoji: "👴", keywords: ["old", "man", "grandpa"] },
      { emoji: "👵", keywords: ["old", "woman", "grandma"] },
      { emoji: "🧑‍💻", keywords: ["developer", "coder", "programmer"] },
      { emoji: "👩‍💻", keywords: ["developer", "coder", "woman"] },
      { emoji: "👨‍💻", keywords: ["developer", "coder", "man"] },
      { emoji: "🧑‍🎨", keywords: ["artist", "creative"] },
      { emoji: "🧑‍🚀", keywords: ["astronaut", "space"] },
      { emoji: "🧑‍🔬", keywords: ["scientist", "lab"] },
      { emoji: "🧑‍🏫", keywords: ["teacher", "professor"] },
      { emoji: "🧑‍⚕️", keywords: ["doctor", "medic", "health"] },
      { emoji: "🧑‍🚒", keywords: ["firefighter", "fire"] },
      { emoji: "🕵️", keywords: ["detective", "spy", "sleuth"] },
      { emoji: "🤴", keywords: ["prince", "royal"] },
      { emoji: "👸", keywords: ["princess", "royal"] },
      { emoji: "🦸", keywords: ["superhero", "hero"] },
      { emoji: "👻", keywords: ["ghost", "spooky"] },
      { emoji: "🤖", keywords: ["robot", "bot", "ai"] },
    ],
  },
  {
    id: "animals",
    label: "Animals & Nature",
    entries: [
      { emoji: "🐶", keywords: ["dog", "puppy", "pet"] },
      { emoji: "🐱", keywords: ["cat", "kitten", "pet"] },
      { emoji: "🐭", keywords: ["mouse"] },
      { emoji: "🐹", keywords: ["hamster"] },
      { emoji: "🐰", keywords: ["rabbit", "bunny"] },
      { emoji: "🦊", keywords: ["fox"] },
      { emoji: "🐻", keywords: ["bear"] },
      { emoji: "🐼", keywords: ["panda"] },
      { emoji: "🐨", keywords: ["koala"] },
      { emoji: "🐯", keywords: ["tiger"] },
      { emoji: "🦁", keywords: ["lion"] },
      { emoji: "🐮", keywords: ["cow"] },
      { emoji: "🐷", keywords: ["pig"] },
      { emoji: "🐸", keywords: ["frog"] },
      { emoji: "🐵", keywords: ["monkey"] },
      { emoji: "🐔", keywords: ["chicken"] },
      { emoji: "🐧", keywords: ["penguin"] },
      { emoji: "🐦", keywords: ["bird"] },
      { emoji: "🦆", keywords: ["duck"] },
      { emoji: "🦅", keywords: ["eagle"] },
      { emoji: "🦉", keywords: ["owl"] },
      { emoji: "🐴", keywords: ["horse"] },
      { emoji: "🦄", keywords: ["unicorn", "magic"] },
      { emoji: "🐝", keywords: ["bee", "insect"] },
      { emoji: "🦋", keywords: ["butterfly"] },
      { emoji: "🐢", keywords: ["turtle"] },
    ],
  },
  {
    id: "food",
    label: "Food",
    entries: [
      { emoji: "🍏", keywords: ["apple", "green"] },
      { emoji: "🍎", keywords: ["apple", "red"] },
      { emoji: "🍐", keywords: ["pear"] },
      { emoji: "🍊", keywords: ["orange", "tangerine"] },
      { emoji: "🍋", keywords: ["lemon"] },
      { emoji: "🍌", keywords: ["banana"] },
      { emoji: "🍉", keywords: ["watermelon"] },
      { emoji: "🍇", keywords: ["grapes"] },
      { emoji: "🍓", keywords: ["strawberry"] },
      { emoji: "🍒", keywords: ["cherries"] },
      { emoji: "🍑", keywords: ["peach"] },
      { emoji: "🥭", keywords: ["mango"] },
      { emoji: "🍍", keywords: ["pineapple"] },
      { emoji: "🥥", keywords: ["coconut"] },
      { emoji: "🥝", keywords: ["kiwi"] },
      { emoji: "🍅", keywords: ["tomato"] },
      { emoji: "🍕", keywords: ["pizza"] },
      { emoji: "🍔", keywords: ["burger", "hamburger"] },
      { emoji: "🍣", keywords: ["sushi"] },
      { emoji: "🍩", keywords: ["donut", "doughnut"] },
      { emoji: "🍪", keywords: ["cookie"] },
      { emoji: "🎂", keywords: ["cake", "birthday"] },
      { emoji: "🍫", keywords: ["chocolate"] },
      { emoji: "☕", keywords: ["coffee"] },
      { emoji: "🍺", keywords: ["beer"] },
    ],
  },
  {
    id: "activities",
    label: "Activities",
    entries: [
      { emoji: "⚽", keywords: ["soccer", "football"] },
      { emoji: "🏀", keywords: ["basketball"] },
      { emoji: "🏈", keywords: ["football", "american"] },
      { emoji: "⚾", keywords: ["baseball"] },
      { emoji: "🎾", keywords: ["tennis"] },
      { emoji: "🏐", keywords: ["volleyball"] },
      { emoji: "🎱", keywords: ["billiards", "pool", "8ball"] },
      { emoji: "🏓", keywords: ["ping pong", "table tennis"] },
      { emoji: "🥊", keywords: ["boxing", "glove"] },
      { emoji: "⛳", keywords: ["golf"] },
      { emoji: "🎯", keywords: ["dart", "target", "bullseye"] },
      { emoji: "🎮", keywords: ["game", "controller", "gaming"] },
      { emoji: "🎨", keywords: ["art", "palette", "paint"] },
      { emoji: "🎭", keywords: ["theater", "drama", "masks"] },
      { emoji: "🎸", keywords: ["guitar", "music"] },
      { emoji: "🎹", keywords: ["piano", "keyboard", "music"] },
      { emoji: "🎤", keywords: ["mic", "microphone", "sing"] },
      { emoji: "🎧", keywords: ["headphones", "music"] },
      { emoji: "🧩", keywords: ["puzzle"] },
      { emoji: "🏆", keywords: ["trophy", "win", "champion"] },
      { emoji: "🚴", keywords: ["cycling", "bike"] },
      { emoji: "🏄", keywords: ["surf", "surfing"] },
      { emoji: "🏃", keywords: ["run", "running"] },
    ],
  },
  {
    id: "objects",
    label: "Objects",
    entries: [
      { emoji: "⌚", keywords: ["watch", "time"] },
      { emoji: "📱", keywords: ["phone", "mobile"] },
      { emoji: "💻", keywords: ["laptop", "computer"] },
      { emoji: "⌨️", keywords: ["keyboard"] },
      { emoji: "🖥️", keywords: ["desktop", "monitor"] },
      { emoji: "🖱️", keywords: ["mouse"] },
      { emoji: "💾", keywords: ["disk", "save"] },
      { emoji: "📷", keywords: ["camera", "photo"] },
      { emoji: "🎥", keywords: ["camera", "video", "movie"] },
      { emoji: "📞", keywords: ["phone", "call"] },
      { emoji: "📺", keywords: ["tv", "television"] },
      { emoji: "🎙️", keywords: ["mic", "studio"] },
      { emoji: "⏰", keywords: ["alarm", "clock"] },
      { emoji: "🔋", keywords: ["battery"] },
      { emoji: "🔌", keywords: ["plug", "power"] },
      { emoji: "💡", keywords: ["bulb", "idea", "light"] },
      { emoji: "📚", keywords: ["books", "library"] },
      { emoji: "📝", keywords: ["note", "memo", "write"] },
      { emoji: "📎", keywords: ["paperclip", "attach"] },
      { emoji: "🔑", keywords: ["key", "unlock"] },
      { emoji: "🔒", keywords: ["lock", "secure"] },
      { emoji: "🛠️", keywords: ["tools", "wrench", "build"] },
      { emoji: "⚙️", keywords: ["gear", "settings", "config"] },
      { emoji: "🧭", keywords: ["compass", "navigate"] },
      { emoji: "🚀", keywords: ["rocket", "launch", "startup"] },
    ],
  },
  {
    id: "symbols",
    label: "Symbols",
    entries: [
      { emoji: "❤️", keywords: ["heart", "love", "red"] },
      { emoji: "🧡", keywords: ["heart", "orange"] },
      { emoji: "💛", keywords: ["heart", "yellow"] },
      { emoji: "💚", keywords: ["heart", "green"] },
      { emoji: "💙", keywords: ["heart", "blue"] },
      { emoji: "💜", keywords: ["heart", "purple"] },
      { emoji: "🖤", keywords: ["heart", "black"] },
      { emoji: "🤍", keywords: ["heart", "white"] },
      { emoji: "⭐", keywords: ["star", "favorite"] },
      { emoji: "🌟", keywords: ["star", "sparkle", "glow"] },
      { emoji: "✨", keywords: ["sparkles", "shiny", "magic"] },
      { emoji: "🔥", keywords: ["fire", "hot", "flame"] },
      { emoji: "⚡", keywords: ["bolt", "lightning", "energy"] },
      { emoji: "💧", keywords: ["drop", "water"] },
      { emoji: "🌈", keywords: ["rainbow"] },
      { emoji: "☀️", keywords: ["sun", "sunny"] },
      { emoji: "🌙", keywords: ["moon", "night"] },
      { emoji: "☁️", keywords: ["cloud"] },
      { emoji: "❄️", keywords: ["snowflake", "cold"] },
      { emoji: "✅", keywords: ["check", "done", "yes"] },
      { emoji: "⚠️", keywords: ["warning", "alert"] },
      { emoji: "🔔", keywords: ["bell", "notification"] },
      { emoji: "💎", keywords: ["gem", "diamond"] },
      { emoji: "🎉", keywords: ["party", "celebrate", "confetti"] },
      { emoji: "🎲", keywords: ["dice", "game", "random"] },
    ],
  },
];

/** Flat list of every entry, for the "all categories" filtered view. */
export const ALL_EMOJI_ENTRIES: readonly EmojiEntry[] =
  EMOJI_CATEGORIES.flatMap((c) => c.entries);
