// documents.generate.ts — real DOCX / XLSX / PPTX generation using vendor-neutral
// in-process encoders (docx, exceljs, pptxgenjs). No cloud OAuth required.
// The generated bytes are uploaded to blob storage via persistGeneratedAsset(),
// which is the single seam for all generated-asset uploads.

import type { CapabilityHandler } from "@oxagen/oxagen";
import {
  documentsGenerate,
  type DocumentsGenerateInput,
} from "@oxagen/oxagen/contracts/document.generate";
import { logger } from "./logger";
import { persistGeneratedAsset } from "./generated-asset.persist";

// ── DOCX builder ─────────────────────────────────────────────────────────────

async function buildDocx(
  title: string,
  content: DocumentsGenerateInput["content"],
): Promise<Uint8Array> {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import(
    "docx"
  );

  const sections = content?.sections ?? [
    { heading: undefined, paragraphs: [title] },
  ];
  const children: InstanceType<typeof Paragraph>[] = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.TITLE,
    }),
  ];

  for (const section of sections) {
    if (section.heading) {
      children.push(
        new Paragraph({
          text: section.heading,
          heading: HeadingLevel.HEADING_1,
        }),
      );
    }
    for (const para of section.paragraphs) {
      children.push(new Paragraph({ children: [new TextRun({ text: para })] }));
    }
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });

  // Use toBuffer() for Node.js — avoids Blob.arrayBuffer() compatibility concerns.
  const buffer = await Packer.toBuffer(doc);
  return new Uint8Array(buffer);
}

// ── XLSX builder ──────────────────────────────────────────────────────────────

async function buildXlsx(
  title: string,
  content: DocumentsGenerateInput["content"],
): Promise<Uint8Array> {
  // exceljs exports Workbook as a named export (CJS package, no default export).
  const { Workbook } = await import("exceljs");
  const workbook = new Workbook();
  workbook.creator = "Oxagen";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(title.slice(0, 31)); // Excel sheet name limit

  const headers = content?.headers ?? ["Column 1"];
  const rows = content?.rows ?? [];

  // Header row with bold formatting.
  sheet.addRow(headers).eachCell((cell) => {
    cell.font = { bold: true };
  });

  for (const row of rows) {
    sheet.addRow(row);
  }

  const buffer = await workbook.xlsx.writeBuffer();
  return new Uint8Array(buffer as ArrayBuffer);
}

// ── PPTX builder ──────────────────────────────────────────────────────────────

async function buildPptx(
  title: string,
  content: DocumentsGenerateInput["content"],
): Promise<Uint8Array> {
  const pptxgenjs = (await import("pptxgenjs")).default;
  const pres = new pptxgenjs();

  const slides = content?.slides ?? [{ title, bullets: [] }];

  for (const slide of slides) {
    const s = pres.addSlide();
    s.addText(slide.title, {
      x: 0.5,
      y: 0.5,
      w: 9,
      h: 1,
      fontSize: 28,
      bold: true,
    });
    if (slide.bullets && slide.bullets.length > 0) {
      s.addText(
        slide.bullets.map((b) => ({ text: b, options: { bullet: true } })),
        { x: 0.5, y: 1.8, w: 9, h: 4, fontSize: 18 },
      );
    }
  }

  // writeFile returns base64 when `outputType` is "base64"; decode to bytes.
  const base64 = await pres.write({ outputType: "base64" });
  const binaryStr = atob(base64 as string);
  const bytes = new Uint8Array(binaryStr.length);
  for (let i = 0; i < binaryStr.length; i++) {
    bytes[i] = binaryStr.charCodeAt(i);
  }
  return bytes;
}

// ── MIME map ──────────────────────────────────────────────────────────────────

const MIME_BY_KIND: Record<
  "document" | "spreadsheet" | "presentation",
  string
> = {
  document:
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  spreadsheet:
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  presentation:
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
};

const EXT_BY_KIND: Record<"document" | "spreadsheet" | "presentation", string> =
  {
    document: "docx",
    spreadsheet: "xlsx",
    presentation: "pptx",
  };

// ── Handler ───────────────────────────────────────────────────────────────────

export const documentsGenerateHandler: CapabilityHandler<
  typeof documentsGenerate
> = async (input, ctx) => {
  // Document generation requires a real user identity for the asset's ownership
  // row. An API-key-only call (no session user) would persist an anonymous asset,
  // which the access-policy model does not support for `user`-scoped assets.
  if (!ctx.userId) {
    throw new Error(
      "documents.generate: userId is required — no user identity in context",
    );
  }

  const { kind, title, content } = input;
  const mimeType = MIME_BY_KIND[kind];

  logger.info(
    { orgId: ctx.orgId, workspaceId: ctx.workspaceId, kind, title },
    "documents.generate: starting",
  );

  let bytes: Uint8Array;
  try {
    if (kind === "document") {
      bytes = await buildDocx(title, content);
    } else if (kind === "spreadsheet") {
      bytes = await buildXlsx(title, content);
    } else {
      bytes = await buildPptx(title, content);
    }
  } catch (err) {
    logger.error(
      { err, orgId: ctx.orgId, workspaceId: ctx.workspaceId, kind },
      "documents.generate: file encoding failed",
    );
    throw err;
  }

  const userId = ctx.userId; // narrowed to string by the guard above
  const asset = await persistGeneratedAsset({
    orgId: ctx.orgId,
    workspaceId: ctx.workspaceId,
    userId,
    kind,
    mimeType,
    bytes,
    // Prompt and model are synthetic for document generation — there is no
    // LLM call; record the operation name and "local" as the model token.
    prompt: `Generate ${kind}: ${title}`,
    model: "local",
    messageId: ctx.messageId ?? undefined,
    accessPolicy: "org",
  });

  logger.info(
    {
      orgId: ctx.orgId,
      workspaceId: ctx.workspaceId,
      kind,
      publicId: asset.publicId,
      sizeBytes: asset.sizeBytes,
    },
    "documents.generate: complete",
  );

  const filename = `${title}.${EXT_BY_KIND[kind]}`;

  return {
    assetId: asset.id,
    publicId: asset.publicId,
    kind,
    mimeType,
    sizeBytes: asset.sizeBytes,
    url: asset.url,
    serveUrl: asset.serveUrl,
    render: {
      componentId: "file-attachment",
      props: {
        url: asset.serveUrl,
        name: filename,
        kind,
        mimeType,
        sizeBytes: asset.sizeBytes,
      },
    },
  };
};
