// Generates src/i18n/messages.d.ts from every messages/*.json (INV-12,
// ARCHITECTURE.md §4): the next-intl AppConfig augmentation that types every
// t() key and namespace, so a key no catalog holds fails tsc. The catalogs
// are read and merged by src/i18n/load-catalogs.ts, the loader the app runs.
//
//   tsx scripts/gen-messages-types.ts           write the file
//   tsx scripts/gen-messages-types.ts --check   exit 1 when the file is stale (CI)
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { Messages } from "../src/i18n/catalogs";
import { loadCatalogs } from "../src/i18n/load-catalogs";

/** Where the generated declaration lives, relative to the app directory. */
export const MESSAGES_TYPES_FILE = "src/i18n/messages.d.ts";

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

function isNamespace(value: unknown): value is Messages {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function typeLiteral(messages: Messages, trail: string, depth: number): string {
  const pad = "  ".repeat(depth + 1);
  const members = Object.entries(messages).map(([key, value]) => {
    const name = IDENTIFIER.test(key) ? key : JSON.stringify(key);
    const at = trail ? `${trail}.${key}` : key;
    if (typeof value === "string") return `${pad}${name}: string;`;
    if (isNamespace(value))
      return `${pad}${name}: ${typeLiteral(value, at, depth + 1)};`;
    throw new Error(
      `messages: ${at} is neither a message string nor a namespace`,
    );
  });
  return `{\n${members.join("\n")}\n${"  ".repeat(depth)}}`;
}

/** The declaration file for a merged catalog. */
export function renderMessagesTypes(messages: Messages): string {
  return [
    `// Generated by scripts/gen-messages-types.ts from messages/*.json. Do not`,
    `// edit: run \`pnpm --filter @oxagen/app gen:messages\`; CI fails when this`,
    `// file is stale (INV-12).`,
    `type Messages = ${typeLiteral(messages, "", 0)};`,
    ``,
    `declare module "next-intl" {`,
    `  interface AppConfig {`,
    `    Messages: Messages;`,
    `  }`,
    `}`,
    ``,
    `export {};`,
    ``,
  ].join("\n");
}

/** Writes the file, or with `--check` compares it; returns the exit code. */
export function run(args: readonly string[], appDir: string): number {
  const file = path.join(appDir, MESSAGES_TYPES_FILE);
  const expected = renderMessagesTypes(
    loadCatalogs(path.join(appDir, "messages")),
  );
  if (!args.includes("--check")) {
    writeFileSync(file, expected);
    return 0;
  }
  let actual: string | null;
  try {
    actual = readFileSync(file, "utf8");
  } catch {
    actual = null;
  }
  if (actual === expected) return 0;
  console.error(
    `${MESSAGES_TYPES_FILE} is stale: run \`pnpm --filter @oxagen/app gen:messages\` and commit the result.`,
  );
  return 1;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  process.exitCode = run(
    process.argv.slice(2),
    fileURLToPath(new URL("..", import.meta.url)),
  );
}
