import { z } from "zod";
import type { ModelMessage } from "ai";
import { generateObjectFor, selectModel } from "@oxagen/ai";
import { logger } from "@oxagen/handlers/logger";

/**
 * suggest-prompts.ts — per-turn, conversation-aware "next step" suggestions.
 *
 * After every assistant turn the chat UI shows exactly 3 chips that propose
 * concrete NEXT prompts the user could send. Unlike the static page-context
 * heuristics in `@/lib/page-context/suggested-prompts` (the no-LLM fallback),
 * these are generated by a fast model that reads the conversation so far and
 * proposes prompts that push the user toward BUILDING something real in Oxagen.
 *
 * Contract: best-effort. This runs AFTER the assistant's answer has already
 * streamed, so any failure (model error, timeout, DB error) returns null and
 * the turn completes unaffected — it must NEVER delay or break the turn.
 */

/** A single generated suggestion chip. */
export interface TurnSuggestion {
  /** Short, title-cased button label (≤5 words). */
  label: string;
  /** The full imperative message sent verbatim when the chip is activated. */
  prompt: string;
}

/** A minimal conversation turn used to ground the suggestions. */
export interface SuggestionTurn {
  role: "user" | "assistant";
  /** Message text (already truncated by the caller). */
  content: string;
}

export interface GenerateTurnSuggestionsInput {
  /** Recent conversation turns (caller trims to ~last 8, ~500 chars each). */
  recentTurns: SuggestionTurn[];
  orgId: string;
  workspaceId: string;
  /**
   * UUID of the message that initiated the turn — flows into token_usage /
   * credit_ledger as the correlation key. MUST be a valid UUID or null.
   */
  messageId: string | null;
  /** Org slug, when cheaply available — lightly grounds the prompts. */
  orgSlug?: string;
  /** Workspace slug, when cheaply available. */
  workspaceSlug?: string;
}

// Exactly 3 suggestions. Char caps keep the label chip-sized and the prompt a
// short imperative message; word-count ("≤5 words") is steered via the system
// prompt + .describe() since zod can't cheaply enforce it.
const suggestionsSchema = z.object({
  suggestions: z
    .array(
      z.object({
        label: z
          .string()
          .min(1)
          .max(40)
          .describe("Button label, Title Case, at most 5 words."),
        prompt: z
          .string()
          .min(1)
          .max(400)
          .describe(
            "1–3 sentence imperative message written exactly as the user would send it.",
          ),
      }),
    )
    .length(3),
});

/**
 * System prompt for the next-step suggestion engine. Kept as a function (not a
 * const) to mirror the `@oxagen/ai` prompt-builder convention and keep the call
 * site tidy.
 */
function suggestionSystemPrompt(): string {
  return [
    "You are Oxagen's next-step suggestion engine.",
    "",
    "Oxagen is a platform where teams build, govern, meter, and resell AI agents.",
    "In Oxagen a user can: create agents and equip them with tools and skills;",
    "connect knowledge sources into a Neo4j knowledge graph and query it;",
    "define automations and workflows; expose capabilities over MCP and a REST API;",
    "track usage and configure billing meters; run eval suites; and publish agents",
    "and tools to a marketplace.",
    "",
    "Given the conversation so far, propose exactly 3 concrete NEXT prompts the",
    "user could send next that BOTH:",
    "  (a) build directly on what was just discussed, and",
    "  (b) lead the user toward BUILDING or CREATING something real in Oxagen —",
    "      an agent, an automation, a connector, a graph query, an eval suite, a",
    "      billing meter, an MCP tool, a workflow — including ideas they may not",
    "      have thought of yet.",
    "",
    "Be creative and specific to THIS conversation. Do not be hesitant to suggest",
    "something ambitious the user has not considered. Never produce generic filler",
    'like "summarize this conversation", "tell me more", or "what can I do here".',
    "",
    "Each prompt must be self-contained and written in the first person as an",
    "imperative message the user sends to the assistant (e.g. \"Create an agent",
    'that ...", "Wire the results above into the knowledge graph as ..."). The',
    "assistant receiving the prompt sees this same conversation, so refer to prior",
    "context naturally rather than restating it.",
    "",
    "Return exactly 3 suggestions. Each label is Title Case and at most 5 words.",
  ].join("\n");
}

/** Render the recent turns into a compact transcript for the model. */
function renderTranscript(turns: SuggestionTurn[]): string {
  return turns
    .map((t) => {
      const speaker = t.role === "user" ? "User" : "Assistant";
      return `${speaker}: ${t.content}`;
    })
    .join("\n\n");
}

/** How many recent turns to feed the model, and how much of each to keep. */
const DEFAULT_MAX_TURNS = 8;
const DEFAULT_MAX_CHARS = 500;

/**
 * Flatten a `ModelMessage` content field (string, or an array of typed parts)
 * into plain text. Only text parts contribute — tool calls, images, and files
 * are dropped since the suggestion model reasons over the conversation's prose.
 */
export function extractTurnText(content: ModelMessage["content"]): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .map((part) =>
      part && typeof part === "object" && "type" in part && part.type === "text"
        ? (part as { text: string }).text
        : "",
    )
    .filter((t) => t.length > 0)
    .join(" ");
}

/**
 * Build the trimmed recent-turn transcript the suggestion model sees: the prior
 * user/assistant history plus this turn's user message and assistant reply.
 * Tool/system messages are dropped; each turn is truncated to `maxChars` and
 * only the last `maxTurns` are kept. Pure — exported for the route + tests.
 */
export function buildRecentTurns(
  history: ModelMessage[],
  current: { userText: string; assistantText: string },
  opts: { maxTurns?: number; maxChars?: number } = {},
): SuggestionTurn[] {
  const maxTurns = opts.maxTurns ?? DEFAULT_MAX_TURNS;
  const maxChars = opts.maxChars ?? DEFAULT_MAX_CHARS;

  const turns: SuggestionTurn[] = [];
  for (const m of history) {
    if (m.role !== "user" && m.role !== "assistant") continue;
    const text = extractTurnText(m.content).trim();
    if (text.length === 0) continue;
    turns.push({ role: m.role, content: text.slice(0, maxChars) });
  }

  const userText = current.userText.trim();
  if (userText.length > 0) {
    turns.push({ role: "user", content: userText.slice(0, maxChars) });
  }
  const assistantText = current.assistantText.trim();
  if (assistantText.length > 0) {
    turns.push({ role: "assistant", content: assistantText.slice(0, maxChars) });
  }

  return turns.slice(-maxTurns);
}

/** Timeout for the whole suggestion generation. Fail-open past this. */
const SUGGESTION_TIMEOUT_MS = 6_000;

/**
 * Generate 3 conversation-aware next-step suggestions. Returns null on any
 * failure, empty input, or timeout — the caller treats null as "no chips this
 * turn" and falls back to the static page-context heuristics.
 */
export async function generateTurnSuggestions(
  input: GenerateTurnSuggestionsInput,
): Promise<TurnSuggestion[] | null> {
  const turns = input.recentTurns.filter((t) => t.content.trim().length > 0);
  // Nothing to ground on — let the static fallback handle the empty state.
  if (turns.length === 0) return null;

  const workspaceLine =
    input.orgSlug && input.workspaceSlug
      ? `Workspace: ${input.orgSlug}/${input.workspaceSlug}\n\n`
      : "";

  try {
    const generation = generateObjectFor({
      schema: suggestionsSchema,
      model: selectModel({ tier: "fast" }),
      system: suggestionSystemPrompt(),
      prompt: `${workspaceLine}Conversation so far:\n\n${renderTranscript(turns)}`,
      // A little warmth so the trio varies turn-to-turn and surfaces ideas the
      // user has not considered — but not so hot the prompts drift off-topic.
      temperature: 0.8,
      // The turn's answer is already streamed; the engine (not the SDK) owns
      // resilience here, and a retry would blow the fail-open timeout budget.
      maxRetries: 0,
      // Cancel the underlying model call if we blow the budget. The Promise.race
      // below is a belt-and-suspenders guard in case the signal is honored late.
      abortSignal: AbortSignal.timeout(SUGGESTION_TIMEOUT_MS),
      telemetry: {
        orgId: input.orgId,
        workspaceId: input.workspaceId,
        surface: "app",
        messageId: input.messageId,
      },
      // NEVER cache: suggestions must vary with the exact conversation.
    });

    const timeout = new Promise<null>((resolve) =>
      setTimeout(() => resolve(null), SUGGESTION_TIMEOUT_MS + 250),
    );

    const result = await Promise.race([generation, timeout]);
    if (!result) return null;

    const suggestions = result.object.suggestions
      .map((s) => ({ label: s.label.trim(), prompt: s.prompt.trim() }))
      .filter((s) => s.label.length > 0 && s.prompt.length > 0);

    return suggestions.length === 3 ? suggestions : null;
  } catch (err) {
    // Best-effort — a suggestion failure must never affect the chat turn, but
    // don't swallow it silently: a persistent failure is otherwise invisible.
    logger.warn({ err }, "[suggest-prompts] generation failed — skipping");
    return null;
  }
}
