import { z } from "zod";
import type { ModelMessage } from "ai";
import { generateObjectFor, selectModel } from "@oxagen/ai";
import { logger } from "@oxagen/handlers/logger";

/**
 * suggest-prompts.ts — per-turn, conversation-aware "next step" suggestions.
 *
 * After every assistant turn the chat UI shows exactly 3 chips that propose
 * concrete NEXT prompts the user could send. Unlike the static page-context
 * heuristics in `@/lib/page-context/suggested-prompts` (the no-LLM fallback),
 * these are generated by a fast model that reads the conversation so far —
 * including the turn's TOOL ACTIVITY (capabilities invoked, inputs, failures,
 * files changed) — and proposes specific, actionable next tasks grounded in
 * what actually happened, not generic product-tour filler.
 *
 * Contract: best-effort. This runs AFTER the assistant's answer has already
 * streamed, so any failure (model error, timeout, DB error) returns null and
 * the turn completes unaffected — it must NEVER delay or break the turn.
 */

/** A single generated suggestion chip. */
export interface TurnSuggestion {
  /** Short, verb-first button label (2–4 words). */
  label: string;
  /** The full task brief sent verbatim when the chip is activated. */
  prompt: string;
}

/** A minimal conversation turn used to ground the suggestions. */
export interface SuggestionTurn {
  role: "user" | "assistant";
  /** Message text (already truncated by the caller). */
  content: string;
}

/**
 * A compact record of one tool call made during the turn. Derived from the
 * translator's persisted content blocks — the same source the trace UI renders
 * — so the suggestion model sees what the agent actually DID, not just what it
 * said. Failures are prime next-step material ("Fix Failing Migration" beats
 * "Automate This" every time).
 */
export interface TurnToolActivity {
  /** Capability / tool name as shown to the user (e.g. `search_repo`). */
  capability: string;
  /** One-line rendering of the tool input (paths, queries, ids). */
  inputPreview?: string;
  /** Set when the call failed — the reason string from the block. */
  errorReason?: string;
}

export interface GenerateTurnSuggestionsInput {
  /** Recent conversation turns (caller trims via `buildRecentTurns`). */
  recentTurns: SuggestionTurn[];
  orgId: string;
  workspaceId: string;
  /**
   * UUID of the message that initiated the turn — flows into token_usage /
   * credit_ledger as the correlation key. MUST be a valid UUID or null.
   */
  messageId: string | null;
  /** Org slug, when cheaply available — lightly grounds the prompts. */
  orgSlug?: string;
  /** Workspace slug, when cheaply available. */
  workspaceSlug?: string;
  /** Tool calls made this turn (see `extractToolActivity`). */
  toolActivity?: TurnToolActivity[];
  /** Files the agent changed this turn (engine `result.changedFiles`). */
  changedFiles?: string[];
  /**
   * True when the turn ran under the code-mode system prompt — steers the
   * suggestions toward engineering tasks against the real repo.
   */
  codeMode?: boolean;
}

// Exactly 3 suggestions. The label cap keeps the chip compact; the prompt cap
// allows a real multi-sentence task brief while staying safely inside the
// 6s fail-open generation budget (≈3×150 output tokens on the fast tier).
// Word-count steering ("2–4 words") lives in the system prompt + .describe()
// since zod can't cheaply enforce it.
const suggestionsSchema = z.object({
  suggestions: z
    .array(
      z.object({
        label: z
          .string()
          .min(1)
          .max(40)
          .describe("Chip label: 2–4 words, Title Case, verb-first."),
        prompt: z
          .string()
          .min(1)
          .max(600)
          .describe(
            "Complete 2–4 sentence task brief written exactly as the user " +
              "would send it: imperative goal, the concrete targets from " +
              "this conversation, and what done looks like.",
          ),
      }),
    )
    .length(3),
});

/**
 * System prompt for the next-step suggestion engine. Kept as a function (not a
 * const) to mirror the `@oxagen/ai` prompt-builder convention and keep the call
 * site tidy. `codeMode` appends a coding-session steer so suggestions become
 * engineering tasks against the actual files/errors in play.
 */
function suggestionSystemPrompt(opts: { codeMode: boolean }): string {
  const lines = [
    "You are Oxagen's next-step suggestion engine. After each assistant reply",
    "the chat UI shows exactly 3 chips; each chip is a TASK the user can hand",
    "straight back to the agent. Propose the 3 most valuable next tasks for",
    "THIS conversation.",
    "",
    "Relevance is the law. Every suggestion must be anchored in concrete",
    "specifics that appear in the conversation or the tool activity: file",
    "paths, entity or agent names, error messages, queries, numbers, decisions.",
    "If a suggestion would read equally well in a different conversation, it is",
    "generic filler — discard it and look closer at what actually happened.",
    "",
    "Aim the trio at three distinct directions (when the conversation supports",
    "it):",
    "  1. FINISH — the most obvious continuation: the next concrete step of the",
    "     work in flight, or the fix for an error/failure that surfaced this",
    "     turn (a failed tool call is always the strongest candidate).",
    "  2. VERIFY — prove or harden what was just produced: run or write a test,",
    "     probe an edge case, validate against real data, re-check a risky",
    "     assumption the assistant made.",
    "  3. EXTEND — an ambitious but directly buildable step the user may not",
    "     have considered, growing this work into something durable.",
    "",
    "Where it genuinely fits, prefer EXTEND steps that exercise Oxagen",
    "capability — turn the result into a reusable agent, an automation, an eval",
    "suite, a knowledge-graph addition, a billing meter, or an MCP tool. Never",
    "force this at the cost of relevance.",
    "",
    "Write each prompt as a complete task brief the agent could execute without",
    "follow-up questions, 2–4 sentences: the imperative goal, the concrete",
    "targets (the actual paths / names / ids from the conversation), any",
    "constraint that matters, and what done looks like (a check, a test, an",
    "observable result). First person, written exactly as the user would send",
    "it. The agent receiving it sees this same conversation, so refer to prior",
    'context naturally ("the failing test above") instead of restating it.',
    "",
    'Labels are 2–4 words, Title Case, verb-first (e.g. "Fix Failing Test",',
    '"Wire The Route", "Meter This Agent"), unique within the trio.',
    "",
    'Never produce: "summarize this conversation", "tell me more", "explain',
    'that again", "what can I do here", or a restatement of work already',
    "completed this turn.",
  ];
  if (opts.codeMode) {
    lines.push(
      "",
      "This conversation is a coding session against a real repository. Every",
      "suggestion must be an engineering task — fix, test, refactor, wire,",
      "migrate, ship — that names the actual files, branches, commands, or",
      "errors from the tool activity below.",
    );
  }
  return lines.join("\n");
}

/** Render the recent turns into a compact transcript for the model. */
function renderTranscript(turns: SuggestionTurn[]): string {
  return turns
    .map((t) => {
      const speaker = t.role === "user" ? "User" : "Assistant";
      return `${speaker}: ${t.content}`;
    })
    .join("\n\n");
}

/** Caps for the activity digest — keep the grounding rich but bounded. */
const MAX_ACTIVITY_ENTRIES = 12;
const MAX_CHANGED_FILES = 20;
const MAX_INPUT_PREVIEW_CHARS = 160;

/**
 * Minimal structural view of a persisted assistant content block. Structural
 * (not imported from stream-event-types) so this server module stays
 * self-contained and trivially testable.
 */
interface ContentBlockLike {
  type: string;
  capability?: unknown;
  inputPreview?: unknown;
  errorReason?: unknown;
}

/**
 * Distill the turn's persisted content blocks into the compact tool-activity
 * records the suggestion model grounds on. Only `tool-call` blocks contribute;
 * inputs are JSON-rendered and clipped so a huge file write can't blow the
 * prompt budget. Pure — exported for the route + tests.
 */
export function extractToolActivity(
  blocks: ReadonlyArray<object>,
): TurnToolActivity[] {
  const activity: TurnToolActivity[] = [];
  for (const block of blocks) {
    const b = block as ContentBlockLike;
    if (b.type !== "tool-call" || typeof b.capability !== "string") continue;
    const entry: TurnToolActivity = { capability: b.capability };
    if (b.inputPreview !== undefined && b.inputPreview !== null) {
      try {
        const rendered =
          typeof b.inputPreview === "string"
            ? b.inputPreview
            : JSON.stringify(b.inputPreview);
        if (rendered && rendered.length > 0) {
          entry.inputPreview = rendered.slice(0, MAX_INPUT_PREVIEW_CHARS);
        }
      } catch {
        // Unserializable preview (circular) — the capability name alone is
        // still useful grounding; drop only the preview.
      }
    }
    if (typeof b.errorReason === "string" && b.errorReason.length > 0) {
      entry.errorReason = b.errorReason.slice(0, MAX_INPUT_PREVIEW_CHARS);
    }
    activity.push(entry);
  }
  return activity;
}

/**
 * Render the turn's tool activity + changed files as a prompt section. Returns
 * "" when there is nothing to report so the caller can skip the section.
 */
export function renderTurnActivity(
  toolActivity: TurnToolActivity[],
  changedFiles: string[],
): string {
  const parts: string[] = [];

  if (toolActivity.length > 0) {
    const shown = toolActivity.slice(0, MAX_ACTIVITY_ENTRIES);
    const lines = shown.map((a) => {
      const input = a.inputPreview ? `(${a.inputPreview})` : "";
      const failure = a.errorReason ? ` — FAILED: ${a.errorReason}` : "";
      return `- ${a.capability}${input}${failure}`;
    });
    const dropped = toolActivity.length - shown.length;
    if (dropped > 0) lines.push(`- …and ${dropped} more tool calls`);
    parts.push(`Tool activity this turn:\n${lines.join("\n")}`);
  }

  if (changedFiles.length > 0) {
    const shown = changedFiles.slice(0, MAX_CHANGED_FILES);
    const lines = shown.map((f) => `- ${f}`);
    const dropped = changedFiles.length - shown.length;
    if (dropped > 0) lines.push(`- …and ${dropped} more files`);
    parts.push(`Files changed this turn:\n${lines.join("\n")}`);
  }

  return parts.join("\n\n");
}

/** How many recent turns to feed the model, and how much of each to keep. */
const DEFAULT_MAX_TURNS = 8;
const DEFAULT_MAX_CHARS = 500;
/**
 * The current turn (this user message + this assistant reply) keeps far more
 * text than trailing history — it is what the suggestions must build on, and
 * 500 chars routinely cut off the very specifics (file paths, error text,
 * conclusions) that make a suggestion non-generic.
 */
const DEFAULT_CURRENT_MAX_CHARS = 2000;

/**
 * Flatten a `ModelMessage` content field (string, or an array of typed parts)
 * into plain text. Only text parts contribute — tool calls, images, and files
 * are dropped since the suggestion model reasons over the conversation's prose.
 */
export function extractTurnText(content: ModelMessage["content"]): string {
  if (typeof content === "string") return content;
  if (!Array.isArray(content)) return "";
  return content
    .map((part) =>
      part && typeof part === "object" && "type" in part && part.type === "text"
        ? (part as { text: string }).text
        : "",
    )
    .filter((t) => t.length > 0)
    .join(" ");
}

/**
 * Build the trimmed recent-turn transcript the suggestion model sees: the prior
 * user/assistant history plus this turn's user message and assistant reply.
 * Tool/system messages are dropped; each history turn is truncated to
 * `maxChars`, the current turn to the more generous `currentMaxChars`, and
 * only the last `maxTurns` are kept. Pure — exported for the route + tests.
 */
export function buildRecentTurns(
  history: ModelMessage[],
  current: { userText: string; assistantText: string },
  opts: { maxTurns?: number; maxChars?: number; currentMaxChars?: number } = {},
): SuggestionTurn[] {
  const maxTurns = opts.maxTurns ?? DEFAULT_MAX_TURNS;
  const maxChars = opts.maxChars ?? DEFAULT_MAX_CHARS;
  const currentMaxChars = opts.currentMaxChars ?? DEFAULT_CURRENT_MAX_CHARS;

  const turns: SuggestionTurn[] = [];
  for (const m of history) {
    if (m.role !== "user" && m.role !== "assistant") continue;
    const text = extractTurnText(m.content).trim();
    if (text.length === 0) continue;
    turns.push({ role: m.role, content: text.slice(0, maxChars) });
  }

  const userText = current.userText.trim();
  if (userText.length > 0) {
    turns.push({ role: "user", content: userText.slice(0, currentMaxChars) });
  }
  const assistantText = current.assistantText.trim();
  if (assistantText.length > 0) {
    turns.push({
      role: "assistant",
      content: assistantText.slice(0, currentMaxChars),
    });
  }

  return turns.slice(-maxTurns);
}

/** Timeout for the whole suggestion generation. Fail-open past this. */
const SUGGESTION_TIMEOUT_MS = 6_000;

/**
 * Generate 3 conversation-aware next-step suggestions. Returns null on any
 * failure, empty input, or timeout — the caller treats null as "no chips this
 * turn" and falls back to the static page-context heuristics.
 */
export async function generateTurnSuggestions(
  input: GenerateTurnSuggestionsInput,
): Promise<TurnSuggestion[] | null> {
  const turns = input.recentTurns.filter((t) => t.content.trim().length > 0);
  // Nothing to ground on — let the static fallback handle the empty state.
  if (turns.length === 0) return null;

  const sections: string[] = [];
  if (input.orgSlug && input.workspaceSlug) {
    sections.push(`Workspace: ${input.orgSlug}/${input.workspaceSlug}`);
  }
  const activity = renderTurnActivity(
    input.toolActivity ?? [],
    input.changedFiles ?? [],
  );
  if (activity.length > 0) sections.push(activity);
  sections.push(`Conversation so far:\n\n${renderTranscript(turns)}`);

  try {
    const generation = generateObjectFor({
      schema: suggestionsSchema,
      model: selectModel({ tier: "fast" }),
      system: suggestionSystemPrompt({ codeMode: input.codeMode === true }),
      prompt: sections.join("\n\n"),
      // A little warmth so the trio varies turn-to-turn and surfaces ideas the
      // user has not considered — but not so hot the prompts drift off-topic.
      temperature: 0.8,
      // The turn's answer is already streamed; the engine (not the SDK) owns
      // resilience here, and a retry would blow the fail-open timeout budget.
      maxRetries: 0,
      // Cancel the underlying model call if we blow the budget. The Promise.race
      // below is a belt-and-suspenders guard in case the signal is honored late.
      abortSignal: AbortSignal.timeout(SUGGESTION_TIMEOUT_MS),
      telemetry: {
        orgId: input.orgId,
        workspaceId: input.workspaceId,
        surface: "app",
        messageId: input.messageId,
      },
      // NEVER cache: suggestions must vary with the exact conversation.
    });

    // Belt-and-suspenders deadline in case `abortSignal` is honored late. The
    // timer is cleared once the race settles — an uncleared 6.25s handle keeps
    // the serverless invocation alive well past a fast, successful generation.
    let timer: ReturnType<typeof setTimeout> | undefined;
    const timeout = new Promise<null>((resolve) => {
      timer = setTimeout(() => resolve(null), SUGGESTION_TIMEOUT_MS + 250);
    });

    const result = await Promise.race([generation, timeout]).finally(() => {
      if (timer !== undefined) clearTimeout(timer);
    });
    if (!result) return null;

    const suggestions = result.object.suggestions
      .map((s) => ({ label: s.label.trim(), prompt: s.prompt.trim() }))
      .filter((s) => s.label.length > 0 && s.prompt.length > 0);

    return suggestions.length === 3 ? suggestions : null;
  } catch (err) {
    // Best-effort — a suggestion failure must never affect the chat turn, but
    // don't swallow it silently: a persistent failure is otherwise invisible.
    logger.warn({ err }, "[suggest-prompts] generation failed — skipping");
    return null;
  }
}
