-- Create "usage_outbox" table
CREATE TABLE "billing"."usage_outbox" (
  "id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "usage_complete" boolean NOT NULL DEFAULT false,
  "payload" jsonb NULL,
  "charge" jsonb NULL,
  "admitted_at" timestamptz NOT NULL DEFAULT now(),
  "finalized_at" timestamptz NULL,
  "delivered_at" timestamptz NULL,
  "attempts" integer NOT NULL DEFAULT 0,
  "next_attempt_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "usage_outbox_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "usage_outbox_pending_idx" to table: "usage_outbox"
CREATE INDEX "usage_outbox_pending_idx" ON "billing"."usage_outbox" ("next_attempt_at") WHERE ((delivered_at IS NULL) AND (payload IS NOT NULL));

-- GENERATED by tools/scripts/gen-rls-migration.ts — do not edit by hand.
-- Re-generate with: pnpm tsx tools/scripts/gen-rls-migration.ts 20260921100000_usage_outbox.sql --only=billing.usage_outbox
-- then: cd packages/database && pnpm exec atlas migrate hash
--
-- Restore tenant + workspace RLS lost in the 2026-06-11 Atlas re-baseline
-- (OXA-1700; original design OXA-1515). `drizzle-kit export` emits only the
-- Drizzle-modeled schema, so policy DDL must live as a versioned migration in
-- this directory to survive rebuilds — exactly like the oxagen_app regrant.
--
-- Bypass-aware: app.rls_bypass='on' (set by withSystemDb / the seeding window
-- when TENANT_RLS_ENFORCEMENT_ENABLED=false) disables filtering; tenant
-- sessions get app.current_org_id / app.current_workspace_id via withTenantDb.
--
-- Org-wide-aware (ADR-086): app.org_wide='on', set by withOrgDb and nothing
-- else, widens the READ of an org-scoped table to every workspace in the
-- organisation while the org fence still holds. It is the whole predicate of a
-- separate FOR SELECT policy, tenant_org_wide_read, and appears NOWHERE in
-- tenant_isolation. USING is the OLD-row test for UPDATE and DELETE too, and
-- WITH CHECK never runs for DELETE, so an org-wide disjunct inside
-- tenant_isolation would widen deletion to the organisation rather than widen
-- the read. Permissive policies are OR'd within a command and AND'd across
-- command types, so a FOR SELECT policy cannot reach an UPDATE's or a DELETE's
-- old-row test. workspace_only tables get no such policy: no org column to
-- fence with. Witness: integration/org-only-sentinel-refusal.test.ts.
-- FORCE applies policies to the table owner too; only superusers and
-- BYPASSRLS roles are exempt — oxagen_app is neither.
-- 1 of 114 manifest tables (--only=billing.usage_outbox).

ALTER TABLE billing.usage_outbox ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing.usage_outbox FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON billing.usage_outbox;
DROP POLICY IF EXISTS tenant_org_wide_read ON billing.usage_outbox;
DROP POLICY IF EXISTS tenant_org_shared_read ON billing.usage_outbox;
CREATE POLICY tenant_isolation ON billing.usage_outbox
  USING (current_setting('app.rls_bypass', true) = 'on' OR (org_id = nullif(current_setting('app.current_org_id', true), '')::uuid AND workspace_id = nullif(current_setting('app.current_workspace_id', true), '')::uuid))
  WITH CHECK (current_setting('app.rls_bypass', true) = 'on' OR (org_id = nullif(current_setting('app.current_org_id', true), '')::uuid AND workspace_id = nullif(current_setting('app.current_workspace_id', true), '')::uuid));
CREATE POLICY tenant_org_wide_read ON billing.usage_outbox
  FOR SELECT
  USING (current_setting('app.org_wide', true) = 'on' AND org_id = nullif(current_setting('app.current_org_id', true), '')::uuid);

GRANT SELECT, INSERT, UPDATE ON billing.usage_outbox TO oxagen_app;
