-- ADR-061 (#2961): steering records → proposals → Context PR.
--
-- Generated by `pnpm db:migrate:diff` from the drizzle schema
-- (packages/database/src/schema/agent.ts) and reviewed: the statements below
-- are this change's; the diff's pre-existing drift (index and constraint
-- renames elsewhere) is left out.
--
--   1. agent.context_records gains the record's classification (kind, force,
--      constraint_effect, sharing_scope, statement) and its publication
--      (commit_sha, path, published_at). merge_context_pr writes them; a record
--      published through publish_context_record carries NULL in each.
--   2. agent.context_proposals: a record proposal and its Context PR, one row
--      per concern, holding the state machine proposed → pr_open →
--      checks_running → checks_passed | checks_failed → merged (rejected via
--      dismiss_proposal). At most one open PR per lineage (partial unique index).
--   3. agent.context_appends: the records agents append through append_record
--      (the protocol's context/append), content-addressed by record_hash and
--      idempotent per workspace. INSERT-only for oxagen_app, like the
--      promotions ledger.
--
-- RLS for the two new tables is in 20260915060100_rls_steering_tables.sql
-- (generated from the tenant policy manifest).

-- ── 1. Classification and publication on the published record ───────────────
ALTER TABLE "agent"."context_records"
  ADD COLUMN "kind" text NULL,
  ADD COLUMN "force" text NULL,
  ADD COLUMN "constraint_effect" text NULL,
  ADD COLUMN "sharing_scope" text NOT NULL DEFAULT 'workspace',
  ADD COLUMN "statement" text NULL,
  ADD COLUMN "commit_sha" text NULL,
  ADD COLUMN "path" text NULL,
  ADD COLUMN "published_at" timestamptz NULL,
  ADD CONSTRAINT "context_records_kind_check" CHECK ((kind IS NULL) OR (kind = ANY (ARRAY['rule'::text, 'constraint'::text, 'procedure'::text, 'fact'::text, 'memory'::text, 'preference'::text]))),
  ADD CONSTRAINT "context_records_force_check" CHECK ((force IS NULL) OR (force = ANY (ARRAY['must'::text, 'should'::text, 'may'::text, 'info'::text]))),
  ADD CONSTRAINT "context_records_constraint_effect_check" CHECK (((constraint_effect IS NULL) AND (kind IS DISTINCT FROM 'constraint'::text)) OR ((constraint_effect = ANY (ARRAY['require'::text, 'forbid'::text])) AND (kind = 'constraint'::text))),
  ADD CONSTRAINT "context_records_sharing_scope_check" CHECK (sharing_scope = ANY (ARRAY['repository'::text, 'workspace'::text])),
  ADD CONSTRAINT "context_records_commit_sha_check" CHECK ((commit_sha IS NULL) OR (commit_sha ~ '^[0-9a-f]{7,40}$'::text));

-- ── 2. Proposals and the Context PR state machine ────────────────────────────
CREATE TABLE "agent"."context_proposals" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "public_id" public.citext NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "updated_by_user_id" uuid NULL,
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "lineage_id" public.citext NOT NULL,
  "kind" text NOT NULL,
  "force" text NOT NULL,
  "constraint_effect" text NULL,
  "sharing_scope" text NOT NULL,
  "statement" text NOT NULL,
  "rationale" text NOT NULL,
  "source" text NOT NULL,
  "support_runs" text[] NOT NULL DEFAULT '{}',
  "support_agents" text[] NOT NULL DEFAULT '{}',
  "supporting_record_ids" text[] NOT NULL DEFAULT '{}',
  "evidence_links" text[] NOT NULL DEFAULT '{}',
  "status" text NOT NULL DEFAULT 'proposed',
  "governance_mode" text NULL,
  "repository" text NULL,
  "base_ref" text NULL,
  "branch" text NULL,
  "path" text NULL,
  "pr_number" integer NULL,
  "pr_url" text NULL,
  "head_sha" text NULL,
  "stamped_record_id" text NULL,
  "record_hash" text NULL,
  "checks" jsonb NOT NULL DEFAULT '[]',
  "merged_commit" text NULL,
  "merged_at" timestamptz NULL,
  "merged_by_user_id" uuid NULL,
  "published_record_id" uuid NULL,
  "promotion_event_id" uuid NULL,
  "dismissed_at" timestamptz NULL,
  "dismissed_reason" text NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "context_proposals_public_id_unique" UNIQUE ("public_id"),
  CONSTRAINT "context_proposals_constraint_effect_check" CHECK (((constraint_effect IS NULL) AND (kind <> 'constraint'::text)) OR ((constraint_effect = ANY (ARRAY['require'::text, 'forbid'::text])) AND (kind = 'constraint'::text))),
  CONSTRAINT "context_proposals_force_check" CHECK (force = ANY (ARRAY['must'::text, 'should'::text, 'may'::text, 'info'::text])),
  CONSTRAINT "context_proposals_governance_mode_check" CHECK ((governance_mode IS NULL) OR (governance_mode = ANY (ARRAY['solo'::text, 'team'::text, 'regulated'::text]))),
  CONSTRAINT "context_proposals_kind_check" CHECK (kind = ANY (ARRAY['rule'::text, 'constraint'::text, 'procedure'::text, 'fact'::text, 'memory'::text, 'preference'::text])),
  CONSTRAINT "context_proposals_merged_check" CHECK ((status = 'merged'::text) = ((merged_commit IS NOT NULL) AND (promotion_event_id IS NOT NULL) AND (published_record_id IS NOT NULL))),
  CONSTRAINT "context_proposals_sharing_scope_check" CHECK (sharing_scope = ANY (ARRAY['repository'::text, 'workspace'::text])),
  CONSTRAINT "context_proposals_status_check" CHECK (status = ANY (ARRAY['proposed'::text, 'pr_open'::text, 'checks_running'::text, 'checks_passed'::text, 'checks_failed'::text, 'merged'::text, 'rejected'::text]))
);
CREATE INDEX "context_proposals_lineage_idx" ON "agent"."context_proposals" ("workspace_id", "lineage_id");
CREATE UNIQUE INDEX "context_proposals_open_pr_idx" ON "agent"."context_proposals" ("workspace_id", "lineage_id") WHERE (status = ANY (ARRAY['pr_open'::text, 'checks_running'::text, 'checks_passed'::text, 'checks_failed'::text]));
CREATE INDEX "context_proposals_org_idx" ON "agent"."context_proposals" ("org_id", "workspace_id");

-- ── 3. Records agents append (the protocol's context/append) ─────────────────
CREATE TABLE "agent"."context_appends" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "public_id" public.citext NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "kind" text NOT NULL,
  "lineage_id" public.citext NOT NULL,
  "statement" text NOT NULL,
  "sharing_scope" text NOT NULL,
  "record_hash" text NOT NULL,
  "source_refs" text[] NOT NULL DEFAULT '{}',
  "evidence_links" text[] NOT NULL DEFAULT '{}',
  "proposal_id" uuid NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "context_appends_public_id_unique" UNIQUE ("public_id"),
  CONSTRAINT "context_appends_kind_check" CHECK (kind = ANY (ARRAY['observation'::text, 'memory'::text, 'knowledge'::text, 'evidence'::text, 'record_proposal'::text, 'context_use'::text, 'context_use_feedback'::text])),
  CONSTRAINT "context_appends_proposal_check" CHECK ((proposal_id IS NOT NULL) = (kind = 'record_proposal'::text)),
  CONSTRAINT "context_appends_record_hash_check" CHECK (record_hash ~ '^sha256:[0-9a-f]{64}$'::text),
  CONSTRAINT "context_appends_sharing_scope_check" CHECK (sharing_scope = ANY (ARRAY['user'::text, 'repository'::text, 'workspace'::text, 'organization'::text]))
);
CREATE INDEX "context_appends_lineage_idx" ON "agent"."context_appends" ("workspace_id", "lineage_id");
CREATE INDEX "context_appends_org_idx" ON "agent"."context_appends" ("org_id", "workspace_id");
CREATE UNIQUE INDEX "context_appends_workspace_hash_idx" ON "agent"."context_appends" ("workspace_id", "record_hash");

-- ── oxagen_app grants ─────────────────────────────────────────────────────────
-- context_appends is append-only at the grant level: SELECT + INSERT and never
-- UPDATE/DELETE — an appended record is evidence, the posture
-- agent.context_promotions already holds. context_proposals is state.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'oxagen_app') THEN
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON agent.context_proposals TO oxagen_app';
    EXECUTE 'GRANT SELECT, INSERT ON agent.context_appends TO oxagen_app';
  END IF;
END
$$;
