-- ADR-055 (WL-24): governed action units at a contracted rate.
--
-- Generated by `pnpm db:migrate:diff` from the drizzle schema
-- (packages/database/src/schema/billing.ts) and reviewed: the statements below
-- are this change's; the diff's pre-existing drift (index and constraint
-- renames elsewhere, the hand-written plans_included_actions_non_negative
-- check, which stays until WL-27 drops the column) is left out.
--
--   1. billing.plans gains the tier's published terms: currency,
--      rate_per_gau_micros, block_size_gau, included_gau_per_month. seed.ts
--      writes them for Free and `pnpm billing:stripe-sync` for the paid plans;
--      existing rows are backfilled with the v1 figures (approved 2026-09-14,
--      metering spec §4.2) before the columns go NOT NULL.
--   2. billing.contract_terms: a negotiated agreement, one row per organization,
--      at most one effective (effective_to IS NULL) at a time.
--   3. billing.gau_buckets: one row per organization per month; the recorder's
--      lazy create and debit is INSERT … ON CONFLICT (org_id, period_start).
--   4. billing.gau_settlements: the one settlement ledger; every block purchase,
--      auto top-up, interim and period-close charge is a Stripe Invoice recorded
--      here, with `paid` the only terminal state.
--   5. billing.org_billing_settings gains the org's billing mode
--      (approved_for_invoice_billing, invoice_gau_max), the auto top-up
--      preferences (auto_topup_enabled, auto_topup_blocks) and the authoritative
--      stripe_customer_id.
--
-- Both terms tables carry (rate_per_gau_micros * block_size_gau) % 10000 = 0
-- so a block prices to whole cents. RLS for the three new org_id tables is in
-- 20260914170000_rls_gau_tables.sql (generated from the tenant policy
-- manifest). governed_action_counters and plans.included_actions_annual stay
-- until WL-27.

-- ── 1. Published terms on the plan row ───────────────────────────────────────
ALTER TABLE "billing"."plans"
  ADD COLUMN "currency" text NOT NULL DEFAULT 'usd',
  ADD COLUMN "rate_per_gau_micros" bigint NULL,
  ADD COLUMN "block_size_gau" integer NULL,
  ADD COLUMN "included_gau_per_month" integer NULL;

-- Backfill the v1 published figures onto existing plans: $5 per 1,000 GAU
-- (5,000 micros per GAU) in 5,000-GAU blocks ($25.00) on every tier; the
-- monthly allowance is the tier's, and enterprise carries the scale figures
-- until a billing.contract_terms row exists. A plan row written before this
-- migration lands on its tier's published figures, never on an unlimited or
-- absent allowance. seed.ts and `pnpm billing:stripe-sync` overwrite these on
-- their next run from the same figures.
UPDATE "billing"."plans"
  SET "rate_per_gau_micros" = 5000,
      "block_size_gau" = 5000,
      "included_gau_per_month" = CASE "tier"
        WHEN 'free' THEN 5000
        WHEN 'build' THEN 50000
        WHEN 'scale' THEN 300000
        WHEN 'enterprise' THEN 300000
      END
  WHERE "rate_per_gau_micros" IS NULL;

ALTER TABLE "billing"."plans"
  ALTER COLUMN "rate_per_gau_micros" SET NOT NULL,
  ALTER COLUMN "block_size_gau" SET NOT NULL,
  ALTER COLUMN "included_gau_per_month" SET NOT NULL,
  ADD CONSTRAINT "plans_gau_terms_check" CHECK ((rate_per_gau_micros >= 0) AND (block_size_gau > 0) AND (included_gau_per_month >= 0) AND (((rate_per_gau_micros * block_size_gau) % (10000)::bigint) = 0));

-- ── 2. Negotiated terms ──────────────────────────────────────────────────────
-- Create "contract_terms" table
CREATE TABLE "billing"."contract_terms" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "agreement_ref" text NOT NULL,
  "currency" text NOT NULL DEFAULT 'usd',
  "rate_per_gau_micros" bigint NOT NULL,
  "block_size_gau" integer NOT NULL,
  "included_gau_per_month" integer NOT NULL,
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "contract_terms_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "contract_terms_effective_range_check" CHECK ((effective_to IS NULL) OR (effective_to > effective_from)),
  CONSTRAINT "contract_terms_gau_terms_check" CHECK ((rate_per_gau_micros >= 0) AND (block_size_gau > 0) AND (included_gau_per_month >= 0) AND (((rate_per_gau_micros * block_size_gau) % (10000)::bigint) = 0))
);
-- Create index "contract_terms_org_effective_idx" to table: "contract_terms"
CREATE UNIQUE INDEX "contract_terms_org_effective_idx" ON "billing"."contract_terms" ("org_id") WHERE (effective_to IS NULL);

-- ── 3. The month bucket ──────────────────────────────────────────────────────
-- Create "gau_buckets" table
CREATE TABLE "billing"."gau_buckets" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "period_start" timestamptz NOT NULL,
  "period_end" timestamptz NOT NULL,
  "included_gau" bigint NOT NULL,
  "purchased_gau" bigint NOT NULL DEFAULT 0,
  "carried_gau" bigint NOT NULL DEFAULT 0,
  "used_gau" bigint NOT NULL DEFAULT 0,
  "overage_invoiced_gau" bigint NOT NULL DEFAULT 0,
  "interim_seq" integer NOT NULL DEFAULT 0,
  "topup_seq" integer NOT NULL DEFAULT 0,
  "open_topup_settlement_id" uuid NULL,
  "closed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "gau_buckets_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "gau_buckets_counts_non_negative" CHECK ((included_gau >= 0) AND (purchased_gau >= 0) AND (carried_gau >= 0) AND (used_gau >= 0) AND (overage_invoiced_gau >= 0) AND (interim_seq >= 0) AND (topup_seq >= 0)),
  CONSTRAINT "gau_buckets_overage_invoiced_within_used" CHECK (overage_invoiced_gau <= used_gau),
  CONSTRAINT "gau_buckets_period_range_check" CHECK (period_end > period_start)
);
-- Create index "gau_buckets_org_period_idx" to table: "gau_buckets"
CREATE UNIQUE INDEX "gau_buckets_org_period_idx" ON "billing"."gau_buckets" ("org_id", "period_start");

-- ── 4. The settlement ledger ─────────────────────────────────────────────────
-- Create "gau_settlements" table
CREATE TABLE "billing"."gau_settlements" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "bucket_id" uuid NOT NULL,
  "kind" text NOT NULL,
  "seq" integer NULL,
  "quantity_gau" bigint NOT NULL,
  "rate_per_gau_micros" bigint NOT NULL,
  "currency" text NOT NULL,
  "status" text NOT NULL DEFAULT 'pending',
  "stripe_checkout_session_id" text NULL,
  "stripe_invoice_id" text NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "settled_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "gau_settlements_bucket_id_gau_buckets_id_fk" FOREIGN KEY ("bucket_id") REFERENCES "billing"."gau_buckets" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "gau_settlements_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "gau_settlements_amounts_check" CHECK ((quantity_gau > 0) AND (rate_per_gau_micros >= 0) AND ((seq IS NULL) OR (seq >= 0))),
  CONSTRAINT "gau_settlements_kind_check" CHECK (kind = ANY (ARRAY['checkout'::text, 'auto_topup'::text, 'interim_invoice'::text, 'period_close'::text])),
  CONSTRAINT "gau_settlements_seq_by_kind_check" CHECK ((kind = 'checkout'::text) = (seq IS NULL)),
  CONSTRAINT "gau_settlements_status_check" CHECK (status = ANY (ARRAY['pending'::text, 'open'::text, 'paid'::text, 'failed'::text]))
);
-- Create index "gau_settlements_bucket_idx" to table: "gau_settlements"
CREATE INDEX "gau_settlements_bucket_idx" ON "billing"."gau_settlements" ("bucket_id");
-- Create index "gau_settlements_bucket_kind_seq_idx" to table: "gau_settlements"
CREATE UNIQUE INDEX "gau_settlements_bucket_kind_seq_idx" ON "billing"."gau_settlements" ("bucket_id", "kind", "seq") WHERE (seq IS NOT NULL);
-- Create index "gau_settlements_checkout_session_idx" to table: "gau_settlements"
CREATE UNIQUE INDEX "gau_settlements_checkout_session_idx" ON "billing"."gau_settlements" ("stripe_checkout_session_id") WHERE (stripe_checkout_session_id IS NOT NULL);

-- ── 5. The org's billing mode ────────────────────────────────────────────────
ALTER TABLE "billing"."org_billing_settings"
  ADD COLUMN "stripe_customer_id" text NULL,
  ADD COLUMN "approved_for_invoice_billing" boolean NOT NULL DEFAULT false,
  ADD COLUMN "invoice_gau_max" integer NOT NULL DEFAULT 100000,
  ADD COLUMN "auto_topup_enabled" boolean NOT NULL DEFAULT true,
  ADD COLUMN "auto_topup_blocks" integer NOT NULL DEFAULT 1,
  ADD CONSTRAINT "org_billing_settings_invoice_gau_max_positive" CHECK (invoice_gau_max > 0),
  ADD CONSTRAINT "org_billing_settings_auto_topup_blocks_positive" CHECK (auto_topup_blocks > 0);
-- Create index "org_billing_settings_stripe_customer_idx" to table: "org_billing_settings"
CREATE UNIQUE INDEX "org_billing_settings_stripe_customer_idx" ON "billing"."org_billing_settings" ("stripe_customer_id");
