-- Replace tacho.sessions.anthropic_user_email with a keyed digest.
--
-- The column held the real email address of the person behind the session,
-- written straight through from the harness. Every other column on the table
-- that identifies a person is a digest, and the same value was also copied
-- into ClickHouse tacho_events, which has no row policy -- so the address was
-- the one readable personal identifier in the tacho record (#3072).
--
-- The new column holds an HMAC-SHA256 the control plane stamps with a key held
-- only by the API deployment (packages/handlers/src/lib/tacho-user-email-digest.ts),
-- written as `hmac-sha256:<64 hex>`. A plain hash would not have been enough:
-- an email address carries so little entropy that whoever can read the value
-- can guess a colleague's address, hash it and compare. A published domain
-- prefix does not change that -- it rules out a generic precomputed table and
-- nothing else. Only a key the reader cannot obtain makes the value one-way
-- for them.
--
-- NOTHING IS BACKFILLED, deliberately. Postgres could call pgcrypto's hmac()
-- here, but the key would have to travel inside the statement and would land
-- in the server log, and ClickHouse -- which needs the identical value for the
-- same person -- has no HMAC function at all. So the rows already written lose
-- the attribute rather than gaining a digest. The addresses are gone, which is
-- what this migration is for; what it costs is attributing historical sessions
-- to a person, which nothing read.
--
-- Atlas tracks idempotency via atlas.sum -- do NOT edit this file after it is
-- applied.

ALTER TABLE "tacho"."sessions" ADD COLUMN IF NOT EXISTS "anthropic_user_email_digest" text;

ALTER TABLE "tacho"."sessions" DROP COLUMN IF EXISTS "anthropic_user_email";
