-- Broaden CHECK constraints on plugin.org_listings and plugin.org_denylist to
-- support the new `capability` plugin type (first-party Oxagen capability packs)
-- and the `oxagen` source value (managed installs from the Oxagen registry).
--
-- Phase 1 of the installable-plugins epic (ADR-013): capability packs reuse
-- org_listings with plugin_type='capability' and source='oxagen'. No new tables
-- are needed; only the two broadened CHECKs are required.
--
-- Strategy: DROP + re-ADD each constraint so the operation is idempotent and
-- safe to replay on a clean database (the old constraint name disappears and
-- the new one is created in its place). Atlas tracks idempotency via the
-- atlas.sum checksum — do NOT edit this file after it is applied.

-- org_listings: plugin_type — add 'capability'
ALTER TABLE "plugin"."org_listings" DROP CONSTRAINT IF EXISTS "org_listings_type_check";
ALTER TABLE "plugin"."org_listings" ADD CONSTRAINT "org_listings_type_check"
  CHECK (plugin_type IN ('mcp_server','integration','content_tool','capability'));

-- org_listings: source — add 'oxagen'
ALTER TABLE "plugin"."org_listings" DROP CONSTRAINT IF EXISTS "org_listings_source_check";
ALTER TABLE "plugin"."org_listings" ADD CONSTRAINT "org_listings_source_check"
  CHECK (source IN ('registry','custom','oxagen'));

-- org_denylist: plugin_type — add 'capability' (denylist applies to all plugin types)
ALTER TABLE "plugin"."org_denylist" DROP CONSTRAINT IF EXISTS "org_denylist_type_check";
ALTER TABLE "plugin"."org_denylist" ADD CONSTRAINT "org_denylist_type_check"
  CHECK (plugin_type IN ('mcp_server','integration','content_tool','capability'));
