-- Agent + workspace avatars, and LLM-inferred agent summaries.
--
-- avatar_url is a nullable text column on BOTH agent.agents and
-- workspace.workspaces, matching the users/organizations avatar_url convention.
-- Unlike those two (which only ever hold an https URL), an agent/workspace
-- avatar_url may ALSO carry the platform's designed-avatar spec string
-- "avatar:v1:<json>" (emoji + background + render mode), so the column is capped
-- at 512 chars at the contract layer rather than storing a plain URL only.
--
-- summary is a short (<=256 char) LLM-inferred, plain-text description of what an
-- agent does, derived from its name/instructions/tools/triggers. summary_checksum
-- is the SHA-256 of the canonical version config the summary was derived from, so
-- a stale summary (config changed since) is detectable and regenerable.
--
-- All columns nullable; idempotent so a re-run is a no-op (parallel-session safe).

-- ── agent.agents ─────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'agent' AND table_name = 'agents' AND column_name = 'avatar_url'
  ) THEN
    ALTER TABLE "agent"."agents" ADD COLUMN "avatar_url" text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'agent' AND table_name = 'agents' AND column_name = 'summary'
  ) THEN
    ALTER TABLE "agent"."agents" ADD COLUMN "summary" text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'agent' AND table_name = 'agents' AND column_name = 'summary_checksum'
  ) THEN
    ALTER TABLE "agent"."agents" ADD COLUMN "summary_checksum" text;
  END IF;
END $$;

COMMENT ON COLUMN "agent"."agents"."avatar_url" IS
  'Nullable. Either an https:// URL or the designed-avatar spec string avatar:v1:<json> ({emoji,bg,mode}). Capped at 512 chars at the contract layer. Same column name as users/organizations for consistency, though it may carry the spec string rather than a plain URL.';
COMMENT ON COLUMN "agent"."agents"."summary" IS
  'Nullable. LLM-inferred, plain-text (<=256 char) description of what the agent does, derived from its config. Regenerated by agent.definition.summarize when stale.';
COMMENT ON COLUMN "agent"."agents"."summary_checksum" IS
  'Nullable. SHA-256 of the canonical version config the summary was derived from (same canonicalization as agent_versions.checksum). When it no longer matches the current config the summary is stale.';

-- ── workspace.workspaces ─────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'workspace' AND table_name = 'workspaces' AND column_name = 'avatar_url'
  ) THEN
    ALTER TABLE "workspace"."workspaces" ADD COLUMN "avatar_url" text;
  END IF;
END $$;

COMMENT ON COLUMN "workspace"."workspaces"."avatar_url" IS
  'Nullable. Either an https:// URL or the designed-avatar spec string avatar:v1:<json> ({emoji,bg,mode}). Capped at 512 chars at the contract layer. Same column name as users/organizations for consistency, though it may carry the spec string rather than a plain URL.';
