-- GENERATED by tools/scripts/gen-rls-migration.ts — do not edit by hand.
-- Re-generate with: pnpm tsx tools/scripts/gen-rls-migration.ts 20260915203100_rls_credential_grants.sql --only=mcp.credential_grants
-- then: cd packages/database && pnpm exec atlas migrate hash
--
-- Restore tenant + workspace RLS lost in the 2026-06-11 Atlas re-baseline
-- (OXA-1700; original design OXA-1515). `drizzle-kit export` emits only the
-- Drizzle-modeled schema, so policy DDL must live as a versioned migration in
-- this directory to survive rebuilds — exactly like the oxagen_app regrant.
--
-- Bypass-aware: app.rls_bypass='on' (set by withSystemDb / the seeding window
-- when TENANT_RLS_ENFORCEMENT_ENABLED=false) disables filtering; tenant
-- sessions get app.current_org_id / app.current_workspace_id via withTenantDb.
-- FORCE applies policies to the table owner too; only superusers and
-- BYPASSRLS roles are exempt — oxagen_app is neither.
-- 1 of 102 manifest tables (--only=mcp.credential_grants).

ALTER TABLE mcp.credential_grants ENABLE ROW LEVEL SECURITY;
ALTER TABLE mcp.credential_grants FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON mcp.credential_grants;
CREATE POLICY tenant_isolation ON mcp.credential_grants
  USING (current_setting('app.rls_bypass', true) = 'on' OR (org_id = nullif(current_setting('app.current_org_id', true), '')::uuid AND workspace_id = nullif(current_setting('app.current_workspace_id', true), '')::uuid))
  WITH CHECK (current_setting('app.rls_bypass', true) = 'on' OR (org_id = nullif(current_setting('app.current_org_id', true), '')::uuid AND workspace_id = nullif(current_setting('app.current_workspace_id', true), '')::uuid));
