-- ADR-058 (G2962): the price book as data, the spend rollup store, the
-- recorders' spend counter.
--
-- Generated by `atlas migrate diff` from the drizzle schema
-- (packages/database/src/schema/cost.ts, billing.ts) and reviewed: the
-- statements below are this change's; the diff's pre-existing drift (index
-- and constraint renames elsewhere) is left out.
--
--   1. The `cost` schema.
--   2. cost.price_entries: every price Oxagen applies. `pnpm
--      billing:price-book-sync` writes the list rows (org_id NULL, source
--      'list') from packages/billing/src/pricing.ts; an organization's
--      negotiated rows carry its org_id. A price is effective over
--      [effective_from, effective_to); a correction is a new row.
--   3. cost.run_totals: one row per sealed run, rebuilt from the run's frames
--      by the cost.run-rollup job. cost_micros and cost_basis are null
--      together: a run no frame priced has no cost, never a zero.
--   4. cost.daily_totals: the per-day fold of run_totals by operator, agent,
--      model, tool and task, rebuilt by the nightly cost.daily-rollup job.
--   5. billing.spend_counters: the running counter the recorders keep per
--      (org, workspace, day) so the spend-budget gate and the budget panel
--      sum Postgres, never ClickHouse (#2820).
--
-- RLS for the four tenant tables is in 20260914223100_rls_cost_tables.sql
-- (generated from the tenant policy manifest). billing.spend_budgets keeps
-- its limit_micros column: the budget contracts move to micros on the wire
-- (ADR-057 §2) with no schema change.

-- ── 1. The cost schema ───────────────────────────────────────────────────────
CREATE SCHEMA "cost";

-- ── 2. The price book ────────────────────────────────────────────────────────
-- Create "price_entries" table
CREATE TABLE "cost"."price_entries" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "created_by_user_id" uuid NULL,
  "updated_by_user_id" uuid NULL,
  "org_id" uuid NULL,
  "provider" text NOT NULL,
  "model" text NOT NULL,
  "model_aliases" text[] NOT NULL DEFAULT '{}',
  "region" text NULL,
  "token_class" text NOT NULL,
  "unit" text NOT NULL,
  "currency" text NOT NULL DEFAULT 'USD',
  "micros_per_million" bigint NOT NULL,
  "effective_from" timestamptz NOT NULL,
  "effective_to" timestamptz NULL,
  "source" text NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "price_entries_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "price_entries_effective_range_check" CHECK ((effective_to IS NULL) OR (effective_to > effective_from)),
  CONSTRAINT "price_entries_org_source_check" CHECK ((source = 'list'::text) = (org_id IS NULL)),
  CONSTRAINT "price_entries_price_check" CHECK (micros_per_million >= 0),
  CONSTRAINT "price_entries_source_check" CHECK (source = ANY (ARRAY['list'::text, 'negotiated'::text, 'override'::text])),
  CONSTRAINT "price_entries_token_class_check" CHECK (token_class = ANY (ARRAY['input_uncached'::text, 'cache_read'::text, 'cache_write_5m'::text, 'cache_write_1h'::text, 'output'::text, 'reasoning'::text, 'server_tool_request'::text, 'embedding_input'::text, 'rerank'::text, 'image'::text, 'video_second'::text])),
  CONSTRAINT "price_entries_unit_check" CHECK (unit = ANY (ARRAY['token'::text, 'request'::text, 'image'::text, 'second'::text]))
);
-- Create index "price_entries_key_idx" to table: "price_entries"
CREATE UNIQUE INDEX "price_entries_key_idx" ON "cost"."price_entries" ((COALESCE(org_id, '00000000-0000-0000-0000-000000000000'::uuid)), "provider", "model", "token_class", (COALESCE(region, ''::text)), "effective_from");
-- Create index "price_entries_lookup_idx" to table: "price_entries"
CREATE INDEX "price_entries_lookup_idx" ON "cost"."price_entries" ("model", "token_class");

-- ── 3. The run rollup ────────────────────────────────────────────────────────
-- Create "run_totals" table
CREATE TABLE "cost"."run_totals" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "run_id" text NOT NULL,
  "run_source" text NOT NULL,
  "operator_principal_id" uuid NULL,
  "agent_principal_id" uuid NULL,
  "agent_key" text NULL,
  "task_ref" text NULL,
  "started_at" timestamptz NOT NULL,
  "sealed_at" timestamptz NULL,
  "turns" integer NULL,
  "steps" integer NOT NULL,
  "model_calls" integer NOT NULL,
  "tool_calls" integer NOT NULL,
  "tokens" jsonb NOT NULL,
  "cost_micros" bigint NULL,
  "currency" text NOT NULL DEFAULT 'USD',
  "cost_basis" text NULL,
  "price_entry_ids" uuid[] NOT NULL DEFAULT '{}',
  "cache_hit_rate" numeric(9,8) NULL,
  "tool_definition_tokens" integer NULL,
  "context_frame_tokens" integer NULL,
  "steering_tokens" integer NULL,
  "retries" integer NULL,
  "verdict" text NULL,
  "accepted" boolean NULL,
  "productive_ratio" numeric(9,8) NULL,
  "enforcement_tier" text NULL,
  "replay_grade" text NULL,
  "governed_actions" integer NULL,
  "billed_at" timestamptz NULL,
  "breakdown" jsonb NOT NULL,
  "rolled_up_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "run_totals_run_id_unique" UNIQUE ("run_id"),
  CONSTRAINT "run_totals_basis_check" CHECK ((cost_basis IS NULL) OR (cost_basis = ANY (ARRAY['gateway_observed'::text, 'client_attested'::text, 'mixed'::text, 'estimated'::text]))),
  CONSTRAINT "run_totals_cost_basis_pair_check" CHECK ((cost_micros IS NULL) = (cost_basis IS NULL)),
  CONSTRAINT "run_totals_counts_check" CHECK ((steps >= 0) AND (model_calls >= 0) AND (tool_calls >= 0) AND ((turns IS NULL) OR (turns >= 0)) AND ((retries IS NULL) OR (retries >= 0)) AND ((governed_actions IS NULL) OR (governed_actions >= 0))),
  CONSTRAINT "run_totals_grade_check" CHECK ((replay_grade IS NULL) OR (replay_grade = ANY (ARRAY['inspect'::text, 'view'::text, 'fork'::text, 'retry'::text]))),
  CONSTRAINT "run_totals_ratios_check" CHECK (((cache_hit_rate IS NULL) OR ((cache_hit_rate >= (0)::numeric) AND (cache_hit_rate <= (1)::numeric))) AND ((productive_ratio IS NULL) OR ((productive_ratio >= (0)::numeric) AND (productive_ratio <= (1)::numeric)))),
  CONSTRAINT "run_totals_source_check" CHECK (run_source = ANY (ARRAY['ledger'::text, 'tacho'::text])),
  CONSTRAINT "run_totals_tier_check" CHECK ((enforcement_tier IS NULL) OR (enforcement_tier = ANY (ARRAY['gateway'::text, 'harness'::text, 'observe'::text]))),
  CONSTRAINT "run_totals_verdict_check" CHECK ((verdict IS NULL) OR (verdict = ANY (ARRAY['flipped'::text, 'failing'::text, 'unmoved'::text, 'unsatisfied'::text, 'tampered'::text, 'unverified'::text, 'waived'::text, 'none'::text])))
);
-- Create index "run_totals_workspace_started_idx" to table: "run_totals"
CREATE INDEX "run_totals_workspace_started_idx" ON "cost"."run_totals" ("workspace_id", "started_at");

-- ── 4. The daily rollup ──────────────────────────────────────────────────────
-- Create "daily_totals" table
CREATE TABLE "cost"."daily_totals" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NOT NULL,
  "day" date NOT NULL,
  "group_kind" text NOT NULL,
  "group_key" text NOT NULL,
  "provider" text NULL,
  "runs" integer NOT NULL,
  "calls" integer NOT NULL,
  "cost_micros" bigint NULL,
  "currency" text NOT NULL DEFAULT 'USD',
  "cost_basis" text NULL,
  "proven_micros" bigint NULL,
  "accepted_micros" bigint NULL,
  "productive_ratio" numeric(9,8) NULL,
  "tokens" jsonb NOT NULL,
  "rolled_up_at" timestamptz NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "daily_totals_basis_check" CHECK ((cost_basis IS NULL) OR (cost_basis = ANY (ARRAY['gateway_observed'::text, 'client_attested'::text, 'mixed'::text, 'estimated'::text]))),
  CONSTRAINT "daily_totals_cost_basis_pair_check" CHECK ((cost_micros IS NULL) = (cost_basis IS NULL)),
  CONSTRAINT "daily_totals_counts_check" CHECK ((runs >= 0) AND (calls >= 0)),
  CONSTRAINT "daily_totals_kind_check" CHECK (group_kind = ANY (ARRAY['operator'::text, 'agent'::text, 'model'::text, 'tool'::text, 'task'::text]))
);
-- Create index "daily_totals_group_idx" to table: "daily_totals"
CREATE UNIQUE INDEX "daily_totals_group_idx" ON "cost"."daily_totals" ("workspace_id", "day", "group_kind", "group_key");

-- ── 5. The recorders' spend counter ─────────────────────────────────────────
-- Create "spend_counters" table
CREATE TABLE "billing"."spend_counters" (
  "id" uuid NOT NULL DEFAULT COALESCE(
CASE
    WHEN (to_regprocedure('public.uuid_generate_v7()'::text) IS NOT NULL) THEN public.uuid_generate_v7()
    ELSE public.uuid_generate_v4()
END, public.uuid_generate_v4()),
  "org_id" uuid NOT NULL,
  "workspace_id" uuid NULL,
  "day" date NOT NULL,
  "spent_micros" bigint NOT NULL DEFAULT 0,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ("id"),
  CONSTRAINT "spend_counters_org_id_organizations_id_fk" FOREIGN KEY ("org_id") REFERENCES "org"."organizations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE,
  CONSTRAINT "spend_counters_spent_check" CHECK (spent_micros >= 0)
);
-- Create index "spend_counters_scope_day_idx" to table: "spend_counters"
CREATE UNIQUE INDEX "spend_counters_scope_day_idx" ON "billing"."spend_counters" ("org_id", (COALESCE(workspace_id, '00000000-0000-0000-0000-000000000000'::uuid)), "day");

-- ── Grants ───────────────────────────────────────────────────────────────────
-- The application role must reach the new schema on an environment that
-- replays migrations in order; the blanket regrant only covers schemas that
-- existed when it ran.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'oxagen_app') THEN
    EXECUTE 'GRANT USAGE ON SCHEMA cost TO oxagen_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cost TO oxagen_app';
    EXECUTE 'GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cost TO oxagen_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA cost GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO oxagen_app';
    EXECUTE 'ALTER DEFAULT PRIVILEGES IN SCHEMA cost GRANT USAGE, SELECT ON SEQUENCES TO oxagen_app';
    EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON billing.spend_counters TO oxagen_app';
  END IF;
END
$$;
