-- Admit workspace.archived, iam.role_created, iam.role_grants_set and
-- iam.role_deleted to the security_events event_type CHECK (issue #2964,
-- ADR-063).
--
-- Archiving a workspace and changing a role definition are privileged
-- configuration changes (SOC2 CC6.1): the first freezes a tenant's workspace,
-- the others change what every holder of the role may ask for. Each is
-- emitted by its handler and belongs in the main audit log as its own domain
-- event rather than only as a generic capability.invoke_allowed row.
--
-- The taxonomy source of truth is packages/compliance/src/security-event-types.ts
-- and this constraint body was generated from it via
-- generateEventTypeCheckClause() (see db-check.ts) — do not hand-edit the list.
--
-- Strategy: DROP + re-ADD so the operation is idempotent and safe to replay on a
-- clean database. security_events is RANGE-partitioned on occurred_at; altering
-- the parent propagates the CHECK to every child partition. Atlas tracks
-- idempotency via the atlas.sum checksum — do NOT edit this file after it is
-- applied. Purely additive: every value the previous constraint admitted is
-- still admitted.

ALTER TABLE "security"."security_events" DROP CONSTRAINT IF EXISTS "security_events_event_type_check";
ALTER TABLE "security"."security_events" ADD CONSTRAINT "security_events_event_type_check"
  CHECK (event_type IN ('auth.sign_in', 'auth.sign_in_failed', 'auth.sign_out', 'auth.token_refreshed', 'auth.password_changed', 'auth.email_verified', 'api_key.created', 'api_key.revoked', 'api_key.used', 'billing.access_denied', 'billing.auto_reload_updated', 'billing.checkout_initiated', 'billing.credits_purchased', 'billing.payment_method_added', 'billing.payment_method_default_changed', 'billing.payment_method_removed', 'billing.plan_changed', 'billing.seats_changed', 'billing.subscription_canceled', 'billing.subscription_reactivated', 'billing.budget_updated', 'capability.invoke_allowed', 'capability.invoke_denied', 'capability.invoke_error', 'organization.created', 'workspace.created', 'workspace.archived', 'org.member_invited', 'org.member_removed', 'org.role_changed', 'iam.role_created', 'iam.role_grants_set', 'iam.role_deleted', 'plugin.installed', 'plugin.uninstalled', 'plugin.enabled_changed', 'plugin.denylist_added', 'plugin.denylist_removed', 'plugin.credential_set', 'plugin.credential_revoked', 'secret.revealed', 'secret.exported', 'secret.value_changed', 'secret.key_deleted', 'security.mfa_policy_updated', 'security.session_revoked', 'data_plane.updated', 'model_credential.set', 'model_credential.revoked', 'agent.registered', 'agent.suspended', 'agent.resumed', 'agent.retired', 'agent_run.event_sequence_conflict', 'agent_run.forged_decision_reference', 'agent_run.stale_deny_generation', 'agent_run.finalization_grant_misuse', 'access.review_completed', 'access.member_access_confirmed', 'privacy.export_requested', 'privacy.erasure_requested', 'privacy.org_erasure_requested'));
