-- Re-admit data_plane.updated to the security_events event_type CHECK.
--
-- Two correct changes composed into a wrong constraint. 20260907140000 added
-- data_plane.updated for ADR-042's set_data_plane handler; 20260908010000
-- (#2752) added the plugin-credential and secret families. Both DROP and
-- re-ADD the whole constraint rather than extending it, and 20260908010000
-- sorts later, so applying them in order leaves a constraint that does not
-- admit data_plane.updated -- the set_data_plane audit write would be
-- rejected at insert time.
--
-- Neither PR's own CI could see it: each migration was generated against a
-- taxonomy that did not yet contain the other's types. It surfaced only once
-- both landed in one tree, as
-- packages/compliance/src/security-event-types.test.ts's "the latest
-- event_type migration contains every value in SECURITY_EVENT_TYPES".
--
-- This migration is purely additive and re-states the constraint over the
-- merged taxonomy: 57 types, main's 56 plus data_plane.updated. Nothing is
-- removed.
--
-- The taxonomy source of truth is packages/compliance/src/security-event-types.ts
-- and this constraint body was generated from it via
-- generateEventTypeCheckClause() (see db-check.ts) -- do not hand-edit the list.
--
-- Strategy: DROP + re-ADD so the operation is idempotent and safe to replay on a
-- clean database. security_events is RANGE-partitioned on occurred_at; altering
-- the parent propagates the CHECK to every child partition. Atlas tracks
-- idempotency via the atlas.sum checksum -- do NOT edit this file after it is
-- applied.

ALTER TABLE "security"."security_events" DROP CONSTRAINT IF EXISTS "security_events_event_type_check";
ALTER TABLE "security"."security_events" ADD CONSTRAINT "security_events_event_type_check"
  CHECK (event_type IN ('auth.sign_in', 'auth.sign_in_failed', 'auth.sign_out', 'auth.token_refreshed', 'auth.password_changed', 'auth.email_verified', 'api_key.created', 'api_key.revoked', 'api_key.used', 'billing.access_denied', 'billing.auto_reload_updated', 'billing.checkout_initiated', 'billing.credits_purchased', 'billing.payment_method_added', 'billing.payment_method_default_changed', 'billing.payment_method_removed', 'billing.plan_changed', 'billing.seats_changed', 'billing.subscription_canceled', 'billing.subscription_reactivated', 'billing.budget_updated', 'billing.reseller_customer_changed', 'billing.reseller_price_plan_changed', 'billing.reseller_attribution_rule_changed', 'billing.reseller_stripe_configured', 'billing.reseller_rebill_pushed', 'capability.invoke_allowed', 'capability.invoke_denied', 'capability.invoke_error', 'organization.created', 'workspace.created', 'org.member_invited', 'org.member_removed', 'org.role_changed', 'plugin.installed', 'plugin.uninstalled', 'plugin.enabled_changed', 'plugin.denylist_added', 'plugin.denylist_removed', 'plugin.credential_set', 'plugin.credential_revoked', 'secret.revealed', 'secret.exported', 'secret.value_changed', 'secret.key_deleted', 'security.mfa_policy_updated', 'security.session_revoked', 'data_plane.updated', 'agent_run.event_sequence_conflict', 'agent_run.forged_decision_reference', 'agent_run.stale_deny_generation', 'agent_run.finalization_grant_misuse', 'access.review_completed', 'access.member_access_confirmed', 'privacy.export_requested', 'privacy.erasure_requested', 'privacy.org_erasure_requested'));
