-- Widen the tacho.sessions runtime CHECK: add 'cursor'.
--
-- Cursor is the fourth wrapped harness, beside Claude Code, Codex and Stella.
-- Its agent reads ~/.cursor/hooks.json, and `tacho-hook --harness cursor`
-- translates its payloads and answers (packages/tacho/src/claude-code/
-- cursor-adapter.ts). Without a 'cursor' member here the daemon would have to
-- file a Cursor session as runtime = 'custom', and the fleet page could not
-- tell it from a custom agent.
--
-- The list is generated from TACHO_RUNTIMES in packages/database/src/schema/tacho.ts
-- (mirrored by packages/tacho/src/envelope.ts); schema/tacho.test.ts holds the
-- LATEST migration that redefines this constraint to that list.
--
-- Additive only: every value the old constraint accepted is still accepted.
-- Atlas tracks idempotency via atlas.sum -- do NOT edit this file after it is applied.

ALTER TABLE "tacho"."sessions" DROP CONSTRAINT IF EXISTS "tacho_sessions_runtime_check";
ALTER TABLE "tacho"."sessions" ADD CONSTRAINT "tacho_sessions_runtime_check"
  CHECK ("runtime" IN ('claude-code', 'claude-agent-sdk', 'custom', 'stella', 'proxy', 'codex', 'cursor'));
