-- Widen the tacho.sessions runtime CHECK: add 'codex'.
--
-- The desktop app wraps Codex CLI through the same tacho-hook as Claude Code
-- (docs/specs/oxagen-desktop/spec.html section 6). Until now the collector had
-- to ship a Codex session as runtime = 'custom', harness = 'codex', because
-- this constraint had no codex member -- so the fleet page could not tell a
-- Codex session from a custom agent without reading the free-text harness.
--
-- The list is generated from TACHO_RUNTIMES in packages/database/src/schema/tacho.ts
-- (mirrored by packages/tacho/src/envelope.ts); schema/tacho.test.ts holds the
-- LATEST migration that redefines this constraint to that list, so any future
-- widening is a new migration that DROPs and re-ADDs the whole constraint.
--
-- Additive only: every value the old constraint accepted is still accepted, so
-- a plain ADD CONSTRAINT validates against existing rows without failing.
-- DROP + re-ADD keeps the operation replayable on a clean database. Atlas
-- tracks idempotency via atlas.sum -- do NOT edit this file after it is applied.

ALTER TABLE "tacho"."sessions" DROP CONSTRAINT IF EXISTS "tacho_sessions_runtime_check";
ALTER TABLE "tacho"."sessions" ADD CONSTRAINT "tacho_sessions_runtime_check"
  CHECK ("runtime" IN ('claude-code', 'claude-agent-sdk', 'custom', 'stella', 'proxy', 'codex'));
