-- Record which workspace governed an export request.
--
-- An organization export is queued under one workspace and downloaded minutes
-- later, and until now the row remembered only the person and the org. The
-- download re-asks `export_data`'s policy, but it asked it about whichever
-- workspace the browser happened to be in: both download routes are mounted
-- under a workspace slug. So an explicit deny written in the workspace the
-- export was queued through was evaded by opening the archive from a sibling
-- workspace of the same organization, and the deny that an administrator
-- believes removed access did not remove it.
--
-- The scope that governed the request is part of the record of the request, so
-- it is stored with it rather than re-derived from the request that reads it.
--
-- Nullable, because rows written before this migration have no answer and
-- inventing one would be a claim about a decision nobody made. The status
-- handler reads a null as org scope, which is what an org-wide archive with no
-- recorded workspace is: an org-level deny still binds it, and no workspace's
-- rules can unlock it.
--
-- Atlas tracks idempotency via atlas.sum -- do NOT edit this file after it is applied.

ALTER TABLE "privacy"."privacy_export_requests"
  ADD COLUMN IF NOT EXISTS "workspace_id" uuid;
