-- Broaden the security_events event_type CHECK constraint to admit the four
-- governed-run integrity event types (agent_run.event_sequence_conflict,
-- agent_run.forged_decision_reference, agent_run.stale_deny_generation,
-- agent_run.finalization_grant_misuse).
--
-- docs/specs/run-evidence-ingress/spec.md; 02-run-attempt-foundation-plan.md
-- Task 5. These four are INTEGRITY failures, not ordinary policy denials — each
-- means some part of the run-evidence chain was contradicted, and none can be
-- produced by legitimate use:
--
--   event_sequence_conflict    two events claimed the same run_seq (or
--                              attempt_id + attempt_seq) with DIFFERENT payload
--                              digests, so the ordered stream forked
--   forged_decision_reference  a caller supplied an authorization-decision
--                              reference on a CapabilityContext; that binding is
--                              platform-created and can never be an input
--   stale_deny_generation      an operation was evaluated against a
--                              deny-generation older than the current one, i.e.
--                              a cached allow outlived its invalidation
--   finalization_grant_misuse  a one-shot finalization grant was presented for a
--                              different attempt, digest, or capability than the
--                              seal it was minted for
--
-- The taxonomy source of truth is packages/compliance/src/security-event-types.ts
-- and this constraint body was generated from it via
-- generateEventTypeCheckClause() (see db-check.ts) — do not hand-edit the list.
--
-- Strategy: DROP + re-ADD so the operation is idempotent and safe to replay on a
-- clean database. security_events is RANGE-partitioned on occurred_at; altering
-- the parent propagates the CHECK to every child partition. Atlas tracks
-- idempotency via the atlas.sum checksum — do NOT edit this file after it is
-- applied.

ALTER TABLE "security"."security_events" DROP CONSTRAINT IF EXISTS "security_events_event_type_check";
ALTER TABLE "security"."security_events" ADD CONSTRAINT "security_events_event_type_check"
  CHECK (event_type IN ('auth.sign_in', 'auth.sign_in_failed', 'auth.sign_out', 'auth.token_refreshed', 'auth.password_changed', 'auth.email_verified', 'api_key.created', 'api_key.revoked', 'api_key.used', 'billing.access_denied', 'billing.auto_reload_updated', 'billing.checkout_initiated', 'billing.credits_purchased', 'billing.payment_method_added', 'billing.payment_method_default_changed', 'billing.payment_method_removed', 'billing.plan_changed', 'billing.seats_changed', 'billing.subscription_canceled', 'billing.subscription_reactivated', 'billing.reseller_customer_changed', 'billing.reseller_price_plan_changed', 'billing.reseller_attribution_rule_changed', 'billing.reseller_stripe_configured', 'billing.reseller_rebill_pushed', 'capability.invoke_allowed', 'capability.invoke_denied', 'capability.invoke_error', 'organization.created', 'workspace.created', 'org.member_invited', 'org.member_removed', 'org.role_changed', 'plugin.installed', 'plugin.uninstalled', 'plugin.enabled_changed', 'plugin.denylist_added', 'plugin.denylist_removed', 'security.mfa_policy_updated', 'security.session_revoked', 'agent_run.event_sequence_conflict', 'agent_run.forged_decision_reference', 'agent_run.stale_deny_generation', 'agent_run.finalization_grant_misuse', 'access.review_completed', 'access.member_access_confirmed', 'privacy.export_requested', 'privacy.erasure_requested', 'privacy.org_erasure_requested'));
