-- Replace tacho.sessions.anthropic_user_email with a digest.
--
-- The column held the real email address of the person behind the session,
-- written straight through from the harness. Every other column on the table
-- that identifies a person is a digest, and the same value was also being
-- copied into ClickHouse tacho_events, which has no row policy -- so the
-- address was the one readable personal identifier in the tacho record (#3072).
--
-- The new column holds a SHA-256, written as `sha256:<64 hex>`, over a fixed
-- domain string, a NUL byte, and the address lowercased and trimmed. The
-- domain prefix is the point: an email address carries so little entropy that
-- a bare sha256 of one can be reversed by anyone holding a list of candidate
-- addresses and willing to hash each. With the prefix the digest matches
-- nothing a generic table or any other digest in the platform produces, and it
-- is still the same value every time for the same person, so counting distinct
-- people and following one person across sessions both still work.
--
-- Collectors digest on the host from this release on, so the address no longer
-- reaches the control plane at all. The UPDATE below is for the rows already
-- written: it reproduces digestUserEmail() in packages/tacho/src/digest.ts
-- exactly, so a backfilled row joins a newly written one. Dropping the old
-- column afterwards is what removes the addresses.
--
-- Atlas tracks idempotency via atlas.sum -- do NOT edit this file after it is
-- applied.

ALTER TABLE "tacho"."sessions" ADD COLUMN IF NOT EXISTS "anthropic_user_email_digest" text;

UPDATE "tacho"."sessions"
SET "anthropic_user_email_digest" = 'sha256:' || encode(
  sha256(
    convert_to('oxagen:tacho:user_email:v1', 'UTF8')
      || '\x00'::bytea
      || convert_to(lower(btrim("anthropic_user_email")), 'UTF8')
  ),
  'hex'
)
WHERE "anthropic_user_email" IS NOT NULL
  AND btrim("anthropic_user_email") <> ''
  AND "anthropic_user_email_digest" IS NULL;

ALTER TABLE "tacho"."sessions" DROP COLUMN IF EXISTS "anthropic_user_email";
