-- Widen the agent.agents harness CHECK: add 'codex' and 'cursor'.
--
-- Codex and Cursor are wrapped harnesses beside Claude Code and Stella: Tacho
-- writes their hooks on an enrolled host (~/.codex/hooks.json,
-- ~/.cursor/hooks.json). `register_agent` refused both, so an operator
-- registering a Codex or Cursor agent had to file it as 'custom', and the
-- register flow then offered the SDK path instead of enrolling the host.
--
-- The list matches agentHarnessSchema in packages/oxagen/src/contracts/agent.list.ts
-- and the harnessCheck in packages/database/src/schema/agent.ts.
--
-- Additive only: every value the old constraint accepted is still accepted.
-- Atlas tracks idempotency via atlas.sum -- do NOT edit this file after it is applied.

ALTER TABLE "agent"."agents" DROP CONSTRAINT IF EXISTS "agents_harness_check";
ALTER TABLE "agent"."agents" ADD CONSTRAINT "agents_harness_check"
  CHECK ("harness" IN ('stella', 'claude-code', 'codex', 'cursor', 'claude-agent-sdk', 'custom'));

COMMENT ON COLUMN "agent"."agents"."harness" IS
  'The harness the agent runs under (MC spec §6.2): stella, claude-code, codex, cursor, claude-agent-sdk or custom.';
