/**
 * builtin-codegen — the reusable engine behind `scripts/embed-skills.ts`.
 *
 * Reads every `skills/<slug>/skill.toml` and renders `src/builtin-skills.generated.ts`,
 * which embeds the raw file contents so builtin skills travel with every bundle
 * (serverless bundlers drop non-imported markdown — see builtin.ts). Lives in
 * `src/` so the drift-guard test can import it without crossing the rootDir
 * boundary; the CLI wrapper in `scripts/` only adds file-writing + argv handling.
 */
import { readdir, readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { resolveContainedPath } from "@oxagen/agent-artifacts";
import { parseSkill } from "./loader";

const HERE = dirname(fileURLToPath(import.meta.url));
export const SKILLS_ROOT = join(HERE, "..", "skills");
export const GENERATED_FILE = join(HERE, "builtin-skills.generated.ts");

export interface EmbeddedReference {
  path: string;
  body: string;
}
export interface EmbeddedFile {
  slug: string;
  raw: string;
  references: EmbeddedReference[];
}

/** Recursively collect every `skill.toml` under `dir` (matches filesystem.ts). */
async function collectSkillPaths(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectSkillPaths(full)));
    } else if (entry.isFile() && entry.name === "skill.toml") {
      out.push(full);
    }
  }
  return out;
}

/** Read a skill file + resolve its declared reference bodies. */
async function readEmbeddedFile(path: string): Promise<EmbeddedFile> {
  const raw = await readFile(path, "utf8");
  // Reuse the real parser so slug + reference-path extraction never drifts.
  const skill = parseSkill(raw);
  const references: EmbeddedReference[] = await Promise.all(
    skill.references.map(async (ref) => ({
      path: ref.path,
      // Same containment proof loadSkillFile applies, so a reference that
      // symlinks out of the bundle cannot get its contents baked into the
      // committed module.
      body: await readFile(await resolveContainedPath(path, ref.path), "utf8")
        // A missing reference degrades to an empty body rather than aborting
        // the whole codegen — but say so, or the generated module silently
        // ships an empty reference nobody notices until an agent reads it.
        // Any other read failure is a build fault and stops the run, which is
        // stricter than loadSkillFile's runtime degrade-and-warn.
        .catch((err: unknown) => {
          if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
          console.warn(
            `[embed-skills] reference missing, embedding an empty body: ${ref.path} (declared by ${path})`,
          );
          return "";
        }),
    })),
  );
  return { slug: skill.slug, raw, references };
}

/** Build the embedded-file list from the skills directory. Shared with the test. */
export async function buildEmbeddedFiles(
  root: string = SKILLS_ROOT,
): Promise<EmbeddedFile[]> {
  const paths = await collectSkillPaths(root);
  return Promise.all(paths.map(readEmbeddedFile));
}

/**
 * Render the generated module. Exported so the drift-guard test can recompute
 * the expected output and compare it against the committed file.
 */
export function renderGeneratedModule(files: EmbeddedFile[]): string {
  // Deterministic ordering keeps the generated file (and the drift diff) stable.
  const sorted = [...files].sort((a, b) => a.slug.localeCompare(b.slug));
  const entries = sorted
    .map((f) => {
      const refs = f.references
        .map(
          (r) =>
            `      { path: ${JSON.stringify(r.path)}, body: ${JSON.stringify(r.body)} },`,
        )
        .join("\n");
      const refsBlock = f.references.length ? `[\n${refs}\n    ]` : "[]";
      return [
        "  {",
        `    slug: ${JSON.stringify(f.slug)},`,
        `    raw: ${JSON.stringify(f.raw)},`,
        `    references: ${refsBlock},`,
        "  },",
      ].join("\n");
    })
    .join("\n");

  return `// AUTO-GENERATED by scripts/embed-skills.ts — DO NOT EDIT BY HAND.
// Regenerate with: pnpm --filter @oxagen/skills gen:skills
//
// Embeds every packages/skills/skills/*/skill.toml as module data so builtin
// skills are ALWAYS present in any bundle. Serverless bundlers trace the import
// graph and drop plain data files like these, so a runtime filesystem read would
// break workspace skill seeding and the create-agent fallback in production.
// Do not replace this with one.

export interface EmbeddedSkillReference {
  readonly path: string;
  readonly body: string;
}

export interface EmbeddedSkillFile {
  readonly slug: string;
  /** Verbatim contents of skill.toml, re-parsed at runtime. */
  readonly raw: string;
  readonly references: readonly EmbeddedSkillReference[];
}

export const BUILTIN_SKILL_FILES: readonly EmbeddedSkillFile[] = [
${entries}
];
`;
}
