import { Hono } from "hono";
import type { CapabilityContext } from "@oxagen/oxagen";
import { requestLogger } from "./middleware/logger";
import { corsMiddleware } from "./middleware/cors";
import { errorMiddleware } from "./middleware/error";
import { authMiddleware } from "./middleware/auth";
import { orgMiddleware } from "./middleware/org";
import { workspaceMiddleware } from "./middleware/workspace";
import { health } from "./routes/health";
import { stripeWebhook } from "./routes/stripe";
import { inngestRoute } from "./routes/inngest";
import { organizationCreateRoute } from "./routes/v1/organization.create";
import { workspaceCreateRoute } from "./routes/v1/workspace.create";
import { billingSubscriptionReadRoute } from "./routes/v1/billing.subscription.read";
import { billingSubscriptionUpgradeStartRoute } from "./routes/v1/billing.subscription.upgrade.start";
import { billingCreditsPurchaseRoute } from "./routes/v1/billing.credits.purchase";
import { chatMessageSendRoute } from "./routes/v1/chat.message.send";
import { chatMessageExecutionRoute } from "./routes/v1/chat.message.execution";
import { chatStreamRoute } from "./routes/v1/chat.stream";
import { agentCodeExecuteRoute } from "./routes/v1/agent.code.execute";
import { agentToolListRoute } from "./routes/v1/agent.tool.list";
import { agentMcpRegisterRoute } from "./routes/v1/agent.mcp.register";
import { agentMcpListRoute } from "./routes/v1/agent.mcp.list";
import { agentSkillListRoute } from "./routes/v1/agent.skill.list";
import { agentSkillLoadRoute } from "./routes/v1/agent.skill.load";
import { agentPlanApproveRoute } from "./routes/v1/agent.plan.approve";
import { agentPlanCreateRoute } from "./routes/v1/agent.plan.create";
import { agentTaskBackgroundStartRoute } from "./routes/v1/agent.task.background.start";
import { agentTaskBackgroundReadRoute } from "./routes/v1/agent.task.background.read";
import { agentTaskBackgroundCancelRoute } from "./routes/v1/agent.task.background.cancel";
import { agentMemoryRecallRoute } from "./routes/v1/agent.memory.recall";
import { agentMemoryWriteRoute } from "./routes/v1/agent.memory.write";
import { agentApprovalResolveRoute } from "./routes/v1/agent.approval.resolve";
import { agentExecutionRecordRoute } from "./routes/v1/agent.execution.record";
import { agentSubagentAggregateRoute } from "./routes/v1/agent.subagent.aggregate";
import { formFillRoute } from "./routes/v1/form.fill";
import { archiveCreateRoute } from "./routes/v1/archive.create";
import { documentsGenerateRoute } from "./routes/v1/documents.generate";
import { documentsPdfCreateRoute } from "./routes/v1/documents.pdf.create";
import { brandkitApplyRoute } from "./routes/v1/brandkit.apply";
import { videoGenerateRoute } from "./routes/v1/video.generate";
import { svgGenerateRoute } from "./routes/v1/svg.generate";
import { imageGenerateRoute } from "./routes/v1/image.generate";
import { systemInstallInstructionsRoute } from "./routes/v1/system.install.instructions";
import { orgMemberAddRoute } from "./routes/v1/org.member.add";
import { orgMemberInviteAcceptRoute } from "./routes/v1/org.member.invite.accept";
import { orgMemberInviteDeclineRoute } from "./routes/v1/org.member.invite.decline";
import { orgMemberRemoveRoute } from "./routes/v1/org.member.remove";
import { orgMemberRoleChangeRoute } from "./routes/v1/org.member.role.change";
import { userPreferencesReadRoute } from "./routes/v1/user.preferences.read";
import { userPreferencesWriteRoute } from "./routes/v1/user.preferences.write";
import { workspaceModelSettingsReadRoute } from "./routes/v1/workspace.model.settings.read";
import { workspaceModelSettingsWriteRoute } from "./routes/v1/workspace.model.settings.write";
import { promptSettingsReadRoute } from "./routes/v1/prompt.settings.read";
import { promptSettingsWriteRoute } from "./routes/v1/prompt.settings.write";
import { conversationListRoute } from "./routes/v1/conversation.list";
import { conversationRenameRoute } from "./routes/v1/conversation.rename";
import { conversationArchiveRoute } from "./routes/v1/conversation.archive";
import { conversationDeleteRoute } from "./routes/v1/conversation.delete";
import { conversationPurgeRoute } from "./routes/v1/conversation.purge";
import { assetUploadRoute } from "./routes/v1/asset.upload";
import { pluginRegistryListRoute } from "./routes/v1/plugin.registry.list";
import { pluginRegistryAddRoute } from "./routes/v1/plugin.registry.add";
import { pluginRegistryRemoveRoute } from "./routes/v1/plugin.registry.remove";
import { pluginRegistrySyncRoute } from "./routes/v1/plugin.registry.sync";
import { pluginCatalogBrowseRoute } from "./routes/v1/plugin.catalog.browse";
import { pluginCatalogGetRoute } from "./routes/v1/plugin.catalog.get";
import { pluginOrgListRoute } from "./routes/v1/plugin.org.list";
import { pluginOrgInstallRoute } from "./routes/v1/plugin.org.install";
import { pluginOrgInstallBulkRoute } from "./routes/v1/plugin.org.install_bulk";
import { pluginOrgUninstallRoute } from "./routes/v1/plugin.org.uninstall";
import { pluginOrgSetEnabledRoute } from "./routes/v1/plugin.org.set_enabled";
import { pluginDenylistAddRoute } from "./routes/v1/plugin.denylist.add";
import { pluginDenylistRemoveRoute } from "./routes/v1/plugin.denylist.remove";
import { pluginWorkspaceSetEnabledRoute } from "./routes/v1/plugin.workspace.set_enabled";
import { pluginCredentialSetSecretRoute } from "./routes/v1/plugin.credential.set_secret";
import { pluginCredentialReauthRoute } from "./routes/v1/plugin.credential.reauth";
import { notificationsListRoute } from "./routes/v1/notifications.list";
import { notificationsMarkRoute } from "./routes/v1/notifications.mark";
import { pluginSettingsSetAuthAlertsRoute } from "./routes/v1/plugin.settings.set_auth_alerts";
import { apiKeyCreateRoute } from "./routes/v1/api.key.create";
import { apiKeyRevokeRoute } from "./routes/v1/api.key.revoke";
import { workflowRoute } from "./routes/v1/workflow";
import { workspaceMemberListRoute } from "./routes/v1/workspace.member.list";
import { workspaceInviteSendRoute } from "./routes/v1/workspace.invite.send";
import { conversationChatRoute } from "./routes/v1/conversation.chat";
import { imageCreateRoute } from "./routes/v1/image.create";
import { imageListRoute } from "./routes/v1/image.list";
import { imageAnalyzeRoute } from "./routes/v1/image.analyze";
import { documentCreateRoute } from "./routes/v1/document.create";
import { documentListRoute } from "./routes/v1/document.list";
import { documentReadRoute } from "./routes/v1/document.read";
import { formCreateRoute } from "./routes/v1/form.create";
import { formSubmitRoute } from "./routes/v1/form.submit";
import { automationListRoute } from "./routes/v1/automation.list";
import { automationCreateRoute } from "./routes/v1/automation.create";
import { automationEnableRoute } from "./routes/v1/automation.enable";
import { automationDisableRoute } from "./routes/v1/automation.disable";
import { automationTriggerRoute } from "./routes/v1/automation.trigger";
import { skillWorkspaceListRoute } from "./routes/v1/skill.workspace.list";
import { agentSubagentDispatchRoute } from "./routes/v1/agent.subagent.dispatch";
import { privacyDataExportRoute } from "./routes/v1/privacy.data.export";
import { privacyDataEraseRoute } from "./routes/v1/privacy.data.erase";
import { connectionRoute } from "./routes/v1/connection";
import { webhookRoute } from "./routes/v1/webhook";
import { githubOauthRoute, githubOauthCallbackRoute } from "./routes/v1/github-oauth";
import { graphNodeUpsertRoute } from "./routes/v1/graph.node.upsert";
import { graphNodeGetRoute } from "./routes/v1/graph.node.get";
import { graphNodeDeleteRoute } from "./routes/v1/graph.node.delete";
import { graphNodeSearchRoute } from "./routes/v1/graph.node.search";
import { graphEdgeUpsertRoute } from "./routes/v1/graph.edge.upsert";
import { graphEdgeDeleteRoute } from "./routes/v1/graph.edge.delete";
import { graphCypherRoute } from "./routes/v1/graph.cypher";
import { webSearchRoute } from "./routes/v1/web.search";
import { webFetchRoute } from "./routes/v1/web.fetch";
import { researchSwarmStartRoute } from "./routes/v1/research.swarm.start";
import { researchSwarmStatusRoute } from "./routes/v1/research.swarm.status";
import { semanticEdgeRoute } from "./routes/v1/semantic-edge";
import { repoRoute } from "./routes/v1/repo";
import { integrationRoute } from "./routes/v1/integration";
import { pluginSchemaRoute, pluginVersionRoute } from "./routes/v1/plugin-schema";
import { graphNodeListRoute } from "./routes/v1/graph.node.list";
import { graphStatsRoute } from "./routes/v1/graph.stats";

export type AppEnv = {
  Variables: {
    requestId: string;
    userId: string | null;
    apiKeyId: string | null;
    orgId: string | null;
    workspaceId: string | null;
    capabilityContext?: CapabilityContext;
  };
};

export const app = new Hono<AppEnv>();

app.use("*", requestLogger);
// CORS must run before auth: a preflight OPTIONS carries no credentials, so
// it has to short-circuit here or the browser never sends the real request.
app.use("*", corsMiddleware);
app.onError(errorMiddleware);

// Public routes — health and Stripe webhook bypass auth. The webhook needs
// the raw body for signature verification and is its own auth surface.
app.route("/health", health);
app.route("/webhooks/stripe", stripeWebhook);
// Connector webhooks: unauthenticated — HMAC validation is the security boundary.
app.route("/webhooks", webhookRoute);
// Inngest cloud polls /api/inngest for the function manifest; signing-key
// verification is enforced inside the inngest/hono serve handler.
app.route("/api/inngest", inngestRoute);

// /v1 user-level routes (org + workspace CRUD) require auth but no
// org scope: a freshly-authenticated user can create their first
// org without one existing.
const userScoped = new Hono<AppEnv>();
userScoped.use("*", authMiddleware);
userScoped.route("/organizations", organizationCreateRoute);
userScoped.route("/user/preferences/read", userPreferencesReadRoute);
userScoped.route("/user/preferences/write", userPreferencesWriteRoute);
app.route("/v1", userScoped);

// /v1/:org_slug/:workspace_slug/* — org + workspace scoped routes.
const orgScoped = new Hono<AppEnv>();
orgScoped.use("*", authMiddleware, orgMiddleware, workspaceMiddleware);
orgScoped.route("/workspaces", workspaceCreateRoute);
orgScoped.route("/billing/subscription", billingSubscriptionReadRoute);
orgScoped.route("/billing/subscription/upgrade/start", billingSubscriptionUpgradeStartRoute);
orgScoped.route("/billing/credits/purchase", billingCreditsPurchaseRoute);
orgScoped.route("/chat/messages", chatMessageSendRoute);
orgScoped.route("/chat/messages/execution", chatMessageExecutionRoute);
orgScoped.route("/chat/stream", chatStreamRoute);
orgScoped.route("/conversations", conversationListRoute);
orgScoped.route("/conversations/rename", conversationRenameRoute);
orgScoped.route("/conversations/archive", conversationArchiveRoute);
orgScoped.route("/conversations/delete", conversationDeleteRoute);
orgScoped.route("/conversations/purge", conversationPurgeRoute);
// Agent-runtime routes live under the org + workspace scope so the runner
// inherits the same auth, isolation, and audit envelope as every other v1 call.
orgScoped.route("/agent/code/execute", agentCodeExecuteRoute);
orgScoped.route("/agent/tools", agentToolListRoute);
orgScoped.route("/agent/mcp-servers", agentMcpRegisterRoute);
orgScoped.route("/agent/mcp-servers", agentMcpListRoute);
orgScoped.route("/agent/skills", agentSkillListRoute);
orgScoped.route("/agent/skills/load", agentSkillLoadRoute);
orgScoped.route("/agent/plans/approve", agentPlanApproveRoute);
orgScoped.route("/agent/plans", agentPlanCreateRoute);
orgScoped.route("/agent/tasks", agentTaskBackgroundStartRoute);
orgScoped.route("/agent/tasks", agentTaskBackgroundReadRoute);
orgScoped.route("/agent/tasks/cancel", agentTaskBackgroundCancelRoute);
orgScoped.route("/agent/memory/recall", agentMemoryRecallRoute);
orgScoped.route("/agent/memory", agentMemoryWriteRoute);
orgScoped.route("/agent/approvals/resolve", agentApprovalResolveRoute);
orgScoped.route("/agent/execution/record", agentExecutionRecordRoute);
orgScoped.route("/agent/subagent/aggregate", agentSubagentAggregateRoute);
orgScoped.route("/agent/subagent/dispatch", agentSubagentDispatchRoute);
orgScoped.route("/forms/fill", formFillRoute);
orgScoped.route("/archive/create", archiveCreateRoute);
orgScoped.route("/documents/generate", documentsGenerateRoute);
orgScoped.route("/documents/pdf", documentsPdfCreateRoute);
orgScoped.route("/brandkit/apply", brandkitApplyRoute);
orgScoped.route("/video/generate", videoGenerateRoute);
orgScoped.route("/svg/generate", svgGenerateRoute);
orgScoped.route("/image/generate", imageGenerateRoute);
orgScoped.route("/system/install-instructions", systemInstallInstructionsRoute);
orgScoped.route("/org/members", orgMemberAddRoute);
orgScoped.route("/org/members/remove", orgMemberRemoveRoute);
orgScoped.route("/org/members/role", orgMemberRoleChangeRoute);
orgScoped.route("/org/invitations/accept", orgMemberInviteAcceptRoute);
orgScoped.route("/org/invitations/decline", orgMemberInviteDeclineRoute);
orgScoped.route("/workspace/model-settings", workspaceModelSettingsReadRoute);
orgScoped.route("/workspace/model-settings", workspaceModelSettingsWriteRoute);
orgScoped.route("/workspace/prompt-settings", promptSettingsReadRoute);
orgScoped.route("/workspace/prompt-settings", promptSettingsWriteRoute);
orgScoped.route("/asset/upload", assetUploadRoute);
orgScoped.route("/plugin/registries", pluginRegistryListRoute);
orgScoped.route("/plugin/registries/add", pluginRegistryAddRoute);
orgScoped.route("/plugin/registries/remove", pluginRegistryRemoveRoute);
orgScoped.route("/plugin/registries/sync", pluginRegistrySyncRoute);
orgScoped.route("/plugin/catalog/browse", pluginCatalogBrowseRoute);
orgScoped.route("/plugin/catalog/get", pluginCatalogGetRoute);
orgScoped.route("/plugin/org/list", pluginOrgListRoute);
orgScoped.route("/plugin/org/install", pluginOrgInstallRoute);
orgScoped.route("/plugin/org/install-bulk", pluginOrgInstallBulkRoute);
orgScoped.route("/plugin/org/uninstall", pluginOrgUninstallRoute);
orgScoped.route("/plugin/org/set-enabled", pluginOrgSetEnabledRoute);
orgScoped.route("/plugin/denylist/add", pluginDenylistAddRoute);
orgScoped.route("/plugin/denylist/remove", pluginDenylistRemoveRoute);
orgScoped.route("/plugin/workspace/set-enabled", pluginWorkspaceSetEnabledRoute);
orgScoped.route("/plugin/credential/set-secret", pluginCredentialSetSecretRoute);
orgScoped.route("/plugin/credential/reauth", pluginCredentialReauthRoute);
orgScoped.route("/notifications", notificationsListRoute);
orgScoped.route("/notifications/mark", notificationsMarkRoute);
orgScoped.route("/plugin/settings/auth-alerts", pluginSettingsSetAuthAlertsRoute);
orgScoped.route("/api-keys", apiKeyCreateRoute);
orgScoped.route("/api-keys/revoke", apiKeyRevokeRoute);
orgScoped.route("/workflows", workflowRoute);
orgScoped.route("/workspace/member/list", workspaceMemberListRoute);
orgScoped.route("/workspace/invite/send", workspaceInviteSendRoute);
orgScoped.route("/conversation/chat", conversationChatRoute);
orgScoped.route("/image/create", imageCreateRoute);
orgScoped.route("/image/list", imageListRoute);
orgScoped.route("/image/analyze", imageAnalyzeRoute);
orgScoped.route("/document/create", documentCreateRoute);
orgScoped.route("/document/list", documentListRoute);
orgScoped.route("/document/read", documentReadRoute);
orgScoped.route("/form/create", formCreateRoute);
orgScoped.route("/form/submit", formSubmitRoute);
orgScoped.route("/automation/list", automationListRoute);
orgScoped.route("/automation/create", automationCreateRoute);
orgScoped.route("/automation/enable", automationEnableRoute);
orgScoped.route("/automation/disable", automationDisableRoute);
orgScoped.route("/automation/trigger", automationTriggerRoute);
orgScoped.route("/skill/workspace/list", skillWorkspaceListRoute);
orgScoped.route("/privacy/export", privacyDataExportRoute);
orgScoped.route("/privacy/erase", privacyDataEraseRoute);
orgScoped.route("/connections", connectionRoute);
// GitHub App OAuth endpoints (workspace-scoped + auth-required)
orgScoped.route("/connections/github", githubOauthRoute);
orgScoped.route("/graph/node/upsert", graphNodeUpsertRoute);
orgScoped.route("/graph/node/get", graphNodeGetRoute);
orgScoped.route("/graph/node/delete", graphNodeDeleteRoute);
orgScoped.route("/graph/node/search", graphNodeSearchRoute);
orgScoped.route("/graph/edge/upsert", graphEdgeUpsertRoute);
orgScoped.route("/graph/edge/delete", graphEdgeDeleteRoute);
orgScoped.route("/graph/cypher", graphCypherRoute);
orgScoped.route("/web/search", webSearchRoute);
orgScoped.route("/web/fetch", webFetchRoute);
orgScoped.route("/research/swarm/start", researchSwarmStartRoute);
orgScoped.route("/research/swarm/status", researchSwarmStatusRoute);
orgScoped.route("/semantic-edges", semanticEdgeRoute);
orgScoped.route("/repos", repoRoute);
orgScoped.route("/integrations", integrationRoute);
orgScoped.route("/plugin-schema", pluginSchemaRoute);
orgScoped.route("/plugin-versions", pluginVersionRoute);
orgScoped.route("/graph/nodes", graphNodeListRoute);
orgScoped.route("/graph/stats", graphStatsRoute);
app.route("/v1/:org_slug/:workspace_slug", orgScoped);

// Public OAuth callback — HMAC-verified state param is the security boundary.
// Must NOT be inside the workspace-scoped group (user has no session when GitHub redirects).
app.route("/oauth/github", githubOauthCallbackRoute);
