#!/usr/bin/env python3
"""Move the secrets worth keeping out of `.env` files and into Parameter Store.

    tools/migrate-secrets.py --env-file ../oxagen-platform/.env.local --plan
    tools/migrate-secrets.py --env-file ../oxagen-platform/.env.local --apply

Parameter Store, not Secrets Manager: standard parameters are free, where
Secrets Manager bills $0.40 per secret per month. A hundred secrets there would
cost more per month than every website in this account combined, and buys
rotation machinery that nothing here uses yet.

Values are never printed. `--plan` shows each key, its classification, and the
length of its value — enough to tell an empty from a populated one, and to spot
a key that is obviously a URL rather than a credential, without putting the
credential itself on a terminal or in a log.

## The four classifications

MIGRATE     A live third-party credential that AWS does not replace. Copied
            across as a SecureString.

SUPERSEDED  A credential for infrastructure being replaced by this migration.
            The new Postgres, Neo4j and ClickHouse passwords are generated by
            Terraform and already in Parameter Store; copying the old ones
            across would install a second, wrong answer to the same question.

ROTATE      A credential that must be replaced rather than moved, because
            something has already happened to it. Copying it to a new home does
            not make it secret again. These are reported and deliberately NOT
            written, because writing them would launder a known-exposed secret
            into a system-of-record and make it look clean.

CONFIG      Not a secret at all — a feature flag, a public identifier, a model
            name, a URL. These belong in the application's configuration, not
            in an encrypted store, and are skipped.
"""

from __future__ import annotations

import argparse
import os
import re
import sys

# --- Classification -------------------------------------------------------

# Matched in order; the first hit wins.
RULES: list[tuple[str, str, str]] = [
    # Superseded by the credentials the data-node module generates.
    (r"^(PREVIEW_|PRODUCTION_)?DATABASE_URL$", "SUPERSEDED", "replaced by the new Postgres node"),
    (r"^PRODUCTION_POSTGRES_URL$", "SUPERSEDED", "replaced by the new Postgres node"),
    (r"^(PREVIEW_|PRODUCTION_)?NEO4J_", "SUPERSEDED", "replaced by the new Neo4j container"),
    (r"^(PREVIEW_|PRODUCTION_)?CLICKHOUSE_", "SUPERSEDED", "replaced by the new ClickHouse container"),
    (r"^(PRODUCTION_)?ANALYTICS_(URL|USER|PASSWORD|DATABASE)$", "SUPERSEDED", "ClickHouse analytics, replaced"),
    (r"^CH_API_KEY", "SUPERSEDED", "ClickHouse Cloud API key, no longer used"),

    # Tied to the Vercel account being migrated away from, and that account is
    # in arrears — every token issued by it should be treated as needing
    # replacement rather than relocation.
    (r"^VERCEL_", "ROTATE", "issued by the Vercel account being decommissioned"),
    (r"^BLOB_", "ROTATE", "Vercel Blob credential; storage moves to S3"),
    (r"^AI_GATEWAY_API_KEY$", "ROTATE", "Vercel AI Gateway key"),

    # Public by design — these ship to the browser.
    (r"^NEXT_PUBLIC_", "CONFIG", "public, served to the browser"),
    (r"_PUBLISHABLE_KEY$", "CONFIG", "publishable by design"),
    (r"^(NODE_ENV|PLATFORM_VERSION|REACT_EDITOR)$", "CONFIG", "build/runtime setting"),
    (r"^OXAGEN_(LLM_|EMBEDDING_|METER_|TARGET_|USAGE_|CLI_)", "CONFIG", "tuning parameter, not a secret"),
    (r"^(IAM_ENFORCEMENT_ENABLED|SANDBOX_ENABLED|SANDBOX_DRIVER|INGESTION_CRYPTO_PROVIDER)$", "CONFIG", "feature flag"),
    (r"^(POSTHOG_HOST|SMTP_HOST|SMTP_PORT|SMTP_FROM_EMAIL|SMTP_FROM_NAME|SMTP_USERNAME)$", "CONFIG", "non-secret endpoint detail"),
    (r"^(BETTER_AUTH_URL|OAUTH_PROXY_PRODUCTION_URL|MODAL_RUNNER_URL)$", "CONFIG", "endpoint URL"),
    (r"_(ID|SLUG|PATH)$", "CONFIG", "identifier, not a credential"),
]

DEFAULT = ("MIGRATE", "third-party credential")


def classify(key: str) -> tuple[str, str]:
    for pattern, verdict, why in RULES:
        if re.search(pattern, key):
            return verdict, why
    return DEFAULT


def read_env(path: str) -> dict[str, str]:
    """Parse a dotenv file well enough for this job.

    Deliberately not a full dotenv implementation: no interpolation, no
    `export` prefixes, no multi-line values. Anything it cannot parse it skips
    and reports, which is the safe direction — a secret silently mangled into
    Parameter Store is worse than one left behind and named.
    """
    out: dict[str, str] = {}
    with open(path, errors="replace") as fh:
        for raw in fh:
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip()
            value = value.strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1]
            if value:
                out[key] = value
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--env-file", required=True, action="append", help="dotenv file to read; repeatable")
    ap.add_argument("--prefix", default="/oxagen/production", help="Parameter Store path prefix")
    ap.add_argument("--region", default="us-east-1")
    group = ap.add_mutually_exclusive_group(required=True)
    group.add_argument("--plan", action="store_true", help="classify and report, writing nothing")
    group.add_argument("--apply", action="store_true", help="write the MIGRATE set to Parameter Store")
    args = ap.parse_args()

    merged: dict[str, str] = {}
    for path in args.env_file:
        if not os.path.exists(path):
            print(f"warning: {path} does not exist, skipping", file=sys.stderr)
            continue
        # Later files win. They are passed most-general first by convention,
        # so an app-specific override lands on top of the shared value.
        merged.update(read_env(path))

    buckets: dict[str, list[tuple[str, str, int]]] = {}
    for key, value in sorted(merged.items()):
        verdict, why = classify(key)
        buckets.setdefault(verdict, []).append((key, why, len(value)))

    for verdict in ("MIGRATE", "ROTATE", "SUPERSEDED", "CONFIG"):
        rows = buckets.get(verdict, [])
        print(f"\n=== {verdict} ({len(rows)}) ===")
        for key, why, length in rows:
            print(f"  {key:42} {length:5}b  {why}")

    if args.plan:
        print("\nplan only; nothing written")
        return 0

    import subprocess

    written = 0
    for key, _why, _length in buckets.get("MIGRATE", []):
        name = f"{args.prefix}/{key}"
        result = subprocess.run(
            [
                "aws", "ssm", "put-parameter",
                "--region", args.region,
                "--name", name,
                "--type", "SecureString",
                "--overwrite",
                # Passed on stdin rather than argv: an argument is visible in
                # the process table to every other process on the machine.
                "--value", "file:///dev/stdin",
            ],
            input=merged[key],
            text=True,
            capture_output=True,
        )
        if result.returncode != 0:
            print(f"  FAILED {key}: {result.stderr.strip()[:160]}", file=sys.stderr)
            continue
        written += 1
        print(f"  wrote {name}")

    print(f"\n{written} parameter(s) written under {args.prefix}")
    if buckets.get("ROTATE"):
        print(
            f"{len(buckets['ROTATE'])} secret(s) classified ROTATE were NOT written — "
            "issue new ones at the provider and add them directly."
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
