/**
 * capability-schema-docs.ts: render, compare and write the published
 * capability schema docs under `docs/capabilities/schemas/`.
 *
 * `gen-capability-schemas.ts` reads the capability registry and hands this
 * module plain data. Everything that decides what the files say lives here, so
 * a test can render a synthetic registry, compare it with a directory and
 * merge two branches of it in a real git repository, without loading the
 * real contracts or running the generator.
 *
 * The output holds no value derived from the whole capability set (ADR-214).
 * `_index.json` once carried `generatedCount` and `README.md` once carried
 * `**N capabilities** across M domains.` and a `- **domain** (N): a, b, c`
 * line per domain. Every branch that added a capability rewrote those lines,
 * so any two such branches conflicted by construction (#3691). A reader who
 * wants the count takes the length of `_index.json`'s `capabilities` array.
 */
import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { toJsonSchema, type ZodLike } from "./zod-json-schema";

/** What the generator needs from one registered capability. */
export interface CapabilityDocSource {
  name: string;
  domain: string;
  description?: string;
  mode?: string;
  surfaces?: readonly string[];
  sensitivity?: string;
  agent?: unknown;
  input: ZodLike;
  output: ZodLike;
  chain: {
    produces: readonly unknown[];
    consumes: readonly unknown[];
    chainHints: readonly string[];
  };
  /** The whole hint is published; only `componentId` is read here. */
  render?: { componentId: string } | null;
}

/** The command that regenerates the directory. Every failure names it. */
export const REGENERATE_COMMAND = "pnpm docs:schemas";

function byName(a: string, b: string): number {
  return a.localeCompare(b);
}

/**
 * Render every file the directory should hold, keyed by file name.
 *
 * Pure and deterministic: the same capabilities, in any order, produce the
 * same map with the same bytes.
 */
export function renderSchemaDocs(
  capabilities: readonly CapabilityDocSource[],
): Map<string, string> {
  const caps = [...capabilities].sort((a, b) => byName(a.name, b.name));
  const files = new Map<string, string>();
  const index: Array<Record<string, unknown>> = [];

  for (const cap of caps) {
    const surfaces = cap.surfaces ?? ["api", "mcp"];
    const doc = {
      name: cap.name,
      domain: cap.domain,
      description: cap.description,
      mode: cap.mode,
      surfaces,
      sensitivity: cap.sensitivity,
      agent: cap.agent ?? null,
      chain: {
        produces: cap.chain.produces,
        consumes: cap.chain.consumes,
        chainHints: cap.chain.chainHints,
      },
      render: cap.render ?? null,
      input: toJsonSchema(cap.input),
      output: toJsonSchema(cap.output),
    };
    files.set(`${cap.name}.json`, JSON.stringify(doc, null, 2) + "\n");
    index.push({
      name: cap.name,
      domain: cap.domain,
      surfaces,
      component: cap.render?.componentId ?? null,
      produces: cap.chain.produces,
      consumes: cap.chain.consumes,
    });
  }

  // No `generatedCount`: it is `capabilities.length`, and a committed copy of
  // it is a line every capability-adding branch rewrites (ADR-214).
  files.set(
    "_index.json",
    JSON.stringify({ capabilities: index }, null, 2) + "\n",
  );
  files.set("README.md", renderReadme(caps));
  return files;
}

/**
 * The human summary: one heading per domain and one capability per line.
 *
 * Neither a total nor a per-domain count appears, and no line joins several
 * names, so two branches that each add a capability, even to the same
 * domain, touch different lines and merge cleanly.
 */
function renderReadme(caps: readonly CapabilityDocSource[]): string {
  const byDomain = new Map<string, string[]>();
  for (const cap of caps) {
    const list = byDomain.get(cap.domain) ?? [];
    list.push(cap.name);
    byDomain.set(cap.domain, list);
  }
  const lines = [
    `# Capability JSON Schemas`,
    ``,
    `Auto-generated by \`tools/scripts/gen-capability-schemas.ts\`. One \`<capability>.json\``,
    `per capability with its input + output JSON Schema, chain metadata`,
    `(produces/consumes/chainHints), and chat render component. Do not edit by hand.`,
    ``,
    `This page gives no count. A count is a line that every branch adding a`,
    `capability rewrites, so two such branches always conflicted on it (ADR-214).`,
    `\`_index.json\` lists every capability for a machine to count.`,
  ];
  for (const [domain, names] of [...byDomain.entries()].sort((a, b) =>
    byName(a[0], b[0]),
  )) {
    lines.push(``, `## ${domain}`, ``, ...names.map((name) => `- ${name}`));
  }
  lines.push(``);
  return lines.join("\n");
}

/** Where a committed file first departs from its regenerated form. */
export interface FirstDifference {
  /** 1-based line number. */
  line: number;
  /** The committed line, or null when the committed file ends first. */
  committed: string | null;
  /** The regenerated line, or null when the regenerated file ends first. */
  regenerated: string | null;
}

/**
 * The first line at which two texts differ, or null when they are equal.
 *
 * A byte check that names only the file sends its reader to diff it by hand.
 * Naming the line and both values says at once whether the file is behind the
 * contracts or was resolved by picking one side of a merge.
 */
export function firstDifference(
  committed: string,
  regenerated: string,
): FirstDifference | null {
  if (committed === regenerated) return null;
  const a = committed.split("\n");
  const b = regenerated.split("\n");
  const length = Math.max(a.length, b.length);
  for (let i = 0; i < length; i += 1) {
    if (a[i] !== b[i]) {
      return {
        line: i + 1,
        committed: a[i] ?? null,
        regenerated: b[i] ?? null,
      };
    }
  }
  // Unreachable: unequal texts differ on some line. Kept so the type is total.
  return { line: length, committed: null, regenerated: null };
}

export interface StaleFile {
  file: string;
  /** False when the file is missing from the directory. */
  exists: boolean;
  difference: FirstDifference;
}

export interface SchemaDocsDiff {
  stale: StaleFile[];
  /** Files on disk that no capability produces. */
  orphans: string[];
}

/**
 * Compare the rendered files with a directory, without writing anything.
 *
 * Iterating the rendered files answers "is every generated file current?".
 * It cannot answer "is every generated file wanted?": a capability that is
 * deleted or renamed is simply not rendered, so its `.json` would never be
 * compared, removed or reported, and the published directory would keep
 * advertising a capability that no longer exists. So the directory is listed
 * too, and anything in it that nothing renders is an orphan. This found
 * `list_workspace_members.json`, absorbed into `list_members` by ADR-025's
 * Appendix E, still published months later (#3173).
 */
export function diffSchemaDocs(
  expected: ReadonlyMap<string, string>,
  dir: string,
): SchemaDocsDiff {
  const stale: StaleFile[] = [];
  for (const [file, contents] of [...expected.entries()].sort((a, b) =>
    byName(a[0], b[0]),
  )) {
    let current: string | undefined;
    try {
      current = readFileSync(join(dir, file), "utf8");
    } catch {
      current = undefined;
    }
    if (current === contents) continue;
    stale.push({
      file,
      exists: current !== undefined,
      difference: firstDifference(current ?? "", contents) ?? {
        line: 1,
        committed: null,
        regenerated: null,
      },
    });
  }
  return { stale, orphans: orphansIn(expected, dir) };
}

function orphansIn(
  expected: ReadonlyMap<string, string>,
  dir: string,
): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries
    .filter((file) => file.endsWith(".json") || file.endsWith(".md"))
    .filter((file) => !expected.has(file))
    .sort(byName);
}

function show(line: string | null): string {
  return line === null ? "(end of file)" : JSON.stringify(line);
}

/**
 * The message `--check` prints on failure, or null when the directory is
 * current. It names every stale file with its first differing line, committed
 * and regenerated, every orphan, and the command that fixes them.
 */
export function formatCheckReport(diff: SchemaDocsDiff): string | null {
  const problems: string[] = [];
  if (diff.stale.length > 0) {
    problems.push(
      `${diff.stale.length} file(s) behind the contracts:\n` +
        diff.stale
          .map((s) =>
            s.exists
              ? `  ${s.file}, first difference at line ${s.difference.line}\n` +
                `    committed:   ${show(s.difference.committed)}\n` +
                `    regenerated: ${show(s.difference.regenerated)}`
              : `  ${s.file}, missing`,
          )
          .join("\n"),
    );
  }
  if (diff.orphans.length > 0) {
    problems.push(
      `${diff.orphans.length} file(s) no contract accounts for:\n` +
        diff.orphans.map((f) => `  ${f}`).join("\n"),
    );
  }
  if (problems.length === 0) return null;
  return (
    `docs/capabilities/schemas does not match the contracts.\n\n` +
    problems.join("\n\n") +
    `\n\nRun \`${REGENERATE_COMMAND}\` and commit the result. These files are the` +
    `\npublished schema other people validate against: a stale one rejects` +
    `\ntraffic the real validator accepts, and an orphaned one advertises a` +
    `\ncapability that no longer exists. After a merge, regenerate from the` +
    `\nmerged tree rather than keeping either side's copy.`
  );
}

/**
 * Write the rendered files into `dir` and delete orphans. Returns the orphans
 * it removed. Only a plain run writes: `--check` must be repeatable with the
 * same meaning, so it never edits the tree it audits.
 */
export function writeSchemaDocs(
  files: ReadonlyMap<string, string>,
  dir: string,
): string[] {
  mkdirSync(dir, { recursive: true });
  for (const [file, contents] of files) {
    writeFileSync(join(dir, file), contents);
  }
  const removed = orphansIn(files, dir);
  for (const file of removed) rmSync(join(dir, file), { force: true });
  return removed;
}
