/**
 * cli-dev/lib — pure, side-effect-free helpers for the `oxagen` dev-CLI
 * installer. Everything here is deterministic given its inputs (filesystem and
 * child-process effects live in the entry script `../cli-dev.ts`) so the logic
 * is unit-testable without touching $PATH or spawning package managers.
 */
import { delimiter, join, resolve } from "node:path";

/** The on-PATH command name the monorepo CLI installs. */
export const BIN_NAME = "oxagen";

/**
 * Marker embedded in every launcher we generate. Used to recognise (and label)
 * a previously-installed dev launcher when sweeping $PATH for stale copies.
 */
export const LAUNCHER_MARKER = "Auto-generated by `pnpm cli:dev`";

/** How a discovered `oxagen` executable was created. */
export type BinKind = "dev-launcher" | "external";

/**
 * Split a `PATH`-style string into absolute, de-duplicated directory entries,
 * preserving priority order (earlier = higher priority). Empty segments are
 * dropped and every entry is resolved so `~/.local/bin` and `~/.local//bin`
 * collapse to one.
 */
export function parsePathEntries(pathEnv: string | undefined): string[] {
  return uniqueDirs((pathEnv ?? "").split(delimiter));
}

/** Resolve, drop empties/nullish, and de-duplicate a list of directories, order-preserving. */
export function uniqueDirs(
  dirs: ReadonlyArray<string | null | undefined>,
): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of dirs) {
    if (!raw) continue;
    const r = resolve(raw);
    if (seen.has(r)) continue;
    seen.add(r);
    out.push(r);
  }
  return out;
}

/**
 * Render the `oxagen` launcher shell script. It execs the repo-local `tsx`
 * against the CLI's TypeScript entry, so every invocation runs the current
 * working tree — no build, no watch, no stale `dist`. A self-check fails loudly
 * if the launcher outlives the monorepo path it points at.
 */
export function buildLauncherScript(tsxBin: string, srcEntry: string): string {
  return `#!/bin/sh
# ${LAUNCHER_MARKER} — runs @oxagen/cli straight from the monorepo working tree
# via the repo's own tsx, so every call reflects the latest source (no build, no
# stale dist). Do not edit; re-run \`pnpm cli:dev\` to refresh it.
__OXAGEN_TSX="${tsxBin}"
__OXAGEN_ENTRY="${srcEntry}"
if [ ! -x "$__OXAGEN_TSX" ] || [ ! -f "$__OXAGEN_ENTRY" ]; then
  echo "oxagen: dev launcher points at a missing monorepo path." >&2
  echo "oxagen: run \`pnpm install && pnpm cli:dev\` in the oxagen monorepo to refresh it." >&2
  exit 127
fi
exec "$__OXAGEN_TSX" "$__OXAGEN_ENTRY" "$@"
`;
}

/**
 * True when `content` is a launcher this repo generated AND it points at
 * `srcEntry` (i.e. this exact monorepo checkout). A launcher referencing a
 * different checkout is treated as foreign so the current repo always wins.
 */
export function isOurLauncher(
  content: string | null,
  srcEntry: string,
): boolean {
  return (
    Boolean(content) &&
    content!.includes(LAUNCHER_MARKER) &&
    content!.includes(srcEntry)
  );
}

/** Classify a discovered `oxagen` executable from its file contents. */
export function classifyBin(content: string | null, srcEntry: string): BinKind {
  return isOurLauncher(content, srcEntry) ? "dev-launcher" : "external";
}

/**
 * Return the path of the first `binName` found while walking `pathEntries` in
 * order — i.e. the one a shell would actually resolve — or null if none exist.
 * `exists` is injected so callers (and tests) decide what "present" means.
 */
export function firstBinOnPath(
  pathEntries: ReadonlyArray<string>,
  binName: string,
  exists: (p: string) => boolean,
): string | null {
  for (const dir of pathEntries) {
    const p = join(dir, binName);
    if (exists(p)) return p;
  }
  return null;
}

/**
 * Choose the directory to install the launcher into. Prefers `~/.local/bin`,
 * then the first writable directory already on $PATH. Never returns a dir that
 * isn't on $PATH unless nothing writable is — in which case it falls back to
 * `localBin` and reports `onPath: false` so the caller can warn.
 */
export function pickInstallDir(opts: {
  localBin: string;
  pathEntries: ReadonlyArray<string>;
  isWritable: (dir: string) => boolean;
}): { dir: string; onPath: boolean } {
  const local = resolve(opts.localBin);
  const onPath = new Set(opts.pathEntries.map((p) => resolve(p)));
  const preferred = uniqueDirs([local, ...opts.pathEntries]);

  for (const dir of preferred) {
    if (!onPath.has(dir)) continue;
    if (opts.isWritable(dir)) return { dir, onPath: true };
  }

  return { dir: local, onPath: onPath.has(local) };
}

/**
 * True when a globally-installed `@oxagen/cli` package lives under `rootDir`
 * (a package manager's global `node_modules`). Handles both the
 * `<root>/@oxagen/cli` and `<root>/node_modules/@oxagen/cli` layouts that pnpm
 * and npm report from `root -g`.
 */
export function hasGlobalPkg(
  rootDir: string | null | undefined,
  exists: (p: string) => boolean,
): boolean {
  if (!rootDir) return false;
  return (
    exists(join(rootDir, "@oxagen/cli")) ||
    exists(join(rootDir, "node_modules/@oxagen/cli"))
  );
}
