export type PolicyClass =
  | "standard"
  | "workspace_nullable"
  | "org_only"
  | "workspace_only"
  // org_or_global: org_id is NULLABLE — NULL rows are a shared/global catalog
  // visible to every tenant, non-NULL rows are tenant-private. Used by
  // mcp.registries (global default-seed registry + optional per-org registries).
  | "org_or_global";

export interface PolicyEntry {
  readonly table: string; // schema-qualified (schema.table_name)
  readonly policyClass: PolicyClass;
}

// Source of truth for which RLS policy each tenant-owned table gets.
//
// Policy classes are derived from the actual scoping-column nullability in
// information_schema (org_id / workspace_id, NN vs nullable) — not from
// domain intuition. A CI test (integration/manifest-coverage.test.ts) asserts
// every org_id column in the live schema appears here, every manifest table
// has FORCE ROW LEVEL SECURITY, and every manifest table carries a
// tenant_isolation policy — so a new owned table can't slip through and a
// future re-baseline that drops the policies fails CI instead of shipping.
//
// The DDL itself is generated by tools/scripts/gen-rls-migration.ts into
// packages/database/atlas/migrations/ (run it after editing this file).
//
// Tables WITHOUT org_id/workspace_id are intentionally absent — their
// isolation is transitive through an FK to a policied parent (e.g.
// agent.agent_versions → agent.agents, ingestion.oauth_tokens →
// ingestion.source_connections) or they are shared/system catalogs
// (billing.plans, billing.stripe_events, mcp.catalog_servers,
// ingestion.connector_schemas, Better Auth).
export const POLICY_MANIFEST: readonly PolicyEntry[] = [
  // ── agent.* (orgScopeMixin: org_id + workspace_id NOT NULL) ──────────────
  // agent.agent_versions excluded: immutable child, no org cols, FK → agents.
  { table: "agent.agents", policyClass: "standard" },
  // Workspace agent-asset registry (20260831120000_agent_asset_registry.sql):
  // tool declarations + context records + the append-only promotions ledger.
  // All tenant-authored (no builtin sentinel rows), so plain standard.
  { table: "agent.tools", policyClass: "standard" },
  { table: "agent.tool_versions", policyClass: "standard" },
  { table: "agent.context_records", policyClass: "standard" },
  { table: "agent.context_record_versions", policyClass: "standard" },
  { table: "agent.context_promotions", policyClass: "standard" },
  // Steering proposals and the Context PR state machine, and the records
  // agents append through append_record (ADR-061); org_id + workspace_id NOT NULL.
  { table: "agent.context_proposals", policyClass: "standard" },
  { table: "agent.context_appends", policyClass: "standard" },
  { table: "agent.agent_executions", policyClass: "standard" },
  { table: "agent.agent_execution_steps", policyClass: "standard" },
  { table: "agent.agent_tool_calls", policyClass: "standard" },
  { table: "agent.approval_requests", policyClass: "standard" },
  // Durable agent-engine v2 run rows + append-only event log (Phase 2a;
  // docs/specs/agent-engine-v2). Both carry orgScopeMixin (org_id +
  // workspace_id NOT NULL) + tenant_isolation RLS added in the Phase 2a
  // migration. agent_run_events has no idMixin (bare uuid pk, immutable
  // child) but is still row-scoped.
  { table: "agent.agent_runs", policyClass: "standard" },
  { table: "agent.agent_run_events", policyClass: "standard" },
  // Fenced attempt foundation (docs/specs/run-evidence-ingress). All four carry
  // orgScopeMixin-equivalent scope columns (org_id + workspace_id NOT NULL) +
  // forced tenant_isolation RLS from the run-attempt-foundation migration.
  // Every one of them is append-only at the grant level (SELECT, INSERT —
  // never UPDATE/DELETE for oxagen_app); RLS is orthogonal to that and still
  // required, or a tenant could read another tenant's evidence.
  { table: "agent.agent_run_attempts", policyClass: "standard" },
  { table: "agent.agent_run_attempt_seals", policyClass: "standard" },
  { table: "agent.agent_run_finalization_grants", policyClass: "standard" },
  {
    table: "agent.agent_run_finalization_obligations",
    policyClass: "standard",
  },

  // ── ai.* — response cache uses orgScopeMixin (tenant_isolation RLS created
  // in 20260704200000_ai_cache_and_batch_jobs.sql) ──────────────────────────
  { table: "ai.response_cache", policyClass: "standard" },

  // ── auth.* — api_keys uses orgScopeMixin ──────────────────────────────────
  // Better Auth tables (users/sessions/accounts/verifications/rate_limit/
  // user_preferences) are NOT row-scoped (no org_id; user-keyed lookups).
  { table: "auth.api_keys", policyClass: "standard" },
  // Per-(user, workspace) coding-agent defaults (default repo/environment).
  // orgScopeMixin (org_id + workspace_id both NOT NULL) + tenant_isolation RLS
  // in 20260713120000_workspace_user_preferences.sql → standard.
  { table: "auth.workspace_user_preferences", policyClass: "standard" },

  // ── billing.* (org_id only; no workspace_id on any billing table) ─────────
  // plans / stripe_events / stripe_event_processing excluded: shared catalogs
  // with no org_id column.
  { table: "billing.subscriptions", policyClass: "org_only" },
  { table: "billing.payment_methods", policyClass: "org_only" },
  { table: "billing.invoices", policyClass: "org_only" },
  { table: "billing.credit_balances", policyClass: "org_only" },
  { table: "billing.usage_outbox", policyClass: "standard" },
  { table: "billing.credit_ledger", policyClass: "org_only" },
  { table: "billing.credit_lots", policyClass: "org_only" },
  { table: "billing.org_billing_settings", policyClass: "org_only" },
  { table: "billing.billing_disputes", policyClass: "org_only" },
  // ADR-055 GAU model (20260914165423_gau_buckets_and_contract_terms.sql).
  // All three carry org_id NOT NULL and no workspace_id: terms, the month
  // bucket and the settlement ledger are org-wide. The recorder reads and
  // writes them through withTenantDb; the webhook branches and the close job
  // through withSystemDb.
  { table: "billing.contract_terms", policyClass: "org_only" },
  { table: "billing.gau_buckets", policyClass: "org_only" },
  { table: "billing.gau_settlements", policyClass: "org_only" },
  // The refunded/disputed half of the settlement ledger (ADR-085). org_id NOT
  // NULL, no workspace_id, written only by the webhook through withSystemDb.
  { table: "billing.gau_reversals", policyClass: "org_only" },
  // Period-to-date spend ceiling. org_id NOT NULL + workspace_id NULLABLE
  // (a NULL-workspace row is the org-level ceiling) → workspace_nullable.
  { table: "billing.spend_budgets", policyClass: "workspace_nullable" },
  // The recorders' running spend counter (ADR-060 §5): org_id NOT NULL,
  // workspace_id NULL for a frame outside a workspace → workspace_nullable.
  // Written and summed through withSystemDb with explicit org/workspace
  // predicates, because an org-level ceiling covers every workspace.
  { table: "billing.spend_counters", policyClass: "workspace_nullable" },

  // ── cost.* (ADR-060) ────────────────────────────────────────────────────
  // The price book: org_id NULL rows are the platform list prices every
  // tenant reads; an org's negotiated rows are its own → org_or_global.
  { table: "cost.price_entries", policyClass: "org_or_global" },
  // Derived spend rollups, rebuilt from frames; org_id + workspace_id NOT NULL.
  { table: "cost.run_totals", policyClass: "standard" },
  { table: "cost.daily_totals", policyClass: "standard" },
  // The findings job's output (ADR-062); org_id + workspace_id NOT NULL.
  { table: "cost.findings", policyClass: "standard" },
  // The organization's cost-center labels (ADR-142): org_id NOT NULL, no
  // workspace_id, so org_only.
  { table: "cost.cost_centers", policyClass: "org_only" },

  // ── chat.* / content.* (orgScopeMixin) ───────────────────────────────────
  { table: "chat.conversations", policyClass: "standard" },
  { table: "chat.messages", policyClass: "standard" },
  // content.documents went with the runtime (ADR-043); the attachment
  // reference row stays and is still tenant-owned.
  { table: "content.generated_assets", policyClass: "standard" },

  // ── graph.* — no graph.* tenant tables. Projection runs directly from the
  //   Inngest sync-execution-to-graph function; there is no outbox table.

  // ── iam.* — principals and principal_role_assignments have nullable workspace_id
  //   (NULL = org-wide principal/assignment); the rest are org-keyed.
  { table: "iam.principals", policyClass: "workspace_nullable" },
  {
    table: "iam.principal_role_assignments",
    policyClass: "workspace_nullable",
  },
  { table: "iam.roles", policyClass: "org_only" },
  { table: "iam.role_grants", policyClass: "org_only" },
  { table: "iam.access_requests", policyClass: "org_only" },
  // Governed-run authorization foundation (docs/specs/run-evidence-ingress).
  // authorization_snapshots is always bound to one executing workspace
  // (org_id + workspace_id NOT NULL) → standard. The other three are legitimately
  // org-wide OR workspace-scoped (workspace_id NULLABLE) → workspace_nullable,
  // same shape as iam.principals above.
  { table: "iam.authorization_snapshots", policyClass: "standard" },
  {
    table: "iam.authorization_deny_generations",
    policyClass: "workspace_nullable",
  },
  { table: "iam.emergency_denies", policyClass: "workspace_nullable" },
  { table: "iam.authorization_decisions", policyClass: "workspace_nullable" },

  // ── ingestion.* — connector epic. Child tables (auth_credentials,
  //   oauth_tokens, webhook_subscriptions) have no org cols; isolation is
  //   transitive through source_connections. oauth_accounts is org-level
  //   (encrypted OAuth tokens + PII, shared across workspaces).
  { table: "ingestion.source_connections", policyClass: "standard" },
  { table: "ingestion.entity_type_mappings", policyClass: "standard" },
  { table: "ingestion.setup_suggestions", policyClass: "standard" },
  { table: "ingestion.deletion_jobs", policyClass: "standard" },
  { table: "ingestion.oauth_accounts", policyClass: "org_only" },
  // Governed repository bindings (docs/specs/run-evidence-ingress). The
  // immutable versioned binding plus its mutable head pointer; both carry
  // org_id + workspace_id NOT NULL → standard.
  { table: "ingestion.repository_bindings", policyClass: "standard" },
  { table: "ingestion.repository_binding_heads", policyClass: "standard" },

  // ── mcp.* — all three tables below are tenant-owned (workspace-scoped).
  //   catalog_servers still exists (schema/mcp.ts) but is deliberately NOT
  //   listed here: it is a global catalog with no org_id/workspace_id column,
  //   so no tenant policy class applies to it.
  //   registries changed from org_or_global (nullable org_id) to standard
  //   (org_id + workspace_id both NOT NULL).
  { table: "mcp.credentials", policyClass: "standard" },
  { table: "mcp.mcp_servers", policyClass: "standard" },
  { table: "mcp.registries", policyClass: "standard" },
  // External-MCP first-use consent grants + tool-descriptor snapshots.
  // Both carry orgScopeMixin (org_id + workspace_id NOT NULL) → standard.
  { table: "mcp.consents", policyClass: "standard" },
  { table: "mcp.tool_snapshots", policyClass: "standard" },
  // The credential broker's grant log (#2958): orgScopeMixin → standard.
  { table: "mcp.credential_grants", policyClass: "standard" },

  // ── notification.* (org_id NOT NULL, workspace_id nullable) ──────────────
  { table: "notification.notifications", policyClass: "workspace_nullable" },

  // ── org.* — membership + invitations (org root itself is not row-scoped:
  //   organizations.id IS the tenant key, there is no org_id column). ───────
  { table: "org.org_users", policyClass: "org_only" },
  { table: "org.invitations", policyClass: "org_only" },
  // Slug-rename audit. org_id NOT NULL, no workspace_id → org_only.
  // Resolver reads via withSystemDb (bypass); writes happen inside tenant scope.
  { table: "org.org_slug_history", policyClass: "org_only" },
  // ADR-042 organisation-scoped data-plane bindings. org_id NOT NULL, no
  // workspace_id → org_only, the same class the other platform-level
  // org-scoped settings tables use (billing.org_billing_settings,
  // security.org_security_policy). Every access is withSystemDb (the resolver
  // runs before a tenant scope exists, and the row is platform state that must
  // stay on the shared plane), so the policy is the backstop, not the filter.
  { table: "org.data_planes", policyClass: "org_only" },
  // ADR-053: the organisation's model-vendor key. Org-only, read through
  // withTenantDb — nothing resolves through it, so RLS is the filter here.
  { table: "org.model_credentials", policyClass: "org_only" },
  // SSO group → role mappings (ADR-145). auth.sso_providers is absent on
  // purpose: it is a Better Auth table read before any tenant scope exists.
  { table: "org.sso_group_roles", policyClass: "org_only" },
  // SCIM provisioning (#3734): the organization's bearer token (hash only),
  // the groups its identity provider pushed, and their members. org_id NOT
  // NULL, no workspace_id. Read through withSystemDb before a tenant scope
  // exists, so the policy is the backstop.
  { table: "org.scim_tokens", policyClass: "org_only" },
  { table: "org.scim_groups", policyClass: "org_only" },
  { table: "org.scim_group_members", policyClass: "org_only" },
  { table: "org.assistant_model_keys", policyClass: "org_only" },
  // The onboarding gate (#2967): one row per organization, org_id is the
  // primary key and there is no workspace_id (the gate's workspace is a plain
  // column) → org_only. Read and written through withTenantDb by the gate
  // handlers; create_org writes the first row through withSystemDb.
  { table: "org.onboarding_state", policyClass: "org_only" },

  // ── plugin.* (workspace-scoped) ────────────────────────────────────────────
  { table: "plugin.installed_plugins", policyClass: "standard" },

  // ── privacy.* — GDPR Art.17/20 request queues (org_id NN, no workspace) ──
  { table: "privacy.privacy_export_requests", policyClass: "org_only" },
  { table: "privacy.privacy_erasure_requests", policyClass: "org_only" },

  // ── security.* (security_events: org_id NOT NULL, workspace_id nullable;
  //   partitioned parent — children inherit enforcement) ────────────────────
  { table: "security.security_events", policyClass: "workspace_nullable" },
  { table: "security.org_security_policy", policyClass: "org_only" },
  // External-MCP server lifecycle audit. Append-only, but org_id +
  // workspace_id are both NOT NULL (servers are workspace-scoped) → standard.
  { table: "security.mcp_server_changes", policyClass: "standard" },

  // ── schema_registry.* — Workspace Schema Registry (Spec §4 + §11 RLS).
  //   All 7 tables carry orgScopeMixin (org_id + workspace_id NOT NULL) → standard.
  //   schema_versions has no softDeleteMixin (immutable once published) but has
  //   org_id + workspace_id NN — still standard policy class.
  { table: "schema_registry.registries", policyClass: "standard" },
  { table: "schema_registry.schema_versions", policyClass: "standard" },
  { table: "schema_registry.schemas", policyClass: "standard" },
  { table: "schema_registry.schema_activations", policyClass: "standard" },
  { table: "schema_registry.node_labels", policyClass: "standard" },
  { table: "schema_registry.relationship_types", policyClass: "standard" },
  { table: "schema_registry.properties", policyClass: "standard" },

  // ── workspace.* ───────────────────────────────────────────────────────────
  //   workspaces has org_id NOT NULL but no workspace_id — org_only policy.
  //   workspace_users is the membership table: workspace_id + user_id but NO
  //   org_id, so it cannot use an org-keyed policy. It gets a workspace_only
  //   policy keyed on app.current_workspace_id — without it the table has NO
  //   RLS and member rows leak across tenants.
  { table: "workspace.workspaces", policyClass: "org_only" },
  { table: "workspace.workspace_users", policyClass: "workspace_only" },
  // Slug-rename audit. org_id + workspace_id both NOT NULL →
  // standard. Resolver reads via withSystemDb (bypass) — workspace slugs are
  // only unique within an org, so the read filters on (org_id, old_slug).
  { table: "workspace.workspace_slug_history", policyClass: "standard" },
  // Agent-memory decay policy. org_id + workspace_id both NOT NULL
  // → standard tenant_isolation RLS.
  { table: "workspace.workspace_memory_policy", policyClass: "standard" },
  // Per-turn budget governance. org_id + workspace_id both NOT NULL
  // → standard tenant_isolation RLS.
  { table: "workspace.workspace_budget_policy", policyClass: "standard" },
  // Wrapped-harness session governance: what the loopback model gateway
  // refuses for a Claude Code or Codex session. org_id + workspace_id both
  // NOT NULL → standard tenant_isolation RLS.
  { table: "workspace.tacho_session_policy", policyClass: "standard" },
  // Verified-Outcome Market Router governance. org_id NOT NULL + workspace_id
  // NULLABLE → workspace_nullable tenant_isolation RLS.
  { table: "workspace.routing_policy", policyClass: "workspace_nullable" },

  // ── environments.* — Agent Environments & Credential Vault (Phase 0, Spec §5).
  //   All four carry org_id + workspace_id NOT NULL → standard tenant_isolation.
  { table: "environments.environments", policyClass: "standard" },
  { table: "environments.secret_keys", policyClass: "standard" },
  { table: "environments.secret_values", policyClass: "standard" },
  { table: "environments.secret_access_log", policyClass: "standard" },
  // Agent → environment bindings (Spec §5.6). org_id + workspace_id NOT NULL
  //   → standard tenant_isolation.
  { table: "environments.agent_environment_bindings", policyClass: "standard" },

  // ── evidence.* — immutable governed-run evidence (run-evidence-ingress).
  //   Only the pinned retention-policy version exists at foundation time; the
  //   manifest/blob ledger lands in the evidence-ledger PR. org_id +
  //   workspace_id both NOT NULL → standard tenant_isolation.
  { table: "evidence.retention_policy_versions", policyClass: "standard" },
  // The export job `export_run` queues (ADR-058): org_id + workspace_id NOT NULL.
  { table: "evidence.run_exports", policyClass: "standard" },
  // Proof (ADR-064): witnesses and their verdicts, written by tacho ingest, and
  // the workspace's disclosure grain. org_id + workspace_id NOT NULL.
  { table: "evidence.witnesses", policyClass: "standard" },
  { table: "evidence.verdicts", policyClass: "standard" },
  { table: "evidence.disclosure_policies", policyClass: "standard" },

  // ── tools.* — mandates and their append-only ledger (ADR-059,
  //   20260915202300_mandates_and_ledger.sql). Both carry orgScopeMixin.
  { table: "tools.mandates", policyClass: "standard" },
  { table: "tools.mandate_ledger", policyClass: "standard" },

  { table: "skills.config_versions", policyClass: "standard" },
  { table: "skills.resolutions", policyClass: "standard" },

  // ── tacho.* — hosts, sessions, and control state for agents Oxagen does
  //   not run (docs/specs/tacho/data-model.md section 3). Every one carries
  //   org_id + workspace_id NOT NULL → standard tenant_isolation.
  { table: "tacho.hosts", policyClass: "standard" },
  { table: "tacho.sessions", policyClass: "standard" },
  { table: "tacho.session_models", policyClass: "standard" },
  { table: "tacho.session_files", policyClass: "standard" },
  { table: "tacho.session_commands", policyClass: "standard" },
  { table: "tacho.control_commands", policyClass: "standard" },
  { table: "tacho.incidents", policyClass: "standard" },
  { table: "tacho.checkpoints", policyClass: "standard" },
  // Single-use enrollment tokens (#2967): orgScopeMixin, consumed by
  // enroll_host inside the token's own tenant scope.
  { table: "tacho.enrollment_tokens", policyClass: "standard" },
  // The control plane's record of each authorised local-MCP-gateway call and
  // the daemon chain it was serving (#3221). Written by `machineKeyDenial`
  // through `withOrgPlaneSystemDb`, which bypasses RLS at authorisation time;
  // read by `tacho.events.ingest` through `withTenantDb`, where the policy is
  // what keeps one organisation's evidence out of another's tier.
  { table: "tacho.gateway_chains", policyClass: "standard" },
  { table: "tacho.contained_launches", policyClass: "standard" },
];
