export type PolicyClass =
  | "standard"
  | "workspace_nullable"
  | "org_only"
  | "workspace_only"
  // org_or_global: org_id is NULLABLE — NULL rows are a shared/global catalog
  // visible to every tenant, non-NULL rows are tenant-private. Used by
  // mcp.registries (global default-seed registry + optional per-org registries).
  | "org_or_global";

export interface PolicyEntry {
  readonly table: string; // schema-qualified (schema.table_name)
  readonly policyClass: PolicyClass;
}

// Source of truth for which RLS policy each tenant-owned table gets.
//
// Policy classes are derived from the actual scoping-column nullability in
// information_schema (org_id / workspace_id, NN vs nullable) — not from
// domain intuition. A CI test (integration/manifest-coverage.test.ts) asserts
// every org_id column in the live schema appears here, every manifest table
// has FORCE ROW LEVEL SECURITY, and every manifest table carries a
// tenant_isolation policy — so a new owned table can't slip through and a
// future re-baseline that drops the policies fails CI instead of shipping.
//
// The DDL itself is generated by tools/scripts/gen-rls-migration.ts into
// packages/database/atlas/migrations/ (run it after editing this file).
//
// Tables WITHOUT org_id/workspace_id are intentionally absent — their
// isolation is transitive through an FK to a policied parent (e.g.
// agent.agent_versions → agent.agents, ingestion.oauth_tokens →
// ingestion.source_connections) or they are shared/system catalogs
// (billing.plans, billing.stripe_events, mcp.catalog_servers,
// ingestion.connector_schemas, Better Auth).
export const POLICY_MANIFEST: readonly PolicyEntry[] = [
  // ── agent.* (orgScopeMixin: org_id + workspace_id NOT NULL) ──────────────
  // agent.agent_versions excluded: immutable child, no org cols, FK → agents.
  { table: "agent.agents", policyClass: "standard" },
  // Workspace agent-asset registry (20260831120000_agent_asset_registry.sql):
  // tool declarations + context records + the append-only promotions ledger.
  // All tenant-authored (no builtin sentinel rows), so plain standard.
  { table: "agent.tools", policyClass: "standard" },
  { table: "agent.tool_versions", policyClass: "standard" },
  { table: "agent.context_records", policyClass: "standard" },
  { table: "agent.context_record_versions", policyClass: "standard" },
  { table: "agent.context_promotions", policyClass: "standard" },
  { table: "agent.agent_executions", policyClass: "standard" },
  { table: "agent.agent_execution_steps", policyClass: "standard" },
  { table: "agent.agent_tool_calls", policyClass: "standard" },
  { table: "agent.approval_requests", policyClass: "standard" },
  // Durable A2A task store (orgScopeMixin + tenant_isolation RLS in
  // 20260704230000_a2a_tasks.sql).
  { table: "agent.a2a_tasks", policyClass: "standard" },
  // Durable agent-engine v2 run rows + append-only event log (Phase 2a;
  // docs/specs/agent-engine-v2). Both carry orgScopeMixin (org_id +
  // workspace_id NOT NULL) + tenant_isolation RLS added in the Phase 2a
  // migration. agent_run_events has no idMixin (bare uuid pk, immutable
  // child) but is still row-scoped.
  { table: "agent.agent_runs", policyClass: "standard" },
  { table: "agent.agent_run_events", policyClass: "standard" },
  // Fenced attempt foundation (docs/specs/run-evidence-ingress). All four carry
  // orgScopeMixin-equivalent scope columns (org_id + workspace_id NOT NULL) +
  // forced tenant_isolation RLS from the run-attempt-foundation migration.
  // Every one of them is append-only at the grant level (SELECT, INSERT —
  // never UPDATE/DELETE for oxagen_app); RLS is orthogonal to that and still
  // required, or a tenant could read another tenant's evidence.
  { table: "agent.agent_run_attempts", policyClass: "standard" },
  { table: "agent.agent_run_attempt_seals", policyClass: "standard" },
  { table: "agent.agent_run_finalization_grants", policyClass: "standard" },
  {
    table: "agent.agent_run_finalization_obligations",
    policyClass: "standard",
  },

  // ── ai.* — response cache uses orgScopeMixin (tenant_isolation RLS created
  // in 20260704200000_ai_cache_and_batch_jobs.sql) ──────────────────────────
  { table: "ai.response_cache", policyClass: "standard" },

  // ── auth.* — api_keys uses orgScopeMixin ──────────────────────────────────
  // Better Auth tables (users/sessions/accounts/verifications/rate_limit/
  // user_preferences) are NOT row-scoped (no org_id; user-keyed lookups).
  { table: "auth.api_keys", policyClass: "standard" },
  // Per-(user, workspace) coding-agent defaults (default repo/environment).
  // orgScopeMixin (org_id + workspace_id both NOT NULL) + tenant_isolation RLS
  // in 20260713120000_workspace_user_preferences.sql → standard.
  { table: "auth.workspace_user_preferences", policyClass: "standard" },

  // ── billing.* (org_id only; no workspace_id on any billing table) ─────────
  // plans / stripe_events / stripe_event_processing excluded: shared catalogs
  // with no org_id column.
  { table: "billing.subscriptions", policyClass: "org_only" },
  { table: "billing.payment_methods", policyClass: "org_only" },
  { table: "billing.invoices", policyClass: "org_only" },
  { table: "billing.credit_balances", policyClass: "org_only" },
  { table: "billing.credit_ledger", policyClass: "org_only" },
  { table: "billing.credit_lots", policyClass: "org_only" },
  { table: "billing.org_billing_settings", policyClass: "org_only" },
  { table: "billing.billing_disputes", policyClass: "org_only" },
  // Period-to-date spend ceiling. org_id NOT NULL + workspace_id NULLABLE
  // (a NULL-workspace row is the org-level ceiling) → workspace_nullable.
  { table: "billing.spend_budgets", policyClass: "workspace_nullable" },
  // Reseller revenue (Stripe-for-agents re-bill loop) — org-only RLS.
  { table: "billing.reseller_price_plans", policyClass: "org_only" },
  { table: "billing.reseller_customers", policyClass: "org_only" },
  { table: "billing.reseller_attribution_rules", policyClass: "org_only" },
  { table: "billing.reseller_rebill_runs", policyClass: "org_only" },
  { table: "billing.reseller_rebill_line_items", policyClass: "org_only" },
  { table: "billing.reseller_settings", policyClass: "org_only" },

  // ── chat.* / content.* (orgScopeMixin) ───────────────────────────────────
  { table: "chat.conversations", policyClass: "standard" },
  { table: "chat.messages", policyClass: "standard" },
  // content.documents went with the runtime (ADR-041); the attachment
  // reference row stays and is still tenant-owned.
  { table: "content.generated_assets", policyClass: "standard" },

  // ── graph.* — no graph.* tenant tables. Projection runs directly from the
  //   Inngest sync-execution-to-graph function; there is no outbox table.

  // ── iam.* — principals and principal_role_assignments have nullable workspace_id
  //   (NULL = org-wide principal/assignment); the rest are org-keyed.
  { table: "iam.principals", policyClass: "workspace_nullable" },
  {
    table: "iam.principal_role_assignments",
    policyClass: "workspace_nullable",
  },
  { table: "iam.roles", policyClass: "org_only" },
  { table: "iam.role_grants", policyClass: "org_only" },
  { table: "iam.access_requests", policyClass: "org_only" },
  // Governed-run authorization foundation (docs/specs/run-evidence-ingress).
  // authorization_snapshots is always bound to one executing workspace
  // (org_id + workspace_id NOT NULL) → standard. The other three are legitimately
  // org-wide OR workspace-scoped (workspace_id NULLABLE) → workspace_nullable,
  // same shape as iam.principals above.
  { table: "iam.authorization_snapshots", policyClass: "standard" },
  {
    table: "iam.authorization_deny_generations",
    policyClass: "workspace_nullable",
  },
  { table: "iam.emergency_denies", policyClass: "workspace_nullable" },
  { table: "iam.authorization_decisions", policyClass: "workspace_nullable" },

  // ── ingestion.* — connector epic. Child tables (auth_credentials,
  //   oauth_tokens, webhook_subscriptions) have no org cols; isolation is
  //   transitive through source_connections. oauth_accounts is org-level
  //   (encrypted OAuth tokens + PII, shared across workspaces).
  { table: "ingestion.source_connections", policyClass: "standard" },
  { table: "ingestion.entity_type_mappings", policyClass: "standard" },
  { table: "ingestion.setup_suggestions", policyClass: "standard" },
  { table: "ingestion.deletion_jobs", policyClass: "standard" },
  { table: "ingestion.oauth_accounts", policyClass: "org_only" },
  // Governed repository bindings (docs/specs/run-evidence-ingress). The
  // immutable versioned binding plus its mutable head pointer; both carry
  // org_id + workspace_id NOT NULL → standard.
  { table: "ingestion.repository_bindings", policyClass: "standard" },
  { table: "ingestion.repository_binding_heads", policyClass: "standard" },

  // ── mcp.* — all three tables below are tenant-owned (workspace-scoped).
  //   catalog_servers still exists (schema/mcp.ts) but is deliberately NOT
  //   listed here: it is a global catalog with no org_id/workspace_id column,
  //   so no tenant policy class applies to it.
  //   registries changed from org_or_global (nullable org_id) to standard
  //   (org_id + workspace_id both NOT NULL).
  { table: "mcp.credentials", policyClass: "standard" },
  { table: "mcp.mcp_servers", policyClass: "standard" },
  { table: "mcp.registries", policyClass: "standard" },
  // External-MCP first-use consent grants + tool-descriptor snapshots.
  // Both carry orgScopeMixin (org_id + workspace_id NOT NULL) → standard.
  { table: "mcp.consents", policyClass: "standard" },
  { table: "mcp.tool_snapshots", policyClass: "standard" },

  // ── notification.* (org_id NOT NULL, workspace_id nullable) ──────────────
  { table: "notification.notifications", policyClass: "workspace_nullable" },

  // ── org.* — membership + invitations (org root itself is not row-scoped:
  //   organizations.id IS the tenant key, there is no org_id column). ───────
  { table: "org.org_users", policyClass: "org_only" },
  { table: "org.invitations", policyClass: "org_only" },
  // Slug-rename audit. org_id NOT NULL, no workspace_id → org_only.
  // Resolver reads via withSystemDb (bypass); writes happen inside tenant scope.
  { table: "org.org_slug_history", policyClass: "org_only" },
  // ADR-042 organisation-scoped data-plane bindings. org_id NOT NULL, no
  // workspace_id → org_only, the same class the other platform-level
  // org-scoped settings tables use (billing.org_billing_settings,
  // security.org_security_policy). Every access is withSystemDb (the resolver
  // runs before a tenant scope exists, and the row is platform state that must
  // stay on the shared plane), so the policy is the backstop, not the filter.
  { table: "org.data_planes", policyClass: "org_only" },

  // ── plugin.* (workspace-scoped) ────────────────────────────────────────────
  { table: "plugin.installed_plugins", policyClass: "standard" },

  // ── privacy.* — GDPR Art.17/20 request queues (org_id NN, no workspace) ──
  { table: "privacy.privacy_export_requests", policyClass: "org_only" },
  { table: "privacy.privacy_erasure_requests", policyClass: "org_only" },

  // ── security.* (security_events: org_id NOT NULL, workspace_id nullable;
  //   partitioned parent — children inherit enforcement) ────────────────────
  { table: "security.security_events", policyClass: "workspace_nullable" },
  { table: "security.org_security_policy", policyClass: "org_only" },
  // External-MCP server lifecycle audit. Append-only, but org_id +
  // workspace_id are both NOT NULL (servers are workspace-scoped) → standard.
  { table: "security.mcp_server_changes", policyClass: "standard" },

  // ── schema_registry.* — Workspace Schema Registry (Spec §4 + §11 RLS).
  //   All 7 tables carry orgScopeMixin (org_id + workspace_id NOT NULL) → standard.
  //   schema_versions has no softDeleteMixin (immutable once published) but has
  //   org_id + workspace_id NN — still standard policy class.
  { table: "schema_registry.registries", policyClass: "standard" },
  { table: "schema_registry.schema_versions", policyClass: "standard" },
  { table: "schema_registry.schemas", policyClass: "standard" },
  { table: "schema_registry.schema_activations", policyClass: "standard" },
  { table: "schema_registry.node_labels", policyClass: "standard" },
  { table: "schema_registry.relationship_types", policyClass: "standard" },
  { table: "schema_registry.properties", policyClass: "standard" },

  // ── workspace.* ───────────────────────────────────────────────────────────
  //   workspaces has org_id NOT NULL but no workspace_id — org_only policy.
  //   workspace_users is the membership table: workspace_id + user_id but NO
  //   org_id, so it cannot use an org-keyed policy. It gets a workspace_only
  //   policy keyed on app.current_workspace_id — without it the table has NO
  //   RLS and member rows leak across tenants.
  { table: "workspace.workspaces", policyClass: "org_only" },
  { table: "workspace.workspace_users", policyClass: "workspace_only" },
  // Slug-rename audit. org_id + workspace_id both NOT NULL →
  // standard. Resolver reads via withSystemDb (bypass) — workspace slugs are
  // only unique within an org, so the read filters on (org_id, old_slug).
  { table: "workspace.workspace_slug_history", policyClass: "standard" },
  // Agent-memory decay policy. org_id + workspace_id both NOT NULL
  // → standard tenant_isolation RLS.
  { table: "workspace.workspace_memory_policy", policyClass: "standard" },
  // Per-turn budget governance. org_id + workspace_id both NOT NULL
  // → standard tenant_isolation RLS.
  { table: "workspace.workspace_budget_policy", policyClass: "standard" },
  // Verified-Outcome Market Router governance. org_id NOT NULL + workspace_id
  // NULLABLE → workspace_nullable tenant_isolation RLS.
  { table: "workspace.routing_policy", policyClass: "workspace_nullable" },

  // ── environments.* — Agent Environments & Credential Vault (Phase 0, Spec §5).
  //   All four carry org_id + workspace_id NOT NULL → standard tenant_isolation.
  { table: "environments.environments", policyClass: "standard" },
  { table: "environments.secret_keys", policyClass: "standard" },
  { table: "environments.secret_values", policyClass: "standard" },
  { table: "environments.secret_access_log", policyClass: "standard" },
  // Agent → environment bindings (Spec §5.6). org_id + workspace_id NOT NULL
  //   → standard tenant_isolation.
  { table: "environments.agent_environment_bindings", policyClass: "standard" },

  // ── evidence.* — immutable governed-run evidence (run-evidence-ingress).
  //   Only the pinned retention-policy version exists at foundation time; the
  //   manifest/blob ledger lands in the evidence-ledger PR. org_id +
  //   workspace_id both NOT NULL → standard tenant_isolation.
  { table: "evidence.retention_policy_versions", policyClass: "standard" },
];
