export type PolicyClass =
  | "standard"
  | "workspace_nullable"
  | "org_only"
  | "workspace_only"
  // org_or_global: org_id is NULLABLE — NULL rows are a shared/global catalog
  // visible to every tenant, non-NULL rows are tenant-private. Used by
  // mcp.registries (global default-seed registry + optional per-org registries).
  | "org_or_global"
  // standard_or_builtin: like standard, but rows stamped with the nil-UUID
  // sentinel org/workspace (packages/skills BUILTIN_*) are a platform-global
  // catalog READABLE by every tenant. WRITES stay tenant-only — creating or
  // altering a builtin row is reserved for the seeding/system path
  // (app.rls_bypass='on'), mirroring the org_or_global asymmetry. Used by the
  // skills tables so seeded builtin skills are visible through withTenantDb.
  | "standard_or_builtin";

export interface PolicyEntry {
  readonly table: string; // schema-qualified (schema.table_name)
  readonly policyClass: PolicyClass;
}

// Source of truth for which RLS policy each tenant-owned table gets.
//
// Rewritten for the 2026-06-11 Atlas baseline (OXA-1700): the schema rebuild
// moved IAM to the `iam.*` Postgres schema, replaced the automation tables
// with the playbook domain in `workflow.*`, added `privacy.*` and `graph.*`,
// and dropped the pre-rewrite orphans this manifest used to track.
//
// Policy classes are derived from the actual scoping-column nullability in
// information_schema (org_id / workspace_id, NN vs nullable) — not from
// domain intuition. A CI test (integration/manifest-coverage.test.ts) asserts
// every org_id column in the live schema appears here, every manifest table
// has FORCE ROW LEVEL SECURITY, and every manifest table carries a
// tenant_isolation policy — so a new owned table can't slip through and a
// future re-baseline that drops the policies fails CI instead of shipping.
//
// The DDL itself is generated by tools/scripts/gen-rls-migration.ts into
// packages/database/atlas/migrations/ (run it after editing this file).
//
// Tables WITHOUT org_id/workspace_id are intentionally absent — their
// isolation is transitive through an FK to a policied parent (e.g.
// agent.agent_versions → agent.agents, workflow.playbook_steps →
// workflow.playbook_versions → workflow.playbooks, ingestion.oauth_tokens →
// ingestion.source_connections) or they are shared/system catalogs
// (billing.plans, billing.stripe_events, mcp.catalog_servers,
// ingestion.connector_schemas, graph.projection_checkpoints, Better Auth).
export const POLICY_MANIFEST: readonly PolicyEntry[] = [
  // ── agent.* (orgScopeMixin: org_id + workspace_id NOT NULL) ──────────────
  // agent.agent_versions excluded: immutable child, no org cols, FK → agents.
  { table: "agent.agents", policyClass: "standard" },
  { table: "agent.skills", policyClass: "standard_or_builtin" },
  { table: "agent.skill_versions", policyClass: "standard_or_builtin" },
  { table: "agent.agent_plans", policyClass: "standard" },
  { table: "agent.agent_executions", policyClass: "standard" },
  { table: "agent.agent_execution_steps", policyClass: "standard" },
  { table: "agent.agent_tool_calls", policyClass: "standard" },
  { table: "agent.approval_requests", policyClass: "standard" },
  { table: "agent.background_tasks", policyClass: "standard" },
  { table: "agent.subagent_fanouts", policyClass: "standard" },
  { table: "agent.subagent_runs", policyClass: "standard" },
  { table: "agent.agent_triggers", policyClass: "standard" },

  // ── auth.* — credentials + api_keys use orgScopeMixin ────────────────────
  // Better Auth tables (users/sessions/accounts/verifications/rate_limit/
  // user_preferences) are NOT row-scoped (no org_id; user-keyed lookups).
  { table: "auth.credentials", policyClass: "standard" },
  { table: "auth.api_keys", policyClass: "standard" },

  // ── billing.* (org_id only; no workspace_id on any billing table) ─────────
  // plans / stripe_events / stripe_event_processing excluded: shared catalogs
  // with no org_id column.
  { table: "billing.subscriptions", policyClass: "org_only" },
  { table: "billing.payment_methods", policyClass: "org_only" },
  { table: "billing.invoices", policyClass: "org_only" },
  { table: "billing.invoice_line_items", policyClass: "org_only" },
  { table: "billing.usage_records", policyClass: "org_only" },
  { table: "billing.credit_balances", policyClass: "org_only" },
  { table: "billing.credit_ledger", policyClass: "org_only" },
  { table: "billing.credit_lots", policyClass: "org_only" },
  { table: "billing.org_billing_profiles", policyClass: "org_only" },
  { table: "billing.org_billing_settings", policyClass: "org_only" },
  { table: "billing.billing_disputes", policyClass: "org_only" },

  // ── chat.* / content.* (orgScopeMixin) ───────────────────────────────────
  { table: "chat.conversations", policyClass: "standard" },
  { table: "chat.messages", policyClass: "standard" },
  { table: "content.generated_assets", policyClass: "standard" },
  { table: "content.documents", policyClass: "standard" },
  { table: "content.forms", policyClass: "standard" },
  { table: "content.form_submissions", policyClass: "standard" },

  // ── graph.* — transactional outbox rows carry the writing tenant's scope.
  //   The Neo4j projector reads cross-tenant via withSystemDb
  //   (app.rls_bypass='on'); tenant sessions only ever see their own rows.
  //   projection_checkpoints excluded: system bookkeeping, no tenant columns.
  { table: "graph.outbox", policyClass: "standard" },

  // ── iam.* — the 2026-06-11 rebuild moved IAM out of org.* into iam.*.
  //   principals and principal_role_assignments have nullable workspace_id
  //   (NULL = org-wide principal/assignment); the rest are org-keyed.
  { table: "iam.principals", policyClass: "workspace_nullable" },
  { table: "iam.principal_role_assignments", policyClass: "workspace_nullable" },
  { table: "iam.roles", policyClass: "org_only" },
  { table: "iam.role_grants", policyClass: "org_only" },
  { table: "iam.access_requests", policyClass: "org_only" },

  // ── ingestion.* — connector epic. Child tables (auth_credentials,
  //   oauth_tokens, webhook_subscriptions) have no org cols; isolation is
  //   transitive through source_connections. oauth_accounts is org-level
  //   (encrypted OAuth tokens + PII, shared across workspaces).
  { table: "ingestion.source_connections", policyClass: "standard" },
  { table: "ingestion.entity_types", policyClass: "standard" },
  { table: "ingestion.entity_type_mappings", policyClass: "standard" },
  { table: "ingestion.setup_suggestions", policyClass: "standard" },
  { table: "ingestion.deletion_jobs", policyClass: "standard" },
  { table: "ingestion.oauth_accounts", policyClass: "org_only" },

  // ── mcp.* — all three tables are now tenant-owned (workspace-scoped).
  //   catalog_servers was removed in the 2026-06-17 workspace-scoping rebuild.
  //   registries changed from org_or_global (nullable org_id) to standard
  //   (org_id + workspace_id both NOT NULL).
  { table: "mcp.credentials", policyClass: "standard" },
  { table: "mcp.mcp_servers", policyClass: "standard" },
  { table: "mcp.registries", policyClass: "standard" },
  // External-MCP first-use consent grants + tool-descriptor snapshots
  // (OXA-816 / OXA-820). Both carry orgScopeMixin (org_id + workspace_id NOT
  // NULL) → standard.
  { table: "mcp.consents", policyClass: "standard" },
  { table: "mcp.tool_snapshots", policyClass: "standard" },

  // ── notification.* (org_id NOT NULL, workspace_id nullable) ──────────────
  { table: "notification.notifications", policyClass: "workspace_nullable" },

  // ── org.* — membership + invitations (org root itself is not row-scoped:
  //   organizations.id IS the tenant key, there is no org_id column). ───────
  { table: "org.org_users", policyClass: "org_only" },
  { table: "org.invitations", policyClass: "org_only" },

  // ── plugin.* (workspace-scoped; org_denylist was removed 2026-06-17) ────────
  { table: "plugin.installed_plugins", policyClass: "standard" },

  // ── privacy.* — GDPR Art.17/20 request queues (org_id NN, no workspace) ──
  { table: "privacy.privacy_export_requests", policyClass: "org_only" },
  { table: "privacy.privacy_erasure_requests", policyClass: "org_only" },

  // ── security.* (security_events: org_id NOT NULL, workspace_id nullable;
  //   partitioned parent — children inherit enforcement) ────────────────────
  { table: "security.security_events", policyClass: "workspace_nullable" },
  { table: "security.org_security_policy", policyClass: "org_only" },
  // External-MCP server lifecycle audit (OXA-820). Append-only, but org_id +
  // workspace_id are both NOT NULL (servers are workspace-scoped) → standard.
  { table: "security.mcp_server_changes", policyClass: "standard" },

  // ── workflow.* — playbook domain (2026-06-11 rebuild). Versions/steps/edges
  //   carry no org cols (immutable children of playbooks → transitive). ──────
  { table: "workflow.playbooks", policyClass: "standard" },
  { table: "workflow.playbook_triggers", policyClass: "standard" },
  { table: "workflow.playbook_runs", policyClass: "standard" },
  { table: "workflow.playbook_step_runs", policyClass: "standard" },
  { table: "workflow.playbook_events", policyClass: "standard" },
  { table: "workflow.playbook_approvals", policyClass: "standard" },

  // ── workspace.* ───────────────────────────────────────────────────────────
  //   workspaces has org_id NOT NULL but no workspace_id — org_only policy.
  //   workspace_users is the membership table: workspace_id + user_id but NO
  //   org_id, so it cannot use an org-keyed policy. It gets a workspace_only
  //   policy keyed on app.current_workspace_id — without it the table has NO
  //   RLS and member rows leak across tenants.
  { table: "workspace.workspaces", policyClass: "org_only" },
  { table: "workspace.workspace_users", policyClass: "workspace_only" },
];
