/**
 * Branded HTML + plain-text template for email-verification emails.
 *
 * Same structure as resetPasswordEmailTemplate: no external assets, no template
 * engine, HTML-escaping via esc() for all user-derived values.
 *
 * The verification URL is generated by Better Auth and carries the token;
 * callers pass the opaque URL as-is.
 */

import { esc } from "./html-escape";

export interface EmailVerificationTemplateInput {
  /** Full verification URL generated by Better Auth (contains the one-time token). */
  verificationUrl: string;
  /** User's email address — used in the greeting. */
  email: string;
}

/**
 * Returns `{ subject, text, html }` for the email-verification transactional email.
 *
 * Security notes:
 * - The verification URL is only embedded, not rendered in visible text beyond the CTA.
 * - Plain-text body includes the URL verbatim so link-only clients work.
 * - Token lifetime (default 1 hour) is communicated to the user.
 */
export function emailVerificationTemplate(
  input: EmailVerificationTemplateInput,
): {
  subject: string;
  text: string;
  html: string;
} {
  const { verificationUrl, email } = input;

  const subject = "Verify your email address";

  const text = [
    `Hi,`,
    ``,
    `Thanks for signing up for Oxagen. Please verify your email address (${email}) to complete your account setup.`,
    ``,
    `Verify your email here: ${verificationUrl}`,
    ``,
    `This link expires in 1 hour. If you did not create an account, you can safely ignore this email.`,
    ``,
    `— Oxagen`,
  ].join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;background:#f9fafb;margin:0;padding:32px 0">
  <table role="presentation" cellpadding="0" cellspacing="0" style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:8px;border:1px solid #e5e7eb;padding:40px">
    <tr><td>
      <p style="font-size:14px;color:#374151;margin:0 0 16px">Hi,</p>
      <p style="font-size:14px;color:#374151;margin:0 0 16px">
        Thanks for signing up for Oxagen. Please verify your email address
        (<strong>${esc(email)}</strong>) to complete your account setup.
      </p>
      <p style="margin:0 0 24px">
        <a href="${esc(verificationUrl)}"
           style="display:inline-block;background:#6366f1;color:#ffffff;font-size:14px;font-weight:600;padding:10px 20px;border-radius:6px;text-decoration:none">
          Verify email
        </a>
      </p>
      <p style="font-size:13px;color:#6b7280;margin:0 0 8px">
        This link expires in <strong>1 hour</strong>. If you did not create an
        account, you can safely ignore this email.
      </p>
      <p style="font-size:12px;color:#9ca3af;margin:0">
        If the button above does not work, copy and paste this URL into your
        browser:<br>
        <span style="color:#6366f1;word-break:break-all">${esc(verificationUrl)}</span>
      </p>
    </td></tr>
  </table>
</body>
</html>`;

  return { subject, text, html };
}
