/**
 * Branded HTML + plain-text template for password-reset emails.
 *
 * Same structure as reauthEmailTemplate: no external assets, no template
 * engine, HTML-escaping via esc() for all user-derived values.
 *
 * The reset URL is already generated by Better Auth and carries the token;
 * callers pass the opaque URL as-is.
 */

import { esc } from "./html-escape";

export interface ResetPasswordEmailTemplateInput {
  /** Full reset URL generated by Better Auth (contains the one-time token). */
  resetUrl: string;
  /** User's email address — used in the greeting. */
  email: string;
}

/**
 * Returns `{ subject, text, html }` for the password-reset transactional email.
 *
 * Security notes:
 * - The reset URL is only embedded, not rendered in visible text beyond the CTA.
 * - Plain-text body includes the URL verbatim so link-only clients work.
 * - Token lifetime (default 1 h, configurable in auth.ts via
 *   `resetPasswordTokenExpiresIn`) is communicated to the user.
 */
export function resetPasswordEmailTemplate(
  input: ResetPasswordEmailTemplateInput,
): {
  subject: string;
  text: string;
  html: string;
} {
  const { resetUrl, email } = input;

  const subject = "Reset your Oxagen password";

  const text = [
    `Hi,`,
    ``,
    `We received a request to reset the password for your Oxagen account (${email}).`,
    ``,
    `Reset your password here: ${resetUrl}`,
    ``,
    `This link expires in 1 hour. If you did not request a password reset, you can safely ignore this email — your password will not change.`,
    ``,
    `— Oxagen`,
  ].join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family:system-ui,sans-serif;background:#f9fafb;margin:0;padding:32px 0">
  <table role="presentation" cellpadding="0" cellspacing="0" style="max-width:520px;margin:0 auto;background:#ffffff;border-radius:8px;border:1px solid #e5e7eb;padding:40px">
    <tr><td>
      <p style="font-size:14px;color:#374151;margin:0 0 16px">Hi,</p>
      <p style="font-size:14px;color:#374151;margin:0 0 16px">
        We received a request to reset the password for your Oxagen account
        (<strong>${esc(email)}</strong>).
      </p>
      <p style="margin:0 0 24px">
        <a href="${esc(resetUrl)}"
           style="display:inline-block;background:#6366f1;color:#ffffff;font-size:14px;font-weight:600;padding:10px 20px;border-radius:6px;text-decoration:none">
          Reset password
        </a>
      </p>
      <p style="font-size:13px;color:#6b7280;margin:0 0 8px">
        This link expires in <strong>1 hour</strong>. If you did not request a
        password reset, you can safely ignore this email — your password will
        not change.
      </p>
      <p style="font-size:12px;color:#9ca3af;margin:0">
        If the button above does not work, copy and paste this URL into your
        browser:<br>
        <span style="color:#6366f1;word-break:break-all">${esc(resetUrl)}</span>
      </p>
    </td></tr>
  </table>
</body>
</html>`;

  return { subject, text, html };
}
