import { readdir, readFile } from "node:fs/promises";
import { extname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  agentDefinitionConfigSchema,
  agentDefinitionSchema,
} from "./agent-schema";

/**
 * Witness for #1010 / OXA-2137: the agent.trigger.* subsystem is removed and
 * triggering lives only on automations/playbooks. An agent definition is now a
 * pure, portable, trigger-free config.
 *
 * The invariant we assert is "no LIVE runtime source references the subsystem",
 * so the scan is deliberately scoped to first-party TypeScript source under
 * apps/ and packages/. We do NOT scan — and must not, because a reference there
 * is legitimate, not a regression:
 *   • migrations/ — an append-only ledger. The drop migration
 *     (20260813130000_drop_agent_triggers.sql) has to name `agent_triggers` to
 *     DROP it, and the earlier migrations that created/altered the table are
 *     immutable history (editing them breaks atlas.sum and bricks the deploy).
 *   • *.test.ts — tests reference the removed names in NEGATIVE assertions
 *     (this file) and in the tenant-policy manifest's count ledger.
 *   • docs/ & tools/ & *.json capability mirrors — design records of what the
 *     system used to be, or artifacts regenerated by the docs pipeline; neither
 *     is the runtime subsystem.
 */
const repositoryRoot = fileURLToPath(new URL("../../..", import.meta.url));

const forbiddenSubsystemNames = [
  ["agent", "trigger"].join("."),
  ["agent", "Trigger"].join(""),
  ["Agent", "Trigger"].join(""),
  ["agent", "EventFilterSchema"].join(""),
  ["Agent", "EventFilter"].join(""),
  ["agent", "triggers"].join("_"),
];

const sourceExtensions = new Set([".ts", ".tsx"]);
const skipDirectories = new Set([
  "node_modules",
  "dist",
  ".next",
  ".turbo",
  "migrations",
  "__tests__",
]);

async function findSubsystemReferences(directory: string): Promise<string[]> {
  const matches: string[] = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) {
      if (skipDirectories.has(entry.name)) continue;
      matches.push(...(await findSubsystemReferences(path)));
    } else if (
      sourceExtensions.has(extname(entry.name)) &&
      !entry.name.includes(".test.") &&
      path !== fileURLToPath(import.meta.url)
    ) {
      const source = await readFile(path, "utf8");
      if (forbiddenSubsystemNames.some((name) => source.includes(name))) {
        matches.push(relative(repositoryRoot, path));
      }
    }
  }

  return matches;
}

describe("portable agent definitions", () => {
  // This walks every .ts/.tsx under apps/ + packages/, so it is I/O-heavy
  // (~0.5s alone, but it competes for the disk when the whole suite runs in
  // parallel worker threads). Give it generous headroom over the 5s default so
  // it stays a deterministic assertion rather than a load-dependent timeout.
  it("have no trigger configuration or legacy trigger subsystem", async () => {
    // 1. The agent definition itself is trigger-free.
    expect
      .soft(agentDefinitionSchema.keyof().options)
      .not.toContain("triggers");
    expect
      .soft(agentDefinitionConfigSchema.keyof().options)
      .not.toContain("triggers");

    // 2. No live TypeScript source — contracts, handlers, API routes, MCP tools,
    //    app UI — still references the removed agent.trigger.* subsystem.
    const references = (
      await Promise.all(
        ["apps", "packages"].map((root) =>
          findSubsystemReferences(resolve(repositoryRoot, root)),
        ),
      )
    ).flat();
    expect(references, "live agent.trigger.* source references").toEqual([]);
  }, 30_000);
});
