// AUTO-GENERATED by tools/scripts/check_manifest.mjs — do not edit by hand.
// Every contract file under ./contracts auto-registers on import; this barrel
// is the single import that pulls them all in. Run `pnpm check:manifest`
// (or the gate) to regenerate after adding or removing a contract.

import "./contracts/agent.approval.resolve.js";
import "./contracts/agent.code.execute.js";
import "./contracts/agent.mcp.list.js";
import "./contracts/agent.mcp.register.js";
import "./contracts/agent.memory.recall.js";
import "./contracts/agent.memory.write.js";
import "./contracts/agent.plan.approve.js";
import "./contracts/agent.plan.create.js";
import "./contracts/agent.skill.list.js";
import "./contracts/agent.skill.load.js";
import "./contracts/agent.subagent.aggregate.js";
import "./contracts/agent.subagent.dispatch.js";
import "./contracts/agent.task.background.cancel.js";
import "./contracts/agent.task.background.read.js";
import "./contracts/agent.task.background.start.js";
import "./contracts/agent.tool.list.js";
import "./contracts/billing.credits.purchase.js";
import "./contracts/billing.subscription.read.js";
import "./contracts/billing.subscription.upgrade.start.js";
import "./contracts/brandkit.apply.js";
import "./contracts/chat.message.send.js";
import "./contracts/documents.generate.js";
import "./contracts/documents.pdf.create.js";
import "./contracts/form.fill.js";
import "./contracts/image.generate.js";
import "./contracts/org.member.add.js";
import "./contracts/org.member.invite.accept.js";
import "./contracts/org.member.invite.decline.js";
import "./contracts/organization.create.js";
import "./contracts/svg.generate.js";
import "./contracts/system.install.instructions.js";
import "./contracts/video.generate.js";
import "./contracts/workspace.create.js";
