// AUTO-GENERATED by tools/scripts/check_manifest.mjs — do not edit by hand.
// Every contract file under ./contracts auto-registers on import; this barrel
// is the single import that pulls them all in. Run `pnpm check:manifest`
// (or the gate) to regenerate after adding or removing a contract.

import "./contracts/agent.approval.resolve";
import "./contracts/agent.code.execute";
import "./contracts/agent.mcp.list";
import "./contracts/agent.mcp.register";
import "./contracts/agent.memory.recall";
import "./contracts/agent.memory.write";
import "./contracts/agent.plan.approve";
import "./contracts/agent.plan.create";
import "./contracts/agent.skill.list";
import "./contracts/agent.skill.load";
import "./contracts/agent.subagent.aggregate";
import "./contracts/agent.subagent.dispatch";
import "./contracts/agent.task.background.cancel";
import "./contracts/agent.task.background.read";
import "./contracts/agent.task.background.start";
import "./contracts/agent.tool.list";
import "./contracts/billing.credits.purchase";
import "./contracts/billing.subscription.read";
import "./contracts/billing.subscription.upgrade.start";
import "./contracts/brandkit.apply";
import "./contracts/chat.message.send";
import "./contracts/conversation.archive";
import "./contracts/conversation.delete";
import "./contracts/conversation.list";
import "./contracts/conversation.purge";
import "./contracts/conversation.rename";
import "./contracts/documents.generate";
import "./contracts/documents.pdf.create";
import "./contracts/form.fill";
import "./contracts/image.generate";
import "./contracts/org.member.add";
import "./contracts/org.member.invite.accept";
import "./contracts/org.member.invite.decline";
import "./contracts/org.member.remove";
import "./contracts/org.member.role.change";
import "./contracts/organization.create";
import "./contracts/svg.generate";
import "./contracts/system.install.instructions";
import "./contracts/user.preferences.read";
import "./contracts/user.preferences.write";
import "./contracts/video.generate";
import "./contracts/workspace.create";
import "./contracts/workspace.model.settings.read";
import "./contracts/workspace.model.settings.write";
