export * from "./types";
export * from "./registry";
export * from "./kernel";
export * from "./plugins";

// Every contract auto-registers on import. The barrel below is generated by
// `tools/scripts/check_manifest.mjs` from the contents of ./contracts — adding
// a contract file is enough; there is no hand-maintained import list to forget.
import "./contracts.generated";
